### PR TITLE
Add information about wiring up OpenLog

### PR DESCRIPTION
**Pull request by joshuabardwell**

### CODE REVIEW

**Comment by joshuabardwell** [comment]
I hope that I have formatted this PR correctly...

**Comment by thenickdude** [comment]
Hm, what's the licensing status of the Naze32 board photos used to make the diagram, are they your own work? I can't imagine that SparkFun would mind their OpenLog photo being used (since it's being used to sell more OpenLogs), but a Naze32 vendor might have second thoughts about it.

**Comment by joshuabardwell** [comment]
You know, I didn't notice that it was watermarked until you mentioned it. That's a shame. Do you think it would be okay if I just pulled the image from the Naze32 manual?

**Comment by thenickdude** [comment]
Definitely not, Baseflight will throw a shitfit if that happens (entirely reasonably). I'll commit a version of your docs which don't include the diagram for now and we can sort something out once we've got a photo we're allowed to use.

**Comment by thenickdude** [comment]
I've merged this now, thanks! I reshuffled the documentation to bring the OpenLog parts together (and reduce a bunch of duplication about choosing a port, which I had split into two sections for no good reason).

**Pull request closed without merging**
