### PR TITLE
Updated Custom Mixer Examples with CMIX instead of MMIX

### PR DESCRIPTION
**Pull request by x0054**
While setting up a custom mix, I realized that the MMIX command is now CMIX. I updated the documentation to reflect this. Also, the motor count starts with 1, not 0, I updated this as well.

### CODE REVIEW

**Comment by joshuabardwell** [comment]
As long as you're in a giving mood, it would be great to see documentation for smix that specifically discussed how to emulate gimbal_flags=4.

**Comment by stuphi** [comment]
I thought that mmix was the new command in 1.10, along with smix which replace cmix.

**Comment by thenickdude** [comment]
Yeah in 1.10 is there is smix (servo mix) and mmix (motor mix). "cmix" is the old name for the custom motor mixer in 1.9.0.

**Comment by hydra** [comment]
This pull request is invalid. the current documentation is correct for 1.10.x.  Thanks anyway though!

**Comment by sppnk** [comment]
Does "servo" command have the same use than "smix" command? I am able to configure my airplanes with 1.8.1 (through GUI Chrome), but as 1.9.0 and 1.10.0 servo tabs don't work, I should use the CLI, but I am really confused. The documentation on "smix" command is incomplete, and in "servo" command inexistent.

For now I have to fly planes with 1.8.1.

**Pull request closed without merging**
