### PR TITLE
Winbond 25Q16CV support in Cleanflight

### PR DESCRIPTION
**Pull request by cahe**
Banggood sells a naze32 rev6 board that uses this chip. It's currently unsupported in cleanflight. I've made this modification and tested it - it works on those boards.

### CODE REVIEW

**Comment by hydra** [comment]
are the naze32 rev6 boards from banggood official or clones?

do you have links to the products on their site?

**Comment by cahe** [comment]
I can't really tell if it's official or a clone. It's this board:
http://www.banggood.com/CK-REV6-NAZE32-10DF-Flight-Controller-For-RC-Multirotors-Baseflight-Configurator-p-1030040.html

**Comment by hydra** [comment]
it's a clone.

users should support official manufacturers and not feed hands into the clone makers.

**Comment by cahe** [comment]
That's probably true, but I bet many people new to this whole Quadcopter thing, just like me, don't really know the difference. Especially in the beginning of their UAV journey. I've seen some comments on reddit and other sites from people not understanding why this does not work properly.

**Comment by bbbenji** [comment]
@hydra 

I have soldered this exact same chip (thinking it was supported) to my authentic Naze32 which came with an unpopulated memory. I would love to see this PR merged so I don't have to manually add the support each time and compile myself.

**Comment by hydra** [comment]
#2148 will take care of this.

**Pull request closed without merging**
