### PR TITLE
./build_all_targets.sh before pushing to ensure a breakage-free push

### PR DESCRIPTION
**Pull request by nathantsoi**
an easy way to make sure i didn't break any targets before pushing

### CODE REVIEW

**Comment by hydra** [comment]
there's already fake_travis_build.sh.

**Comment by nathantsoi** [comment]
@thenickdude and i were talking about this in irc, `fake_travis_build.sh` doesnt seem to do the trick...

**Comment by thenickdude** [comment]
It was .travis.sh that didn't do the trick, the other fake Travis build script does work.

**Comment by nathantsoi** [comment]
you're totally right, tried again and it works fine. thx all!

**Pull request closed without merging**
