### PR TITLE
Many Performance Improvements // Fast Math // Delayed Acc For Acro

### PR DESCRIPTION
**Pull request by borisbstyle**
In preparations for migration of main features from betaflight to
cleanflight this is a very important one. Especially F1 boards will
notice a massive improvement in performance.

Quaternions used to boost Acc effect on performance

Not my PR. It's a mixed of various things from my Betaflight branch by digitalentity, prodrone, me and some others.

### CODE REVIEW

**Comment by digitalentity** [comment]
@borisbstyle 
Your quaternion IMU from this PR breaks compass functionality. I have something in the works for my nav-rewrite (2ecb9e21f69d32a9b19ce351303d4f69e131be6a, also quaternion based IMU, but with compass support) - it was developed for my navigation, but there's not a big deal to rebase it on latest master and post a PR. There is also a separate PR for fast math - #1107 :smiley:

**Comment by tracernz** [comment]
Fast math is [something else](https://gcc.gnu.org/onlinedocs/gcc-4.9.3/gcc/Optimize-Options.html#index-ffast-math-951) :P

**Comment by digitalentity** [comment]
In this case fast math is exactly what I ment. The referred PR for fast
trigonometry is a subset of this PR. And gcc options are not involved at
all.

**Comment by tracernz** [comment]
What I meant is that it's probably not a good name as it's easily confused with the GCC fast math options and the GCC macro  __FAST_MATH__. :)

**Comment by digitalentity** [comment]
Oh, now I see!

**Comment by borisbstyle** [comment]
I made this pr so that the code mixed from some prs doesnt get lost. @digitalentity I would really like to see this going into cf with your navigation fixes added to it :)

**Comment by digitalentity** [comment]
I'd love to see most of this PR in cleanflight as well, but not the compass-less quaternion IMU from betaflight :smirk:
Ref. navigation - I've hit the flash memory limit on CC3D, must compile something out to free up some space :confused:

**Comment by borisbstyle** [comment]
add a pr uppon on this one than with those navigation parts in it than so it gets complete. Maybe some cleanup as well?

Are you using the OP bootloader?

**Comment by borisbstyle** [comment]
This PR together with my i2c overclock PR opens a lot of processing room :).
After that we might redo the filter stuff to get better.

**Comment by digitalentity** [comment]
@borisbstyle, my quaternion is completely different from yours. It's being tested currently and soon will be merged to my navigation. I'll rebase it on current master and open a PR here.

**Comment by digitalentity** [comment]
Im not using OPBL, I had to enable SKIP_CLI_COMMAND_HELP to free up some memory, but soon I'll have to start dropping features.

**Comment by borisbstyle** [comment]
Ok so yours is different? In what sense?

This one was kind of made from different prs around and prodrone helped me
a while back with this.

Whats the performance gain on yours? This one lets the F1 targets drop
looptime from 1200 to 800 on integer based pid controllers.

I could later make a separate pr with delayed acc reading in acro.
Op 17 okt. 2015 10:43 schreef "Konstantin Sharlaimov" <
notifications@github.com>:

**Comment by digitalentity** [comment]
Test rig: CC3D, acc/gyro enabled
Stable 800 looptime in rate mode on PIDC1, stable 1000 looptime in horizon mode on Lux.

**Comment by digitalentity** [comment]
I developed this IMU together with @MauroMombelli (discussion here - #1253). It is based on Mahony's DCM filter implemented by S. Madgwick and in some way modified by myself and @MauroMombelli. It is fast to respond, aware of compass and make ANGLE mode feel more locked in if compared to complementary IMU (what we currently have in CF).

IMU code is located in c3d18d8413b5f730ba4fe3bc1eb9bef54b1d1aee, but this commit is based on my navigation branch, not on current master.

**Comment by bdoiron74** [comment]
@borisbstyle This looks a lot like the quaternion IMU I never quite finished. Did you solve the reversed yaw issue they mentioned here: https://github.com/cleanflight/cleanflight/pull/1192 ?

I think mag support would be pretty straight forward to add using the same cross vector approach with 'north' and the mag data.

**Comment by digitalentity** [comment]
@bdoiron74 my quaternion IMU is almost finished. I'll post a PR in a few days.

**Comment by borisbstyle** [comment]
@bdoiron74
Yes yaw is easily solved by just inverting it :)
Op 17 okt. 2015 15:41 schreef "Konstantin Sharlaimov" <
notifications@github.com>:

**Comment by bdoiron74** [comment]
I thought it might be. I wonder if quaternion_from_rpy() should also have the inverted yaw for consistency: https://github.com/cleanflight/cleanflight/pull/1404/files#diff-877904013669bfdb61add5272a15eb8bR464

**Comment by digitalentity** [comment]
Just posted a PR with my implementation of quaternion imu (#1411)

**Comment by borisbstyle** [comment]
Closed this one as @digitalentity handles this better :D

**Pull request closed without merging**
