### PR TITLE
Add MOTOLAB build target and associated source files

### PR DESCRIPTION
**Pull request by MotoLab**
This is for the MotoLab Tornado and MotoF3 controller boards.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
I've tested this on the MotoF3, and it works really well. No Problems.

**Comment by hydra** [comment]
Hiya,

There needs to be a Board - MotoF3.md to go with this (and yes, the Colibri Race guys need to do the same thing too!).

It should describe the board, some of it's features, pinouts, etc.  Please refer to the other Board- *.md files for reference.

Links to the board's website and photos of it would also be good, as would connection diagrams (preferably in source format so we can use them as a basic to create connection diagrams for other boards), if there's a schematic available then a link to it would be good too.

**Comment by MotoLab** [comment]
I've added the Board - MotoLab.md file, rebased on master and squashed the commits.

**Comment by MotoLab** [comment]
Rebased on master and conflicts resolved.

**Comment by NullVoxPopuli** [comment]
:+1:

**Comment by andymac4182** [comment]
Any chance of adding this into a minor release of 1.10 since these are shipping now.

**Comment by NullVoxPopuli** [comment]
Yeah, this is stable. 

I've been testing betaflight: and it's pretty stable there too: https://github.com/borisbstyle/cleanflight/blob/betaflight/obj/betaflight_MOTOLAB.bin

**Comment by borisbstyle** [comment]
Yeah works great...flew it a few times now :)

**Comment by andymac4182** [comment]
@hydra Any update if this will be included in 1.10.1?

**Comment by hydra** [comment]
Hi guys.  I'm having issues with targets being requested all the time.  It creates a big testing overhead.  Work on #357 and #884 needs to be looked at first.

In the mean time please keep this PR updated and build users binaries until we have had the chance to look at the issues mentioned.

multiple targets = testing overhead = problems refactoring = increased time between release = fail.
fewer targets + dynamic configuration = less testing overhead = shorter time between releases = win.

**Comment by andymac4182** [comment]
I understand that this can cause a large amount of work. This target has been heavily tested and it would be good to have it merged since it has been here so long and there are boards designed for Cleanflight that are unable to run it without custom compiled versions causing more testing work when a bug is found.

I understand if you want to reject future target changes till those changes are completed.

**Comment by PProvost** [comment]
Here's a question for you guys... is there any available telemetry (perhaps from the Configurator) on how many of the current targets are being used? I work in the software business so I totally understand the pain associated with a large testing matrix. My thinking here is to actually measure and prioritize those that are supported directly in the main builds based on actual usage of the target.

I know MotoMoto is selling these things as fast as he can get them manufactured so if this one isn't big now, it may not make the cut, but I suspect it will grow if this board is as good as it looks.

Also, while you're discussing refactoring, I wonder... is there a way to refactor the hardware layer to enable something like a "targets-contrib" project where a larger audience of developers could develop and contribute new targets. (Perhaps the two issues that @hydra linked above will help.)

**Comment by hydra** [comment]
Merged, we want the users.  There will be two more targets this year (not named for confidentiality reasons) and they will be the last until work has been done to cleanup the target support.

**Comment by NullVoxPopuli** [comment]
:+1:

**Pull request merged**
