### PR TITLE
SPRacingF3Mini - Target support including Race Transponder and MicroSD card logging

### PR DESCRIPTION
**Pull request by hydra**
Many thanks to @thenickdude for the awesome work on the SD Card Logging feature!

The CJMCU target is currently failing due to code size.  Likely because of the serial buffering code that was also added from existing PR's for VCP targets and not the new target support.

### CODE REVIEW

**Comment by thenickdude** [comment]
Hey @hydra I'm getting garbled CLI output with this version, at least when switching from the Receiver tab to the CLI tab:

```
Entering CLI Mode, type 'exit' to return, or 'help'

# ode, type 'exit' to return, or 'help'

# 
```

```
Entering CLI Mode, type 'exit' to return, or 'help'

#  to return, or 'help'

# 
```

SPRACINGF3MINI and STM32F3DISCOVERY

**Comment by thenickdude** [comment]
When I set looptime=0, the GUI works extremely slowly/unreliably, which is quite noticeable on the Setup tab with the 3D model moving at about 3 FPS. looptime=1000 works fine and the model moves smoothly. Are you seeing this same issue?

**Comment by hydra** [comment]
@thenickdude I haven't tried that.  I will try to replicate here soon.  Got some postage related actived to attend to at the moment.

**Comment by borisbstyle** [comment]
remove gtune in cjmcu tarjet or remove the target entirely. It is kind of outdated.

@thenickdude 
I think looptime of 0 would mess up the scheduler?

**Comment by borisbstyle** [comment]
i remember that buffering pr....when i teied it I had garbled cli as well

**Comment by hydra** [comment]
@thenickdude confirmed, same issue here.  probably something to do with scheduler code.

**Comment by hydra** [comment]
@borisbstyle yes, I'll remove GTune or something for CJMCU and get this merged ASAP.

**Comment by hydra** [comment]
@thenickdude the slowdown appears to be related to sensor calibration. it goes back to normal after a short time.

**Comment by hydra** [comment]
@thenickdude some garbled CLI output is expected using latest 1.2.0 configurator due to the way CLI detection is now handled.

**Pull request merged**
