### PR TITLE
blackbox - add amperageLatest logging

### PR DESCRIPTION
**Pull request by ledvinap**
Raw ADC value is logged, currentMeter configuration is stored in header(as `H currentMeter:<offset>,<scale>`)

vbatLatest refactored to vbatLatestADC

Amperage sounds terrible, but current will collide with temporal meaning. Anyone got better idea?

This PR is untested, it is ready for review, but don't merge yet, I'll test it soon.

### CODE REVIEW

**Comment by thenickdude** [comment]
Looks good to me! Once I see what the raw data looks like, I can add a cumulative mAh usage and peak current display to the renderer.

**Comment by hydra** [comment]
@thenickdude do you think we use a seperate issue tracker for the blackbox tools so the 'todo' in your comment is tracked?

**Comment by thenickdude** [comment]
Good idea, I posted a new issue there.

**Comment by thenickdude** [comment]
ledvinap: did you record a log with this feature yet? Please share!

**Comment by ledvinap** [comment]
Mostly testing on table. Here is one real log: https://drive.google.com/file/d/0B9HM4UOKDQBLa0NHYjhCNUxTRlE/view?usp=sharing

**Comment by thenickdude** [comment]
Excellent, thanks, looks like the values decode okay in blackbox_decode, so I can add support for blackbox_render. Note that you're missing this fix in the firmware so the current meter scale / offset is absent from your header and it won't decode properly without it:

https://github.com/cleanflight/cleanflight/commit/e134574c8185e3128f7ad2bfb99886074185f4f3

(You can just add the values in to the header with a hex editor)

**Comment by thenickdude** [comment]
Decoding is now supported in the JS log viewer.

**Pull request merged**
