### PR TITLE
MAVLink telemetry cleanup

### PR DESCRIPTION
**Pull request by digitalentity**
Continuation of https://github.com/cleanflight/cleanflight/pull/806
I've enclosed mavlink library with pragmas to disable -Wpedantic to avoid compile warnings (until the unnamed union issue is resolved in https://github.com/mavlink/mavlink/pull/386)

### CODE REVIEW

**Comment by digitalentity** [comment]
This is **not** ready to be merged yet. Still cleaning things up.

**Comment by Susurrus** [comment]
Do note that I'm have commit rights to the MAVLink repo and have many commits there under my belt. If there's something you'd like to push on that end I can help try to move it along.

**Comment by hydra** [comment]
@Susurrus hi!  anything you could do to help would be great, having to maintain patches or modified libraries is always a pain that no-developer needs.

**Comment by Susurrus** [comment]
Yes, the point of MAVLink is that it serves everyone's needs. I've been running it on a 16-bit microcontroller and others use a full 32-bit CPU and Linux on top of that. So if you raise issues on the main MAVLink repo I can shepard them and help them into PRs and get them merged. This effort does need to be lead by someone else, however, as I don't have hardware for CF nor do I have experience building it.

**Comment by vooon** [comment]
@hydra @digitalentity  wide parameters still not in use by APM or PX4, but easiest is to use `-std=gnu11` instead of gnu99 (since you use gnu extensions).

**Comment by digitalentity** [comment]
@hydra what do you think about switching to -std=gnu11?

**Comment by hydra** [comment]
@digitalentity not had time to check the differences.  would be curious as to what @martinbudden and @ledvinap think too.

**Comment by digitalentity** [comment]
@martinbudden @ledvinap 
What to you think, can we merge this?

**Comment by hydra** [comment]
i relocated the mavlink code to `/lib/main/mavlink` and merged it.

**Comment by digitalentity** [comment]
Thanks @hydra, I've forgot about this PR :smile:

**Pull request merged**
