### PR TITLE
Change linker settings

### PR DESCRIPTION
**Pull request by cctsao1008**
add -flto -ffat-lto-objects  to pass build in win64

### CODE REVIEW

**Comment by MJ666** [comment]
Using Win64 already since more than a year to build CF without having any issues?

**Comment by hydra** [comment]
Why is this needed? what version of GCC are you using?  I use Windows 7 x64 - no issues here with this version

arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 4.8.4 20140725 (release) [ARM/embedded-4_8-branch revision 213147]

2014 - q3

**Comment by MJ666** [comment]
I'm using Windows 8.1 x64 and the same compiler than Dominic and never had problems?

**Comment by hydra** [comment]
Maybe this helps explain what this PR is for:

http://stackoverflow.com/questions/13799452/what-is-the-difference-in-gcc-between-lto-and-fat-lto-objects

@cctsao1008 can you please give us more details of the issue and why you want this change?

**Comment by hydra** [comment]
Closing, no activity and no response.  Remains in the issue tracker for reference if needed.

**Pull request closed without merging**
