### PR TITLE
Fixing vagrant provisioning error.

### PR DESCRIPTION
**Pull request by inbilla**
Provisioning succeeds with this change.
#2250

### CODE REVIEW

**Comment by ledvinap** [comment]
Isn't it possible to add proper public keys? This only masks the problem ...

**Comment by inbilla** [comment]
I'll try it, give me a moment

**Comment by inbilla** [comment]
Seems to work, happier with this @ledvinap?

**Comment by ledvinap** [comment]
This should be more robust, thanks. Will merge tomorrow if there are no objections ..

**Comment by inbilla** [comment]
no prob, glad to help

**Comment by hydra** [comment]
@ledvinap no objects, go ahead

**Comment by ledvinap** [comment]
Sorry, forgot about this ...

**Pull request merged**
