### PR TITLE
CLI code size reduced with 544 bytes.

### PR DESCRIPTION
**Pull request by ProDrone**
Target of this PR is to preserve some code space.
This is done by using single byte codes for repeated parts in variable name strings.
Result is:
```
 CODE SIZE MASTER WITH ORIGINAL CLI:
   text    data     bss     dec     hex filename
 116596     264   13368  130228   1fcb4 ./obj/main/cleanflight_NAZE.elf
 
 CODE SIZE MASTER WITH ADAPTED CLI:
    text    data     bss     dec     hex filename
 116052     264   13424  129740   1facc ./obj/main/cleanflight_NAZE.elf
 
    544 bytes saved.
```

### CODE REVIEW

**Comment by ProDrone** [comment]
@hydra In the hope it gives a little space on smaller targets...

**Comment by ProDrone** [comment]
@hydra Strange. I tried to combine my code with PR #927 for additional space, but it is getting bigger, so i left it out.

**Comment by hydra** [comment]
Interesting...  This might help @Pierre-A with PR #792

**Comment by hydra** [comment]
I think that we need to think about #347 before looking at this.

**Comment by ProDrone** [comment]
@Hydra I agree it is related, but my goal for this PR is having the same functionality while using less memory. I feel that the `issues->PR->added features` is going at an increasing speed. Soon there will be no more targets where Cleanflight fits in memory.

**Comment by ledvinap** [comment]
@ProDrone : Interesting approach .. 
IMO this is case of overoptimization. Code readability suffers a lot ...
Maybe use some external tool to generate 'optimized' strings automatically, if saved space is that important? Or use some compression for strings? Most targets are flash limited, not ram (even decompressing strings when entering CLI may make sense)

**Comment by ProDrone** [comment]
@ledvinap I think saving space should not start to be an issue when it is all used up :) so we should make an effort as-we-go to preserve it. String compression will (probably) not give the amount of gain as referring 5 times to the same (long) strings as in `_telemetry_baudrate`, `_blackbox_baudrate`, etc. The 544 bytes are saved flash, not ram. I assumed that soon we will drop the CLI in favor of another solution, as indicated by @hydra in #922 I agree with you on over-optimization and readability, but until a better solution is there, it is not to hard to use it like this.

**Comment by ProDrone** [comment]
Closed: Because commit ca22fb0ee322c4a77ba6d9051561a2dd852b7f71 already removed the longest strings and the added complexity of this PR vs gained space is IMO out of balance.

**Pull request closed without merging**
