### PR TITLE
Remove redundant pid controller typedef

### PR DESCRIPTION
**Pull request by rosek86**
Minor cleanup in pid controller module.

### CODE REVIEW

**Comment by hydra** [comment]
Cannot merge this as is.  cleanflight header files should not include other header files.  The only exception should be "platform.h" which includes the stm libraries and target.h.

Each C source file needs to explicity state it's include dependencies at the top of the file.  During the binary and test build processed these files can be swapped in/out with real or test versions on an as needed basis.

If you move the include statements into the .c files in another commit I can merge the changes.

**Comment by rosek86** [comment]
That's a bit weird constrain, how about if I would like to create interface
with function pointers and then fill the interface by e.g. two
implementations at runtime? I'd need to include interface file in header
file for functions prototypes.

stdint, stdbool?

2015-02-23 1:24 GMT+01:00 Dominic Clifton <notifications@github.com>:

**Comment by hydra** [comment]
We can address that issue should we need to, but this is currently how the codebase is structured.  One common 'clean code' goal is not to code for the future since that envisaged future may never happen.

**Comment by hydra** [comment]
Cleanups done in bc8e53a9d82fa99258059111a50e79fa07b3e877

**Pull request closed without merging**
