### PR TITLE
Frsky telemetry heading without GPS

### PR DESCRIPTION
**Pull request by samcook**
As mentioned in #486 and on IRC yesterday, heading is only displayed when a GPS fix is available (the behaviour on my Taranis appears to be if the lat/long are zero then the heading doesn't update).

The issue could be worked around by setting `frsky_default_lattitude` and `frsky_default_longitude` to a non zero value, if you happened to know doing that would have this side-effect.

This PR has FrSky telemetry always send a location of 1 deg north/1 deg east when a GPS sensor isn't available (it's kind of a hack, but if you have no GPS then the lat/long is going to be meaningless anyway).

(I've stacked this on top of PR #854, let me know if you want it rebased)

### CODE REVIEW

**Comment by hydra** [comment]
Can you rebase this PR on master once you've tested the recent changes in 69292fc9668ec668af9ac1cd1b313159ce32519e

**Comment by samcook** [comment]
Rebased onto master.

**Comment by hydra** [comment]
I will merge this and clean it.

**Comment by hydra** [comment]
See 802218b77bcbcb5ec6d805577998067720c975df

**Pull request merged**
