### PR TITLE
serial: allow buffering to speed up USB virtual COM ports.

### PR DESCRIPTION
**Pull request by nzmichaelh**
I noticed this when working on my Python MSP library.  MSP over a VCP is much less reliable when running on a virtual machine as it sens one USB packet per byte.  This patch adds support for buffering at the driver level and uses it in MSP and the CLI.

This makes the polled MSP_STATUS message fit in one USB frame instead of 20 and greatly speeds up the CLI.

### CODE REVIEW

**Comment by ledvinap** [comment]
Did you consider https://github.com/cleanflight/cleanflight/pull/886?

**Comment by nzmichaelh** [comment]
@ledvinap heh, I didn't notice your patch, no.  I went down this route as I'm hoping that having the application mark large writes will also simplify the UART DMA code.

I think I have a CC3D so I might be able to test both branches.

**Comment by ledvinap** [comment]
@nzmichaelh : 
Implementing write(void*, size) function for serial port should have similar/greater performance effect and is common interface in C.  
Even with begin/end instrumentation each byte is handled through virtual table -  most of compiler optimizations are useless here (C++ virtual method can probably handle this much better).

**Comment by bdoiron74** [comment]
Thank you! This VASTLY improves offloading the blackbox data from the CC3D datafash!

**Comment by nzmichaelh** [comment]
@ledvinap for embedded I prefer exposing the devices buffers via the start() / commit() pattern instead.  It saves the extra buffer and extra copy and lets you send a full frame at a time.  The API looks something like this:

uint8_t *serialStart(int* capacity);
void serialCommit(int wrote);

and then you use it like:

int capacity;
uint8_t *p = serialStart(&capacity);
*p++ = 1;
*p++ = 2;
serialCommit(2);

I'm not worried about the indirect function call.  The Cortex-M has a short pipeline so it won't be expensive compared to the rest of the code.  I suspect the cost of the extra copy would outweigh the cost of the call.

I'll prepare an alternate branch that does something like write(buf) instead.

@bdoiron74 cool, great to hear!  There should be ~20 times fewer USB frames for the same transfer.  Try hacking the [20] in serial_usb_vcp.h to anything up to 32 and see if it gets even quicker.

**Comment by ledvinap** [comment]
@nzmichaelh : Yes, the Start/Commit is good approach. Split buffer needs to be handled somehow if used with circular queues, but  that's manageable. Simple read(void*)/write(void*,n) is a bit more generic and easier to use.. In both cases serial code will need to be modified..

The cost of indirect call is not in call overhead but in the fact that compiler can't make any assumptions about called function. Direct call can be inlined and pointers cached. Calling through pointer can't be inlined and compiler probably has to assume that memory got clobbered - caller has to reload most of registers.
The copy should be quite cheap, memcpy may copy 4 bytes at a time (with free barrel shifter on ARM core).

But all this is only my personal opinion. @hydra is in charge ...

**Comment by nzmichaelh** [comment]
@ledvinap thanks for the feedback.  I had a deeper look and it turns out the USB DMA memory region needs 16 bit aligned writes so I can't directly expose it via start() / end().  It might be better to do something like sk_buf: allocate a buffer at the application level, hand it to the driver for sending, and then have the driver release it.

Something like:

struct sk_buf {
    uint8_t capacity, count;
    uint8_t data[];
};

sk_buf_t *buf = skAlloc(16 /* size hint */);
buf->data[0] = 1;
buf->data[1] = 2;
serialSend(buf, 2);

For USB, the USB driver can immediately copy it into the USB DMA region and then release.  For UART, the UART can enqueue the buffer, DMA it out in the background, and then release once the DMA completes.

**Comment by ledvinap** [comment]
@nzmichaelh : Well .. yes, it is possible. But buffer management will get pretty complicated - most approaches may result in memory fragmentation, possibly leading to ugly bugs. One possibility is slab allocator or something similar, but it is incredibly difficult to fix all bugs. Or you implement fixed size buffers and buffer chaining, but it also gets complicated (works great with multiple threads - only small insertion code needs lock).

RAM is not scare resource on CF. Usually writing code like:
```
char buff[64];  // may be common for all messages
uint8_t *p=buff;
// switch() {
// case x:
*p++=1
*p++=2;
// break
// }
*p++=checksum(buff, p-buff);  // may be common after switch
serialSend(buff, p-buff);
```
and copying buffer into serial ringbuffer in serialSend is reasonably fast, readable end easy to debug (message is readily available). And resulting speed will be considerably better than current byte-by-byte approach..

**Comment by bdoiron74** [comment]
@nzmichaelh : I tried 32 and saw no measurable improvement.

**Comment by nzmichaelh** [comment]
@ledvinap yip, my favourite is memory pools where you have a few fixed sized blocks to allocate.  There's no fragmentation problem, there's no list to manipulate (as alloc/free is check an allocation table or bitmap), and it's easy to implement.  You still have the alloc/free problem.

I had quick hack and that's a dead end as well.  I'm currently thinking of creating a BufferedWriter on the stack around the serial port and using that.  This solves the allocation problem.  It means a extra copy but, as you say, that's probably offset by better compiler optimisations.

**Comment by nzmichaelh** [comment]
@ledvinap have a look at #1151 for a writeBuf() plus buffered writer implementation.

**Comment by borisbstyle** [comment]
I tried this one and I get broken cli. With big commands like dump it gets scrambled here and there.

**Pull request closed without merging**
