### PR TITLE
Port changes

### PR DESCRIPTION
**Pull request by ledvinap**
Here are some improvement that accumulated in my 'local' branch. The changes are mostly stylistic, code functionality should not be modified, except:

- i2c interrupts are disabled sooner on error
- fixed typo in serial_uart_stm32f30x.c
- some conditional compilation is added
- 4096 is used instead of 4095 in ADC scaling

### CODE REVIEW

**Comment by ledvinap** [comment]
Tell me if some commits should be removed from this PR, i'll rewrite it

**Comment by ledvinap** [comment]
Any idea why Travis fails during tests? I can't reproduce it locally

**Comment by thenickdude** [comment]
Did you see the Travis status page? Looks like a floating point exception (likely, a division by zero) in BatteryTest.BatteryADCToVoltage:

https://travis-ci.org/cleanflight/cleanflight/jobs/48768268

Looks like that test is garbage: It creates a batteryConfig on the stack and passes it to batteryInit completely uninitialised. That uninitialised memory is later used by batteryAdcToVoltage, which likely by chance treats the random memory contents as an invalid float and triggers a floating point exception.

**Comment by ledvinap** [comment]
Actually it was my change that caused the problem - I replaced loop computing cell count with equivalent division. maxcellvoltage was then used as divisor.

Strange is that I was not able to reproduce it locally

Fix is pushed to PR

**Comment by ledvinap** [comment]
Rebased

**Comment by ledvinap** [comment]
@thenickdude Thanks for help

**Comment by thenickdude** [comment]
Isn't 4095 the correct divisor for the ADC? It's the maximum value the ADC
reads which should correspond to the VREF of 3.3V?

**Comment by ledvinap** [comment]
Yes, 4095 is correct value. But error caused by using 4096 is negligible and shift can be used instead of full division ...

**Comment by hydra** [comment]
Can you do another rebase on the current master and we can get all this merged in.

Also I'm not a big fan of the common/utils.h file.  I do not want it to be a dumping ground for random stuff.  If i open up a file called 'utils.h' i never know what i'm going to find.  I'd perhaps pefer common/string.h and/or other appropriately named files and content.

**Comment by hydra** [comment]
Please remove blocked label when rebase is done.

**Comment by ledvinap** [comment]
Rebased

**Comment by hydra** [comment]
Excellent. Thanks.

**Comment by hydra** [comment]
Merging.

**Comment by hydra** [comment]
@ledvinap Thanks for all those cleanups, much appreciated.

**Pull request merged**
