### PR TITLE
TPS, pid scaling and throttle expo updated outside main PID loop

### PR DESCRIPTION
**Pull request by DzikuVx**
Currently, TPA and throttle expo are updated every iteration of PID main loop. With new RX data available only at 50Hz this means that the same operations are repeated for the same data.
With looptime 2000 the same output is computed 10 times before it changes. 
This pull requests updates those coefficients only when new RX data is available

### CODE REVIEW

**Comment by martinbudden** [comment]
@hydra , @borisbstyle I think the RX scheduler setting of 50Hz is probably to small. From looking at the DeviationTx software, DSM2 protocol seems to send a packet every 10ms, and some other protocols send a packet every 5ms. So setting the RX period to at least 100Hz and probably 200Hz seems a good idea.

**Comment by ledvinap** [comment]
@martinbudden : I thought that RX frequency is event-driven (it was when RC interpolation was implemented). This did change with new scheduler?

**Comment by martinbudden** [comment]
@ledvinap , no, there has not been a change in the event-driven stuff.

To be honest, I'm not sure when the event-driven stuff is used, and when polling is used - I need to get my head around this. What, then is the purpose of the 50Hz RX period?

**Comment by ledvinap** [comment]
https://github.com/cleanflight/cleanflight/blob/2d1b548d0599c1575aecb345327f2737f52ea426/src/main/mw.c#L779

New RX data are checked at much higher frequency (each scheduling?). 50Hz is fallback when when `taskUpdateRxCheck()` does not return true.

**Comment by martinbudden** [comment]
I sort of get that. What I don't really understand is when the fallback condition would actually occur.

**Comment by borisbstyle** [comment]
@martinbudden 
Fallback is for PWM / PPM at the moment and when in failsafe. I know someone was working to make PPM event driven too? Not sure if it got merged

**Comment by hydra** [comment]
ok, merging.

**Comment by martinbudden** [comment]
@DzikuVx , @hydra , I've just had a further look at this, and **ALL** of the `annexCode` is RX data dependent - so it should all be moved into `taskUpdateRxMain`. Indeed this is what @borisbstyle has done in betaflight.

In fact we can go further - we can move the `filterRc` code there as well.

**Comment by ledvinap** [comment]
@martinbudden: `filterRC` does interpolate received command to PID frequency. It does help to reduce steps in RC signal - dynamics are fast enough to react to single steps. With D-term based on gyro only, this effect is greatly reduced, but IMO the cost is slower reaction to stick command (D-TERM will augment stick reaction).

**Comment by borisbstyle** [comment]
@ledvinap
I think I helped that fact with making P accelerating / increased with more stick input.
You can get more out of your tune as we feel the increasing stick always more than decreasing stick deflections.

What I did for now is just a easy math what makes Kp dynamic. It adds up to 50% of P linearly with more stick input up to certain stick threshold.
This brings the back the sharpness took away eith delta from measurement without penalty.

**Comment by ledvinap** [comment]
@borisbstyle:  With D-term from stick command, the braking starts when stick starts moving toward neutral position. With P-term augmentation, P-term effect will be increased only if you go to opposite side. But maybe second variant feels better ..

**Comment by borisbstyle** [comment]
yes but the delta from measurement handles braking also really well.
Also reduced P with stick falling back introduces some slight smoothing to
the neutral.

There is always a downside, but I think this is a good compromise for all
scenarios.
Op 7 mei 2016 13:21 schreef "Petr Ledvina" <notifications@github.com>:

**Comment by ledvinap** [comment]
Delta from measurement is in opposite direction - D-term has negative sign, opposing change...
But I am talking about theory only - in practice, it may feel well

**Comment by borisbstyle** [comment]
O yeah you mean opposite from the sticks.

I think that for the feel it doesnt make difference as your brain wants to
slow the rotation down and there is no sharpness needed.

Another good experiment would be to use rcSmoothing for derivative
calculation only and use actual unsmoothed rccommand for the rest of the
calculations.
Op 7 mei 2016 14:08 schreef "Petr Ledvina" <notifications@github.com>:

**Comment by hydra** [comment]
it should be noted that was a ciritical bug with this PR see #2165 and the fix in #2171

**Pull request merged**
