### PR TITLE
Sparky LED strip pin rewired to PWM 8

### PR DESCRIPTION
**Pull request by Thor368**
The standard pin for WS2812 LED strips is PWM 5 which is unfavourable in some cases. Some changes need to be applied to the target file and light drivers to rewire the output to PWM 8 aka PA7. Most of the code was already there but apparently someone lost interesst in getting through it.

You will find the precompiled binary of the master including my patch in the attachment. I also converted the hex file to the proprietary dfu format for flashing with the DfuSe tool. Happy testing^^.

[cleanflight_SPARKY_patch.zip](https://github.com/cleanflight/cleanflight/files/160420/cleanflight_SPARKY_patch.zip)

### CODE REVIEW

**Comment by hydra** [comment]
can you squash all the commits and I will merge it.

**Comment by Thor368** [comment]
Well, how do I do this? I am a github newbee. Do I need to make a new PR with only one commit in it?

**Comment by dkisselev** [comment]
Search around for guides on how to "git squash", there are a few really good tutorials out there and YouTube videos are usually really helpful as well.

Here are a few that I've sent people in the past:

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

You'll notice that both those guides tell you not to rebase changes that you've already pushed, but generally this is safe when you're working on your own branch in your own fork (it's highly unlikely that anybody else has ever checked your branch out and intends to make changes). Just keep that in mind, if you've ever pushed a branch and think that there's a chance that someone else may have checked it out, don't rebase and push that branch, make a new one.

In this case, once you perform the rebase on your computer and have verified that it all worked well and you didn't lose any code, you can type `git push -f` to FORCE git to push the changes, overwriting the stored history. Github is smart and will automatically recognize that you've pushed a rebase and update the PR for you (no need to close/reopen).

**Comment by Thor368** [comment]
Wow, that was some work and head bending to get this going. Sorry, that this took so long but I just finished my exam phase. So no time, just stress. ;)

**Comment by Thor368** [comment]
Ah, I just realized that it would be beneficial if I changed that doc for sparky board as well. Maybe directly with this pr?

**Comment by hydra** [comment]
this is blocked by the io allocation #357  since the PR doesn't add the code needed to disable VBAT when led strip is used (or vice versa)  it makes sense to wait at this time.

**Pull request closed without merging**
