### PR TITLE
Added initial CMake support for the unit-tests

### PR DESCRIPTION
**Pull request by landstroem**
Tested by diffing <unittest>_result.xml files vs the Makefile on Ubuntu
14.04 LTS (CMake version 2.8.12.2)

Partial support working on Windows 7 + Cygwin + GCC 5.3.0
- Missing memcpy for ledstrip_unittest
- Some failed test for PIDUnittest

Not tested for:
shell uname -s "Darwin" (uses different linker flags for some tests)

### CODE REVIEW

**Comment by ledvinap** [comment]
@landstroem : I'll fix the memcpy problem. This problem is cynwin-32 specific, cygwin64 should work

Personally I like plain Makefile (but unittest building needs redesign), but CMake may make bookkeeping a bit easier.

This will work only if Makefile is replaced, keeping both makes no sense ...

**Comment by landstroem** [comment]
@ledvinap : Yes - it worked on cygwin64 so I'll remove the disabling of ledstrip_unittest for Cygwin. (I saw your PR #2207.)

Hopefully CMake can also make it easier to change the current unittest build process, this PR generally just tries to mimic the existing Makefile.

If this gets pulled in and matures, the existing Makefile for unittests should probably be replaced in the long run in order to avoid duplication. But that will also involve changes to the existing Makefile and CI configuration (?) which seems a bit scary to me...

**Comment by hydra** [comment]
interesting, what's missing however is *why* we want this.  I can see it looks like less work to add a new test but some insight from you on why you spent quite a bit of time doing this would clarify things for us all.

**Comment by hydra** [comment]
@landstroem please answer my previous comment on this.

**Comment by landstroem** [comment]
I used CMake to
- generate a Visual Studio solution
- keep my builds out-of-source so I could easily compare output files

and wanted to share.

I don't really think that Cleanflight needs the extra portability that comes with using CMake to create the Makefiles, but in my opinion, it doesn't hurt either.

I personally think it's easier to add a test (and reorganize builds) when CMake is used, but that is just my preference.

**Comment by hydra** [comment]
i have been contacted recently about cmake support again. from my limited exposure to it it sure seems clearer than makefiles.

I have been thinking a little about re-organizing the build system a little for cleanflight 2.0.0 (for F4 support) so this PR is starting to become relevent again.

Is there any chance you could rebase this against the current master?

**Comment by landstroem** [comment]
@hydra sure. Updated now.

**Pull request closed without merging**
