### PR TITLE
Added PT1 Element to PID1, PID2 and PID3 (rebase of #1007)

### PR DESCRIPTION
**Pull request by borisbstyle**
Shared CUT value for PID1, PID2, PID3 and PID5

Put back moving average

This is actually how I have been testing it lately. For some reason PID1
jusst needs this moving average for the best result

Added moving average PID2

PT1 main_cut_hz configurable in cli (default=0 disabled)

Removed some code and changed description

PID3 added PT1 filter

Harakiri MAIN_CUT_HZ fix (was broken)

### CODE REVIEW

**Comment by fedorcomander** [comment]
Just FYI... I had lots of vibrations issues on luxfloat on overpowered setup. Yesterday changed to pidc1 with PT1, gyro_lpf = 256 (off)... main_cut_hz=17.... Tuned briefly... It flies like on rails.

https://www.youtube.com/watch?v=amX0grst01Y

Camera is HARD mounted on the Mini... No vibration dampeners of any kind.

**Comment by borisbstyle** [comment]
@fedorcomander 
I know all about luxfloat and the floating point precision to see all micro vibrations ;)

**Comment by ATA250** [comment]
Kinda feels like you're flying simulator with PT1 & gyro_lpf=256, handles almost too perfectly to feel like it's actually in the real world :D I like a lot!

**Comment by borisbstyle** [comment]
@ATA250 Hehe exactly how it felt for me as well :D. Couldn't come up with better description. The racing through the gates with 5bft winds really felt like a video game. It were the flags reminding me that there was some wind.

**Comment by borisbstyle** [comment]
I am going to close this one as I want to make a new PR with cleaner code and more flexibility to add it to other PID controllers as well.

**Comment by henn1001** [comment]
See

http://www.rcgroups.com/forums/showpost.php?p=31920349&postcount=9100

**Pull request closed without merging**
