### PR TITLE
FLIGHT - PID cleanup

### PR DESCRIPTION
**Pull request by MauroMombelli**
as for issue #929, starting to make the things a bit more clean

### CODE REVIEW

**Comment by MJ666** [comment]
Do we really need to include all of this header files?

**Comment by MauroMombelli** [comment]
@MJ666 yes we need, but only because all include in the code are inside .c instead of .h; this mean not only you need to directly import what you need, but all of its dependency.
(if the include is done by the header files, the inclusion dependency is resolved by compiler)

As i have no idea why this choose has been made (probably just a legacy thing, see http://stackoverflow.com/questions/3943352/where-to-put-include-statements-header-or-source, but maybe something else is going on, like some makefile magic) I don't plan to fix this.

if you want to fix this, it will make the code more clean *wink wink*

**Comment by MauroMombelli** [comment]
moved the definition of pointer to function pidControllerFuncPtr from pid.c to pid.h, that way mw.c does not have to re-declare it

**Comment by hydra** [comment]
@MauroMombelli We don't want to add masterConfig as a dependency; @MJ666 is right when he asks "Do we really need to include all of this header files?"

The dependencies should be REDUCED, otherwise it makes the code harder to create unit tests for.  The dependency of masterConfig was specifically removed for this reason.

Cannot merge this as is.  I'm fine with other solutions to cleanup multiple defintions of functions.

**Comment by MauroMombelli** [comment]
ok, not a problem, the tile branch is taking care of cleaning the multiple
declaration and importing only the needed arguments, as in
https://github.com/inkonova/cleanflight/commit/f1fe14f96dbe5b3a73ba001dee4ec23cda1f81ac

2015-05-30 8:33 GMT+02:00 Dominic Clifton <notifications@github.com>:

**Comment by hydra** [comment]
I'll close this one as we don't want all the dependencies, as per comment https://github.com/cleanflight/cleanflight/pull/930#issuecomment-106994855

**Pull request closed without merging**
