### PR TITLE
Fix for compiler warning in serial_cli.c

### PR DESCRIPTION
**Pull request by drtunes**
During clean compile, I got the following compiler warning:

    %% serial_cli.c
    ./src/main/io/serial_cli.c: In function 'cliRxFail':
    ./src/main/io/serial_cli.c:615:52: warning: 'mode' may be used uninitialized in this function [-Wmaybe-uninitialized]
                     channelFailsafeConfiguration->mode = mode;
                                                        ^

In the default case for a switch, no value was assigned to variable *mode*. The default case has a return statement in it, so leaving mode unassigned would not be a problem in reality. Minor changes to avoid the compiler warning.

### CODE REVIEW

**Comment by thenickdude** [comment]
Which compiler version are you using? This warning isn't present in the compiler used for the official builds, "GCC 4.9 2015 q2". If your compiler is older then this isn't something that should be fixed in CF (since the code is already correct) but rather a compiler bug which you should update to fix.

**Comment by drtunes** [comment]
Using 4.8.4. (4.8 2014 q3)

I followed the instructions under docs/development/Building in Mac OS X.md

"Cleanflight is built using the 4.8 series GCC compiler provided by the GNU
Tools for ARM Embedded Processors project. The newest "4.9" series compiler
produces builds that don't boot on CC3D and Sparky targets (and perhaps
others), so it's better to use the older 4.8 compiler for the moment."

Should the directions be updated?

On Wed, Aug 19, 2015 at 2:44 AM, Nicholas Sherlock <notifications@github.com

**Comment by hydra** [comment]
I updated the documentation, we use 4.9 now.

I don't like the fix, since nothing will ever see the '?' and it just takes up flash space.

Got a better solution?

**Comment by drtunes** [comment]
The simplest fix would be to initialize the variable `rxFailsafeChannelMode_e mode = RX_FAILSAFE_MODE_HOLD;` That gets rid of the warning no the older compiler.

**Comment by Echelon9** [comment]
This revised approach is preferable.

**Comment by hydra** [comment]
this is fixed already in a030d4dd9e9996e715987fc88d38500505c4ced0

**Pull request closed without merging**
