### PR TITLE
Add ability for Blackbox to record to an onboard dataflash chip

### PR DESCRIPTION
**Pull request by thenickdude**
This allows the Blackbox to record to the Full Naze32's onboard 2MB flash chip rather than recording to an OpenLog serial logger.

A new option "blackbox_device" is added to choose which device (serial or flash) to record to.

New MSP commands are added for erasing the flash and downloading its contents.

New CLI commands are added: "flash_info" for identifying what flash chip is being used and its geometry, "flash_erase" for clearing the chip, and "flash_read" and "flash_write" for inspecting its contents. flash_read and flash_write are probably only useful for debugging, so should I remove those two? Or would they be helpful?

### CODE REVIEW

**Comment by digitalentity** [comment]
Can this be enabled for CC3D as well? CC3D has a 2MB M25P16 flash chip connected to SPI2.

**Comment by thenickdude** [comment]
Yeah, almost certainly. I currently have a CC3D on its way to me right now,
so I'll test it out and publish it if I can get it working. It's the same
chip as the one supported on the Naze, so only the port needs to be
configured in the target.h file.

**Comment by digitalentity** [comment]
Thanks! I own a CC3D and will be happy to test the code while you wait for your board.

**Comment by thenickdude** [comment]
Okay, having only read the schematic and never seen a CC3D in my life, here's a hex file to test:

https://github.com/sherlockflight/cleanflight-dev/releases/tag/v0.1-experimental

I don't know how to flash it to the device either. Don't attach props to it if you value your face. It'll certainly erase your existing settings so back those up first. After flashing you should be able to run the command "flash_info" on the CLI tab and get something that's not just a string of zeros as the result. 

If that works then you can follow the directions to log to dataflash here:

https://github.com/cleanflight/cleanflight/blob/master/docs/Blackbox.md

In order to download the logs that you've recorded, you will need to be using the latest development version of the Configurator:

https://github.com/cleanflight/cleanflight-configurator/tree/development

**Comment by digitalentity** [comment]
Thanks! Your build failed to connect using USB. I had to checkout your cleanflight-dev repo and recompile using GCC 4.8-2014-q2 (you are probably using GCC 4.9 that may cause flaky builds, see issue #452). I was able to issue a 'flash_info' command on CLI, however I've got only zeroes. Can't figure out why, will look into the code tomorrow.

**Comment by thenickdude** [comment]
Can you confirm the exact markings on the flash chip on your CC3D? It's the chip with the 8 fat legs at the bottom center of this photo:

CC3D board photo

**Comment by digitalentity** [comment]
Yes, exactly the same: 25P16VP by ST

**Pull request merged**
