### PR TITLE
Refactor IS_RC_MODE_ACTIVE

### PR DESCRIPTION
**Pull request by ledvinap**
Refactored to RC_MODE to match `features()`, `FLIGHT_MODE()`, etc.

@hydra, what do you think?

Maybe it would be even better to change it into function (rcMode()). With LTO there is no gain from using macros and functions have a bit better compile-time checking. Also internals (rcModeActivationMask) may be hidden

### CODE REVIEW

**Comment by hydra** [comment]
ok, quick thoughts.
1) it's consistent, but...
2) i might have gone the other way so the code reads better in english,  e.g. leave IS_RC_MODE_ACTIVE() alone and refactor FLIGHT_MODE into IS_FLIGHT_ACTIVE() and so on.  so that lines read like this `if (IS_XXX_ACTIVE()) { .. do stuff .. }`

prefer functions that are used to check status/return booleans start with a question (is/have).  if i see `RC_MODE(SOMETHING)` I don't know if it's a question or if `SOMETHING` is being enabled.

3) maybe yes functions, hiding implementation = good. and additional compile time checking = good.

**Comment by ledvinap** [comment]
OK .. You are in charge

Personally I prefer denser code (https://www.kernel.org/doc/Documentation/CodingStyle).
It is easier to read and understand code that is short (up to a point).
In this context, '_ACTIVE' carries almost no information. `RC_MODE` is either on or off. If it can be 'ENABLED', 'STARTING', .. then there is usually default/usual  meaning that needs no suffix.

`IS_` is prefix. I usually try to use naming scheme that starts with most generic information and then concertizes it. It fits nicely with OOP in C (name starts with object type/package it belongs to, then its function, then differences between similar function).
LISP uses P suffix to mark predicate .. I quite like that - it is  short and descriptive...
maybe `rcModeIsActive(uint32_t)` (but confusion with rcModels  is a bit problematic)

**Comment by hydra** [comment]
yes, `rcModeIsActive()` is quite ok apart from the `rcModels\rcModeIs` problem.  haha, there's always something.

The issue with just `RC_MODE()` is that you don't know what it does until you look it up, where as with 'IS_RC_MODE_ACTIVE()` you can guess and you'd likely be correct.  Less cross-referencing = easier to follow and understand the first time you read it. :smile:

**Comment by ledvinap** [comment]
OK, refactored ...  Better?

**Comment by hydra** [comment]
yup, prefer it.

**Comment by hydra** [comment]
Noted that #1672 contains this too.

**Comment by ledvinap** [comment]
Fixed last unittest problems, force-pushed

#1672 is branchched from this, I hope that github will handle that correctly .. 

Or is there better way to generate dependent PRs?

**Comment by hydra** [comment]
merging

**Comment by hydra** [comment]
the merge was a bit fiddly, but it's done now.  also going to close #1672 since #2075 contains it, #2075 will need a rebase/merge of master.

**Pull request merged**
