### PR TITLE
Support new 230400 baud rate which allows >750Hz Blackbox logging

### PR DESCRIPTION
**Pull request by thenickdude**
Adds 230400 and 250000 baud rates. Adds Blackbox support for user-selected baud rates.

Also adds new 2 stop-bit port mode, so Blackbox can use more stop bits when using faster baud rates (OpenLog can't synchronise properly when baud is 230400 and stop bits is only 1).

### CODE REVIEW

**Comment by ledvinap** [comment]
Maybe it would be good idea to mention Sandisk ultra in blackbox documentation...

**Comment by thenickdude** [comment]
To say that it's good or bad? Do you mean the poor performance from the 32GB version of the Ultra?

**Comment by ledvinap** [comment]
Well, all Sandisk ultra's I used were behaving very well and quick Google search seemed to confirm that it is good choice. But I'am using smallest cards I can get ...

**Comment by hydra** [comment]
Going to merge.

Noted that we think the port modes should probably just be MODE_RX/TX/BIDIR and that other stuff like stop bits and inversion etc should be port options.  @thenickdude to submit seperate PR to clean that a bit.

**Pull request merged**
