### PR TITLE
Update failsafe to be triggered by a range of values on channels

### PR DESCRIPTION
**Pull request by TighMacFanatic**
Update failsafe to be triggered by a range of values on channels that match a mask.

Fix range constraints on inputs.

### CODE REVIEW

**Comment by JohnieBraaf** [comment]
Should this not be 885? For people using the 900 to 2100 range?

    masterConfig.rxConfig.rx_min_usec = 985;

**Comment by TighMacFanatic** [comment]
I reset rx_min_usec to 700, that line was actually removed.

It fails the test because there are new variables that need initializing by the test.  I'll be testing it all out tonight and figure out where those should be initialized.

**Comment by hydra** [comment]
The defaults should currently not be changed from 985 to 750 because of the way sbus RX's are handled.  i'm guessing you've not tested with an SBus RX in failsafe mode?

Ideally there should be a unit test for this.

The mask might be useful, but I'm not sure for who or why at this stage so I'm inclined to look at the other PR's for failsafe related issues before this one.

**Comment by hydra** [comment]
See #995

**Comment by TighMacFanatic** [comment]
On a Turnigy XR7000 (and probably others), the only indication of TX lost is that the aux switches go to mid range.  They are two way switches, so normally are either at min or max.  By having a mask and a range of failsafe values (instead of valid values), I can trigger failsafe on my RX.  There's no way to do that with the original implementation.

As for the defaults, I had to lower them for my setup because pushing any of my sticks to minimum went below the default and the sanity check caused them to jump back to mid until I let off, which is very undesirable behaviour.

**Comment by hydra** [comment]
no need for this any more, cleanflight has a new FAILSAFE mode which you can activate when channels go into a specific range.

If the latest version doesn't work for you please create a new PR and/or discuss with @ProDrone

**Pull request closed without merging**
