### PR TITLE
Configuration storage

### PR DESCRIPTION
**Pull request by ledvinap**
Reset by template implemented ; fixed some minor problems

Space saving is considerable:
129080	   1240	  19188	 149508	  24804	./obj/main/cleanflight_SPRACINGF3MINI.elf
128580	   1240	  19188	 149008	  24610	./obj/main/cleanflight_SPRACINGF3MINI.elf

### CODE REVIEW

**Comment by ledvinap** [comment]
This is beast I can get without doing too much preprocesor magic. Some -pedantic rules are a bit a annoying (you can't cast function pointer to data pointer).

Special section is used to test if pointer is function or initialization template. This should be quite portable (PG_REGISTER is dependent on sections anyway) and new init class can be easily implemented with small overhead.

`_ARR` initialization is not implemented yet (it is unused in current code). What should it do? 
- Init all array members with same template. Item size will be necessary for this, but it may be added to template.
- Copy template over config
- Implement both variants
- don't implement it, use function for reset

**Comment by hydra** [comment]
looks really good.  Zero WTF's :smile: 

With regards to your question.  One approach is YAGNI.  if we dont need it don't implement it.   When we do we can implement it.  I think we've got bigger fish to fry right now than worrying about something we don't use, right?

Is this ready for merge as is?

**Comment by ledvinap** [comment]
@hydra: unittests are fine, but I did not test it on hardware. The changes are pretty safe.
cygwin and OSX unittest should be checked, but all mechanisms are identical to storage.

Lets merge it into configuration-storage now and merge with master after quick testing.

as for _ARR - I'll add note to ask for implementation when needed.

**Comment by ledvinap** [comment]
I'll fast-forward configuration-storage and rebase this PR before merging.  Tomorrow ...

**Comment by ledvinap** [comment]
I fast-forwarded configuration-storage to master and cleaned-up the PR a bit.

It is ready for merge into configuration-storage branch and after quick testing (Cygwin  and OSX unittests, few targets) into master.

**Pull request merged**
