### PR TITLE
FrSky RPM Telemetry Motor_Stop Bugfix

### LINKED ISSUE #562: RPM telemetry reporting incorrect with MOTOR_STOP
When throttle is minimum, and board is armed, frsky telemetry RPM reports Minimum Throttle (ie. motors spinning) whether feature motor_stop is used or not.  When motor_stop is enabled, the RPM should be reporting the Minimum Command when throttle is minimum (as the motors are stopped)

I've made a fix for this in commit fc67c981b4669debc2a53104c68b8ad66c9c22e0 which seems to work well on my naze board.  I'm not sure if this is the best way to do this? can someone advise or test? If this is ok, I'll create a pull request

Thanks
Jenny

### PR DESCRIPTION
**Pull request by pinkywafer**
using calculateThrottleStatus this time, send 0 as RPM when THROTTLE_LOW and
MOTOR_STOP.
rxConfig and deadband3d_throttle are passed from mw.c through telemetry.c

closes #562 

replaces original PR (#577) which I've closed

### CODE REVIEW

**Comment by hydra** [comment]
great, thanks

**Comment by s700ky** [comment]
I upgraded to 1.8 & 6.3 on Acro Naze32 and I am getting no telemetry anymore?

**Comment by thenickdude** [comment]
@s700ky that is probably an unrelated configuration issue like having forget to select "FrSky" on the Telemetry dropdown on the Ports tab for the port you're using. Or forgetting to "set telemetry_inversion=1" if you're using it on a Softserial port.

**Comment by s700ky** [comment]
Doh! I failed to select it from the drop down. 

Thanks.

**Pull request merged**
