### PR TITLE
Revert cleanup 4way 2

### PR DESCRIPTION
**Pull request by ledvinap**
Another attempt to revert my mistake, now commit-by-commit, should revert everything correctly

### CODE REVIEW

**Comment by ledvinap** [comment]
This reverts invalid merge completelly

**Comment by ledvinap** [comment]
Another option is to merge #2090, it fixes 4way-if problems, tested on Sibabs and both Atmel bootloaders ...

**Comment by martinbudden** [comment]
@ledvinap , one thing you might like to try is renaming your `git remote upstream` for your cleanflight directory. If you change it form `upstream` to, say, `cf-upstream` it makes it harder to make mistakes (of course it makes some ordinary things a bit more difficult as well).

**Comment by jamde** [comment]
hello Martinbudden

naze32 was supported Nrf24 yet ? i try connect nrf24 to naze32 and use protocol v202 but it doesn't work . I use GNU arm to compile code .

can you post file hex for naze 32 support nrf24l01 ?

**Comment by ledvinap** [comment]
@martinbudden: 
I have git configured to require explicit remote specification. But in magit merge remote has to be set and it is used as alternative push target.
Main problem is that I was pushing 'msp-mem-interface' to upstream (set to correct branch) and did not realize I am on 4way branch (with upstream set to master)

**Comment by ledvinap** [comment]
I'll merge this soon to get master to working state. Both commits and reverts may be reset later ..

**Comment by martinbudden** [comment]
@ledvinap , well accidents do happen...

**Pull request merged**
