### PR TITLE
Smart Port telemetry GPS ground speed unit is not applicable. (#2166)

### PR DESCRIPTION
**Pull request by hori64**
fix this issue

### CODE REVIEW

**Comment by ledvinap** [comment]
@hydra: This scaling is used in OpenTX, should be merged: https://github.com/opentx/opentx/blob/master/radio/src/telemetry/frsky_sport.cpp#L80

**Comment by ledvinap** [comment]
@hori64 : Sorry, I did not check properly - you must use `GPS_speed` variable, this is not iNav ...

**Comment by hori64** [comment]
I was distracted, I'm sorry
I corrected, but I do not know what to do.

**Comment by ledvinap** [comment]
You can rewrite history and force-push to your branch. But squashing the PR during merge is simpler in this trivial case.

BTW: It's better to create new branch for each pull request .. git has some learning curve, but it's extremely powerful when learn how to use it ..

**Pull request closed without merging**
