### PR TITLE
inital light telemetry (LTM) implementation

### PR DESCRIPTION
**Pull request by stronnag**
Initial implementation of LTM. (Garden) bench tested with mwp. Lightweight telemetry with useful selection of data and good refresh rates (5 / 10 Hz at 2400 baud).

Addresses https://github.com/cleanflight/cleanflight/issues/36

### CODE REVIEW

**Comment by stronnag** [comment]
Flight test. Exceptional point density and lack of dropout for 3DR. Simple test out to c. 60m

selection_350

**Comment by JohnieBraaf** [comment]
So which type of radio supports this protocol? I can't find much on the internet...

**Comment by stronnag** [comment]
It is independent of the radio (at least 3DR, Bluetooth, ESP8266 transparent serial). It is supported by a (small) number of OSD, ground station and antenna trackers.

**Comment by dkisselev** [comment]
What are the benefits of it over mavlink or some of the other protocols that are implemented? (just curious, I've never heard of it, so I'm just wondering if there are specific use-cases where it's awesome and something I should start using)

**Comment by stronnag** [comment]
update rate and low bandwidth. Usable over soft serial at good update rates, unlike the mavlink proposal (which I tested), and then finally got around to implementing LTM. Your use case may be different.

**Comment by digitalentity** [comment]
@stronnag is there an feature-rich OSD for LTM that I can use onboard the aircraft? I need GPS coordinates, altitude, home direction and distance, velocities, voltage and current. For now it seem to me that the only hardware supporting LTM is KipK Ghettostation and GhettOSD for groundstation.

**Comment by dkisselev** [comment]
@digitalentity From what I've gathered, the benefit of LTM is that its data is relatively compact, so it makes sense as a protocol for streaming to a ground station. On-board the craft, you basically have full-speed serial available with no penalty so mavlink or anything else would work just fine.

From a few quick glances, it looks like ghettOSD runs on minimosd hardware, so that might be an option

**Comment by digitalentity** [comment]
I think this is worth trying out - ghettOSD might be a good options if it can be installed onboard.
Using an OSD on the ground is not a good option for me - usually I have an uplink for my RC control and a downlink for my video. Using OSD on the ground required a third reliable link for telemetry. 
Using two telemetry protocols is also not a viable option for me - I usually have just enough serial ports for GPS and one telemetry. I even have to stick with PPM receiver as I lack the third serial port to hook it up.

**Comment by dkisselev** [comment]
https://github.com/KipK/Ghettostation/blob/master/GhettOSD/GhettOSD/GhettOSD.ino

> GhettOSD is forked from minimosd-extra. Mavlink support has been removed. 

Sounds like you're good to go, might just be stuck with an older feature-set.

**Comment by digitalentity** [comment]
I've looked at the ghettOSD configurator an it seems to me that I'm good to go with LTM - it can display just enough information to suite my needs :)
LTM might even be a better choise as it uses less bandwidth and less memory onboard.

**Comment by marksev1** [comment]
Digitalentity actually you may be able to get away with just two providers since for example openlrsng can be used for both rc and transparent telemetry downlink.

**Comment by hydra** [comment]
I'll merge this if you write some unit tests for it too.

**Comment by digitalentity** [comment]
@stronnag 
While testing this today I've found that your LTM implementation does not send out OFRAME information (home information), while this is essential IMO. When flying in new areas I'd like to know what direction my point of launch is so I can safely return my copter. Can you add oframe support to your LTM implementation? It should be quite trivial.

**Comment by digitalentity** [comment]
@stronnag, an addition to my previous comment - I am using LTM as a datalink to my onboard OSD. I am not using Ghettostation or downlink to some groundstation.

**Comment by digitalentity** [comment]
@stronnag please see 2b91ead1a784a6ada17775f861aef10646f148c2 for implementation

**Comment by stronnag** [comment]
@digitalentity, thanks for the code, I was not previously aware of the OFRAME.

**Comment by digitalentity** [comment]
@hydra, @stronnag 
I've been testing this today - works fine with my onboard OSD rewritten using @ShikOfTheRa's scarab-osd as a base. I vote for this to be merged when possible. 
What unit tests should be written for a telemetry module? I can assist with writing them so this can get to master asap.

**Comment by stronnag** [comment]
@digitalentity, I plan to do some ltm units tests over the weekend.

**Comment by SamuelBrucksch** [comment]
Any progress on this? I want to use it with my open360tracker (see reference) so i really love to see this in CF. Thanks for all the effort so far...

**Comment by digitalentity** [comment]
@SamuelBrucksch 
LTM is fully integrated into iNav (navigation-enabled fork of CF). Merging this to the "vanilla" cleanflight is up to @hydra, hopefully this will happen soon enough.

**Comment by hydra** [comment]
MSP telemetry now deleted. See #1106 and #1575.  Earlier today I set the milestone to 1.13.0 but I'm thinking we add this now since it will impact the upcoming task scheduling PR that we also want for 1.12.0.  I will merge shortly (barring any issues).

**Pull request merged**
