### PR TITLE
more baros for spracing derivatives

### PR DESCRIPTION
**Pull request by nathantsoi**
an alternative to https://github.com/cleanflight/cleanflight/pull/1691

### CODE REVIEW

**Comment by nathantsoi** [comment]
already merged into betaflight https://github.com/borisbstyle/betaflight/pull/123, it would be great if you could pull this in @hydra

**Comment by nathantsoi** [comment]
someone asked about a link to the board: http://nathan.vertile.com/blog/2016/02/03/rctimer-beerotorf3-flight-controller

**Comment by nathantsoi** [comment]
bump @hydra

**Comment by skaman82** [comment]
+1

**Comment by hydra** [comment]
the beerotor guys should get more involved if they want hardware support.

**Comment by nathantsoi** [comment]
? everyone is involved. lol. no worries though, betaflight y'all!

**Comment by thandyadriel** [comment]
Hi, sorry for the dumb question, but which firmware should I install in beerotor F3? I just got my board and I am new in this hobby.  Thank you

**Pull request closed without merging**
