### PR TITLE
- Add TBS BST Code

### PR DESCRIPTION
**Pull request by larryho5**

### CODE REVIEW

**Comment by hydra** [comment]
@larryho5  Correct me if I'm wrong, but is much of the BST code a copy of the stm32f3 i2c code?  Only had a quick look so far.

**Comment by hydra** [comment]
The CRC calculation code should likely be in a file called crc.c and have an approriate unit test, I'm guessing it's pretty generic.

**Comment by larryho5** [comment]
@hydra The BST is similar to stm32f3 i2c code but not the same.

**Comment by ledvinap** [comment]
Here is faster way to generate crc8 (avoiding 256B table):
```
uint8_t crc8_bst(uint8_t crc, uint8_t data)
{
   static const uint8_t t_76[]={0x00, 0xd5, 0x7f, 0xaa};
   static const uint8_t t_210[]={0x00, 0xd0, 0x75, 0xa5, 0xea, 0x3a, 0x9f, 0x4f};
   crc ^= data;
   return crc ^ (crc >> 3) ^ (crc << 2) ^ t_76(crc >> 6) ^ t_210(crc & 0x07);
}
```

Also this version mixes in data first, so zero should not be appended to data (`crc8Cal(0);`)

**Comment by larryho5** [comment]
Do you think i can use stm32f30x_crc.h?

**Comment by ledvinap** [comment]
@larryho5: F1 does not support configurable CRC polynom. Also sharing CRC unit would be quite problematic.
Use the code from previous comment, it should work (at least did produce identical results in perl).
only change is that state is passed explicitly (`crc = crc8_bst(crc, data); ) and no `0` is appended to data.

**Comment by larryho5** [comment]
@ledvinap 
how do you set polynom in the previous code?
should I make crc8.c and crc8.h?
which folder should i put into?

**Comment by ledvinap** [comment]
it's for BST polynom (0xD5), the polynom is hardwired (https://en.wikipedia.org/wiki/Computation_of_cyclic_redundancy_checks#Parallel_computation_without_table), but the poly is too 'dense' to get nicer results (but maybe I am overlooking something)

I would use `src/main/common/crc.h` and `src/main/common/crc.c`. There are more CRCs that can be moved into this file, I'll eventually generate the PR .. ( @hydra, what do you think? )

Or just place the function into BST file, it can be polished later ...

**Comment by ledvinap** [comment]
You should concentrate on I2C first. This may be hard to implement on F1 targets. Also using cleanflight as I2C slave is a bit strange.

And duplicating msp code if probably bad idea too.

BTW: Any documentation/reference for BST?

**Comment by borisbstyle** [comment]
@ledvinap 
This is not ment to be for F1 targets. It is only for COLIBRI_RACE(The cube), which is a F3 target with integrated OSD what uses BST to configure everything without a need for any configurator tools.

**Comment by ledvinap** [comment]
@borisbstyle : Too many TLAs for me ;-)

It is very target-specific hack. Will merging it bring something other than maintenance nightmare?

**Comment by martinbudden** [comment]
@hydra , @borisbstyle , @ledvinap , @larryho5 

In essence it seems TBS (Team Black Sheep) BST (Black Sheep Telemetry) seems to be an implementation of MSP over I2C (current MSP is over serial). This seems a desirable thing and could be used by other flight controllers in future, for example it would allow bluetooth or OSD to be connected via I2C and would help solve the "shortage of serial ports problem". Additionally I see no reason why the TBS CORE PNP PRO module could not be used on flight controllers other than the TBS Powercube.

However this implementation is problematic, in particular because it reimplements rather than re-uses existing Cleanflight code. In particular:

1. `drivers/bus_bst_stm32f30x.c` reimplements a lot of `drivers/bus_i2c_stm32f30x.c` code. Instead it should reuse the existing I2C code and put a BST layer on top
2. `io/i2c_bst.c` reimplements a huge amount of `io/serial_msp.c`, in particular it reimplements the MSP protocol instead of just using it. Instead it should redirect the `serialise8` and `read8` to use I2C instead of serial and then implement the small amount of remaining  BST specific code separately.

These changes would make the BST code more maintainable and potentially reusable for other flight controllers. To given an example of the maintainability problem, the recently implemented PR https://github.com/cleanflight/cleanflight/pull/1976 (Refactor configuration storage) requires a large amount of changes to `io`i2c_bst.c`.

In fairness `io/serial_msp.c` really needs a bit of restructuring to allow this to this reuse. But with the changes I suggest we would have a solution that:

1. Supports TBS BST
2. Is maintainable
3. Allows future devices to use MSP over I2C to help solve the shortage of serial ports problem

**Comment by larryho5** [comment]
@hydra , @borisbstyle , @ledvinap, @hydra 

@martinbudden Thank you for your comment.
For the BST implementation, we are still changing it, you can see it in betaflight (following link https://github.com/borisbstyle/betaflight/blob/betaflight/src/main/drivers/bus_bst_stm32f30x.c). <-- this show you why i'm not reuse the i2c code, because it is different. But yea, you are right, we should reuse the MSP serial code.

**Comment by ledvinap** [comment]
@martinbudden: The concept of CleanFlight as I2C slave sound a bit problematic to me, but it may be doable (on dedicated I2C interface).
Using multi-master I2C (I hope I remember this PR correctly), acting both as master and slave is IMO too complicated.

As for MSP - All messages are quite small and it is reasonable to limit message size (force multiple messages if more data needs to be transferred). Re-implementing MSP with (fixed maximum) buffer abstraction should be quite easy, it will probably reduce code size and increase speed.
Then we just need small wrapper that will add headers/checksum to buffer use MSP over Serial and another simple wrapper for MSP over I2C ...

**Comment by martinbudden** [comment]
@larryho5 , I've had a look at your link, and yes it looks like the differences in the I2C code are too large for any meaningful reuse.

@ledvinap MSP is already implemented with a fixed maximum buffer. I had a look at refactoring it a while ago when I was writing some MSP test code and I think it would be fairly easy to split it into a core with an Serial wrapper and then add a I2C wrapper at a future date. Splitting out the core is a good thing to do in itself, since it will make writing test code much easier (writing MSP test code at the moment is a bit of a nightmare).

**Comment by martinbudden** [comment]
@ledvinap , @larryho5 

I've created a "for discussion" PR https://github.com/cleanflight/cleanflight/pull/2043 that splits `serial_msp.c` into a much smaller `serial_msp.c` which just contains the serial specific code, and a new `msp_protocol.c` which implements the MSP protocol, independent of the serial code. With this change it would be fairly straightforward to write an I2C wrapper over the MSP protocol.

**Comment by ledvinap** [comment]
@martinbudden : Playing with MSP too ...

**Comment by ledvinap** [comment]
I'am working on something a bit more radical - implement MSP to take cmd+data as input and return buffer with reply + error state. No checksum, no header, no length field in packet..

**Comment by martinbudden** [comment]
@ledvinap , that sounds interesting...

**Comment by ledvinap** [comment]
Looks easy so far ...

Is there any case when error reply has nonzero length?

**Comment by martinbudden** [comment]
@ledvinap , I'm not quite sure what you mean by error reply length. If you are referring to `headSerialError`, then the error reply length is the same size as the non-error length.

**Comment by ledvinap** [comment]
i see `headSerialError(0);` everywhere ...

**Comment by martinbudden** [comment]
Yes, you are correct.

**Pull request closed without merging**
