### PR TITLE
Added test for MSP_BOARD_ALIGNMENT and MSP_SET_BOARD_ALIGNMENT.

### PR DESCRIPTION
**Pull request by martinbudden**
Added test to check MSP handling of `boardAlignment`.

Not tested on the _configuration-storage_ branch, but I think with a [one line change](https://github.com/cleanflight/cleanflight/pull/1986/files#diff-c1e72aea90a72ea52c2952dd4cfb2584R491)  this can be used as a test with the new parameter group code.

### CODE REVIEW

**Comment by hydra** [comment]
can you rebase this against configuration-storage branch and I will merge into that.

**Comment by martinbudden** [comment]
Oh, oh, I think I've messed up the rebase. I'll try again

**Comment by martinbudden** [comment]
Actually, perhaps my rebase was OK.

@hydra, not sure if my rebase worked or not. Is the PR okay for you to merge? If not, let me know and I'll redo it again from scratch.

**Comment by blckmn** [comment]
@martinbudden it's cause your pull request is to clean flight master... If you close it and PR to the configuration-storage branch :)

**Comment by hydra** [comment]
no need, i can cerry-pick the commit.

**Comment by martinbudden** [comment]
@blckmn , thanks, I had just about worked out that for myself. But I thought @hydra would probably still be able to merge it in, hence the question.

**Comment by hydra** [comment]
merged.

**Pull request closed without merging**
