### PR TITLE
MSP : Add HDOP + don't scale mag_decl

### PR DESCRIPTION
**Pull request by gaelj**
Add HDOP value to MSP_RAW_GPS
Do not scale mag_decl by 10
Update API_version_minor to 18
(See associated CFC pull request)

### CODE REVIEW

**Comment by ledvinap** [comment]
OSDs etc using MSP may be affected by `mag_decl` change.

**Comment by ledvinap** [comment]
(sorry, wrong button)

**Comment by gaelj** [comment]
Could you please direct me to some help regarding the issue ?

**Comment by gaelj** [comment]
Is this failed check a problem ?

**Comment by martinbudden** [comment]
@gaelj , looks like you just need to add a stub for `GPS_hdop` in `serial_msp_unittest.cc`.
In the stubs section at the bottom of the file, in the part labeled `//from gps.c` just add the line:
```
uint16_t GPS_hdop;
```
That should fix the problem.

**Comment by gaelj** [comment]
Thank you very much for the hint.

**Comment by gaelj** [comment]
Hi. Should I squash this PR ?

**Comment by stronnag** [comment]
It would be useful to also consider the inav MSP_GPSSTATISTICS API (which also provides HDOP) in order to maximise the chances of this being well supported in ground stations / OSDs.

**Comment by gaelj** [comment]
continued in https://github.com/cleanflight/cleanflight/pull/2054

**Pull request closed without merging**
