### PR TITLE
- Enable MPU9250 for Colibri Race

### PR DESCRIPTION
**Pull request by larryho5**

### CODE REVIEW

**Comment by martinbudden** [comment]
@larryho5 

To set the default rc config to AETR you just need to remove the line:
``` 
parseRcChannels("TAER1234", rxConfig());
```
you don't need to add
```
parseRcChannels("AETR1234", rxConfig());
```
since AETR is the default.

Also if you `#define BOARD_HAS_VOLTAGE_DIVIDER` in `target/COLIBRI_RACE/target.h` you can remove `featureSet(FEATURE_VBAT);` since it will be set if `BOARD_HAS_VOLTAGE_DIVIDER` is defined.

You can also remove `featureSet(FEATURE_FAILSAFE);` from under the `COLIBRI_RACE` `#define` since `FEATURE_FAILSAFE` is set by default.

You can also remove `pidProfile()->pidController = PID_CONTROLLER_MWREWRITE;` from under the `COLIBRI_RACE` `#define` since that is the default.

The less board specific code there is in `config.c` the better. The above changes should get you down to 3 lines of Colibri specific code.

**Comment by hydra** [comment]
@larryho5 please update the PR based on @martinbudden 's comments above and we'll get this merged.

**Comment by larryho5** [comment]
@martinbudden, thank you, i will change it asap

**Comment by hydra** [comment]
thanks @larryho5 - merged.

**Pull request merged**
