### PR TITLE
Configuration storage - templates + improvements

### PR DESCRIPTION
**Pull request by ledvinap**
- template reset
- fixed duplicate registration in unittest
- unittests for new templates, unittest for memory zeroing

### CODE REVIEW

**Comment by ledvinap** [comment]
Can someone test on OSX an cygwin32, please ?

Unless I made some stupid mistake, this should be safe to merge. 500bytes of FLASH are saved
 by template approach.

**Comment by lampros87** [comment]
V1.12.1
Why my copter is drifting to a direction at center stick? I correct  as I fly more and more. I almost keep the roll/pitch stick at bottom left at the very end. At the beginning is not too bad.
Why on the modes tab the bars are not moving when I change mode? The copter changes modes correctly tested outdoors.
Can I connect a led board with a buzzer on it with pwm?
You are doing very good work guys. You are the people that make other people happy.

**Comment by martinbudden** [comment]
@ledvinap , I get the following error when building the test code under OSX:

```
c++ -g -Wall -pthread -Wextra -ggdb3 -O0 -DUNIT_TEST -isystem ../../lib/test/gtest/inc -MMD -MP -std=gnu++11 ../../obj/test/io/ledstrip.o ../../obj/test/ledstrip_unittest.o ../../obj/test/gtest_main.a -o ../../obj/test/../../obj/test/ledstrip_unittest
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "_pgResetFn_colors", referenced from:
      _colors_Registry in ledstrip.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../../obj/test/ledstrip_unittest] Error 1
```
I also get the warning
```
c++ -g -Wall -pthread -Wextra -ggdb3 -O0 -DUNIT_TEST -isystem ../../lib/test/gtest/inc -MMD -MP -std=gnu++11 -Iunit -I../main -c unit/config_eeprom_unittest.cc -o ../../obj/test/config_eeprom_unittest.o
unit/config_eeprom_unittest.cc:161:5: warning: attribute declaration must precede definition [-Wignored-attributes]
    PG_REGISTER_ARR_WITH_RESET_FN(someSystemArrayItem_t, 10, someSystemArray, PG_RESERVED_FOR_TESTING_2, 0);
    ^
../main/config/parameter_group.h:167:62: note: expanded from macro 'PG_REGISTER_ARR_WITH_RESET_FN'
    extern void pgResetFn_ ## _name(_type *) __attribute__ ((weak));    \
                                                             ^
unit/config_eeprom_unittest.cc:150:10: note: previous definition is here
    void pgResetFn_someSystemArray(someSystemArrayItem_t *instance)
         ^
unit/config_eeprom_unittest.cc:148:5: warning: unused function 'someSystemArray_arr' [-Wunused-function]
    PG_DECLARE_ARR(someSystemArrayItem_t, 10, someSystemArray);
    ^
../main/config/parameter_group.h:110:28: note: expanded from macro 'PG_DECLARE_ARR'
    static inline _type (* _name ## _arr(void))[_size] { return &_name ## _SystemArray; } \
                           ^
<scratch space>:22:1: note: expanded from here
someSystemArray_arr
^
2 warnings generated.
```

**Comment by ledvinap** [comment]
@martinbudden : Thanks for report. Fixed now; so code from other attempts was left, masking this problem
Can you test it again?

**Comment by martinbudden** [comment]
The tests now compile and run correctly. I now just get a single warning:

```
c++ -g -Wall -pthread -Wextra -ggdb3 -O0 -DUNIT_TEST -isystem ../../lib/test/gtest/inc -MMD -MP -std=gnu++11 -Iunit -I../main -c unit/config_eeprom_unittest.cc -o ../../obj/test/config_eeprom_unittest.o
unit/config_eeprom_unittest.cc:148:5: warning: unused function 'someSystemArray_arr' [-Wunused-function]
    PG_DECLARE_ARR(someSystemArrayItem_t, 10, someSystemArray);
    ^
../main/config/parameter_group.h:108:28: note: expanded from macro 'PG_DECLARE_ARR'
    static inline _type (* _name ## _arr(void))[_size] { return &_name ## _SystemArray; } \
                           ^
<scratch space>:150:1: note: expanded from here
someSystemArray_arr
^
1 warning generated.
```

**Comment by hydra** [comment]
ok, i'll merge this shortly and then suggest someone make a new PR or commit directly to fix the warning - add a unit test perhaps?

**Pull request merged**
