### PR TITLE
Feature softserial

### PR DESCRIPTION
**Pull request by ledvinap**
Preview of softserial code is here

This pull request is only for reference, do not merge it. I'll rewrite history in my branch.

### CODE REVIEW

**Comment by hydra** [comment]
right, @ledvinap this is next on my list of stuff to do since it's the olded pull request and also very important.  We need to get this finished.  Any chance of a rebase before I look at it?

**Comment by hydra** [comment]
ok great, thanks @ledvinap.  Not sure I'm going to get to look at this before my holiday. Very busy few weeks coming up.  I'll see if I can give it a quick test one even this week so that you can work on it while I'm away.

**Comment by ledvinap** [comment]
Rebased, fixed bug in timer quueue

**Comment by hydra** [comment]
@ledvinap Sorry, still not had time to look at this.  I've been overloaded with work on the SPRacingF3 target.

**Comment by hydra** [comment]
For 1.8.0 I plan on getting as many serial-port changes in as possible, this now has my attention.  I need to merge in the serial-cleanup branch to master and then this needs rebasing again - sorry, i know it's a pain.

How is your time schedule over the next couple of weeks looking so we can get this done and dusted?

**Comment by ledvinap** [comment]
I can rebase it. Maybe some (simple and safe) parts can be merged into master first.

There are still unanswered issues/design choices, can you review them and the code?

**Comment by hydra** [comment]
ok @ledvinap I'll go though the commits and see how many i can cherry pick soon.

**Comment by hydra** [comment]
oops,  I was commenting on the wrong PR! doh, i thought this was the other one. Previous comment deleted.

Perhaps it's worth creating separate PR's for the stuff to merge into master now, and then it will be easier to review?

I need to refresh my memory on the CC3D schematic to see which pins/timers might be free for this.

Can the current PWM code be updated so that the timers can be used for PWM and softserial?

It's possible that we could also say: no softserial and whatever conflicts with it on the CC3D.

**Comment by Pierre-A** [comment]
guys,
would be bad to give up with softserial on CC3D as it's a nice way to get telemetry on this board.

**Comment by ledvinap** [comment]
The problem with new softserial is that the code needs some signal to check that whole character is received. I implemented timerQueue for this (but this mechanism may be useful elsewhere. HOTT character timing, blackbox throttling come, reply delay in SPort telemetry are hot candidates).

First version used designated timer channel, but that was problem on CC3D (this channel should be on timer with ARR=0xffff). New code uses systick for timer queue. Timing (that was based on systick) is implemented using timer CNT register. Only requirement is that there is one timer that has ARR=0xffff and is not skipped (oneshot 125). This is also necessary for softserial timer, so as long as softserial is enabled, this new function is free.

**Comment by ledvinap** [comment]
As for splitting this this PR (reading diff and writing comments) :
- pindebug is separate, it is nice tool for debugging some problems and can help new coders
- callback may be merged, it should not create any problems until used. It works fine in my local branch
- pwm_rx changes are mostly removal of code duplication, only timer sharing is slightly changed. I would like to update interface in future (make it IO oriented), but it can wait
- serial.h
-- I use MODE_SINGLEWIRE instead of MODE_BIDIR. The functionality is almost identical, IMO my version is slightly cleaner and easier to extend. this can be merged immediately.
-- new softserial supports halfduplex mode, it is enforced for singlewire and is fasted when used on timer channel pair (in comparison with fullduplex mode). There is no point untill softserial is changed
-- UART code support optional DMA. It was partly implemented in master in meantime, may be merged.
-- default modes must be reworked, it is too hard to use as implemented.
-- rxcallback refactoring is ready to merge (I hope you don't mind using `serialReceiveCallback*` instead of `serialReceiveCallbackPtr`. IMO the first one is much easier to read)
- softserial code - the code is complicated. It did rewrite it completely few times and I don;t think it can be much simpler. The queue between capture and processing is eating a lot of CPU cycles, but low latency is impossible otherwise.

- timer.c 
-- timer counting and cycle skip (oneshoot125) is reworked. 
-- timerGetRunningTimeCNT may be optimized a bit
-- this is quite mayor change, needs review, but may be merged separately
-- maybe the code may be special-cased for oneshot. It's bookkeeping is costing few cycles (but I would like to try PWM synchronization for other modes)
-- mostly the changes are improvement of existing aster version
-- delay code is protected by TIME_USE_TIMER, so it may be merged
-- millis must be called at least once per 2^31usec (35 minutes). IMO this is acceptable limitation ;-)

- timer.h
-- channel allocation needs to be solved. New timer code depends on it

- timer_input, timer_output - needs testing, but may be merged. Some changes may result from softserial testing

- timer_queue - needs timing source = channel allocation. Then it may be merged and tested (works when used as periodic 1ms timer for millions of triggers)

rest of code needs to be checked after rebase, but contains no major changes.

**Comment by LupinIII** [comment]
Someone suggested to add my request here, since i can't open an "issue". Petr, could you check out my CF fork, where I implemented the use of UART 4 and 5 on F103V targets?
https://github.com/LupinIII/cleanflight/tree/more_uarts
Unfortunately it's in the "old" way, where everything is duplicated for every port, but maybe you could add the provisions for these ports as well to your rewrite of the serial code. I tested the UARTs by using SBUS and GPS (ublox) on them all (also simultaneously).
UART 4 and 5 are the same as the others, with these exceptions I found:
* the pins are fixed. They have no remapped pins at all
* UART5 can not be served by DMA
* the RX and TX pins of UART5 are on separate GPIOs (C and D)

Would be nice if we could have this if everything gets merged sometime. CLI, SBUS, smartport, GPS and blackbox all at the same time ;)

**Comment by ledvinap** [comment]
Implementing new uarts in my code is quite trivial: https://github.com/ledvinap/cleanflight/blob/local/src/main/drivers/serial_uart_stm32f10x.c

Main problem is that it does use IO abstraction, and it is far from final version. Without IO the merge is a bit difficult ... 

I'll look at merging IO abstraction only, maybe it is way to go ...

**Comment by LupinIII** [comment]
Sure, I didn't mean to add it immediately. Just that you should keep an eye out that your code would not preclude ports that use different GPIOs for RX and TX or do not support DMA for example.

**Comment by hydra** [comment]
@ledvinap Ok, this PR is really old now.  We need to make some decisions to get this and the IO related code finished and merged.

Suggest completing the work on #884.

**Pull request closed without merging**
