### PR TITLE
BUG - Fixed black box gyro logging bug caused by PR#869

### PR DESCRIPTION
**Pull request by SteveAmor**
Oops

### CODE REVIEW

**Comment by ksal0** [comment]
Seems like everything is back to normal. Thanks.

**Comment by hydra** [comment]
No. The solution is to fix the blackbo, logging tool to use tue tenamed field.

Please sumbit a PR that updates the blackbox-log-viewer project?

**Comment by SteveAmor** [comment]
I looked at doing that and decided it was better to make the change that I did for the following reasons:

1. It is not logging pure gyroADC as it averages the reading so it seemed sensible to  keep the name as gryoData.
2. Changes in the Blackbox log viewer code means that further code would need to be added to make it backwards compatible with older logs (field == gyroADC || field == gyroData).
3. Similar changes would also be required in Blackbox Tools code.

**Comment by ledvinap** [comment]
Just curious - I can't find any gyro averaging in current code. Did I miss something?

**Comment by SteveAmor** [comment]
@ledvinap: you're right, it's the prediction that's averaged https://github.com/cleanflight/cleanflight/blob/master/src/main/blackbox/blackbox.c#L603
So I'm not 100% sure my 1st comment is accurate in terms of the true raw gyroADC being written to the blackbox or not.

**Comment by SteveAmor** [comment]
Updated BlackboxViewer here https://github.com/cleanflight/blackbox-log-viewer/pull/13
Blackbox viewer will still read pre V1.9.0 logs correctly.

Will submit another PR for the Blackbox Tools

**Comment by thenickdude** [comment]
IMO the best approach would be to rename the field name descriptors back to gyroData, but keep the variable names in the source gyroADC to match the name of the field those values are read from (so only line 205-207 of blackbox.c would change).

**Comment by SteveAmor** [comment]
@thenickdude and line 784?

**Comment by hydra** [comment]
The problem now though is all the logs generated by 1.9.0 that are out there...

**Comment by SteveAmor** [comment]
So the PR under black box viewer will fix the 1.9.0 logs already out there

**Comment by thenickdude** [comment]
Ah of course @hydra, I didn't think that through. Yeah in that case we want to update the viewers instead of this PR.

**Comment by thenickdude** [comment]
Now fixed in blackbox-log-viewer and blackbox-tools.

**Comment by hydra** [comment]
Thanks everyone.

**Pull request closed without merging**
