### PR TITLE
Moved sonar pin assignments into relevant target files

### PR DESCRIPTION
**Pull request by martinbudden**
Moved sonar pin assignments from sonar.c to relevant target.h files.

Fixes issue https://github.com/cleanflight/cleanflight/issues/1860.

### CODE REVIEW

**Comment by jflyper** [comment]
Can you merge the support for trigger/echo pins on different gpio groups if I send you a patch or even a whole file? I already have a code, but trying to find out how to create a pull-request from my brand new github desktop; it gives me auth error...

**Comment by martinbudden** [comment]
@jflyper , yes. Send me a patch, or the whole file and I'll have a look at merging it into this PR, or making a separate one depending on the scale of the changes.

**Comment by jflyper** [comment]
Here are the files. The mods are actually very small.

[issue_1868_sonar_pin_detection_in_pwmInit.zip](https://github.com/cleanflight/cleanflight/files/146235/issue_1868_sonar_pin_detection_in_pwmInit.zip)

**Comment by jflyper** [comment]
@martinbudden , I have a problem in the `original issue_1860_sonar_pin_assignment` branch; it does not reboot properly when sonar is enabled in the CFC config tab. I don't have the sonar connected, but I don't think it really matters.

Env: NAZE target, running on a banggood clone.

**Comment by martinbudden** [comment]
@jflyper , I'll withdraw this PR temporarily until I have time to investigate.

**Comment by jflyper** [comment]
@martinbudden , I'm doing some investigation myself, but hit another problem.

Quick question. Are triggers should be evenly spaced around 0.1sec intervals?
With both 12.0 stable and current + detection patch, my NAZE clones with RX_PPM+SONAR assigns trigger to RC7, but interval is not even, and very short, sometimes as short as a few msec or so.

12.0 stable, RX_PPM + SONAR, notice the leading PWM pulses.
12 0_stable-rx_ppm sonar

Current + detection patch, RX_PPM + SONAR, RC7 no longer has leading PWM pulses. (Sorry for the different magnification.)
current detection_patch-rx_ppm sonar

12.0 stable, RX_PPM + SOFTSERIAL + SONAR, nice triggers on PWM5
12 0_stable-rx_ppm softserial sonar

Current + detection patch, RX_PPM + SOFTSERIAL + SONAR, nice triggers on PWM5
current detection_patch-rx_ppm softserial sonar

**Comment by jflyper** [comment]
Should I open a new issue?

**Comment by martinbudden** [comment]
@jflyper sorry the delay in replying.

Sonar triggers should go off about every 70ms. If they are too closely spaced then the echoes from sequential pulses can be confused and give an erroneous distance reading.

This is fixed in my PR that adds support for the SRF10 sonar rangefinder, https://github.com/cleanflight/cleanflight/pull/1787 , but no harm in opening a new issue.

**Comment by martinbudden** [comment]
@jflyper I've also submitted the code you sent me as PR https://github.com/cleanflight/cleanflight/pull/1907

**Pull request closed without merging**
