### PR TITLE
Add 'vbat_hysteresis' parameter

### PR DESCRIPTION
**Pull request by ethomas997**
Adds a 'vbat_hysteresis = #' CLI parameter, where '#' is the battery-alarm-hysteresis value in 0.1V increments. Default value is 1 (0.1V), which mirrors the current (v1.13.0) behavior.  Setting "vbat_hysteresis=0" can reduce time-delay lag in the battery-alarm response, especially on 1S and 2S setups.  This CLI parameter has been [implemented](https://github.com/borisbstyle/betaflight/pull/302) in Betaflight.

The VBATT_HYSTERESIS functionality was added when the battery-state detection code was reworked in Cleanflight a while back.  My feeling is that hysteresis is not needed and negatively impacts the battery-low alarms; it adds an annoying time-delay lag to the warning-beep response, and on 1S micro setups the alarm tends to get "stuck" on when it shouldn't.  With VBATT_HYSTERESIS removed, the alarm tracks the state of battery like it should.

I posted a PR on Betaflight to remove VBATT_HYSTERESIS, but some felt that it should stay.  BorisB requested that it be made a CLI parameter, so I posted a PR to do that, and it has been [merged](https://github.com/borisbstyle/betaflight/pull/302) in to the main branch.

--ET

### CODE REVIEW

**Comment by ethomas997** [comment]
Also, posted this issue on subject of battery alarm settings:  Improvements to VBAT alarm settings #2220

--ET

**Comment by hydra** [comment]
@ethomas997 yes i remember this, merging.

**Comment by hydra** [comment]
ahh.. except there is a small problem.  adding a new parameter in the middle of a structure used as a parameter group is not allowed.  they must be added to the end of the structure.  can you update the PR please.

Please also verify the default value of the new setting when a user upgrades from 1.13.0 to a build with the new parameter added to the end.  - without erasing the entire chip/eeprom.

please report your findings in comments below.

**Comment by ethomas997** [comment]
@hydra I've moved the new 'vbathysteresis' field to the end of parameter group in "battery.h".

If the user upgrades from 1.13.0 to a build with the new 'vbat_hysteresis' parameter without erasing the entire chip/eeprom, the 'vbat_hysteresis' parameter ends up with an odd value (like 9 or 118).  Doing a Reset Settings to defaults sets the 'vbat_hysteresis' value to the proper default (1).  Is there a way to make it handle the upgrade better?

--ET

**Comment by ethomas997** [comment]
On Betaflight they've modified it so the hysteresis is only applied downwards of the configured minimum levels, and not downwards and upwards, as per [BF PR #831](https://github.com/betaflight/betaflight/pull/831).  I think this is a good improvement.  I can make this PR also do the same if desired; let me know...

--ET

**Comment by hydra** [comment]
ok, with regards to the PG reset invalid value issue don't worry, that is already in-hand in #2395.

yes, please make the change to the hysteresis as you suggest as it seems like that solution is liked by you and other betaflight testers.

**Comment by ledvinap** [comment]
@hydra: Invalid value after upgrade is strange - even old code did reset the structure first, then writing data from EEPROM ...

**Comment by ethomas997** [comment]
Rebased, modified so hysteresis is only applied downwards, and updated unit test.  Should be ready for merge.

--ET

**Comment by ethomas997** [comment]
Also, doc update adding 'vbat_hysteresis' and doing minor improvements to other 'vbat' descriptions.

--ET

**Comment by ethomas997** [comment]
Rebased to master 2016-10-30.  This PR should be ready to be merged in.

--ET

**Comment by hydra** [comment]
thanks. I will take another look at this asap.

**Comment by hydra** [comment]
looks good now, very minimal changes. merging.

**Pull request merged**
