### PR TITLE
Reinstatement of OPBL support for CC3D.

### PR DESCRIPTION
**Pull request by martinbudden**
Code fits if AUTOTUNE and BLACKBOX are ommitted (SONAR and DISPLAY now fit).

### CODE REVIEW

**Comment by flacjacket** [comment]
`AUTOTUNE` has already been removed in favor of `GTUNE`, so that is unnecessary, seemingly only `BLACKBOX` needs to be removed.

**Comment by martinbudden** [comment]
Can you please reinstate this. The CC3D is a bit of a nightmare to program, even more so if you have a Mac.

Removing AUTOTUNE and BLACKBOX allows the code to fit. Those who want these features are no worse off than before, whereas everybody else benefits from having OPBL support.

**Comment by martinbudden** [comment]
Oops, accidentally closed this. Reopened.

**Comment by martinbudden** [comment]
There are actually two issues here:
1. does the `cleanflight_CC3D.bin` file form part of the release?
2. does the build support OPBL, that is does the makefile support a OPBL target, and is stm32_flash_f103_128k_opbl.ld included in the build?

I argue that whether or not `cleanflight_CC3D.bin` is shipped as part of the release, the build should certainly support OPBL.

I'm doing some development work using a CC3D as my test FC and I am spending a totally disproportionate amount of time making sure I've got the correct makefile as I swap between branches.  Time spent patching makefiles is time not spent writing code and testing.

**Comment by hydra** [comment]
We made a conscious descision to drop support for the bootloader for a number of reasons, the main ones being:
1) the additional testing overhead (including the need for GCS to test the build).
2) problems with USB VCP not working.
3) user confusion between OPBL and non-OPBL builds.
4) additional complication of the build and release process.
5) the build continually breaking when stuff doesn't fit in the CC3D build, this diverts developer time away from coding.

If you can solve all the above we can consider re-instating it. :smile: 

I do however share your pain with regards to swapping branches.

Suggest solving your flashing issues.  Perhaps flash via OpenOCD/SWD to make your life easier.

**Pull request closed without merging**
