### PR TITLE
IBUS new sensor 2

### PR DESCRIPTION
**Pull request by hali9**
This is PR for https://github.com/cleanflight/cleanflight/issues/2833 (second try).

### CODE REVIEW

**Comment by McGiverGim** [comment]
Please, don't make a push every time that you make a commit. Work only with your local repo.

**Comment by mikeller** [comment]
@hali9: Why did you close your first pull request, instead of just fixing it like you were instructed?

This needs some more fixes:
- tests are still failing;
- some F3 targets are overflowing I suggest you move https://github.com/cleanflight/cleanflight/blob/master/src/main/target/common_fc_pre.h#L111 to below https://github.com/cleanflight/cleanflight/blob/master/src/main/target/common_fc_pre.h#L141

(Also, please remove the other occurrences of `#define TELEMETRY_IBUS` in this file.)

Once this is done and all tests pass, please rebase and squash the commits into one.

**Comment by McGiverGim** [comment]
@hali9 Some news about this PR? I'm very interested in.

**Comment by qba667** [comment]
Improved version introduced in https://github.com/cleanflight/cleanflight/pull/3000

**Comment by mikeller** [comment]
@qba667: I think this has been superseded by betaflight/betaflight#4978? If so, can you close please?

**Comment by qba667** [comment]
@mikeller this PR should closed - please see
https://github.com/cleanflight/cleanflight/pull/3000

**Pull request closed without merging**
