### PR TITLE
Code from jflyper. Fixes issue 1868

### PR DESCRIPTION
**Pull request by martinbudden**
I'm submitting this PR on behalf of @jflyper who kindly sent me the code.

Adds separate gpios for trigger and echo.

### CODE REVIEW

**Comment by hydra** [comment]
This still needs to be fixed by the looks of things.  Suggest rebasing changes onto master and merging asap.  We could also release v1.13.1 with this.

I think this got missed because of all the different issues, PR's and cross referencing between them.  it is hard to tell if this still needed doing even now.

**Comment by jflyper** [comment]
@martinbudden @hydra 
Shall I rebase in my branch and submit as a new PR?
There's a single line conflict with regard to PG change.

**Comment by martinbudden** [comment]
@hydra , @jflyper , I've only just seen this - I must have missed a github notification.

Anyway, rebased.

**Comment by jflyper** [comment]
🆒 Thank you!

**Comment by hydra** [comment]
merged, thanks!

**Pull request merged**
