### PR TITLE
Fail Travis build when PR contains warnings

### PR DESCRIPTION
**Pull request by ledvinap**
Makefile will pass -Werror to gcc when building Travis Pull
request. Branches are build normally.

This PR should fail now - there are warnings in master

### CODE REVIEW

**Comment by ledvinap** [comment]
Added unittest handling too. Works as desired.

Checks should go fine when warnings in master are removed

**Comment by hydra** [comment]
excellent, that should help the authors of PR's fix their code before we get involved.

**Comment by hydra** [comment]
I'll merge now, hopefully master will build afterwards :smile:

**Comment by hydra** [comment]
@ledvinap the build failed!

https://travis-ci.org/cleanflight/cleanflight/jobs/134477685

Can you take a look?

**Comment by martinbudden** [comment]
@hydra this should fix it: https://github.com/cleanflight/cleanflight/pull/2193

**Comment by hydra** [comment]
@martinbudden nope, that didn't fix it.  PR fails to build.

**Comment by ledvinap** [comment]
The problem is that CC is exported by Travis, so it get's inherited to submakefile (in `make test`)

**Pull request merged**
