### PR TITLE
Runtime ESC count / gpio / pin detection

### PR DESCRIPTION
**Pull request by 4712**
Runtime ESC gpio/pin detection
Runtime ESC count detection

Optimizes #1246 and #1465.

### CODE REVIEW

**Comment by hydra** [comment]
can you remove the RMDO3 target support from this please.

Not adding any more targets to cleanflight at the moment, the RMDO build will be fine for now

**Comment by 4712** [comment]
Why remove and how?
It is only the flash size different from RMDO...

**Comment by hydra** [comment]
yes i know. Each PR should be focussed on doing one thing.
add another commit to delete the RMDO3 changes.
I can then squash the commits in the merge

**Comment by 4712** [comment]
Ok, will try.

**Comment by 4712** [comment]
Is this OK?

**Comment by dkisselev** [comment]
Hi @4712,

Hydra said he will squash for you in this case, but just as an fyi/learning point, here's a tutorial on what he means: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Squashing basically undoes your two commits and re-creates them as if they were one, since the second commit isn't really another change in the context of cleanflight, it's just a fix for the first change.

By that tutorial you will just need to do git rebase -i HEAD~1, and change 'pick' in front of the 'delete RMDO3...' commit to 'squash', so Git will combine the two for you.

After that check your history to make sure everything looks good, then 'git push -f' to OVERWRITE your branch on github and this PR will update to show just the one "clean" commit. This makes cleanflight's history look cleaner because the one commit shows all the relevant changes.

Note that push -f is generally pretty dangerous, you never want to do it when there's a chance that someone else has checked out or made any commits on your code since their repository won't sync up with yours anymore. In this case it's reasonable to assume that it's safe since it's unlikely that someone is using your repository as a base for anything (ie, it's just where you are making your own changes, not a shared repo like cleanflight itself)

**Comment by 4712** [comment]
Hi @dkisselev thanks for the commands. I finally had to  "git rebase -i HEAD~2". But then it worked. Without your help, never... 
I guess, I never will learn git and always will ask for help ;)

**Comment by dkisselev** [comment]
Looks great! I'm glad you worked it out, always happy to help someone learn more git (it's pretty awesome). I have no idea why I said HEAD~1, thinking back that makes so sense but I'm glad you worked it out.

**Comment by hydra** [comment]
great, good to remove some of the target specific code here.

**Comment by hydra** [comment]
I'm not a fan of usb1WireInitialize().

Since it now does two things, 1 count ESCs, the value of which is used by the CLI to check the range.  and 2, it changes GPIO modes.  If the range is invalid the GPIOs are still configured.

why do all the GPIO's need to be configured before they're actually used?  Shouldn't just the GPIO for pass-though esc be configured?

also, i notice a fix for beeper,  that seems very out of place.  under what exact circumstances does it occur?

**Comment by hydra** [comment]
I will merge the existing code, and some cleanup work I did, but the points above need to be answered and addressed so I will leave this PR open for now since it needs additional commits.

**Comment by hydra** [comment]
Please also use an indentation level of 4 not 2 (use 4 spaces, no tabs).

**Comment by 4712** [comment]
usb1WireInitialize() is essential. The whole CLI stuff can be removed - my opinion.
BLHeliSuite handles all the negotiations and uses MSP for it.
usb1WireInitialize() is needed to initialize all servo lines to go high, which will cause to activate the bootloaders of all ESC.
Any reason why this is not recommended?

**Comment by 4712** [comment]
@hydra pr is now ready for merge.
usb1WireInitialize() only retrieves the ESC GPIO settings and the number of ESC.
The first call of usb1WirePassthrough() sets ESC GPIO to Mode_IPU and adds a short delay.
bepperSilence() works adequate in usb1WirePassthrough() , only short beeps can be heard (if beep condition is valid) while switching the ESC channels.

I left 1wire CLI active, but added define USE_SERIAL_1WIRE_CLI in target.h, so it can be excluded easily.

**Comment by 4712** [comment]
Will close here and open another pr.
Needs to be revised, again...

**Pull request closed without merging**
