### PR TITLE
Implement RX to servo mixer

### PR DESCRIPTION
**Pull request by hydra**

### CODE REVIEW

**Comment by hydra** [comment]
[cleanflight_2.1.0_NAZE-20170405-2010.zip](https://github.com/cleanflight/cleanflight/files/977303/cleanflight_2.1.0_NAZE-20170405-2010.zip)
[Uploading cleanflight_2.1.0_SPRACINGF3-20170405-2010.zip…]()

**Comment by hydra** [comment]
to try this, change motor outputs to servo outputs using `resource` command.
then use `mixer RX_TO_SERVO`.
configure an RX as usual.

**Comment by hydra** [comment]
tested on SPRACINGF3 with 8 PWM inputs mapped to 8 PWM outputs using the following configuration

```
# Cleanflight / SPRACINGF3 2.1.0 May  4 2017 / 20:18:55 (18bea4a)
resource MOTOR 1 NONE
resource MOTOR 2 NONE
resource MOTOR 3 NONE
resource MOTOR 4 NONE
resource MOTOR 5 NONE
resource MOTOR 6 NONE
resource MOTOR 7 NONE
resource MOTOR 8 NONE
resource SERVO 1 A06n
resource SERVO 2 A07n
resource SERVO 3 A11n
resource SERVO 4 A12n
resource SERVO 5 B08n
resource SERVO 6 B09n
resource SERVO 7 A02n
resource SERVO 8 A03n
mixer RX_TO_SERVO

feature -RX_PPM
feature RX_PARALLEL_PWM
map TAER1234
```

**Comment by jimmyhorns** [comment]
Tested using Naze32 acro rev6 10DOP, JR XG14 Tx and JR RG031BX (xbus only output) Rx.

Used the attached Naze firmware. Flashes fine.

Configured UART2 to serial Rx in 'Ports'
Selected serial based receiver and Xbus type B in 'Configuration'
In 'Receiver' changed channel map to AER2T134 (and hit save)

Onto the CLI and then:

mixer RX_TO_SERVO   
#note that this displays as PPM to Servo in the GUI configuration after doing this.
#then remove the motor assignments for motors 1 through 6

resource MOTOR 1 none
resource MOTOR 2 none
resource MOTOR 3 none
resource MOTOR 4 none
resource MOTOR 5 none
resource MOTOR 6 none

#then assign servos to the appropriate outputs (these were originally the designated pins for MOTOR 1 through 6).

resource SERVO 1 A08n
resource SERVO 2 A11n
resource SERVO 3 B06n
resource SERVO 4 B07n
resource SERVO 5 B08n
resource SERVO 6 B09n

#When you are done if you type resource in the CLI you should end up with a listing that looks like this:

# resource
resource BEEPER 1 A12n
resource SERVO 1 A08n
resource SERVO 2 A11n
resource SERVO 3 B06n
resource SERVO 4 B07n
resource SERVO 5 B08n
resource SERVO 6 B09n
resource PPM 1 A00n
resource PWM 1 A00n
resource PWM 2 A01n
resource PWM 3 A02n
resource PWM 4 A03n
resource PWM 5 A06n
resource PWM 6 A07n
resource PWM 7 B00n
resource PWM 8 B01n
resource LED_STRIP 1 A06n
resource SERIAL_TX 11 A07n
resource SERIAL_TX 12 B01n
resource SERIAL_RX 11 A06n
resource SERIAL_RX 12 B00n


This will then give you direct servo output or passthrough, whether the board is armed or not, with the following assignments:

Servo 1  === Aileron / Roll
Servo 2 === Elevator / Pitch
Servo 3 === Rudder / Yaw
Servo 4 === Throttle
Servo 5 === Aux 1
Servo 6 === Aux 2


This is working fine with both Analog and Digital servos

Thanks very much for your help with this, solves my problem perfectly. For what its worth now I know how to get things working properly with AIRPLANE mode and using resource to correctly assign the servos im likely to give that a go too in some of my fixed wing models :)

**Comment by hydra** [comment]
great.  i use CF on a couple fixed wings, the stabilisation really makes a big difference, especially in high-wind!

thanks for the feedback.

**Comment by Starejpes** [comment]
Hi Hydra, I am several nights trying to make SPRACINGF3 with 8 PWM inputs mapped to 8 PWM using Hitec radio. I used your advice from May 5, 2017 it is working somehow but not with AETR1234 mapping. Is there any documentation to allow me to understand resources and their mappings. Would you be able to help me? Thank you.

**Comment by mikeller** [comment]
@Starejpes: https://github.com/betaflight/betaflight/wiki/Betaflight-resource-remapping

**Comment by Starejpes** [comment]
Hi,
I am already familiar with the link you sent me, Thank you, unfortunately it does not bring any light for me.
1/ I have receiver connected to SP Racing F3 board and it display movements of the controls well. Screen shot Receiver.PNG.
2/ I removed Motors (profile Airplane) from resources I am getting movement on the different servos I expect to get
Pitch on servo 7
Roll on servo 4, 5
Yaw on servo 6
Trottle on nill
3/ I do not understand software philosophy to solve the issue. Can anybody help to understand?
Best regards

Jindrich Kratochvil
67A North Beach Road, North Beach WA 6020
Mobile: +61 410 389 087
Email: jkratochv@hotmail.com

**Pull request merged**
