### PR TITLE
1-wire-pass-through-vcp

### PR DESCRIPTION
**Pull request by 4712**
also changed uart 1wire-pass-through to avoid need of FC reboot after
exit.

### CODE REVIEW

**Comment by 4712** [comment]
For testing use BLHeliSuiteBeta 14.4.0.4 or above
https://github.com/4712/cleanflight/releases/tag/v1.12.0-1wire-pass-through-vcp

**Comment by hydra** [comment]
great!!  this will make a lot of people happy.

can other people please try this out?

**Comment by Arakon** [comment]
Tested on a CC3DF3 (CC3D with F3 chip instead of F1) and it works flawless.

**Comment by 4712** [comment]
Superseded by https://github.com/cleanflight/cleanflight/pull/2019

**Pull request closed without merging**
