### PR TITLE
i2cWriteBuffer() for F3 targets

### PR DESCRIPTION
**Pull request by jflyper**
A rush job solution for #2111 , but it works.

Converted the single byte i2cWrite() to loop for the given buffer, just like the i2cRead() does.
A new i2cWrite() calls the converted i2cWriteBuffer().

### CODE REVIEW

**Comment by ledvinap** [comment]
@jflyper : This PR is empty.
Also I2C functionality can be improved as part of new feature PRs, no need to hurry/get it out in 1.13

**Comment by jflyper** [comment]
@ledvinap 
Oops!  I thought I could stuff the PR in before anyone sees it empty!

Yes, the I2C functionality definitely needs improvements; multi channel, ...

**Comment by hydra** [comment]
as a general principle we don't want unused code in the codebase.  prefer as part of a feature PR instead. @ledvinap is correct.

**Comment by hydra** [comment]
rather than leaving this PR open for eternity I'll close it since it's essentially dead code.  I'm happy to merge it in as part of supporting some new external device.

**Pull request closed without merging**
