### PR TITLE
I have added new BMP280 barometer support in cleanflight

### PR DESCRIPTION
**Pull request by rlehey**
It builds

### CODE REVIEW

**Comment by JohnieBraaf** [comment]
Why did you add it to makefile and target.h for all the boards? Should you not just add it only to the baords that actually have this sensor?

**Comment by rlehey** [comment]
I follow the bmp085 which is a similar sensor.
It could be a replacement.
There is no target specific code, so it doesn't hurt to build it.

**Comment by rlehey** [comment]
Also it can connect by breakout board to any target with i2c. This is how I test it.

**Comment by JohnieBraaf** [comment]
I would say you only define the sensors actually present on the target. 
Otherwise you should also add all the other ones no?

**Comment by rlehey** [comment]
See my comment just before your. It can connect to any target using I2C breakout.

**Comment by JohnieBraaf** [comment]
Yeah, that makes sense

**Comment by JohnieBraaf** [comment]
How do you make cleanflight pick the right sensor?

**Comment by rlehey** [comment]
It's automatically detected, the case-switch in sensors/initialization.c, if not detected then it will try another or else disable that type of sensor. So without it connected also still works.

**Comment by rlehey** [comment]
What's the status on this?

**Comment by developingchris** [comment]
I have a board with a bmp280, that I'd love to get support for. What needs to happen to this, for it to be in the next release?
@JohnieBraaf  ?

**Comment by hydra** [comment]
There are older existing pull requests that need to be addressed first, there's quite a backlog.

Bugs are prioritized over new features too.

**Comment by hydra** [comment]
Oh, and i need to be able to test the code before its merged but i dont have a board with a BMP280 here. Unit tests would be good too.

**Comment by rlehey** [comment]
http://www.watterott.com/en/BMP280-Breakout is what I used

**Comment by developingchris** [comment]
@hydra being rather new to this space, is there anything I can do to help with those? Can I tag the ones with bad travis builds or something, in a way to triage bugs that can be paid attention to?

**Comment by hydra** [comment]
Yes, submittig PRs that fix the bugs would help immensely.

**Comment by stronnag** [comment]
@rlehey , you may also consider that somewhat less disingenuously describing the target of this patch may help merging into main line. Specifically, rather than spamming all targets, creating a dedicated target (such as DODOF3) may more accurately identify the real purpose of the PR and thus hasten its acceptance. I would council against the  terms such as SERIOUSLY or WOW in creating such a target if you intend the PR to be taken, dare I say it, seriously.

**Comment by rlehey** [comment]
the sensor can be used by other targets with breakout boards.

the same way there is BMP 085/180 support now. anyone making a commercial
for profit board with that?

**Comment by rlehey** [comment]
my PR adds support for the barometer.
I have no idea what dedicated target you are talking about. I've added it
into every target that had i2c headers where external board can be
attached. last I checked committing support for new hardware didn't require
having commercial interest in a particular target.

**Comment by thenickdude** [comment]
[AfroMini revision 3](http://abusemark.com/store/index.php?main_page=product_info&cPath=1&products_id=45) is now shipping with this BMP280 barometer.

**Comment by FenomPL** [comment]
@hydra Any chance to merge it soon?

**Comment by theantnest** [comment]
Hey guys, would appreciate this to be merged. Thanks for all your hard work

**Comment by hydra** [comment]
The servo/mixer code and related configurator changes to support the tilt flight modes are currently the highest priority.

Some unit tests for this PR wouls help immensely.

**Comment by theantnest** [comment]
Please let me know if there's any way I can help out (in any way - not just related to this pull request). I know screw all about coding, but have a pretty decent lab kitted up for hardware, and am no noob about firmware and protocols.

**Comment by thenickdude** [comment]
@theantnest unit tests that check for datasheet-specified conversions between barometer raw readings and the output pressures/temperatures would be the main testable component here. The preexisting `baro_bmp085_unittest.cc` can be used as a template.

**Comment by add1ct3dd** [comment]
Any progress on this? Could do with this being in the next release (imo).

**Comment by leothehuman** [comment]
I have checked this out on afromini rev3, the code works, nothing is broken as far as I can see. The values it outputs look correct, but very imprecise. 
Changes look like a port from baseflight.
I would suggest to limit the impact to naze boards, as attaching separate bmp280 seems unlikely.
I would consider baro not working on afromini rev3 as a bug and give it a priority.

**Comment by xoxota99** [comment]
What's blocking this merge? Is it just the backlog of pull requests? Something else?

**Comment by leothehuman** [comment]
@hydra please, consider accepting this. It works and helps people with rev3 afrominis.

**Comment by flacjacket** [comment]
I've taken this code and added the requisite unit tests, see #1316.

**Comment by hydra** [comment]
merged.

**Pull request closed without merging**
