### PR TITLE
target file clean up

### PR DESCRIPTION
**Pull request by henn1001**
It always bugged what a complete mess those files where so i´m trying to make them cleaner with this pr. Introduce some standardization...

It´s still WIP as i haven´t double checked everything for errors, but i hope that something like this will be welcomed!? 

I think it´s also time to slowly think about ways to rip out all this target depended ifdefs out of the codebase  and create a extra file in the /target folders for timer/pwm/interrupt setups etc.

### CODE REVIEW

**Comment by hydra** [comment]
needs a rebase.  please wait till 1.12.0 is out, then rebase.

**Comment by henn1001** [comment]
ok

**Comment by martinbudden** [comment]
> I think it´s also time to slowly think about ways to rip out all this target depended ifdefs out of the codebase and create a extra file in the /target folders for timer/pwm/interrupt setups etc.

This has been done in betaflight. I won't give a PR link, since it has happened over a number of different PRs. The betaflight work should be ported over at some point.

**Comment by hydra** [comment]
let's address this as part of the IO changes in 1.15.0

**Pull request closed without merging**
