### PR TITLE
Added script to dump cleanflight CLI config.

### PR DESCRIPTION
**Pull request by mikeller**
Hey there.

I wrote a little bash script to make it easier / quicker to dump the CLI config from cleanflight and derivatives. I think it might be of use to others.
Let me know if you want to include it in the cleanflight repo.

Cheers
  Michael Keller

### CODE REVIEW

**Comment by lostcontrol** [comment]
You probably need to configure the serial port settings (speed, etc) first. I guess it defaults to 9600 but maybe you use your script after having connected with Cleanflight configurator first!?

I use two small Python scripts for backup and mainly restore since this is the tricky part. I would personally prefer to see something in e.g. Python since it would make it a bit easier to port to e.g. Windows (not that I really care about Windows at all but if it can run everywhere it would be even better).

But I really think this kind of script should be part of Cleanflight. Now, I have seen discussions to remove CLI completely and do everything over MSP...

**Comment by mikeller** [comment]
Fair enough re python. The idea is that you connect with the cleanflight configurator and open the CLI tab, then run the script, and then scrape the output from the CLI terminal in the configurator.

Sounds like your scripts are more advanced, would you be willing to share them?

**Comment by lostcontrol** [comment]
Yes I could share my scripts but they would need more work first. I wanted them to be very simple.

There is http://www.etheli.com/CF/clipytool/ which is more advanced and probably covers all the needs. I haven't try it but it is probably a good one. Maybe instead of added a backup/restore script to Cleanflight, a link in the documentation could be added to some of these scripts. I'm sure they are many on the web.

**Comment by mikeller** [comment]
Yes, clipytool is exactly the tool I was looking for. Thanks for pointing it out. Want me to submit a pull request for updated documentation that includes a reference to clipytool?

**Comment by lostcontrol** [comment]
I'm not a Cleanflight developer but I think it would be worth pointing to it in the documentation. When I started using Cleanflight some months back, I would have really appreciate a link to it in the documentation :wink: So I would say, please submit a PR (maybe wait for @hydra to comment on this first).

**Pull request closed without merging**
