### PR TITLE
CC3D - PPM glitch fix

### PR DESCRIPTION
**Pull request by edusteinhorst**
A periodic glitch happens on AUX channels when using OneShot on CC3D,
especially with faster update loops. This is caused by a race condition
while forcing timer overflows and sharing the timer for PPM capture.
It causes the craft the fall out of the sky when using a switch to arm.

Please see edusteinhorst@930c6ce69d103a9a666717e73e847f2dab4de119

This fixes cleanflight/cleanflight#1748,
fixes borisbstyle/betaflight#64, fixes borisbstyle/betaflight#127

### CODE REVIEW

**Comment by edusteinhorst** [comment]
I couldn't reproduce the glitch anymore with these changes. I tested the outputs using my oscilloscope and everything looks right (Oneshot, PWM@400Hz, PWM@8KHz). I also tested RSSI_ADC and SOFTSERIAL. Couldn't test SONAR because I don't have the model supported, but should work normally.

One thing I did notice is that servo output is not right for SERVO_TILT. When SERVO_TILT is enabled motors 1,2,3 are output on S1,S2,S3 respectively, and motor 4 is output on S5. Pitch servo is output on S4 and S6 outputs a PWM @ 400Hz. No roll servo. This issue is already present in the master, but IMO would be better served by a separate PR.

Here's a CC3D compile from latest source if anyone wants to test it (please remove props!):

[cleanflight_CC3D.zip](https://github.com/cleanflight/cleanflight/files/122044/cleanflight_CC3D.zip)

**Comment by hydra** [comment]
thanks for the PR. I will give this a whirl.  Bit late for including in 1.12.0 final. more testing required.

**Comment by edusteinhorst** [comment]
No problem!

**Comment by borisbstyle** [comment]
@hydra This one doesnt affect other targets at all. Can be added

**Comment by Luckylalla** [comment]
Hello has this been implemented in 1.12.0 or just in the line for 1.13? As i am running cc3d on 1.12.0 and have exactly the problems mentioned  Ill try the .zip and see if that helps.

Greetz.

**Comment by edusteinhorst** [comment]
Please report back after testing. Just be aware that the zip is based on the master from early Feb, check your configurations.

**Comment by Luckylalla** [comment]
Thank you for the quick answer but I fried my cc3d today so I can't test it anymore sorry. Installing naze32 tomorrow. 

Greetz lucky.

**Comment by hydra** [comment]
merged.

**Pull request merged**
