### PR TITLE
Port of refactored beeper code 181_1

### PR DESCRIPTION
**Pull request by ethomas997**
This the "Port of refactored beeper code #669" modification applied to version 1.8.1 (4/4/2015) of the code.  See the previous PR for info:  http://github.com/cleanflight/cleanflight/pull/669

Code and hex test file are also here: http://www.etheli.com/CF/refactoredBeeperCode

--ET

### CODE REVIEW

**Comment by Lordnibbler** [comment]
:+1: nice

**Comment by hydra** [comment]
@ethomas997 merged, please test master and verify beeper code is as you expect, there were some minor conflicts with the failsafe code due to the recent failsafe changes.  Please comment on here once you have tested it and open a new PR to fix anything that's not right if possible.

**Comment by digitalentity** [comment]
@hydra, @ethomas997  this commit breaks flight_failsafe_unittest.

**Comment by hydra** [comment]
Ahh yes, I remembered it would half way through the merge and then forget to go back and update it.  Just a couple of stubs to add and stub call counters to verify I expect.

@ethomas997 can you take a look and create a PR that updates the tests and I can merge it tomorrow?

**Comment by ethomas997** [comment]
Sure; will do.

**Comment by hydra** [comment]
Please can you re-test the current master, I did a bunch of cleanup commits.

I'm not entirely happy with:

* the mode also being used for priority.
* BEEPER_MULTI_BEEPS is exposed, should only be used internally
* BEEPER_STOPPED is exposed, should only be used internally
* The queueConfirmationBeep has different timings for one beep vs more than one beep can get out of sync, perhaps a constants used in the declaration of `beep_confirmBeep` and in `queueConfirmationBeep` would fix this.
* queueConfirmationBeep doesn't actually queue anything, it's name is misleading.
* beeperCalculations could probably be renamed to something like processBeeperCommand - each entry in the sequence is a command (on duration, off duration, repeat, stop).

**Comment by hydra** [comment]
oh, and i wasn't a fan of BEEPER_RX_SET.  I think beeping out GPS fix should work like queueConfirmationBeep currently does.  i.e.  conditionally call a new method if GPS is enabled: `beepStatus(gpsFix, gpsSatCount)`, update the multibeep array, call `beeper(BEEPER_MULTI_BEEPS)`.

That way the switch statement can be replaced with a simple table lookup for beepPtr based on the index of the mode.

**Comment by hydra** [comment]
I have addressed a few of the items noted above in 064de090a06222a39181eec6137aa9b31514c89e.  IMHO The code is much cleaner now.

**Comment by ethomas997** [comment]
@hydra  I tested the master (at 1d069ad), beeper functionality looks (sounds) good.

--ET

**Comment by ethomas997** [comment]
I think "beeper.c"  doesn't need:  #include "flight/failsafe.h"

--ET

**Pull request merged**
