### PR TITLE
Added minimal MAVLink telemetry

### PR DESCRIPTION
**Pull request by digitalentity**
This PR implements a subset of MAVLink protocol and can provide interoperability with MAVLink based OSD (i.e. unmodified minimOSD) and antenna trackers built for ArduCopter, APM or PX4 boards.

### CODE REVIEW

**Comment by thenickdude** [comment]
Very nice! Out of interest I checked the code size, this is the current dev head:

```
   text	   data	    bss	    dec	    hex	filename
 114668	    264	  12948	 127880	  1f388	./obj/main/cleanflight_NAZE.elf
```

And this is the PR:

```
   text	   data	    bss	    dec	    hex	filename
 116420	    260	  13556	 130236	  1fcbc	./obj/main/cleanflight_NAZE.elf
```

So it's just 1752 bytes of text and 608 bytes of BSS, pretty impressive for the source-code size. I guess that's the advantage of MAVLink's "header only" approach.

**Comment by digitalentity** [comment]
Yes, MAVLink's footprint is pretty low, mostly due to the header-only approach - only used functions are being linked in. However this PR uses very limited subset of MAVLink protocol - only messages, needed for OSD or Antenna tracker to work.

Didn't have the chance to test with actual minimOSD hardware, but QGroundControl software is able to parse the telemetry string and display valid HUD. Attitude, altitude, heading and voltage are tested. GPS piece of code is completely untested yet - don't have a GPS receiver connected to my development CC3D board.

**Comment by digitalentity** [comment]
Rebased to latest master

**Comment by digitalentity** [comment]
Squashed today's commits and rebased against current master. MAVLink telemetry is now compatible with minimOSD out of the box (no need to configure baud rate).

**Comment by digitalentity** [comment]
Tested this with minimosd-extra firmware today. Runs just fine and takes only 3 wires from CC3D to minimOSD board (GND, +5V, TX). Can be shared with MSP without any effort. Can probably be shared with NMEA GPS or with SerialRX with some effort (#782, #713).

**Comment by digitalentity** [comment]
Doing some testing and fixing today. Will squash commits after fixing some bugs.

**Comment by digitalentity** [comment]
Fixed some bugs with altitude display. Rebased. Should be safe to merge, IMO.

**Comment by stronnag** [comment]
Nice. Updated mwp to work with this mavlink subset. It would be nice if the sensors were reported in the MAVLINK_SYS_STATUS structure.

**Comment by digitalentity** [comment]
@stronnag done in d31b0788494d2c4ac2f6808ea1edcae11adc9c2a. However this patch does not build on CC3D with OPBL due to flash size limitation.

**Comment by stronnag** [comment]
Status note rather than a problem report:
I've been testing this on a Naze32 with USART1 and softserial. With USART1 it is highly reliable, and I 
can switch between MSP / Mavlink / MSP etc on arm / disarm for as long as I have the patience to test. With softserial, it appears the soft serial subsystem gets corrupted within c. 3 minutes or less, resulting in extensive CRC errors at the Mavlink receiver, and a failure of the board to respond to MSP on disarm. 

This is more a comment on soft serial limitations (which is the subject of other PRs) rather than this PR, which just provokes known soft serial behaviours.

**Comment by digitalentity** [comment]
Yep, that's pretty much a softserial limitation. Did you have a chance to test the d31b0788494d2c4ac2f6808ea1edcae11adc9c2a? Does it work for you?

**Comment by stronnag** [comment]
I've just tested  d31b078, works fine, thank you.

**Comment by stronnag** [comment]
I've also modified my 3DR settings (which penalise MSP throughput), and that fixes the softserial errors.I'm getting c. 33 messages / sec over 19200 soft serial on a flip32+. Good work. I'll try and fly it this weekend.

**Comment by stronnag** [comment]
Tested with flip32+ and GPS. Works as expected.

**Comment by digitalentity** [comment]
Rebased and squashed commits for a clean merge.

**Comment by digitalentity** [comment]
LTM is probably a better candidate for new telemetry.

**Comment by digitalentity** [comment]
Reopened, rebased.

**Comment by digitalentity** [comment]
@hydra what are the chances of this PR making it into 1.12 or 1.13?

**Comment by Linjieqiang** [comment]
It's great for me to use 3DR'sTower to control it by my phone .Thanks for your work!

**Comment by digitalentity** [comment]
Sorry guys, was migrating iNav to a different repo.

**Comment by Susurrus** [comment]
Any movement on this? I'd love to use QGC or Tower to interface with my Cleanflight-running drone.

**Comment by digitalentity** [comment]
@Susurrus 
Some time ago @hydra mentioned scheduling this for 1.13 or 1.14

**Comment by Susurrus** [comment]
So did this get merged then or why was it closed?

**Comment by digitalentity** [comment]
Accidentally deleted the branch, sorry :)

**Comment by Susurrus** [comment]
You still working on getting this merged then?

**Comment by digitalentity** [comment]
Yes, this is going to be merged to CF 1.13

**Comment by digitalentity** [comment]
@hydra 
I did some bugfixes and improvements to MavLink support and did a rebase against latest master. I'll verify that telemetry is valid and after that you can merge this at will.

**Comment by digitalentity** [comment]
@hydra 
What's the status on merging this into CF?

**Comment by fsedarkalex** [comment]
+1

would be happy to test with RadioLink PRM-02

**Comment by digitalentity** [comment]
@fsedarkalex do you need assistance with building the hex file? What FC do you fly?

**Comment by fsedarkalex** [comment]
@digitalentity you must smell that I started compiling about 10 minutes ago :)

I cloned your branch and compiled it. it is already flashed to my SPRacing F3...
But I can't figure out how to configure it as of course the cofigurator doe not know about the new option so I have to use CLI and I have nearly never used cleanflight's cli actively before... Could you lead me to which commands I need to enter?

**Comment by digitalentity** [comment]
serial 2 **256** 115200 38400 115200 115200

this will set MAVLink telem on Serial3 @ 115200 baud

**Comment by fsedarkalex** [comment]
weelll...
I am using UART1 for this purpose (Telemetry when armed)
I guess it is then
serial 0 257 115200 57600 115200 115200

My remote is just showing hexadecimal data as "Time" and zeroes for all the telemetry data. sometines there are wrong infos on the screen for about 50 milliseconds. I guess the baudreate is wrong... Are you sure that 115200 is correct for PRM-02 or was that just an assumption?

**Comment by digitalentity** [comment]
I'm not sure, it may be 57600

**Comment by fsedarkalex** [comment]
no chance... can't get it to work even using uart2 exclusively.... tried different settings BUT I noticed a similar strange behaviour even when the serial cable is not attached to the PRM... I got a second module and will test this tomorrow. (its 3 a.m. here)

**Comment by digitalentity** [comment]
I know a guy with Radiolink and PRM02, I'll try to borrow the device and
test myself.

**Comment by fsedarkalex** [comment]
tried with the other module, same phenomenon.... it is strange as even if I do only connect the PRM to the receiver without connecting serial to FC I get values like [D099-00-00 00-00 as "Time" every second or so

Thus please do not cound my propblem as  100% error in CF. I will do some research about what is happenning here...

**Comment by fsedarkalex** [comment]
@digitalentity I found the error...
I needed to upgrade my Transmitter firmware, now I get  no  weird data anymore but unfortunatel I was still not able to get Telemetry running. I do no receive any information. Every value is at zero except mode and Throttle, but I think those values are not from telemetry but directly from remote (tested without drone powered)

**Comment by davidgrm** [comment]
Prm-02 expects a baudrate of 57600. 
Take a look at my post about bypassing the PRM-02 and connecting directly to FC:
http://www.rcgroups.com/forums/showthread.php?t=2236519&page=14#post34359050

**Comment by digitalentity** [comment]
@hydra 
This is now tested with MinimOSD (stock MAVLink firmwar) and RadioLink PRM-02 module. Rebased and ready for review.

**Comment by hydra** [comment]
@digitalentity great!

**Comment by hydra** [comment]
First thoughts: "holy cr**p that's alot of code".

**Comment by digitalentity** [comment]
@hydra that's MAVLink library. I can remove unused files to slim the source.

**Comment by digitalentity** [comment]
You should probably be looking at telemetry/mavlink.c :smile:

**Comment by digitalentity** [comment]
@hydra 
This is now tested and ready to merge. If you have no objections I'll merge this by e/o this week.

**Comment by fsedarkalex** [comment]
do you also have changing the config tool to support this on your agenda for 1.13.0? Or is that already done and I just missed that?

**Comment by digitalentity** [comment]
@fsedarkalex I'm on it. Will submit pull request for Configurator in a day or two.

**Comment by fsedarkalex** [comment]
isn't that already there?
https://github.com/cleanflight/cleanflight-configurator/pull/161

**Comment by digitalentity** [comment]
Its very outdated, I'll re-submit it soon.

**Comment by fsedarkalex** [comment]
ah okay sorry for bothering :)

**Comment by digitalentity** [comment]
@fsedarkalex no problem. Actually thanks for reminder :smile:

**Comment by fsedarkalex** [comment]
Yeah I am waiting for two motors to arrive from china to build my second "cheaper" copter as I want to try around a bit and don't want to have my first real flight with my expensive one :dash: 

Researching for possibilities to get Telemetry running with my AT10D makes waiting easier so I am a bit impatient- Sorry for this :smile:

**Comment by digitalentity** [comment]
@fsedarkalex your wish for mavlink in Configurator granted!

**Comment by ledvinap** [comment]
```
%% mavlink.c
In file included from ./src/main/mavlink/common/../protocol.h:5:0,
                 from ./src/main/mavlink/common/common.h:30,
                 from ./src/main/mavlink/common/mavlink.h:25,
                 from ./src/main/telemetry/mavlink.c:75:
./src/main/mavlink/common/../mavlink_types.h:53:204: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
 MAVPACKED(
                                                                                                                                                                                                            ^
In file included from ./src/main/mavlink/common/../protocol.h:5:0,
                 from ./src/main/mavlink/common/common.h:30,
                 from ./src/main/mavlink/common/mavlink.h:25,
                 from ./src/main/telemetry/mavlink.c:75:
./src/main/mavlink/common/../mavlink_types.h:82:237: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
 MAVPACKED(
                                                                                                                                                                                                                                             ^
./src/main/mavlink/common/../mavlink_types.h:82:240: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
 MAVPACKED(
                                                                                                                                                                                                                                                ^
./src/main/mavlink/common/../mavlink_types.h:82:260: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
 MAVPACKED(
                                                                                                                                                                                                                                                                    ^
./src/main/mavlink/common/../mavlink_types.h:82:16: warning: struct has no named members [-Wpedantic]
 MAVPACKED(
                ^
%% sonar.c
```

**Comment by ledvinap** [comment]
@hydra: Can we just drop -Wpedantic?

**Comment by hydra** [comment]
@ledvinap I was suprised to find this merged today.  I think right now I'd prefer to keep -Wpedantic. Curious as to what others think.

@digitalentity in the mean time can you fix the warnings or is it a problem that they are in a library?

If it's a problem then perhaps the mavlink library could be compiled without -Wpedantic as it's 3rd party code.

Also perhaps raise an issue with them to fix it?

**Comment by hydra** [comment]
@digitalentity see this please https://github.com/cleanflight/cleanflight-configurator/pull/161#issuecomment-217528732

**Comment by hydra** [comment]
@digitalentity  Sorry I didn't get back to you regarding timeframe to merge this.  I hadn't had a chance to review it properly (due to amount of code, and my limited time recently) and was suprised to find it merged.  Still it will be nice to try it out with some mavlink compatible gear I was sent when I get time.

I prefer, though it doesn't always happen, to merge cleanups, bug fixes etc first, and then add new features.  In my mind I was still in cleanup / fix mode.  perhaps in the future we should have a task issue for each new cleanflight release that details the order of things and lists each PR.  Similar to what @martinbudden did with #2103 which I earlier renamed.  We could then keep the first post up-to-date with what has been done and what is still to do.  This would also go someway to managing users expectations of what's in a new release.

**Comment by ledvinap** [comment]
@hydra: `-Wpedantic` is set only on for F103 targets.

Also Cleanflight is currently quite dependent on gcc (most of them supported by clang, rest can be implemented in differently in clang) features. I am mostly responsible .. 
Compiling under IAR compiler will need lot of work, other compilers are probably not important.

@digitalentity:
wrapping affected sections #pragmas is probably enough
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
<code>
#pragma GCC diagnostic pop
```

**Comment by Susurrus** [comment]
For the unnamed struct warning, see here: https://github.com/mavlink/mavlink/pull/386

**Comment by ledvinap** [comment]
what about `-std=c11` option?

**Comment by digitalentity** [comment]
@hydra thanks for comments. There is certain demand for MAVLink (not big, but still significant). I see people migrating from PixHawk and APM to CF/INAV and asking for MAVLink to keep same hardware. I'm also trying make CF futureproof - new CONNEX HD FPV gear requires MAVLink to show useful info in OSD and it's going to hit the market very soon.

I'll maintain this part of code and cleanup in the following few days.
I'm also working on something for both CF and Configurator to avoid relying on API version to detect supported features. 

As a next step we could have different telemetries selectable compile-time. I.e. on targets with limited flash space drop MAVLink and signal that it's not supported to Configurator.

@ledvinap, @Susurrus thanks for suggestions. I'll look into the possibilities to reduce warnings.

**Comment by digitalentity** [comment]
Continued in #2107

**Pull request merged**
