### PR TITLE
Enable ccache

### PR DESCRIPTION
**Pull request by hydra**
however, see this if you use cygwin

https://github.com/betaflight/betaflight/issues/774

(basically, cygwin + ccache = fail)

### CODE REVIEW

**Comment by ledvinap** [comment]
Can you check if there is any benefit to ccache?
On my linux box:
with ccache enabled:
```
make all_targets clean
time make all_targets
real    13m18.738s
user    10m52.612s
sys     0m42.772s

make all_targets clean
time make all_targets
real    13m6.715s
user    10m51.476s
sys     0m42.612s
```
with ccache disabled:
```
make all_targets clean
time make all_targets
real    12m48.151s
user    10m50.548s
sys     0m44.192s
```

Maybe ccache is configured incorrectly (just did apt-get install ccache), but IMO main problem is that ccache wont help with LTO compilation. At least it does not make things worse ..

**Comment by ledvinap** [comment]
OK, it does help for single project, but ccache cache size must be properly sized to hold all_targets
```
make clean
time make
real    0m37.295s
user    0m30.688s
sys     0m2.148s

make clean
time make
real    0m9.700s
user    0m7.396s
sys     0m0.440s
```

**Comment by ledvinap** [comment]
After some testing:
~ 1.5G cache is required on debian to build all targets.
~ 0.5G cache is required when compression is enabled. This may increase build time a bit, but nothing dramatic (build times differ even with same options, I am too lazy to get enough data)

compression disabled:
```
real    13m41.311s
user    11m9.464s
sys     0m50.864s

real    4m21.027s
user    2m25.688s
sys     0m11.964s
```
with compression enabled:
```
real    14m58.598s
user    12m43.048s
sys     0m49.344s

real    3m42.460s
user    2m32.300s
sys     0m10.816s

```

This should be at least documented. Or better, makefile should be modified to set options accordingly (probably using local configuration and cache)

**Comment by hydra** [comment]
@ledvinap thanks for that info. much appreciated.

I hadn't actually tried it, i just pulled the commits from betaflight.  I'm not sure if this will be useful to speed up the travis builds because the cache is obviously not shared.  still locally it is useful when properly configured.

Do you have any details of what changes you made to the ccache settings and/or how to do it?  I've not looked into that.

**Comment by ledvinap** [comment]
```
CCACHE_COMPRESS=true
export CCACHE_COMPRESS
```
and possibly set CCACHE_DIR to directory in cleanflight and store config there. 
CCache parameters did change lately (my Debian version is quite different to newest), so take care

Also ccache is supported by Travis (but $HOME/.ccache must be used):
https://docs.travis-ci.com/user/caching/#ccache-cache

With ccache care should be taken not to include PR/git commit dependent data into most files ...

**Comment by ledvinap** [comment]
BTW: No cached files are reused between different targets

**Comment by hydra** [comment]
ok, added the travis config, let's see what happens :smile:

**Comment by hydra** [comment]
merged this now, if there's any issues other than the one linked we can revert.

**Pull request merged**
