### PR TITLE
Update Spektrum bind.md

### PR DESCRIPTION
**Pull request by Zappes**
Added a description for connecting the SAT to a Flip32+ board

### CODE REVIEW

**Comment by MJ666** [comment]
I only would change the reference to the orange RX into general Spectrum compatible Sat.
 And adding a section like tested satellite transmitter combinations:

Orange R100 - Spektrum DX6i  (bind value of 3)
Lemon RX DSM2/DSMX - Spektrum DX8
Lemon RX DSMX Devo10 - (Deviation 4.01)  up to 12 channels
Lemon RX DSM2 Devo7 - (Deviation)

**Comment by Zappes** [comment]
OK, I changed it like that. As a Github-Newbie, I have to ask: Is it sufficient that I committed my change or do I have to do something else?

**Comment by MJ666** [comment]
Looks good. You are hesitant to add the additional information I provided regarding other tested RX/TX combinations?

**Comment by fiveangle** [comment]
This is incomplete without citing the rev of the flip32. Rev 6 is yet again different from your description.

My post on rev5: http://www.rcgroups.com/forums/showpost.php?p=28577567&postcount=105

My post on rev6: http://www.rcgroups.com/forums/showpost.php?p=29315006&postcount=151

In both cases you need to not only make the correct connection (which you detail for rev5), but you also need to disconnect the errant connection by cutting traces (which you don't even mention).  

Also, rev4 has yet a different problem where the lines were wired out of order, blowing up the sat if you used it at all (IIRC). 

If you want to help clarify for everyone, you really need to be either comprehensive, or purposefully sparse, and simply reference 3rd-party documention (such as that Flip32 thread on RCG).

Oh, I almost forgot, you reference the "Flip32+" exclusively, but the "Flip32" is identical in this regard. I would either reference both, or drop the "+" and let the "Flip32" act as an ambiguous reference to the Flip32 "family" (similar to the Naze32 "family").

Otherwise, looks good - more clarity is always better !

-=dave

**Comment by fiveangle** [comment]
Oh, while you're making changes, it probably couldn't hurt to add "…and it's clones, such as the Dragon32…" once when first introducing the Flip32 controller info. 

-=dave

**Comment by Zappes** [comment]
@fiveangle You are absolutely right, I guess. I simply don't have the knowledge to write this properly, though. I have received the hardware I have as a gift, it's my first contact with all of this and all I can do is describing what I did in order to make my gear work. I was asked to add that to the docs by Hydra and so I did to the best of my capabilities.

I have no objection whatsoever if this pull request is discarded, amended or changed in whatever way anybody finds suitable. I just can't add more than I did already, not for lack of motivation, but for lack of knowledge.

@MJ666 I didn't add the other combinationations because I didn't even know the hardware you mentioned ande I didn't feel comfortable documenting stuff that I don't understand.

**Comment by MJ666** [comment]
Also have an MW32 V2 which is quite similar to the Flip32+. Likely an older revision from the same source.

The tree combination I added I personally know they work since I have tested by myself or friends of mine have tested this when I ported the Spectrum bind support to CF.

**Comment by Zappes** [comment]
@MJ666 I tried to add your information, but as I'm not really sure what all of it means, you might want to correct that after it's been merged.

**Comment by MJ666** [comment]
Sorry my writing was not so clear. Please modify the table like below and than it will be perfect.

| Lemon RX DSM2/DSMX   | Spektrum DX8     |                                                                       
| Lemon RX DSMX              | Walkera Devo10  | Deviation firmware 4.01 up to 12 channels | 
| Lemon RX DSM2              | Walkera  Devo7   | Deviation firmware                                       |

**Comment by fiveangle** [comment]
"I just can't add preto this…"

But we pointed you to the exact resources and suggrsrions to change. I'm sure you can review it ms make the necessary changes without much effort. 

Don't give up so easily :)

-=dave

**Comment by Zappes** [comment]
@fiveangle I'm really sorry, but I can't really help you there. I happily provide a documentation of what I did, but I do not intend to become an expert on the topic or the maintainer of that information. If what I contributed does not meet the requirements for proper documentation in this project, please feel free to discard the pull request and be sure that there will be no hard feelings from my side.

**Comment by hydra** [comment]
@Zappes some documentation is better than none. 
Happy to merge as is.

@fiveangle can you create another PR after I merge these that has the changes you would like?

**Comment by hydra** [comment]
@Zappes also, please create a branch-per-pull request.  add additional commits to the corresponding PR branch and push and the PR will be updated automatically.  Avoid creating PR's fromy our master branch.  See documentation in cleanflight for the basic steps:

https://github.com/cleanflight/cleanflight/blob/master/CONTRIBUTING.md

**Comment by Zappes** [comment]
@hydra ok, I will do that in the future!

**Pull request merged**
