### PR TITLE
OLED Armed page bitmap addition

### PR DESCRIPTION
**Pull request by ChiggerPepi**
I have added a bitmap in place of the "ARMED" title page for the OLED
img_2926

### CODE REVIEW

**Comment by thenickdude** [comment]
I suspect that code size could be reduced quite a bit by run-length encoding the bitmap.

**Comment by hydra** [comment]
Can you please add the source of the image (in BMP/PNG/etc) to the pull request.

**Comment by hydra** [comment]
Any notes how how you generated the image from the source would be good too.

**Comment by ChiggerPepi** [comment]
The original bmp is located here:
https://dl.dropboxusercontent.com/u/11391690/armed01.bmp

I tried a couple different bmp to hex converters, and I had best luck using LCD Assistant located here:
http://en.radzio.dxp.pl/bitmap_converter/

The BMP is 128x28, but I had issues with formatting at the end of the image unless I chose 128x32 in the converter.

I'll start working on encoding and decoding RLE, but it may take me a bit.  I did find some pretty good documentation regarding the format here:
https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.45-200002-I!!PDF-E&type=items

**Comment by thenickdude** [comment]
It doesn't need to conform to anyone's published RLE format, you can just write one byte for the run length, then follow that with the byte that is to be repeated. It would collapse all those runs of 0x00 bytes into two bytes.

**Comment by ChiggerPepi** [comment]
Agreed, but it might make sense to use a published format if there will be future BMP additions.  I'll look into it anyway.

227 0x00 bytes in the file as is...

**Comment by digitalentity** [comment]
@ChiggerPepi have look here: http://www.gabotronics.com/tutorials/run-length-encoding-for-lcd.htm, looks like the image converter described can convert to RLE right away and decoding algorithm is very simple.

**Comment by ChiggerPepi** [comment]
Crazy, I was just reading that exact page...

**Comment by digitalentity** [comment]
I tried their image converter - 246 bytes compressed compared to 384 bytes uncompressed. That's 138 byte gain, but decoding algo will also take some flash. We might end up using even more space in flash memory.

**Comment by ChiggerPepi** [comment]
So it probably depends how many future BMPs may be implemented.  Is this something people want?

**Comment by digitalentity** [comment]
I like to see big fat "ARMED" on my OLED screen, but that's it. IMO, if you can fit compressed image + decompression algo in those 384 bytes, we have a codebase for future images if there will be any demand. If the size will exceed 384 bytes, I guess its not worth it.

**Comment by ChiggerPepi** [comment]
Agreed on all counts.  I'll fiddle with it for a bit...

**Comment by ChiggerPepi** [comment]
Saved 128 bytes, including the decompression code.

**Comment by flying4fun** [comment]
Nice!  Much better.  Now I can read it without being right next to it.

**Comment by digitalentity** [comment]
@ChiggerPepi excelent! Hope @hydra will merge this soon!

**Comment by thenickdude** [comment]
@ChiggerPepi please add the original bmp file and a little note on how to convert it to your commit. You might add a .md note on "Encoding OLED images" in `/docs/development` and the .bmp somewhere, not sure where would be best.

**Comment by ChiggerPepi** [comment]
Github does not support uploading of .bmp files.  This is the final version of what I used for the armed page:
https://dl.dropboxusercontent.com/u/11391690/Github/armed128x32.bmp

The image was created in Photoshop.  Images supported by this pull request are required to be 128 pixels wide, with the exception being an image only 8 pixels in height.  I found much less problems with creating the required hex files when the image height was divisible by 8, but should not be larger than the display height of 64.  Example Photoshop new image settings here:

photoshop

Once you have saved your .bmp file, it will need to be converted to RLE compressed hex.  The Gabotronics Image to HEX Converter v1.03 worked very nicely for this.  I show the proper settings in the screenshot below.  
http://www.gabotronics.com/download/resources/bmp-converter.zip
gabotronics

**Comment by thenickdude** [comment]
ChiggerPepi, I mean add it (as files) to this commit, so that people who check out the repository will be able to edit and regenerate the image.

**Comment by ChiggerPepi** [comment]
@thenickdude Got it done.

**Comment by thenickdude** [comment]
Awesome, thanks!

**Comment by hydra** [comment]
Cool, also, the cleanflight font is NFS font - you could make it say 'ARMED' using that font :smile: 

http://www.dafont.com/nfs-font.font

**Comment by ChiggerPepi** [comment]
Better?

img_2943

**Pull request closed without merging**
