### PR TITLE
removed unneccasary static array as rcDataMean was always reset before use

### PR DESCRIPTION
**Pull request by atomiclama**

### CODE REVIEW

**Comment by atomiclama** [comment]
Space and code saving, before
   text	   data	    bss	    dec	    hex	filename
 124628	   1144	  13684	 139456	  220c0	./obj/main/cleanflight_CC3D.elf

after
  text	   data	    bss	    dec	    hex	filename
 124596	   1144	  13660	 139400	  22088	./obj/main/cleanflight_CC3D.elf

Not a huge amount but it all counts ;-)

**Comment by martinbudden** [comment]
I agree, every bit of ROM reduction counts.

**Comment by hydra** [comment]
great catch!  there's still so many wierd bits of code floating around from baseflight/multiwii.  

Curious as to how you found this though?

**Comment by atomiclama** [comment]
@hydra thanks, I was tracing the rcData path through the code with the view to making PWM event driven instead of time, just spotted it.
Alternatively, it was my brilliant analytically skills as I systematically go through the code ;-)

**Comment by borisbstyle** [comment]
haha
Op 22 feb. 2016 13:12 schreef "Andy" <notifications@github.com>:

**Pull request merged**
