### PR TITLE
Add softserial to SP Racing F3 EVO (via ESC outputs 5-8)

### PR DESCRIPTION
**Pull request by hydra**
Provided as-is for those that want to test.

## TODO

- [ ] Documentation
- [ ] Testing

### CODE REVIEW

**Comment by hydra** [comment]
rebased

**Comment by hydra** [comment]
I'm going to merge this now, people can test as part of release candidate phase.

**Comment by urlu75** [comment]
Tried SoftSerial 1 and 2 for SmartPort telemetry with no success (9600 & 19200).
Also give a try with SerialRX, it fails.

**Comment by monelli** [comment]
Build from master branch, using SP Racing F3 Evo.
Smartport on softserial does not work.

For softserial1 I connect "motor output" 5 and 6 to smart port
From cleanflight documentation:
You have to bridge TX and RX lines of SoftSerial and connect them together to S.Port signal line in receiver

**Pull request merged**
