### PR TITLE
usb: mark register accesses as volatile.

### LINKED ISSUE #763: Build - ARM GCC compiler (Q1/2015) generates non-working USB code
Likely not directly connected to the CF code but important to know. Coded generated with latest version of the ARM GCC (Q1/2015) will build code with an non working USB VCP. In general the code is working with this compiler tested on an ALINEWII F1. I was not able to connect anymore to an ALIENWII F3 via USB after upgrading. Any how from LED behavior the reminder of the firmware looks to be working. Windows is reporting an error with the USB device when connecting and the VCP is not showing up. Reverting to the ARM GCC (Q3/2014) version will make it work again with compiling from the same source code. This will likely affect also the Sparky and all other FC's which using the STM USB with VCP. Not sure this will also affect other platforms and operating systems. I'm completely on windows (8.1)

### PR DESCRIPTION
**Pull request by nzmichaelh**
Fixes the LTO build with GCC 4.9.  Tested on the STM32F3DISCOVERY.  I
assume the compiler was doing cross function optimisation, saw that
the same non-volatile address was read twice, and dropped the second
read.

Fixes #763.

Signed-off-by: Michael Hope <mlhx@google.com>

### CODE REVIEW

**Comment by digitalentity** [comment]
Thanks for posting this. I'll test the patch on my CC3D today.

**Comment by digitalentity** [comment]
@nzmichaelh 
Tested with latest GCC 4.9-2015-q2 on my CC3D
Provied some build warnings like "*./lib/main/STM32_USB-FS-Device_Driver/src/usb_regs.c:656:51: warning: initialization discards 'volatile' qualifier from pointer target type*" but builds fine.
I was able to use VCP with this patch no problem. Going to switch to gcc-4.9.

**Comment by nzmichaelh** [comment]
I've tidied up the warnings.

**Comment by hydra** [comment]
Awesome thanks for tracking that down.  Hopefully the hint regarding LTO was of some use.

Quick note regarding commit messages - please keep them purely factual and with some context.  It's very tempting to put funny messages and such like in them but such comments are generally not helpful when reviewing commits or tracking down where a change came from, conversely factual messages with context are really helpful.

**Comment by nzmichaelh** [comment]
Heh, no worries.  I'll modify the commit message.

**Comment by nzmichaelh** [comment]
Hmm, I've already pushed the branch so I can't push the modified push message.  Sorry.  I'm happy to send another CL.

**Comment by thenickdude** [comment]
You can use the force push option to overwrite the branch with your modified one.

**Comment by digitalentity** [comment]
Another test of this PR today. Works fine on my CC3D.

**Comment by hydra** [comment]
I restarted the failed jobs (network errors), waited for the build to pass and have now merged.

**Pull request merged**
