### PR TITLE
include dependencies in header files

### PR DESCRIPTION
**Pull request by Windfisch**
Changes all header files to include their necessary dependencies, instead of relying on the unit that uses them to do this. Please see issue #1967 for a detailed explanation.

Also adds some `#pragma once` to header files where this is missing.

This PR strictly doesn't touch any code, except for adding "#include" directives. It should not carry any functional changes.

This fixes issue #1967

### CODE REVIEW

**Comment by dkisselev** [comment]
It looks like in some cases your changes cause duplicates (they're near the top of the diff, blackbox_io, among others).

**Comment by Windfisch** [comment]
oops, thanks! I've removed all the duplicated includes, and I also have removed any empty lines introduced by me.

**Comment by AndersHoglund** [comment]
Very Good. I like this kind of structure, every file (.h .c or whatever) should take its own responsibility for its own dependencies, not relying on someone else doing it for you.  I have made objections earlier on some indirect deps beeing added to fix compile problems, "un-clean" quickfixes. 
We should strive for living up to the bold name "cleanflight" by using clean methods and source code structure.

**Comment by hydra** [comment]
no.

at the moment we don't want this.

I specifically include all dependencies in order to highlight dependency and coupling issues.

**Comment by dkisselev** [comment]
@hydra, what do you mean by 

> I specifically include all dependencies

The current code does not explicitly do that, this MR explicitly adds the dependency lists to each module.

If a module is too dependent/tightly coupled, shouldn't that be apparent when you see a painfully long include list at the top of the file, not when you go to make a change and the build fails because the code depends on some include that used to exist 3 layers up?

**Pull request closed without merging**
