### PR TITLE
Changed code for accelerometer handling, filtering is now done in acc…

### PR DESCRIPTION
**Pull request by mamalala**
…eleration.c, using

the biquad filter, like in betaflight. Changed imu and boot.c accordingly.

### CODE REVIEW

**Comment by mamalala** [comment]
I fixed the unit tests that broke due to the change.

However, the Travis CI build still fails. This is due to  the removal of two legacy targets by hydra, they were accidentally left as targets in the fake_travis_build.sh script.

**Comment by hydra** [comment]
@mamalala I'll fix the travis issue now. can you rebase when it's done?

**Comment by mamalala** [comment]
OK, hopefully i did the rebase the correct  way, i'm rather new to using GIT. The current CI build should go well now.

**Comment by mamalala** [comment]
Closing this PR, re-opened it under a proper name.

**Pull request closed without merging**
