### PR TITLE
EasyRaceLapTimer Transponder Provider

### PR DESCRIPTION
**Pull request by SSPW**
I have coded and tested an EasyRaceLapTimer (ERLT) transponder provider based on the existing CF transponder framework.
I have also modified the transponder update delay and jitter so those values are transponder specific.
I have tested this with SPRACINGF3EVO and RG_SSD_F3 targets.

I have also made a pull request on the CF Configurator for the supportng Transponder Tab change.

### CODE REVIEW

**Comment by hydra** [comment]
thanks for this, I will take a look asap.

**Comment by hydra** [comment]
looks very good, well done!

Do you mind if I squash the commits when merging?

Is it possible you could add another commit that updates the documentation files?  I'd like to see at least a section that has links to ERLT receivers, forum threads, etc.

**Comment by SSPW** [comment]
I don't mind if you squash. I am kind new to contributing. Definitely should have cleaned up a bit more before doing the request.

But before you squash, I have one question about configurator and EPROM storage and transponders. Seems the hex digits entered at configurator is "inverted" by the hex to string helpers for transponders data and stored that way. Got me a bit confused as I had to invert it back in my ERLT provider. Is there a reason for this? Just thinking that later when msp is used from a tx or osd to set transponder codes, those msp clients are going to have to send inverted byte data. This seems a bit confusing to me.

I can make changes in configurator and transponder providers do transponder data is stored "wysiwyg" as long as there isn't something else I am missing here. Let me know.

I looked at the docs but didnt find anything for the existing transponder support. I can start one. What doc would you suggest as a template?

**Comment by SSPW** [comment]
created a Transponder.md
https://github.com/SSPW/cleanflight/blob/erlt-provider/docs/Transponder.md

**Comment by hydra** [comment]
Great.  The main reason for inverting them was the privacy of people's iLap transponder codes which are paid for.

I'll try this and merge it this weekend.  Does the configurator need an update? Have you done it/are you doing it?

**Comment by SSPW** [comment]
Configurator mods are ready. I'll create a pull request for it.

**Comment by hydra** [comment]
squashed and merged.

**Pull request closed without merging**
