### PR TITLE
Brushed max throttle limit

### PR DESCRIPTION
**Pull request by EvilBadger**
Noticed on the brushed boards its not possible to get 100% duty cycle on the motors, somewhat limiting the power available. This simple fix seemed to make it better for me, let me know if it needs more work.

### CODE REVIEW

**Comment by hydra** [comment]
This seems like a bit of a hack to me.

likely the issue is either in this code:

https://github.com/cleanflight/cleanflight/blob/78b52c53d51b44fb2b2e9ce7ad54baa2be57d2b0/src/main/flight/mixer.c#L723-L741

or the pwm output code needs updating.

Can you give me details on which board you're using and how you're measuring the duty cycle?

also, the PR has too many commits, there should be just one for the change.  Perhaps use this as an excuse to learn how to rebase your PR and update it if you don't know how?

**Comment by EvilBadger** [comment]
Yea didn't realise github would all commit history just assumed it would be a patch. Tested on a custom board but using alienwii f1 build measured using analyser where you can clearly see the input to the fet not being full duty, motor output was set using GUI to 100% for testing. From a quick look the fix I think needs to be in the pwm output code that constrains the Max pwm for esc's. Thoughts?

**Comment by dkisselev** [comment]
You don't have to close the PR, just rebase/squash your own feature branch. GitHub recognizes rebasing and will update the existing PR to reflect your changes.

**Comment by SteveAmor** [comment]
The following code appears to act as expected:

https://github.com/cleanflight/cleanflight/blob/78b52c53d51b44fb2b2e9ce7ad54baa2be57d2b0/src/main/flight/mixer.c#L723-L741

I actually can't find an issue at all.  See #1520

**Pull request closed without merging**
