### PR TITLE
Feature exti 2

### PR DESCRIPTION
**Pull request by ledvinap**
rebased #1421, to avoid force-push for now.

### CODE REVIEW

**Comment by MJ666** [comment]
I like this is now going into this direction. This will allow the cleaner implementation of the AlienFlight F3 V2 LED driver (already present in RaceFlight). Also all pin initialisation code is much more simple if all is finaly updated.

**Comment by blckmn** [comment]
If this gets merged in we can start updating the drivers throughout - it can also be used in the configuration updates @hydra is working on.

Key is to keep the implementation hidden and not bleed it throughout. That way it's nice and easy to adjust for different MCUs in future.

**Comment by hydra** [comment]
will attend to this after #1976

**Comment by hydra** [comment]
some other PR's need to be merged first.  so annoying having to delay this yet again.  

#2016 and #2012 take priority.  rebases and updates to this PR welcomed!

**Comment by blckmn** [comment]
It'd be great to have this one ready for 1.14 :) very keen to get it in - waiting on it for some driver updates to put forward. @ledvinap @hydra what do you reckon?

**Comment by blckmn** [comment]
@ledvinap if you could rebase - I am happy to add more IO changes to your branch.

**Comment by ledvinap** [comment]
Rebased, some testing on real HW is probably necessary

**Comment by ledvinap** [comment]
Merged upstream. Maybe it would be worth rebasing before merge, but it's quite time consuming

**Comment by ledvinap** [comment]
@hydra: Can you find time and decide what to do ith this PR? It's 10 months old, its quite boring to keep it in sync ..

**Comment by blckmn** [comment]
Its working well. Was in RF and now in BF.

**Comment by borisbstyle** [comment]
Yeah this PR is a killer!

**Comment by martinbudden** [comment]
Yes, I agree, this PR should be tested and merged in as soon as possible.

**Comment by hydra** [comment]
Is this ready for merge?

**Comment by hydra** [comment]
it still merges cleanly with master and compiles...

**Comment by martinbudden** [comment]
It looks good to me. I've just finished converting the whole of iNav to the new IO, so I am somewhat familiar with this code now.

Probably good to get confirmation from @ledvinap , though.

Good to see you are about to start this work.

**Comment by hydra** [comment]
@martinbudden ok great, let's merge this now then and we'll pick up the pieces as they fall.  This is long overdue and I fear that if it's not in master soon it'll never get done.

**Comment by hydra** [comment]
@ledvinap see 91debadaba2931a725f61317013251e499aa47e7.

Tested on EVO and F3OSD hardware OK.  Merged.

**Comment by ledvinap** [comment]
I'll get to this next week. Only exti handling got changed, it should work correctly.

**Pull request merged**
