### PR TITLE
Remove all tab characters and trailing whitespace from *.c and *.h files under src.

### PR DESCRIPTION
**Pull request by lchish**
Removes whitespace at the end of lines in affected files.

http://www.emacswiki.org/pics/static/TabsSpacesBoth.png

### CODE REVIEW

**Comment by ledvinap** [comment]
Good idea in long term, but annoying to merge. It should be followed with git setup/documentation to handle this automatically in future.

**Comment by lchish** [comment]
I did it all manually in my patch to get the indentation to match in some of the header files. I agree about the gigantic merge, not much we can do about that though. Having a mix of tabs and spaces will be more confusing in the long run.

It would be nice if Travis CI checks for tabs in the code and throws warnings. I made this pull request out of annoyance that files with tabs in them keep getting added.

I used this command to find files with tabs in them:
find . -name *.h -o -name *.c -print -exec grep -ir -P '\t' {} \;
And this to remove trailing whitespace
sed -i 's/[ \t]*$//' "$1"

In the coding style document there is an astyle command that could also be used to clean things up.

astyle --style=kr --indent=spaces=4 --pad-header --pad-oper --align-pointer=name --align-reference=none --convert-tabs --indent-switches  --min-conditional-indent=1 --preserve-date --suffix=none --mode=c src/*.*

**Comment by lchish** [comment]
I've written a quick script for travis that will look for files under src/ and return an error if a c file, cc unit test or header file contains trailing whitespace or a tab character.

````#!/bin/bash

TABS=$(grep -nRP '\t' --include=\*.{cc,c,h} src)

if [[ $TABS ]] ; then
    echo "Error: Tab characters found!"
    echo "$TABS"
    exit 1
fi

TRAILING_WHITESPACE=$(grep -nRP " +$" --include=\*.{cc,c,h} src)

if [[ $TRAILING_WHITESPACE ]] ; then
    echo "Error: Trailing whitespace found!"
    echo "$TRAILING_WHITESPACE"
    exit 1
fi
````

**Comment by hydra** [comment]
ahh yes, that script is a good idea.

What do you think @ledvinap ?

**Comment by ledvinap** [comment]
Yes, its better than nothing ...
some automatic style checking will be nice, but that's probably long way to go ...

**Pull request closed without merging**
