### PR TITLE
A fix for bmp085 baro driver not using EOC flag

### PR DESCRIPTION
**Pull request by digitalentity**
Partially fixes issue #569 when bad values are being read from bmp085 due to the fact that sometimes pressure conversion takes longer than specified in the datasheet.

### CODE REVIEW

**Comment by digitalentity** [comment]
#720 fixes the timing, this one fixes the situation when baro is being read regardless of convDone flag on targets with BARO_EOC_GPIO available (NAZE & PORT103R)

**Comment by ledvinap** [comment]
Maybe whole code should be wrapped in `#if defined(BARO)` ? @hydra?

**Comment by digitalentity** [comment]
IMHO this is worth doing. Would make things more readable.

**Comment by digitalentity** [comment]
Sorry, accidentally pushed wrong repo

**Comment by hydra** [comment]
Commits squashed and merged. Thanks!

**Pull request closed without merging**
