### PR TITLE
Bit-banged SPI based RTC6705 VTX support

### PR DESCRIPTION
**Pull request by jflyper**
Add support for VTX control.

For micro builds where every gram is a premier, or builds with concealed VTX, controlling the VTX from FC may be a good idea. This PR provides support for RTC6705 based VTX with SPI signal accessibility.  FX758-2 is an example of such VTX, and TX5823 could be used with a minor mod.

The SPI interface is driven with bit-banging SPI using any three unused GPIO ports.  Native/hardware SPI may be supported in the future.

The entire bit-banged VTX control is enabled by specifying a feature **VTXBB**.
In addition to the **VTXBB** feature, three GPIO ports for SPI signals must be specified with three CLI variables **vtxbb_ss_pcode**, **vtxbb_sck_pcode** and **vtxbb_mosi_pcode**, in 'port code' or 'pcode'.  A port code is a 3 digit number, with 100's place digit specifying GPIO group (GPIOA = 100, GPIOB = 200, ... GPIOF = 600), and lower two digits specifying pin number in decimal.  Port code examples are: PA2 = 102, PB11 = 211, PC13 = 313 and PF5 = 605.

CLI variables **vtx_mode**, **vtx_band**, **vtx_chan** and **vtx_freq** control a frequency which the VTX module will transmit on.  When vtx_mode = 0, the frequency is determined by vtx_band and vtx_chan according to the pre-defined table. When vtx_mode = 1, the frequency is determined directly by vtx_freq. (This scheme is partially compatible with multiFlite and SINGULARITY FC.)

The frequency is set only once upon initialization by init() in this PR.

Currently tested with NAZE and SPRACINGF3.

### CODE REVIEW

**Comment by hydra** [comment]
ahh very interesting!  I have been thinking about cleanflight VTX support for a while now.

Can you also look into adding stick commands for 'enable vtx' and 'cycle channel' and 'cycle band' too?

**Comment by jflyper** [comment]
@hydra As a matter of fact, the code for stick commands already exists, derived from SINGULARITY support code written by MrBreakmore (@sblakemore) available at:

https://github.com/sblakemore/cleanflight/tree/singularity-cf

Let me do some code cleaning.

**Comment by jflyper** [comment]
@hydra  Do you prefer independent PR for the stick commands?

**Comment by jflyper** [comment]
Oh, and 'enable vtx' is bit hard to implement, if it means commencing transmission. I have looked into this, and came up with (1) have a dedicated power supply, for example a pololu, and use an additional GPIO line to enable/disable it or (2) discover the usages of PA (Power Amplifier) control of RTC6705 chip. The (1) requires dedicated PS, and (2) requires some help from RTC6705 specialist.

**Comment by sblakemore** [comment]
As mentioned there has already been work done in this area by Giles Burgess from multiflite.co.uk in creating a driver for the RTC6705 using a hardware SPI peripheral rather than bit banging. I then used his work, with permission, and added support for stick commands, as well as mapping channels to AUX ranges for use with switches. Code from my fork is actually already being used in a shipping product in the Singularity FC: http://singularity.impulserc.com/ There is full documentation on how my current implementation works here: http://singularity.impulserc.com/assets/files/manual.pdf

There has been a good amount of testing done over an extended period and I've come up with some methods for keeping things safe. Most notably that changing VTX frequencies only works before the quad is first armed. Once it's armed nothing can change again until the board is power cycled. This is important to stop things like a failsafe or accidentally knocking a switch while flying causing an accident by killing yours and/or your friends/competitors video.

I haven't submitted a PR before now since I didn't believe new targets were being accepted at the moment and wasn't aware the VTX code would be useful to anyone else.

I'm certainly very keen to see VTX support merged but it seems to me there is more than one use case. My code is targeted towards using a VTX module integrated with the FC on a hardware SPI peripheral, this PR is for re-purposing existing pins on an FC to drive an off the shelf VTX by bit banging, possibly with mods to enable the SPI interface of the specific module.

I think each have merit but it's worth considering both together before merging anything so they can live together nicely.

Perhaps an ideal approach would be for my to organise my repo a little better so that the Singularity target and the VTX support are in separate branches and then you can submit your bit bang driver as a pull request to me. That way we can work on integration of your run time based approach for configuring the pins with my compile time approach specific to a target using a dedicated SPI peripheral.

**Comment by sblakemore** [comment]
I've gone ahead and separated out the VTX code into it's own branch, it needed doing anyway!

https://github.com/sblakemore/cleanflight/commits/vtx

There is some more code in there I've been working on that wasn't previously pushed anywhere public, including support for changing power output using a GPIO pin as well as some initial work to decouple things so that drivers for modules based on chips other than RTC6705 can be supported, however this would also accommodate your bit bang driver.

**Comment by hydra** [comment]
@sblakemore Yes the VTX code is much-wanted.  This is not forgotten.  There are a few things we need to do in cleanflight first though.  Please keep your code changes as isolated and mergable as possible so that we can get it merged in the near future.  Is there any chance you could send me a board and corresponding VTX so I have development hardware for testing with?  If so grab my email from a commit and drop me a message.

**Comment by hydra** [comment]
@jflyper yes a new PR for the stick commands, cli commands and documentation (e.g. the stuff from the impulserc manual) would be perfect.  It seems quite isolated code so I don't expect any problems merging.

**Comment by sblakemore** [comment]
@hydra Happy to send hardware for you to test. I did send you an email some time ago but had no response, did you receive it or should I try again?!

**Comment by hydra** [comment]
@sblakemore yes, please try again!  I'm not sure if I saw it or responded, much has happened since july.

I have code locally with VTX support and a proper VTX API which I will publish soon.  Once it's done we can revisit this to update the code to support the VTX API.  The current high-level API is VTX agnostic and just requires the low level driver to implement a few basic functions.

Having hardware here that needs bit-banged support would be most helpful indeed.

**Comment by hydra** [comment]
blocked, pending merge of the new VTX code I have here.

**Comment by sblakemore** [comment]
@hydra Sorry for the delay replying, I've been away at the Worlds for the last couple of weeks. More than happy to send you some hardware for testing. I just shot through another email.

**Comment by jflyper** [comment]
@hydra I read somewhere that you are coming up with a consolidated API for VTX. Can I review it somewhere? I'm working on the smartaudio support for BF (betaflight/betaflight#1283), and may put some provisioning for the API.

**Pull request closed without merging**
