### PR TITLE
Implemented support for FlySky i-Bus serial receiver.

### PR DESCRIPTION
**Pull request by digitalentity**
This is per #780, Code mostly ported over from baseflight. 
Until configurator support for this is added, to activate iBus receiver one need to execude in cli the following: `set serialrx_provider = 7`

### CODE REVIEW

**Comment by digitalentity** [comment]
Unfortunately, failsafe for this protocol is not possible. When receiver looses signal it freezes channels to latest values, but continues to send them via i-bus. No special flags are present in the i-bus frame, only sync byte, raw channel data and a checksum. I-bus frames sent to FC when link is good and those sent when link is lost are identical!

**Comment by ledvinap** [comment]
From manual it seems failsafe may be set to preset position or last position. Using preset value outside valid CF range may trigger failsafe ...

**Comment by digitalentity** [comment]
Indeed it can, but I was unable to set the channel value outside valid CF
range. I'll pay with it tomorrow and try to figure out if failsafe can be
triggered somehow.

**Comment by MJ666** [comment]
Harakiri is implementing an "dead pilot" function. If there are no stick movements for a predefined time it will also go into the failsafe mode.

**Comment by digitalentity** [comment]
Good idea, but it won't help with receivers providing some jitter - these
would be most if not all pwm and ppm receivers, unless there is a threshold
for jitter.

**Comment by smiling-Jack** [comment]
I've tested it and it works great. 
But I have two questions : 

Why only 8 channels ? My Radio and RX can 10ch
Are there risks to use it over soft serial ?

**Comment by digitalentity** [comment]
Flysky i-Bus driver was ported from baseflight, 8ch limitation comes from there and I don't have a 10ch transmitter to patch this for more channels.

**Comment by BimmerTas** [comment]
Hi there. New to the project and programming in general... So probably not much help to you.. 

Does this branch of code have a chance at being included in the main cleanflight build? If so what needs to be done?

I'm happy to do some testing. But this would be my first go at building my own .hex/.bin. Any known issues (obviously aside from those that come with cleanflight) with compiling this branch for CC3D?

"FS-SEV01 Serial Bus Receiver" according to flysky this uses the same i-bus protocol... do you think it might work with existing code? I already have an I6aB RX on the way and should be able to do some testing this weekend with that.

**Comment by digitalentity** [comment]
@BimmerTas 
I've tested this code with CC3D and NAZE rev4 without issues. Feel free to test the code and report bugs if found!
FS-SEV01 is not a _receiver_ it is a _repeater_. However FS-iR4 is a receiver and it should be compatible with this code as well (however it might be limited to 4 channels - needs to be tested)

**Comment by BimmerTas** [comment]
Cheers for the info! . Will report back. and order a FS-iR4 for testing when i can.. Thanks or your work porting this over!

**Comment by dixiak** [comment]
I'm seeing something weird. I've configured my naze32 to use ibus with an FS-IA6b and everything seems to work ok, EXCEPT that every few seconds there's a pulse where a random channel gets a lower value, most frequently throttle. 
error
I noticed this when the quad was in-flight and now I'm observing it in the Configurator. I also set up an Arduino to read the data coming out of the I-bus port at the same time as the naze32. I am certain that the receiver is not sending these pulses - Cleanflight is making them up!

**Comment by BimmerTas** [comment]
Thanks for sharing. :) Has anyone else reported this ^ same issue? Could be
an issue with the hardware on that particular board??

 I haven't had a chance to test yet. Will have a go using the instructions
you provided soon and see if i have any luck using my arduino for its FTDI
adapter.

The instructions i had used previously were missing the step you
highlighted "*Remove a short from SBL pins!" * I had never tried removing
the short after powering on the CC3D.

**Comment by ledvinap** [comment]
@dixiak : This may be caused by serial transmission error.
Do not use AUX channel to arm with `disarm_kill_switch` enabled - single spike will disarm and you need level quad and zero throttle to arm again, so crash is almost unavoidable ..

**Comment by dixiak** [comment]
@ledvinap I am currently using a softserial port so my first thought was slight bit-rate mismatch or some kind of serial error. However, an iBus frame is 32 bytes long and the last 2 bytes are a checksum. The chances of a random error in the throttle value and another matching random error in the checksum are incredibly slim.

**Comment by ledvinap** [comment]
Maybe failsafe is kicking in when too many frames are broken? Softserial is not very reliable ... 
Try using debug[] to count i-bus frame errors ...

**Comment by tracernz** [comment]
Might like to give some credit in the header comments, you didn't write this code. ;)

**Comment by digitalentity** [comment]
@tracernz Thanks for noticing that. I was hurrying to get the code working and eventually missed the credits as baseflight's ibus.c didn't have them. Will fix this :)
I figure you have commited the iBus code to baseflight, you must be the initial author of the code?

**Comment by tracernz** [comment]
No, I think fiendie but he may have got it elsewhere. It's always a nice touch but as you say, easy to miss. :)

**Comment by digitalentity** [comment]
@tracernz figured who's code is that already! See b8b21e67e8a579bb528d306ee779678b3e78a5bb for proper contributions.

**Comment by dixiak** [comment]
@ledvinap Thanks for your help. That's exactly what happened: about 60% of the frames failed checksum and were discarded. I hadn't realised that softserial was so unreliable ... although I can see now that it is kind of mentioned in the documentation.

**Comment by BimmerTas** [comment]
No problems to report yet. works great!  :) .. bit of backyard tuning and just took it down to the park for a couple of batteries in a 250 racer

**Comment by digitalentity** [comment]
@dixiak 
Indeed, softserial is very unreliable, especially at high speeds (i-Bus runs at 115200 bps)
@BimmerTas 
Thanks for testing this on CC3D and confirming this works.
@hydra 
Can this PR be merged into 1.10?

**Comment by 0ip** [comment]
@hydra I'd love to see this merged too :+1:

**Comment by thedutchviking** [comment]
Forgive this noob comment, but would this discussion have anything to do with me being able to connect my FlySky FS-T6 / FS-R6B with Cleanflight? Right now I'm getting really strange input responses in the "Receiver" tab. 

ROLL - no response: fixed at 1500
PITCH - no response: fixed at 1500
YAW - no response: fixed at 1500
THROTTLE - no response: stuck at 885
AUX 1 - responds properly to SWD on/off
AUX 2 - responds properly to SWB on/off
AUX 3 - responds correctly to yaw input
AUX 4 - responds correctly to throttle input

**Comment by BimmerTas** [comment]
@thedutchviking Well i shouldn't have anything to so with it... I think fs-t6 only supports PWM ... you should have that selected on main config page and  if so none of this applies to you, sorry that doesn't help. 
@digitalentity First time i have checked back in a while, just noticed "This branch is up-to-date with the base branch" Is it already merged with main build? or planed to be soon? :D

**Comment by thedutchviking** [comment]
@BimmerTas Thanks for the reply. At least I can scratch that off my troubleshooting list. (It's more than I had!).

**Comment by thedutchviking** [comment]
@BimmerTas Thanks for the reply. At least I can scratch that off my troubleshooting list. (It's more than I had!).

**Comment by BimmerTas** [comment]
@thedutchviking  Oh... just had a thought... try changing all the channels to the reverse order that they are plugged into now... seems like that could be the issue. IE: if plugged in now 1-6 change to 6-1... obviously the GRD,5V,Signal still need to be plugged in the right way ;)

**Comment by thedutchviking** [comment]
@BimmerTas Woah, that's a wonderful idea! Will pursue. Thank you muchly.

**Comment by thedutchviking** [comment]
@BimmerTas That totally did the trick! I also manually entered my own order in the channel map (super cool that Cleanflight lets the user do that!). I owe you a virtual beverage. lol

**Comment by hydra** [comment]
going to merge this and add configurator support now.

**Comment by digitalentity** [comment]
Thanks!

**Comment by hydra** [comment]
Configurator support added, see https://github.com/cleanflight/cleanflight-configurator/commit/e7ef71c2440f0321a88a0f713621612093276c79

**Comment by hydra** [comment]
If anyone has time please consider working on supporting iBUS telemetry, see #1125

**Comment by Pierre-A** [comment]
**@hydra** , **@digitalentity** see issue #1589, lokupTableSerialRX should be updated with "IBUS".

**Comment by tb942** [comment]
This may be a stupid question, but what are the advantages of ibus over ppm? does it have lower latency? - its just that short of having more channels possible through it, the lack of failsafe makes me wonder what the advantage of ibus is?

**Comment by huston007** [comment]
@tb942 iBus should has same advantages as SBUS and other serial receivers protocols: reliability, lower delay, more channels than over PPM.
For example, I have a cheap TX FlySky I6 with IA6B receiver. It has 6 channels by default, but there is an (updated firmware)[http://www.rcgroups.com/forums/showthread.php?t=2486545] with 10(!!!) channels support (only by iBus). iBus support is the main cleanflight point for me to move from LibrePilot.

**Pull request merged**
