### PR TITLE
Update Mixed docs to match source code

### PR DESCRIPTION
**Pull request by ledvinap**

### CODE REVIEW

**Comment by ledvinap** [comment]
https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/servos.c#L463-L465 is pprobably wrong, or I don't understand it ...

angleAtMin / angleAtMax is not used in code

gimbal code may be easily implemented as normal rules (with minor conditional rule extension)

servo speed granularity is probably too coarse - 1us/cycle, max slowdown is 0.5s middle->full extreme

servo reversal is a bit redundant, it may be implemented as rules (but custom config would be necessary) 

There are no servos for CUSTOM mode - dual and single copter can't be customized

And code could use some face-lift ..

**Comment by ledvinap** [comment]
Updated smix min/max ... Sorry, it took some sleep to read the code correctly ...

**Comment by hydra** [comment]
with regard to angleAtMin/angleAtMax that was so that the tilt drone guys could continue their PR's for tilt support but the work has not been completed.

With regards to the cleanup of the mixer code again the tilt drone guys submitted a PR for it but it's not been worked on yet.  Quite when it'll get done I don't know.  There is just so much to do...

**Comment by hydra** [comment]
I'll merge the documentation changes now, and when we look at servo code we can refer to your notes.

**Pull request merged**
