### PR TITLE
CC3D Atom mini not func AUX1 in Betaflight to V2.3.5.

### PR DESCRIPTION
**Pull request by FPV-Addiction**
**Hello boris
I have a problem, I need help!
I Flashing my CC3D MINI ATOM Betaflight to V2.3.5.
The problem is that I can not properly configure the flight modes with botton AUX1.
In RECIVER, AUX1 does not work!

If I eh not explained well just you tell me 

sorry my English

FPV Addiction

Spain**

### CODE REVIEW

**Comment by borisbstyle** [comment]
What is this PR doing here?

**Comment by FPV-Addiction** [comment]
PR?

**Comment by borisbstyle** [comment]
You made a Pull request to Cleanflight master

**Comment by FPV-Addiction** [comment]
LOL.. jejej
Where I can ask for help

**Comment by borisbstyle** [comment]
close this PR

I cant help you with target I dont have

2016-02-09 11:35 GMT+01:00 FPV-Addiction <notifications@github.com>:

**Comment by SteveAmor** [comment]
@FPV-Addiction please close this PR. RC Groups is a good place for support.

**Pull request closed without merging**
