### PR TITLE
Targets - Add support for the STM32DIP40 F103 development board.

### PR DESCRIPTION
**Pull request by shakhor-shual**
Port to new additional hardware

### CODE REVIEW

**Comment by digitalentity** [comment]
A link to board specs or a site where you can buy it would be nice

**Comment by shakhor-shual** [comment]
my board was like this http://www.rcscomponents.kiev.ua/modules.php?name=Asers_Shop&s_op=viewproductdetails&lid=-72591

but worldwide I think more better - this (but it  a little bit different in pinouts )
http://www.ebay.com/sch/i.html?_from=R40&_trksid=p2050601.m570.l1313.TR0.TRC0.H0.Xstm32+board.TRS0&_nkw=stm32+board&_sacat=0

**Comment by hydra** [comment]
Hi.

there are some problems.
1) pr is unfocussed, there is HIL still and new target support - each PR must be focussed or they will not get merged.
2) hil usage isn't documented in the PR (unless i missed it)
3) there was loads of included files added to one of the source files - this is bad, do not introduce dependencies just to get a master_config or profile settings, pass in what you need instead.

lastly, we need to decide once and for all a cheap development board for people to use.

i personally recommend the PORT103R for F103 development, it's cheap and has extra IO and a sensible pinout.

there is another PR for the MapleMini board which people are FAR mre likely to have than this unknown board since it is sold in far more places.

Also, the fact that you have to modify the board board you can use I2C with it, well...  it's just not right.

I'm in favour of using the maplemini rather than this board but I've not looked at either closely.

To progress this, can you do three things please?

1) remove any non-board specific code from this PR.
2) cleanup and create a new PR for HIL stuff, and we'll discuss that on the new PR.
3) cleanup the board documentation - keep it purely factual, no need to mention countries and their political system 

thanks!

**Comment by shakhor-shual** [comment]
sorry. I just not familiar with git and github, so good, for understanding what exactly my eclipse git plugin doing, when I commit my local changes to my github account(As i thought) I only made my first PR for new target and after that decided working farther on HIL. And why all my next commits of the HILL development, are placed HERE in this my first PR (at the end) I not good understand. I will try decouple this from each other

**Comment by hydra** [comment]
Its no problem.   You should create one single branch for each PR. Please review the developer documentation withi. The projects and look at github workflow guides.

**Comment by shakhor-shual** [comment]
I'm not so beginner in programming, (15+ years maybe ) but it my first experience in open source development, git|github etc. I will very glad for any help or suggestion for organizing right development process with it. And I many years not worked on C, last years it was usually java. Because of that structure of C projects in my creation not not a perfect, sorry. Now I work rewriting traymarc C code for PC because in not work rightly in HIL with FlightGear 3.4+/ After rewriting it and full testing it with FlightGear, cleanflight & MSP RC i try to decide where put in for wide access, because traymarc leave this project (as I think) but without it HIL can't work/ May be a good thought add fork of this code to development under cleanflight project as auxiliary( like a cleanflight-configurator for example)

**Comment by hydra** [comment]
Closing this PR.  Inactive, not needed.

**Pull request closed without merging**
