### PR TITLE
various: header, printf, and flashing fixes

### PR DESCRIPTION
**Pull request by nzmichaelh**

### CODE REVIEW

**Comment by hydra** [comment]
not sure we want the null checking in the serial code.

http://elegantcode.com/2010/05/01/say-no-to-null/

It's better to never pass null in the first place - null checking everywhere is bad.

Best if PR's are focussed on one thing too, makes it easier to merge and discuss.

What caused you to add the null checking?

**Comment by nzmichaelh** [comment]
Thanks for the feedback.  I normally do one feature per patch, but in this case they're so small I thought I'd do one combined.  I'll split them apart in the future.

re: the null checking, I wanted to do some old school style printf() debugging.  printf() uses printfSerialPort which is set when the CLI is open but NULL otherwise.

What's a good way of debugging without going the JTAG route?  How about a debug.h that mimics NuttX's excellent macros:

http://sourceforge.net/p/nuttx/git/ci/master/tree/nuttx/include/debug.h

**Comment by ledvinap** [comment]
@nzmichaelh : there is MSP command to send text message cleanflight. It would be great for printf like debugging (all initialization could log status/problems)..

**Comment by hydra** [comment]
hmm, the stlink boards are so cheap it's almost rude not to have one.  printf debugging is a bit, um, old-hat.  just say no. :smile: 

I you remove the serial null checking commit from this PR i will merge it for you.

**Comment by nzmichaelh** [comment]
But... printf debugging!  It feels so good even though it feels so bad! :)

I did it as I didn't want to solder the JTAG connector onto my NAZE.  I might buy a couple of STM32F3DISCOVERY's instead.

I've reverted the printf() NULL check patch.

**Comment by ledvinap** [comment]
@hydra: Diagnostic messages would be extremely useful. For example feature conflict resolution (and channel placement) are confusing, few info lines would help a lot ...

**Comment by hydra** [comment]
Merged.

**Pull request closed without merging**
