### PR TITLE
Changed Throttle LED Strip functionality

### PR DESCRIPTION
**Pull request by DrClaes**
Throttle Overlay for LED strip fades color (all HSV) smoothly from chosen color to next user defined color

### CODE REVIEW

**Comment by mikeller** [comment]
@DrClaes: Something is not quite right with your PR. Can you please rebase / fix?

**Comment by McGiverGim** [comment]
@DrClaes The base is betaflight:master and not cleanflight:master?

**Comment by DrClaes** [comment]
Yes; I will try to put the pull request to betaflight. First time ever for me.

/Claes Williamsson

**Comment by mikeller** [comment]
@DrClaes: All good, nothing that couldn't be fixed. If this PR has been superseded, can you please close it?

**Pull request closed without merging**
