### PR TITLE
Fix Makefile 'make help' feature

### PR DESCRIPTION
**Pull request by Echelon9**
Some simple typo and string clean-ups to the `make help` feature.

Output now prints cleanly as:
```
$ make help

Makefile for the cleanflight firmware

Usage:
        make [goal] [TARGET=<target>] [OPTIONS="<options>"]

Valid TARGET values are: ALIENWIIF1 ALIENWIIF3 CC3D CHEBUZZF3 CJMCU COLIBRI_RACE LUX_RACE EUSTM32F103RC MOTOLAB NAZE NAZE32PRO OLIMEXINO PORT103R RMDO SPARKY SPRACINGF3 SPRACINGF3MINI STM32F3DISCOVERY 

Default make goal:
hex         : Make filetype hex only
Optional make goals:
all         : Make all filetypes, binary and hex
binary      : Make binary filetype
hex         : Make hex filetype
all_targets : Make all TARGETs
clean       : clean up all temporary / machine-generated files
flash       : flash firmware (.hex) onto flight controller
st-flash    : flash firmware (.bin) onto flight controller
unbrick     : unbrick flight controller
cppcheck    : run static analysis on C source code
help        : print this help message and exit
test        : run the cleanflight test suite
```

### CODE REVIEW

**Comment by Echelon9** [comment]
We are both unlikely to convince the other of our respective positions it seems.

I'll remove the contentious third commit in my PR, so it doesn't hold up the rest which appear to have broadly accepted merits. I should be able to push it later today.

**Comment by hydra** [comment]
I'm fine with the current code.  I'm not a fan of hiding behavior from users, the help serves as a form of documentation.  documentation + code relating to it = win.  random bits of code without documentation = fail.

**Comment by hydra** [comment]
additional commit added to fix the situation.

keep both or remove both is my preference.  keeping both for now, imho it's not a big deal to keep both - some users may find them handy. personally i've always used 'binary' and will continue to do so.  at least we know that 'bin' is an ALIAS now.

thanks for the PR and ensuing discussion guys!

**Comment by Echelon9** [comment]
Great. I enjoyed the discussion with @AndersHoglund and believe we ended up with a good situation.
Looking forward to contributing more in future!

**Comment by AndersHoglund** [comment]
Yes, agree. Good solution.

**Pull request merged**
