### PR TITLE
Lux Target issues.

### PR DESCRIPTION
**Pull request by Timbone1343**
Sorry if this is not formatted correctly, this is my first pull request. 

I am trying to use the Lux target on the Lux and the GUI no longer reboots the board when you press save & reboot(it did with colibri race). Also, I cannot arm even though it sees the arm signal via Aux 1.

If you need more info just let me know.

Using to following equipment.
Lux
Lux 2.3.4 firmware

X4R-SB on SBUS
Taranis x9d+

### CODE REVIEW

**Comment by SteveAmor** [comment]
Pull requested are for developers to provide code changes. 

You appear to have a support question. 

Please close this PR and ask for support on RC Groups.

**Comment by Timbone1343** [comment]
But that's just it, I don't need support, I was simply stating that the arm function doesn't work when I flash the Lux with the Lux firmware. It works just fine on the colobri race firmware.

But if you think this is not code related I can certainly close the request..

**Comment by SteveAmor** [comment]
OK, you need to raise an issue. :-)

**Comment by Timbone1343** [comment]
Thanks, I just did.

**Pull request closed without merging**
