### PR TITLE
Msp mem interface

### PR DESCRIPTION
**Pull request by ledvinap**
Separate MSP command processing from serial port and serial framing

- add streamBuf abstraction
- use `mspPacket_t` to handle packet processing
- `serial_msp.c` code handles MSP framing on input and output
- activeBoxIds is handled as bitmask, permanent IDs and boxNames are returned in boxId_e order

4WAY-IF MSP entry is not implemented yet

### CODE REVIEW

**Comment by ledvinap** [comment]
4way code is so ugly.
Is it kept in sync with some project? Or is it OK to clean it up first before merging it with MSP ?

**Comment by martinbudden** [comment]
@ledvinap , I'd just merge it in as it is. Leave the cleanup to a separate PR. It's always possible to introduce subtle bugs when cleaning up code, and I'd like to see this MSP code merged into master as soon as possible.

**Comment by martinbudden** [comment]
I've just noticed that `streambuf.c`, `streambuf.h` and `msp.h` don't have the "This file is part of Cleanflight...." comment at the top of the file.

**Comment by ledvinap** [comment]
I'll add copyright notices

4way interface still needs work. Setting flag to enter 4way (together with serialPort to use) and handling it in serial code is probably cleanest option ...

**Comment by jflyper** [comment]
The RAM space is much more scarce in MCUs used for traditional OSDs than STM32s.

For example, ATmega328 used in extremely popular MinimOSD and variants only have 2KB RAM.
Under such environment, the BOXNAMES is really a problem, because the max list grows very quickly and endlessly as we keep adding new fancy modes and cool switches. The BOXIDS is similar, but it grows only one byte/mode.

We should invent a new message, say, something like `BOXDEF <bitpos> <name string>`, so we can tell receivers about literal names of bits in the STATUS in a one-by-one fashion with bounded message length, and stop adding things to BOXNAMES.

**Comment by ledvinap** [comment]
@jflyper : command returning one boxname per query may help a bit - OSD may request only displayed boxnames (28 boxes probably won't fit the screen anyway) or request boxnames on the fly.
And it will solve long boxnames reply.

Using permanentBoxId to map from bit to name is not that wasteful - you can save permanentBoxId for each bit (32 bytes with current protocol).

**Comment by jflyper** [comment]
@ledvinap : Just a comment.
I believe the BOXNAMES is intended for receivers having no prior knowledge of modes and switches, although some OSD implementations (MWOSD at least) do compare received names against known names to map literal strings to fancy icons. With BOXIDS, the receiver is expected to have full knowledge of what each ID mean. I can think of a possible use case of all raw strings given by BOXNAMES: a page filled with all names and their states for ... say, pre-flight check? :)

P.S.
While watching the fantastic work on MSP separation, I did some clean up job on MWOSD code to make some room for I2C receive buffer; waiting for MSP messages over I2C now :)

Some random thoughts:
- Interrupt (requires a pin), periodic polling, multi-master?
- Fragmentation protocol? Maximum fragment size?
- I2C bus scheduling (to avoid interfering gyro read ... ah, no multi-master then)?

**Comment by ledvinap** [comment]
@jflyper : As long as `peramanentId`s are unique, OSD may contain ROM table of all/common names to save RAM. Unknown names may be fetched from FC. Returning BOXNAMES on demand will remove longest MSP message. Command to get permanentId by bit index may help with orthogonality, but is not necessary until more than 32bits for modes is implemented.

MSP over I2C - polling from CF (with optional interrupt) is IMO easiest to implement and most robust.

Quick idea:

Use FIFO for command parameters and reply (with shared memory space to save RAM).
`CMD FIFO-LEN FIFO-REG'
Master will poll command register until non-idle command is read, then fetch LEN (or all) bytes from FIFO, process it, write reply to FIFO (length can be implicit) and confirm command by writing processing result into CMD register (or use different register address).
FIFO access may be split into multiple  I2C transactions, it's on master (CF) to handle bus arbitration.

If CF-initiated commands are necessary (MSP telemetry in old code), then just split FIFO memory (or implement command for FIFO arbitration), write params to FIFO and invoke command by writing command register. Possible reply may be handled as normal polled command.

Open new PR if you are interested implementing something like this ..  we can create protocol specification, implementation in code should be quite easy.

**Comment by hydra** [comment]
@ledvinap and @martinbudden fyi, I'm travelling for few days so won't be able to work on this for a few days.  Please continue to work together to complete this cleanup so we can merge it into master ASAP.  When it's ready for merging please add a comment on here and I'll keep an eye out for it.

To be honest with the quality work you're both doing recently I'd be happy to let you merge this yourselves when you both think it's ready.

**Comment by martinbudden** [comment]
@ledvinap , following @hydra 's comments, do you think this is ready for merge?

I've been using it with the Cleanflight configurator with no problems. I haven't tried it with an OSD though.

It's taking a step back to go forward, in the sense that the 1-wire stuff is not in there yet, but that's not far from finished.

I'd like to see this merged and then complete the 1-wire stuff afterwards. What do you think?

**Comment by ledvinap** [comment]
@martinbudden : 4way-if is (almost?) ready, it would be easier to merge it first and then adapt msp before merging ...

**Comment by martinbudden** [comment]
@ledvinap , whichever way you think is easier. I just wanted to indicate that I think that this is ready to merge, but by all means finish the 4way stuff first.

**Comment by hydra** [comment]
Is this ready for merging now?

**Comment by martinbudden** [comment]
@hydra, as far as I am concerned, this is good to go. @ledvinap can you confirm?

**Comment by ledvinap** [comment]
Currently this PR will disable 4-way interface.
Can we merge #2090 first? I can create minimal fix for current version if absolutely necessary .. 
Or is it OK to live without 4way until it is fixed?

**Comment by martinbudden** [comment]
@ledvinap , @hydra , I assumed https://github.com/cleanflight/cleanflight/pull/2090 would be merged in first, since that is ready to go as well.

**Comment by ledvinap** [comment]
4way interface is working now.
Ready to merge.

**Comment by hydra** [comment]
@ledvinap awesome, i will give this a whirl tonight.

**Comment by martinbudden** [comment]
Yes, @ledvinap , this is a really excellent piece of work.

**Comment by ledvinap** [comment]
Thanks

**Comment by hydra** [comment]
needs a merge of master due to merge of #1668

**Comment by hydra** [comment]
I didn't have the chance to test this yet, I'm trying to do a few quick-wins as per #2103 (prepare for 1.13.0)

**Comment by martinbudden** [comment]
@ledvinap , can you rebase this - there are now conflicts.

**Comment by ledvinap** [comment]
Done

**Comment by hydra** [comment]
done and done!

**Pull request merged**
