### PR TITLE
Possibility to auto RTH when battery at xx.xxV or bellow.

### PR DESCRIPTION
**Pull request by ricard0g0mes**
It would be great if the FC measuring the battery would return to home when battery low.
It could blink some led or use the buzzer 1 minute before or something like that and then, auto RTH

### CODE REVIEW

**Comment by skaman82** [comment]
I'm not sure if you are targeting the right branch. Is this a vilid PR?

**Comment by gaelj** [comment]
In addition you should use remaining mah capacity rather than voltage.

**Comment by martinbudden** [comment]
@ricard0g0mes , is this meant to be a PR for iNav rather than Cleanflight?

**Comment by turboworks** [comment]
hi,in inav, any way to get 2 active servo pins in custom or custom tri or bi ?in custom  tricopter it comes close ,works in the motor page, but only one output pin for servo, motors are good. naze 32 . inav works amazing ! great work.
thanks
Rick   
turboworks@yahoo.com

**Comment by hydra** [comment]
I think this PR has been created in the wrong place.

**Comment by turboworks** [comment]
Hi, thanks ,were would you ? Sorry,hardware guy. Btw good work!

**Pull request closed without merging**
