### PR TITLE
Invalid cycle_time calculation

### PR DESCRIPTION
**Pull request by DreamNik**
Hi!
I'm working on compiling Cleanflight to run on PC.
I've noticed that on first loop the "cycleTime" variable is very small (12-18, compared to expected 3500).

Is this normal?

Almost always it lead to arithmetic exception in function "filterRc" https://github.com/cleanflight/cleanflight/blob/master/src/main/mw.c#L681 due to small "cycleTime".

I've changed "cycleTime" calculation algorithm.
So please, please and please check if this won't cause any problems on real hardware!

On PC now it's perfectly calculated around 3500.

### CODE REVIEW

**Comment by dkisselev** [comment]
It looks like an unrelated commit made its way into the same branch as this change, I'm guessing you'll need to fix that before the PR can be merged.

**Comment by borisbstyle** [comment]
looptime variable is used for other things as well like for example blackbox.

**Comment by ledvinap** [comment]
@borisbstyle : removed `loopTime` is local to `loop()`, IMO it is safe to remove it

**Comment by borisbstyle** [comment]
o yeah right.....the other one is from the config.
Op 16 nov. 2015 12:50 schreef "Petr Ledvina" <notifications@github.com>:

**Comment by DreamNik** [comment]
Ok, I've moved commit and updated branches.

BTW, is that correct to modify local git history and then force-push to github, if no one merged with my commits yet?

**Comment by borisbstyle** [comment]
Did you test this?

Your approach doesn't work actually.

**Comment by DreamNik** [comment]
I've tested in on PC build (https://github.com/cleanflight/cleanflight/pull/1496).
There is works fine.
I haven't tested in hardware yet.

**Comment by borisbstyle** [comment]
Try it and you will see that it doesnt work on the hardware.

I compiled your version and I get cycletimes of 3700 while 3500 is
configured.
Op 17 nov. 2015 17:55 schreef "DreamNik" <notifications@github.com>:

**Comment by borisbstyle** [comment]
I think it's ok the way it is when we want to reuse it. Prevents
recalculations.

There is another way to solve that filtered looptime with initializing it
instead of starting with calculations.
Op 17 nov. 2015 18:31 schreef "Boris B." <dreambb1982@gmail.com>:

**Comment by ledvinap** [comment]
https://github.com/DreamNik/cleanflight/blob/fix_cycleTime_1/src/main/mw.c#L755-L757

previous time is time after imuUpdate, so full looptime is longer...

**Comment by borisbstyle** [comment]
yes exactly. You get the imu processing delay in the looptime
Op 17 nov. 2015 20:15 schreef "Petr Ledvina" <notifications@github.com>:

**Comment by borisbstyle** [comment]
And I guess becaude he was testing yhe code on the pc he didnt have the
additional imu lag :)

But funny enough we all fell into this one.
Op 17 nov. 2015 20:33 schreef "Boris B." <dreambb1982@gmail.com>:

**Comment by DreamNik** [comment]
Yes, looks like "imuUpdate" on PC takes zero time.
I've removed second measure of currentTime.
I've checked on PC with forced delay on "imuUpdate" - works fine.

**Comment by DreamNik** [comment]
Why "currentTime" measured right after sensor readings?
Is it safe to measure it before?

So I think of two variants:

1)
currentTime = micros();
if( ... ){
   imuUpdate(...)
   cycleTime = ....
   ....
}


2)
currentTime = micros();
if( ... ){
   imuUpdate(...)
   cycleTime = ....
   currentTime = micros();
   ....
}

**Comment by DreamNik** [comment]
https://github.com/DreamNik/cleanflight/commit/44edd980a36590a986cf539e858056fc3a997762

**Comment by ledvinap** [comment]
With your change you removed imuUpdate processing jitter from cycleTime..

**Comment by borisbstyle** [comment]
@DreamNik 
I hope you realize why it was done like that.

**Comment by DreamNik** [comment]
The whole problem of this issue is that I've got division by zero in filters.
That is because the first loop is executed immediately, so that currentTime-previousTime where close to zero.
On hardware this didn't showed up yet because of imuUpdate delay, which causes cycleTime to be slightly bigger, so there is no division by zero.

**Comment by hydra** [comment]
It's liklely that the newly merged task scheduler code invalidates this PR.  Closing.  If there's still an issue please create a new issue and reference this one.

**Pull request closed without merging**
