### PR TITLE
Put CLI commands in code blocks so they appear in the markdown correctly

### PR DESCRIPTION
**Pull request by mtrl**
Preview of the new rendering of code blocks

MD preview

### CODE REVIEW

**Comment by thenickdude** [comment]
They actually appear with grey backgrounds with GitHub's rendering:

Before: https://github.com/cleanflight/cleanflight/blob/master/docs/Cli.md
After: https://github.com/mtrl/cleanflight/blob/master/docs/Cli.md

But yeah, that looks nicer.

**Comment by mtrl** [comment]
This hasn't been merged. It also puts each command onto new lines which they currently aren't

**Comment by hydra** [comment]
I have been using tripple "`" to introduce blocks rather than leading spaces.  Copy/paste with leading spaces is not as user friendly when editing the raw .md files.

I will fix now.

**Comment by hydra** [comment]
@mtrl Please review 0c82141 to see preferred format.   Thanks for the corrections and PR.

**Pull request merged**
