### PR TITLE
IO - implement USB serial buffering

### PR DESCRIPTION
**Pull request by ledvinap**
Allow larger USB serial packets, buffer USB streams

USB endpoints are hardcoded, rest of code is modeled after USART.

Tested on sparky, no packet errors and no looptim spikes. This code should not be called inflight (no USB), so it should be quite safe to merge

### CODE REVIEW

**Comment by hydra** [comment]
Needs testing on CC3D.

**Comment by ledvinap** [comment]
I don't have CC3D...

I'll try to improve separation between serial and CDC. Wait a bit with merging (but i't OK to test)

**Comment by ledvinap** [comment]
Ok, now serial code is separated from USB, only buffers are passed (get/ack mechanism)

**Comment by ledvinap** [comment]
Rebased ...

**Comment by ledvinap** [comment]
Rebased, fixed subtle bug in buffer negotiation

**Pull request closed without merging**
