### PR TITLE
4way Interface for ESC configuration and flashing - SK and BL bootloaders and USB VCP support.

### PR DESCRIPTION
**Pull request by hydra**
This PR supersedes #2003.

This PR exists so that other cleanflight developers can contribute to cleaning this code up so it can be merged into master.

I tested very breifly using an SPRacingF3Mini using BLHeliSuite 14.4.0.5 from here:

https://www.mediafire.com/folder/dx6kfaasyo24l/BLHeliSuite

I was able to read esc setup, change parameters, flash and verify firmware and control motor outputs via VCP USB.

TODO:
* cleanup large amounts of code and logic duplication.
* include files including other files (a no-no in cleanflight right now).
* fix code style `preferCamelCase` for new code `not_underscores`, `x = y` not `x=y`, etc
* delete unneeded code.
* move some of the code from serial_msp, if possible.

QUESTIONS:
a) do we need the old 1WIRE code if we now have the 4way interface code?

POSSIBLE ANSWERS:

a.1) no, delete it.  then there will be less to cleanup.

### CODE REVIEW

**Comment by 4712** [comment]
OK, I will remove the 1wire-uart and 1wire-vcp.
atm there are 2 options for the 4way-if
#define USE_SERIAL_4WAY_BLHELI_BOOTLOADER
#define USE_SERIAL_4WAY_SK_BOOTLOADER

Remove this? Always compile for BLHeli **and ** SimonK bootloader?
This would simplify all further...

**Comment by 4712** [comment]
Compiles atm to:

compilesizes

**Comment by hydra** [comment]
i making the default build support BL and SK bootloaders would make the most sense - otherwise users would be like: `but it's a BL heli ESC and it doesn't connect`.  Cutting down on the user support so we can spend more time coding = win.

**Comment by digitalentity** [comment]
Tested, working flawlessly!

**Comment by hydra** [comment]
yeah, i gave this a whirl myself after merging master with it, working fine on the 12 esc's i tested it on (both SK & BLHeli bootloaders)  did a variety of tasks including reflashing and had no issues.

will continue review and merge ASAP.

**Comment by hydra** [comment]
ok, aside from some code style issues I'm happy enough for now with this.

Since it's not core flight code and is very isolated we can merge as-is now.  I welcome cleanup PR's on this code.

**Pull request merged**
