### PR TITLE
Sync looptime to gyro interrupt 

### PR DESCRIPTION
**Pull request by nksreera**
gyro interrupt at lpf 42hz fires every 1000us, with this change the loop is executed as soon as a gyro read is available. 
this should benefit soft filters as well.

currently it is settable on a profile using cli
set sync_looptime=1

tested on naze32 loop time is at 2000us with accelerometer
and 1000us when acc_hardware=1

should be 1000us for f3 processors as well.

future additions would be to calculate gyro soft filters in the interrupt so if gyro_lpf is set to 256 the soft filters are evaluated every 125us.

### CODE REVIEW

**Comment by nksreera** [comment]
tested on naze32 rev5 and flip32

**Comment by borisbstyle** [comment]
Going to quickly test this and see how it works and add it to my local build.

I see you added an extra file to link that variable :D. It should be possible to do somehow differently.

**Comment by borisbstyle** [comment]
It works on SpracingF3 board as well. I like the fix and was something on the list to try, but I am not sure about this being better above standard stable looptime way.

@ledvinap 
What do you think of this fix. It certainly works, but it does add jitter to the looptime what also affects the PID's


Here an example.
Notice how my PID's now show jitter on looptime around 600. The logging is 1/2
https://dl.dropboxusercontent.com/u/31537757/cleanflight/sync_loop.TXT

**Comment by nksreera** [comment]
@borisbstyle the loop time on the f3 should be around 1000. maybe you are using gyro_lpf=256 ? that triggers the interrupt every 125us which is as good as setting the loop time to 0 and that would cause the jitter.

the thought I had here was that the pid controller uses the full output of the gyro and doesn't re-use the same values. i.e. if loop time were to be set to 300 we would be fed 3x.

I will remove the extra file and move it to acc_gyro.h.

**Comment by borisbstyle** [comment]
@nksreera 
Yes correct I was using gyro_lpf = 0 (256)......yeah that's where it can't keep up gyro anymore.
It would be nice to get like 2-4 samples when gyro_lpf is set to 256 so we can apply some filtering.
Intruduce something like gyro ticks and when we get correct amount of ticks continue loop and apply filter.

**Comment by borisbstyle** [comment]
I don't think that will actually every reach 125us due to i2c speed. In my case looptime was around 600.

**Comment by bdoiron74** [comment]
Ever measure the read time on the CC3D? SPI should be able to go pretty quick. 
A DMA implementation would be cool.

**Comment by nksreera** [comment]
I tested looptime 600 and understood why it didn't work for Boris.
at 600 and gyro lpf 256 the effective loop time requested becomes 125 at which point the jitter is introduced. I made some changes and need to test it further.
Boris i'll add it to my local fork so that you could review and possibly test

**Comment by henn1001** [comment]
Taulabs is dealing with something similar at the moment
https://github.com/TauLabs/TauLabs/issues/1730
might be a good reading

**Comment by fakatwork** [comment]
I think the sample rate divider is the way to go, and it was mentioned by @ledvinap back then in #1014 first comment. Current boards obviously can't digest the data at 8kHz, and whatever the gyro rate, the acc rate will be 1kHz, so it's best to get both data at the same rate.

I don't think that taking 7 extra values and averaging would be better than just getting the data sampled at 1kHz, adding filters on top of filters is not the solution.

I suggest that whenever the code initializes gyro_lpf to 256 it also sets the srate divider so we always get (at least on those chips) data at 1kHz.

**Comment by henn1001** [comment]
Better idea is to make it configurable? Problem is that the f1 boards can´t run at looptime=1000 without disabling the ACC. I´m fine running it without the acc because i don´t need it anyway but i figure most don´t want to do that.

**Comment by bdoiron74** [comment]
Maybe 'snap' the user entered looptime to a division of the MPU rate (1khz
or 8khz as configured), then configure the MPU divider to match.

**Comment by borisbstyle** [comment]
@henn1001 
Yeah I saw that discussion on taulabs earlier this week.
@bdoiron74 
This is how ledvinap implemented the divider. You can check based on LPF setting no need to check someones looptime.This PR pretty much disables the looptime actually
https://github.com/ledvinap/cleanflight/blob/local/src/main/drivers/accgyro_mpu6050.c#L397-L401

The more and more I look into this I think the current implementation as it is is not bad at all when you think about the current hardware limitations.

Another option to consider is to drop divider to 1khz and collect 2 samples and apply filter on it. Let looptime skip one cycle to make it stable for all boards around 2000us.

**Comment by borisbstyle** [comment]
What do you guys think of doing this feature with MPU6050 set to sampling rate of 600hz for naze32 and 1khz for F3 targets?
That should give a solid synced gyro to loop and enough room for FC to keep up.

**Comment by henn1001** [comment]
Idk if fixed values will make the masses happy :D maybe ask around in rcgroups?

**Comment by borisbstyle** [comment]
@henn1001 
Well no real need for asking around. Just from the engineering point of view to get the maximum performance with any kind of used hardware the divider for sampling rate should be determined based on the target and LPF setting when this feature is enabled.
To keep some headroom for CPU I would go for ~1600-1700 looptimes on F1 targets and ~700-800 looptimes on F3 targets.

Summary: Sampling rate divider needs to be dynamic based on the configuration. Perhaps later current looptime method can be entirely removed if you ask me and use synced loop by default. The user will always get optimal performance. It always caused a lot of confusion for most common users and still is.

**Comment by borisbstyle** [comment]
I will upload some code after some testing where the looptime is fully disabled and the best sample rate is automatically selected for all targets.

**Comment by henn1001** [comment]
I understand that but with the current mentality regarding looptimes we would certainly need some proof that this works actually better that the old system :). Also idk about that 1600-1700 looptime. My Acro Flip32 runs only at a stable 1450-1500 with luxfloat. A full naze would be even slower and when they activate features like softserial/LEDs/Displays or whatever idk if that will be enough.. But i can´t test that.

**Comment by borisbstyle** [comment]
@henn1001 I knew someone would say that lol. Even F3 target can go much lower, but I do want to add some overhead for future features etc. I don't think it should make any much more difference. The divider is also very restricted as for example when using lpf below 256 where you cant run 1khz, but I only can divide by 2 which will get 500hz and the board can handle more. With 8khz you have more dividing ability. So take that in mind as well

**Comment by borisbstyle** [comment]
I do think this change would require not using the gyro_lpf, but fully convert to soft filters so you can get the maximum divider flexibility.

**Comment by swilkens** [comment]
What about people flying around with ~400Hz input ESCs, a looptime below 2500 would essentially be wasted - right? In stead of re-using gyro frames in the old situation you'd be dropping them in the new situation, on older ESCs.

The same fixed value issue I suppose. Can't cater to all?

**Comment by borisbstyle** [comment]
@swilkens 
The processing of data is more important than ESC refresh rates. With any possible PWM rate the esc will always get the last calculated value based on a fresh gyro input. The processing in between will get the best aliasing performance and filtering.

In other words getting gyro + pid controller synced will benefit all scenarios.

**Comment by joshuabardwell** [comment]
>A full naze would be even slower and when they activate features like softserial/LEDs/Displays or whatever idk if that will be enough..

I was having the same thought. Imagine somebody running a fully-kitted copter with SoftSerial GPS, SoftSerial OSD, OLED Display, and LED lights. What's the absolute maximum looptime that can occur when all available features are enabled?

**Comment by borisbstyle** [comment]
@joshuabardwell 
I didn't see any significant increases when running mag and baro on full naze. Never tried GPS though. I think I never saw a naze board exceeding 1600 for example. 
The worst I saw was on a naze with broken oscillator. There is a little oscillator onboard what often can get damaged. Everything still works, but the naze32 would clock itself back to 64mhz I believe.

**Comment by joshuabardwell** [comment]
>Never tried GPS though. I think I never saw a naze board exceeding 1600 for example. 

It's not the GPS as much as it is the SoftSerial. In my experience, SoftSerial adds about 100 us when Telemetry is enabled at 9600 baud and the copter is armed. Presumably, doing 2x SoftSerial (e.g. telemetry and GPS) would add more, and higher baud rates would add more still. I've never tested LEDSTRIP myself.

**Comment by borisbstyle** [comment]
Ok I think I have some good flyable code

@nksreera 
Your approach isn't correct. The reason you were seeing looptimes of 1000 is because that was the lower limit :D. You need to check for interrupt each time prior to loop.

**Comment by nksreera** [comment]
to get loop time of 1000 the following are needed
1. sync_looptime=1 
2. gyro_lpf=42 (default)
3. acc_hardware=1
4. looptime=3500  (default)

when the gyro data ready interrupt is fired the last gyro read is saved and the main loop picks up executes in and writes to motors (if oneshot is enabled)

the reason it didn't work for you are because you have
1. gyro_lpf=0
2. looptime=600

in the case when gyro_lpf is set to 0 or 256 or even the loop time is less than 2000 the sync_looptime acts in a adverse way and works similar to setting the loop time to 0 (we not quite but something like x+-125. which is totally bad and makes the loop time neither 0 or 1000. but something totally random.

**Comment by borisbstyle** [comment]
I was really trying to figure out hoe this should have worked for you, but your method doesn't work at all for me even with gyro_lpf of 42.
Looptime should have nothing to do with it. That interrupt only goes off when function called and thats not happening outside the loop. 

You need to check for data ready flag in the mpu. I also tested forcing MPU to another sampling rates with success. There is a INT_STATUS flag and that's the one you need to poll for. That's your interrupt request.

I tested everything between 500hz and 1.6khz sampling rates and it works really well.
I also found an issue in the current MPU init sequence, which never caused issue as default sampling dividers were being used. 
There are even some unexisting functions in the headers there which can be removed.

**Comment by borisbstyle** [comment]
Guys who can help me out with the Cleanflight targets. If I want to make a serious PR supporting all targets there would be separated in something like below. I am talking about different performance grouping in terms of refresh rates. What about sparky?

F1 targets: Default gyro sampling 500hz, when no lpf and acc disabled 1,6khz)
      MPU6000 (mpu6000 interrupt)
      MPU6050 (mpu6050 interrupt)

F3 Targets (when no gyro_lpf 1.6khz, with gyro_lpf 1khz):

**Comment by henn1001** [comment]
Well i had a quick look at the datasheets and the problem with the samplerate divider should only be on targets with the mpu6500 (so mpu9250 is affected too). There the divider is only active when the DLPF is active ( so anything below 256).

Sparky 1 uses the mpu6050(mpu9150) so it should be fine. But someone with a Board should test that for you ofc.

Besides that, sounds great so far :+1:

**Comment by borisbstyle** [comment]
@henn1001 
I think it's done now and it works. Can someone perhaps do some quick verification on the CC3D as that one uses MPU6000 and SPI. The code isn't much different than for MPU6050, but I would like someone to run 3 simple tests? No need for flying here just looptime checks with some scenarios.

**Comment by pulsar256** [comment]
@borisbstyle tell me what to do. I can hook it up to SWD and do some debugging if necessary.

**Comment by borisbstyle** [comment]
@pulsar256 
Test is simple. Thanks!

Needed for testing: Cleanflight configurator / Cli
Test sequence:
1) verify if it works!  
2) set gyro_lpf to 42 and acc_hardware 0 (default) - Check looptime (expected result around 2000)
3) set gyro_lpf to 0 or 256 and acc_hardware 0 (default) - Check looptime (expected result around 1600)
4) set gyro_lpf to 0 or 256 and acc_hardware to 1 - Check looptime (expected result around 625-700)


Hex file for CC3D:
https://dl.dropboxusercontent.com/u/31537757/cleanflight/Beta/cleanflight_CC3D.hex

**Comment by borisbstyle** [comment]
A better overview
refresh rates

**Comment by borisbstyle** [comment]
One correction to above. Divider for 1.6khz is 5 and not 6

**Comment by nksreera** [comment]
@borisbstyle sounds like you got it working better, that is awesome. 
its disappointing that you didn't see the same effect as I saw on my end. would love to help you test this one. do you have the changes on your local fork ?

**Comment by borisbstyle** [comment]
I will put it soon once I have done my performance testing. Tested so far on Naze32 and SpracingF3.
These are the new tested values for optimal performance. you can also nice see dfference in F1 and F3 performance. All due to floating point performance.
refresh rates

**Comment by pulsar256** [comment]
@borisbstyle 
1) verify if it works!
ACC / Gryro working just fine

2) set gyro_lpf to 42 and acc_hardware 0 (default) - Check looptime (expected result around 2000)
acc_hardware = 0, gyro_lpf = 42 -> Looptime ~780

3) set gyro_lpf to 0 or 256 and acc_hardware 0 (default) - Check looptime (expected result around 1600)
acc_hardware = 0, gyro_lpf = 0 -> Looptime ~780

4) set gyro_lpf to 0 or 256 and acc_hardware to 1 - Check looptime (expected result around 625-700)
acc_hardware = 1, gyro_lpf = 0 -> Looptime ~100

numbers according to cf configurator gui 0.65.0 over USART1 (*not* VCP)

**Comment by borisbstyle** [comment]
@pulsar256 
GREAT! Very happy it works! I trust the numbers.....all I wanted to know was if it works on MPU6000.

I also finished my flight testing and all I have to say very happy! I did have to bring down those 2khz rates down to 1.6kh as it was a bit jittery and blheli ESC's having troubles arming, but that's no issue.
1.6khz results were impressive!

Off to few more tests and I will start getting this into my local. It would be helpfull if @hydra  would merge the latest filter PR as I also had to change some things on gyro filtering. It would be great if I can make a PR from the master with those changes.

**Comment by digitalentity** [comment]
@borisbstyle, @nksreera 
While this is a great PR, please don't forget that MPU6050 is not the only gyro we have that supports data ready interrupt. MPU6000, MPU3050, L3GD20 and L3G4200D has that as well and this feature must be supported for all of them.
BTW, initialisation code for hardware LPF is working it correctly on arbitrary gyro_lpf values **only** on MPU60x0. other gyros get initialised to lowest possible lpf frequency when gyro_lpf is set to unsupported value,

**Comment by borisbstyle** [comment]
Here is my PR
https://github.com/cleanflight/cleanflight/pull/1186

**Comment by nksreera** [comment]
I got the sampling working, however I see boris has already created a PR.
should I close this PR ?

**Comment by borisbstyle** [comment]
@nksreera Yeah I suggest closing it as it is confusing now.

**Comment by hydra** [comment]
this is invalidated by the other PR that has already now been merged. 

thanks for the contributions everyone!

**Pull request closed without merging**
