### PR TITLE
Added MSP commands to get/set Selective Software Filtering (and yaw P limit) with GUI

### PR DESCRIPTION
**Pull request by ProDrone**
To support Selective Software Filtering from #1028 (and yaw P limit) in GUI.
These commands are used by other pull request for the configuration GUI: https://github.com/cleanflight/cleanflight-configurator/pull/216

### CODE REVIEW

**Comment by hydra** [comment]
I'm not sure about this.  I'm torn.

Yes, we want to allow users to configure and change the values.
No, we don't want to confuse them.

MSP_PID_FILTERS doesn't feel like the right name for this stuff to me.

Something along the lines of MSP_GYRO_CONFIG for the LPF settings

Perhaps extending MSP_PID/MSP_SET_PID to set the other values makes more sense rather than introducing a new command, the code to SET the pids can check the incoming packet length and set the other values if they are present.

Should yaw jump prevention also be moved into pid profile?

Should the code at the top of mixTable() that uses the yaw_jump_prevention_limit really be where it is or should it really be done as part of a pid controller output post processing activity? - the purpose of the mixTable() code is to update motors and servos, not to apply corrections to the axisPID values.

**Comment by ProDrone** [comment]
What is the confusion? I added `yaw_p_limit` because i thought it was missing in the configurator (and later complemented that with `yaw_jump_prevention_limit` as advised by @borisbstyle). I can remove it if is it causes confusion. Basically it is a matter of specifications (you may specify different and you will get what you want :smile: )

I created a new command instead of extending an existing one, so that other clients like EZ-GUI do not have to adapt. At the same time i felt it belongs to an existing MSP command. Also because i see these MSP commands as soon to be dropped items (in favor of a new/additional protocol to cover changed storage). The latter is something i like to sink my teeth in, but prefer to complete my other open PR's first.

I did not look where and how `yaw_jump_prevention_limit` and `yaw_p_limit` where used. Just wanted to expose them to the user. Sound like you are right.

From now on and next week i am on holiday, when i'm back i will modifiy it as you indicated above (and perhaps according to some additional notes by then).

**Comment by borisbstyle** [comment]
Some pid controllers use yaw_p_limit and some not, but all of them have yaw_jump_prevention_limit applied at the end.

I agree hydra that some parts could be in the pid controllers like that one above, but we are dealing here with a lot of legacy stuff which was already there. It's slowly getting cleaner :D

**Comment by borisbstyle** [comment]
But there is indeed some true what @hydra says. We don't want to confuse the enduser by much. Perhaps there should be an extra tab in the configurator called "Advanced Tuning"
All advanced parameters should be accessible from there with remark stay away if you don't know what you are doing :D.
Default is in 99% of cases fine unless you are the guy looking for the optimal precision and performance

**Pull request closed without merging**
