### PR TITLE
Fix 3D Mode #3696

### PR DESCRIPTION
**Pull request by KenImhof**
Added two missing lines of code to 3.2.0-RC3 [mixer.c].  Addresses a problem with 3D mode not being able to control the motor throttle output. Throttle would immediately go to full reverse throttle during positive to negative transition.
  
[mixer.zip](https://github.com/cleanflight/cleanflight/files/1228560/mixer.zip)

### CODE REVIEW

**Comment by mikeller** [comment]
@KenImhof: Can you please close this one? betaflight/betaflight#3870 has been merged, so this is unneeded.

**Comment by KenImhof** [comment]
I am so sorry, but I want to make sure I do it right.  The option I have is to delete the branch as listed below. Is this what I should do?

**Comment by mikeller** [comment]
All good, I've closed the pull request already (it had some urgency because it kept sending notifications for all merges into master). It is up to you if you want to delete the branch or not (you can always restore it).

**Comment by KenImhof** [comment]
Hi Michael,

 

Sorry to ask as I know you are very busy with mission critical work. I am hoping you can give me a little direction.  I received my STM32F3DISCOVERY kit so I can better debug my code.  I have been struggling for many days to compile BetaFlight under Eclipse.  I have tried the CleanFlight documentation for Eclipse Luna with both Cygwin and MinGW MSYS, but I always get errors when trying to build the project.

 

I have also tried both Eclipse-Luna and Oxygen using the BetaSite documentation (https://github.com/martinbudden/betaflight/blob/master/docs/development/Building%20in%20Eclipse.md) but, the GNU MCU will not load and says solutions not available.

 

Am I going down the right path or is there another approach I should take.

 

Thanks,

**Comment by mikeller** [comment]
Hi @KenImhof. I am not the right person to ask about setting up a dev environment under Windows, I am a  linux user. To ask for development related advice on Betaflight, I would recommend you join the Betaflight slack at http://www.betaflight.ch/ .

**Comment by KenImhof** [comment]
Thanks Michael!!!

**Pull request closed without merging**
