### PR TITLE
Add pause/resume switch support to Blackbox

### PR DESCRIPTION
**Pull request by thenickdude**
Initial implementation by @fedorcomander in #1122.

You can now add a mode switch to enable Blackbox logging. If no Blackbox mode is defined, the old behaviour remains (always log), otherwise log events are only logged when the mode is active.

screen shot 2015-07-14 at 09 40 21

Matching support for blackbox_decode and the web viewer has already been committed in.

### CODE REVIEW

**Comment by fedorcomander** [comment]
This is very good stuff @thenickdude ! Thanks!!!

**Comment by borisbstyle** [comment]
I get compiler warnings in this one in case you didn't know:


./src/main/blackbox/blackbox.c: In function 'handleBlackbox':
./src/main/blackbox/blackbox.c:1336:67: warning: passing argument 2 of 'blackbox                                             LogEvent' from incompatible pointer type
                 blackboxLogEvent(FLIGHT_LOG_EVENT_LOGGING_RESUME, &resume);
                                                                   ^
./src/main/blackbox/blackbox.c:1106:6: note: expected 'union flightLogEventData_                                             t *' but argument is of type 'struct flightLogEvent_loggingResume_t *'
 void blackboxLogEvent(FlightLogEvent event, flightLogEventData_t *data)
      ^

**Comment by thenickdude** [comment]
Thanks Boris, I'm not sure how I missed that one. Should be fixed now!

**Comment by borisbstyle** [comment]
Cheers. Will try it out soon.

**Comment by borisbstyle** [comment]
This works really well :dancer:

**Comment by hydra** [comment]
Suggestions on how to reduce the code size for the OPBL CC3D build welcomed. :smile: 

Is there any de-duplication that can be done in the blackbox code itself?

**Comment by thenickdude** [comment]
I've now tidied up Blackbox a bit and it now fits with OPBL. 

I've only bench tested this version (my copters are in another country). It should work fine, but if someone wants to fly-test it and check the resulting graphs for sanity, that would be great.

**Comment by hydra** [comment]
@thenickdude Thanks for code
@borisbstyle Thanks for testing

:smile:

**Comment by jdn-za** [comment]
:+1: :boom:

**Comment by fedorcomander** [comment]
Very good stuff guys!!!

**Pull request merged**
