### PR TITLE
Add Tones for Arm/Disarm

### PR DESCRIPTION
**Pull request by Ravenholm14**
Two Short Beeps for arm
One Longer beep for Disarm.

### CODE REVIEW

**Comment by hydra** [comment]
The buzzer code cleanup needs to be ported from baseflight first.

**Comment by 12-hak** [comment]
This would be a good feature and reuses existing beeper code that would be changed after cleanup. Why not include it now?

**Comment by thenickdude** [comment]
The cleanup would likely include deciding what statuses should have which beep patterns, and there's a bunch of statuses that need to be clearly distinguished. Assigning a pattern to arm/disarm now (and everybody getting used to it) only to possibly have to change it immediately upon rebuilding the beep patterns would be a pain in the ass for users.

**Comment by Ravenholm14** [comment]
I've been compiling my own hex files with those two extra lines of code for months, and running it on my two quads without a problem. I guess ignorance is bliss.

**Comment by thenickdude** [comment]
The suggested `blinkLedAndSoundBeeper` disarm beep would hang the system for 1590ms and the arm beep for 280ms.

**Pull request closed without merging**
