### PR TITLE
Modified failsafe (issue #112)

### PR DESCRIPTION
**Pull request by ProDrone**

### CODE REVIEW

**Comment by ProDrone** [comment]
@Hydra Sorry no luck with testing. I cannot achieve a stable altitude hold (i have both a baro and a sonar). I had a mix of bad weather and failing tests so far - and a crash ;-( i hope to be back in the game soon...

**Comment by hydra** [comment]
Any update?

**Comment by ProDrone** [comment]
@Hydra Is it possible for you to ignore the commits from 26 november and only use the code from before that date? I have very little effective testing time and still no clue as to why my altitude hold is not working. This is a requirement for testing that latest addition. I don't want to hold up the other mods. As soon as i have a working alt hold and tested things i will do a separate pull request for that.

**Comment by hydra** [comment]
Yes. OK.  Good idea.

**Comment by ProDrone** [comment]
@hydra I did a rebase to the best of my knowledge ;-S Please shine your light on it... I really hope i did not break anything...

**Comment by ProDrone** [comment]
@hydra I did a rebase to the best of my knowledge. Next i made some corrections since the code did not compile locally without errors (naze build). Travis CI build still failed after that. What should i do to correct?

**Comment by thenickdude** [comment]
@ProDrone: You're calling altitudeHoldGetEstimatedAltitude(), but this is not available on targets which don't support altitude hold as they have no baro and no sonar (the contents of altitudehold.c are wrapped in a `#if defined(BARO) || defined(SONAR)` block).

If your code also requires a baro or sonar, you'd need similar checks for those symbols.

**Comment by ProDrone** [comment]
@thenickdude: Thanks, i saw it too! Previously i used the variable `estAlt` combined with some `#if defined(BARO) || defined(SONAR)` construction. It is corrected and passes now.
@hydra: I noticed that my local test build with TARGET=CC3D OPBL=yes, fails when using the latest (__gcc-arm-none-eabi-4_9-2014q4-20141203-win32__)  toolchain. Any idea why?

**Comment by thenickdude** [comment]
GCC 4.9 creates binaries that don't work on CC3D, and they also end up a
little too big to fit into flash (which causes the fatal error). Use the
GCC 4.8 series from here instead:

https://launchpad.net/gcc-arm-embedded

It could also be that we now just have too large of a code size to fit into
that target.

**Comment by ProDrone** [comment]
@thenickdude: Today i just updated the 4.8 2014q1 to the latest 4.9 2014q4 release. The next release milestone is planned at 31/3. I noticed also that successful Travis CI testbuilds seems to use 4.8 2014q3 release. I am reluctant to go back in time and prefer to solve problems with the latest toolchain.

**Comment by thenickdude** [comment]
Sure, if you can figure out why the 4.9 binaries don't work on Sparky or CC3D that would be better. I would love to debug it but I only have debug equipment for the Naze, which runs fine with 4.9 binaries.

I suspect it's most likely due to not initialising all the members of a struct somewhere and then handing it off to the hardware for initialising some device, which only works by coincidence on 4.8.

**Comment by hydra** [comment]
@ProDrone is this ready for merging?

**Comment by ProDrone** [comment]
@hydra not yet. I need to check the implications when there are only 4 channels available (PWM and VBAT on CC3D as you mentioned earlier). The use of altitude in failsafe has never been field tested because i have no working barometer/sonar quad available.

@thenickdude Oké, i have the same limitations for debugging and no Sparky or CC3D either. I went back to 4.8 2014q3 toolchain. I hope the issue will be solved with new 4.9 milestone.

**Comment by hydra** [comment]
@ProDrone ok, so that we can progress things here, I would like to merge in the code changes that remove the failsafe vtable usage and then wait for you to do field testing of any additional code.

I will do that now.  Then you will have to rebase this PR on the latest master and perform field testing before we can merge.

**Comment by hydra** [comment]
Failsafe vtable usage removed in e40a366

@ProDrone over to you.

**Comment by ProDrone** [comment]
@hydra If you merge all of the PR you need to set the number of channels (which i set from 4 to 6 in commit 3e1e30fcef3481030aaae57c037bd72a2c465ad6) conditionally to 6, i mean when there are 6 or more available. The intention is to have a switch that can activate the failsafe mode, you cannot have that when there is none available (obvious i think). Another thing is that the failsafe using altitude is not tested. You can fix it at 0 to keep it deactivated. I really think it should work unless the altitude measurement is not accurate enough.

**Comment by ProDrone** [comment]
@hydra this weekend i flighttested the modified failsafe. It worked exactly as intended. Yesterday i lost orientation and actually needed it. I just could pickup the quad, removed dust and was ready for the next take off. I cannot test the altitude feature and hope someone else (with a good working barometer) can do that.

**Comment by ProDrone** [comment]
@hydra today i thoroughly bench tested the code again. It is now ready to merge.

**Comment by hydra** [comment]
Great!

**Comment by ethomas997** [comment]
I'd say it looks good, but one thing I'm wondering is why add the 'failsafe_abortable' setting?  Seems like operators could get into trouble if they set "failsafe_abortable=0" and have any small radio glitch always result in the full failsafe auto-landing.

--ET

**Comment by ProDrone** [comment]
@ethomas997 I added that so the operator has a choice. I imagined an intermittent failure preventing a failsafe landing to complete. For instance flying FPV behind obstacles, resulting in a situation where the operator is 50% of the time in control, leading to a crash (probably). Default value is set to 1. If no one think it is useful it can be removed. Small glitches are already suppressed because the interruption must have a minimum duration of `failsafe_delay`

**Comment by ethomas997** [comment]
How about, instead of 'failsafe_abortable', we implement a failsafe-recovery delay ('failsafe_rec_delay'), defined as the wait time after a stable radio signal is recovered before the failsafe action is aborted (and TX control is back).  A large 'failsafe_rec_delay' value (anything larger than 'failsafe_off_delay') would operate the same as "failsafe_abortable=0".  A value like 50 (0.5 seconds) would be a good guard against intermittent radio signals messing up a failsafe auto-landing (this could be the default value).

@ProDrone, etc, what do you think?  If you don't have time to implement this I can work on it.

--ET

**Comment by ProDrone** [comment]
There is already a fixed recovery time (of 0.65 seconds = 33 correct packets) in the code, so recovery is not at the first correct packet. If the general consensus is that `failsafe_abortable` should be removed from the code, then it will be removed (i don't use it myself...).

**Comment by hydra** [comment]
@ProDrone you're going to hate me. 

So, in recent testing I noticed a bug with failsafe and SBus RX and another issue where the LED strip indicators wouldl flash when a SBus RX was indicating failsafe state (due to the RX sending out a low value for each channel), this led me to look further at the existing failsafe code and I noticed a few other things too.

Anyway, I've refactored the existing failsafe code in the hope that it is simpler to make changes too, some of the changes are quite similar to your changes too it seems.

I think, once my new code is merged, we should look at the features offered by this PR and add them to the refactored failsafe system.  e.g. checking throttle positions, making it interruptable or not, etc.

Anyway, here's the new code, not merged yet, not fully tested either.

https://github.com/cleanflight/cleanflight/commits/rework-failsafe

**Comment by hydra** [comment]
I should not there is much cleanup to do still.

**Comment by ProDrone** [comment]
If you really want me to hate you, you have to try harder... ;-)
Today i spend most of my time on testing and changing code. I have a limited set of hardware, so no sbus receiver and only naze32 FC's. Any other testing and input is very welcome. I am (was?) happy with what i accomplished today. The most annoying is that i need to rebase my code again and again to get in sync. with master.

**Comment by hydra** [comment]
ok, so i did a couple more commits to the branch i created and created a PR for it which we can comment on.

See #781

**Comment by ProDrone** [comment]
@hydra Did you take a look at or maybe even tried the code in my pull request at the current state? I am just afraid you will encounter all problems i already solved in there. Would be a wast of time.
Apart from me not being able to use other hardware, i did a lot of testing. Detection of a failsafe condition may be hardware dependent, but handling should be separate and hardware independent in my vision.

**Comment by ProDrone** [comment]
Closed and replaced by new request #852

**Pull request closed without merging**
