### PR TITLE
Fixes Issue1751 - decreases ROM size of CJMCU target by about 1500 bytes

### PR DESCRIPTION
**Pull request by martinbudden**
Further use of build #defines, in particular USE_QUAD_MIXER_ONLY, BARO, TELEMETRY and BEEPER to reduce the ROM size of the CJMCU. This will give more headroom for future changes.

Fixes issue https://github.com/cleanflight/cleanflight/issues/1751

### CODE REVIEW

**Comment by hydra** [comment]
Ahh good work, and well done for addressing the MSP motor commands too.

**Comment by martinbudden** [comment]
Well, not good enough work - I should have built all variants before making the PR. Anyway fixed now.

**Comment by martinbudden** [comment]
BTW, I have some test code pull requests outstanding. I guess you've been pretty busy with the new board and also the betaflight stuff, but any chance of getting those in soon?

**Comment by martinbudden** [comment]
One other thing. I've been working on an agressively reduced ROM variant and (mainly by getting rid of CLI and MSP) have managed a sub 32K ROM. Not flight tested yet though.

Is this something you are interested in?

Some people have been hacking some of the toy quads. Most of these have 16K ROMs, but a few have 32K ROM. So a sub-32K Cleanflight build could be the basis for someone to put Cleanflight on a toy quad. I find this an interesting prospect. (Most of the current hacks seem to be based on outdated flight software, it would be good to enable someone to put a current version of Cleanflight on a toy quad.)

**Comment by hydra** [comment]
@martinbudden hi.  yes. removal of CLI is on the roadmap.  What do you use instead of MSP to configure it?

**Pull request merged**
