### PR TITLE
Moved gyro params out of imuConfig_t into gyroConfig_t

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by ledvinap** [comment]
IMO `gyro_sync` and `looptime` belong to IMU, not gyro ...

**Comment by martinbudden** [comment]
The only place `looptime` is used is in 
```
    gyroSetSampleRate(imuConfig()->looptime, gyroConfig()->gyro_lpf, imuConfig()->gyroSync, imuConfig()->gyroSyncDenominator);   // Set gyro sampling rate divider before initialization
```
in `fc/boot.c`

The main looptime variable is now `targetLooptime` which is owned by `drivers/gyro_sync.c`

In other words, it is all a bit of a confused mess.

My view is that `gyro_sync` should go - gyro sync should just be alway used, there is no advantage to not using gyro sync. `looptime` is superfluous and should also go.

Then we have the question of the ownership of `targetLooptime`.  My view is that it should be part of the `gyro_t` structure, but I'm willing to be conviced otherwise.

**Comment by hydra** [comment]
gyro drivers likely shouldn't care about such things as 'loops' right?

perhaps the single responsibility principle can be used to figure it out?  i.e. one source of/reason for change.

in my mind the IMU code is what cares about loop times and we change loop time related code when we change how the IMU works.

**Comment by hydra** [comment]
another way of thinking about it is, if you wanted to take the gyro reading code and did not use it in an IMU then would you need 'looptime'?

**Comment by martinbudden** [comment]
@hydra to answer your points

> gyro drivers likely shouldn't care about such things as 'loops' right?

Well, actually its the IMU that shouldn't care about things such as loops. And indeed it doesn't - `looptime` is not used by the IMU.

And while gyro drivers shouldn't care about loops, the gyro driver does care about how often the gyro is read, that is the gyro driver should care about `gyroReadInterval` - which is a property of the gyro and how it is set up (in particular what hardware filtering set).

> another way of thinking about it is, if you wanted to take the gyro reading code and did not use it in an IMU then would you need 'looptime'?

No. But you would need something like `gyroReadInterval`.

As I said above, the whole concept of `looptime` is flawed and is a hangover from MultiWii/Baseflight. By moving `looptime` into the gyro config we localise the problem to the gyro code and the code can then rationalised entirely within the gyro code.

This change is a step towards rationalising the code, not the end point.

**Comment by hydra** [comment]
ok, I'm convinced.  What's next in ditching the old looptime stuff then?

**Comment by hydra** [comment]
perhaps the `gyroReadInterval` change you mention should also be done as part of this?

**Comment by martinbudden** [comment]
I'll need to think a bit more about what the final cleanup should look like. So I think this should be merged as is.

**Comment by borisbstyle** [comment]
Why not cleaning up mw.c first?

**Comment by martinbudden** [comment]
Yes, `mw.c` needs cleanup as well. But one step at a time...

**Comment by borisbstyle** [comment]
IMO thats the messiest file.

**Comment by martinbudden** [comment]
No, `pwm_mapping.c` is the messiest file. But @blckmn is going to fix that soon.

**Comment by martinbudden** [comment]
@hydra , note this can be merged. The only check to fail is the NAZE build and that is for space reasons, which I understand will be fixed elsewhere.

**Comment by hydra** [comment]
See #2416

**Comment by hydra** [comment]
This PR is out of date now due to #2416.  Can you push new commits to this PR or do you want to make a new one?

**Comment by martinbudden** [comment]
Rebased.

**Comment by hydra** [comment]
@martinbudden thanks for speedy turnaround. merging.

**Pull request merged**
