### PR TITLE
Configurable armed led colors #2047

### PR DESCRIPTION
**Pull request by gaelj**
Armed status lights up LEDs using the user-defined color parameter instead of static blue

### CODE REVIEW

**Comment by gaelj** [comment]
Only the last commit is related to #2047

**Comment by Arakon** [comment]
Doesn't work, won't compile.
./src/main/io/ledstrip.c: In function 'applyLedModeLayer':
./src/main/io/ledstrip.c:619:47: error: called object 'colors' is not a function
 or function pointer
                     setLedHsv(ledIndex, colors(ledConfig->color));
                                               ^
./src/main/io/ledstrip.c:230:13: note: declared here
 hsvColor_t *colors;
             ^
Makefile:902: recipe for target 'obj/main/SPRACINGF3/io/ledstrip.o' failed
make: *** [obj/main/SPRACINGF3/io/ledstrip.o] Error 1

**Comment by Arakon** [comment]
And here's why. It should be:
setLedHsv(ledIndex, &colors[ledConfig->color]);

**Comment by gaelj** [comment]
Hi, thanks for taking interest.
I'm afraid applying your suggestion doens't compile on my side !
My CR passed the Travis-build so I would tend to think the problem lies on your end.
Anyways I am implementing a new CLI command to customize all "static" colors.

**Comment by Arakon** [comment]
That's strange, because the way I put it is the same way it's used in several other places. After the change it compiles and works fine for me.

**Comment by gaelj** [comment]
Are you sure you can compile cleanflight/master ?

**Comment by Arakon** [comment]
I actually used betaflight, but the file is the same for both. I just made the exact same change to a current cleanflight git, though, with exactly the same result.. fails with setLedHsv(ledIndex, colors(ledConfig->color));, compiles and works with setLedHsv(ledIndex, &colors[ledConfig->color]);.

**Pull request closed without merging**
