### PR TITLE
Yaw_fix default values

### PR DESCRIPTION
**Pull request by borisbstyle**
Pull request #802 has by default disabled yaw jump. That is fine on the
most of the configurations, but one of my multirotors had an angled
motor due to crash and this was causing weird behaviour.
It is also possible to configure very low values, which can even cause a
craft to not be able to stop after yaw and I am talking about the extremaly low values
below 100 like 1,2 etc.

Anyway this fix provides only valid configurable values what can't cause
any danger. Also default parameter is not unlimited anymore and is
configured to 200, which is a safe value to anybody who does the
upgrade.
cli.md is also edited

### CODE REVIEW

**Comment by MJ666** [comment]
This PR will not allow to disable the yaw jump prevention completely anymore. I'm not sure how many copters will be really affected by this problem? All my small copters fly without this since a while without negative impact.

There are many settings you can modify and set to values wich make CF unflyable or at least have negative impact if not used well.

Proper documentation of the parameters will be key. This  was my intention after being back home an may get an better understanding why this limits are introduced initialy.

**Comment by borisbstyle** [comment]
@MJ666 Noobs can set the values to very low value and they will get worse problems.

I personally think that disabling is totally unnecessary as 500 has pretty much the same effect.

Regarding the issue I mention. Try to losen up one screw of one of the motors on a quadcopter so it gets a bit angle and especially on assymetric designs. It will fly well, but hard yaw stops will get it in uncontrollable jumps. This is of course really rare problem, but it happened to me on one of my prototypes :D. 

If you really want to disable it all I should perhaps modify the code that 500 means disabled? In this way the very low value can't be chosen. What do you think?

**Comment by borisbstyle** [comment]
This could be the modification:

if (motorCount >= 4 &&  mixerConfig->yaw_jump_prevention_limit != 500) {
        // prevent "yaw jump" during yaw correction (500 is no limit)
        axisPID[YAW] = constrain(axisPID[YAW], -mixerConfig->yaw_jump_prevention_limit - ABS(rcCommand[YAW]), mixerConfig->yaw_jump_prevention_limit + ABS(rcCommand[YAW]));
    }

**Comment by MJ666** [comment]
Make sense. Good idea.

**Comment by hydra** [comment]
@borisbstyle @MJ666 thanks guys, merged.

**Pull request merged**
