### PR TITLE
Apply the same maximum control rates (1.0) in CLI and MSP

### PR DESCRIPTION
**Pull request by thenickdude**
Previously it was possible to set roll/pitch rate > 1.0 using MSP, but not using the CLI. Roll/pitch rate > 1.0 is meaningless.

### CODE REVIEW

**Comment by tricopterY** [comment]
The pid_tuning.html for class="rate-tpa", currently has max="2.55" for roll/pitch and yaw. These should be limited to max="1.0".

**Comment by thenickdude** [comment]
I figure that the Configurator is not the only consumer of the MSP API so it would be better to cover our bases. I've added the limit to TPA as well now.

**Comment by hydra** [comment]
I was under the assumption that some people use > 1 rates.  Can you ask/check on the rcgroups thread?

**Comment by tricopterY** [comment]
If you examine annexCode() in mw.c L#170, you do not expect to end up with -ve values for prop2, when you are calculating with a datum of 100 i.e rates are meant to be between 0 and 100%, which translates to limits of 0 to 1.0.
Note casting to (uint16_t) at L#204
 prop1 = (uint16_t)prop1 * prop2 / 100; 
We can end up with two's complement if prop2 is -ve, i.e something large.

**Comment by thenickdude** [comment]
Roll/pitch rates >1.0 end up applying a negative factor of the PID correction (i.e. it makes the craft actively unstable), nobody would be using those.

Yaw rate >1.0 does make sense but the CLI has always limited that to max 1.0 so I doubt many are using it.

**Comment by hydra** [comment]
It was RC rate that I was thinking of, couldn't remember last night.

**Pull request merged**
