### PR TITLE
Naze32 Pinout images and doc updates

### PR DESCRIPTION
**Pull request by modem158**

### CODE REVIEW

**Comment by dkisselev** [comment]
It looks like you don't list the individual PWM channel inputs. Is that by design? I know most people use PPM anyway but it might be useful for completeness and in case anyone's having trouble with the PWM pinout. (I don't have an opinion about it either way, just pointing it out for discussion)

As Nick said in the other thread, if you need to make changes just push changes to your master branch and they will automatically appear in this PR.

You may also want to look up how to git rebase: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase it's a more advanced feature that takes some learning, but it lets you squash all of your commits into a single clean one that just has the final copy of the changes in it, as if you didn't need to go back to make small tweaks.

**Comment by modem158** [comment]
Hey guys.  Sorry about cluttering things up.  I'm starting to understand GIT but it's very different from Subversion which I use at work.  I'll read up on rebase.  

I have added the PWM pins.  Let me know if there is anything else you feel is needed.

**Comment by modem158** [comment]
I'll also upload the orginal .svg files from Inkscape once we feel that the .png files are finished.  That way the project will be able to make any changes moving forward.

**Comment by ethomas997** [comment]
Nice diagrams.  One thing, though, is the red/green LED descriptions need to be swapped:  L0 (red) is "flight mode" and L1 (green) is "armed LED".

--ET

**Comment by hydra** [comment]
@modem158 can you add the source for the .svg files to the PR please.

**Comment by hydra** [comment]
I'm gonna close this.  I think a better way to do it would be using a tool like fritzing so that they can be more easily worked on by everyone.

http://fritzing.org/home/

If you want to have a go at doing Fritzing diagrams that would be awesome!

**Pull request closed without merging**
