### PR TITLE
Virtual Current Sensor Support

### PR DESCRIPTION
**Pull request by tracernz**
This adds support for a virtual current sensor as per #346 which estimates current draw based on throttle position (and armed status). It uses the existing current_meter_offset and current_meter_scale settings along with a new setting, current_meter_type which currently has possible values of 0 = none, 1 = adc, 2 = virtual. Documentation is included in the pull request.

Another problem I ran into while testing is issue #297 which was causing problems with the ADC readings. I have corrected this issue in pwm_mapping.c. Additionally I have ammended a line in main.c which will allow PWM to use the current sensor ADC pin if current_meter_type= 0 or 2 (i.e. none or virtual).

### CODE REVIEW

**Comment by hydra** [comment]
cool thanks for this and the pwm mapping fix.

**Comment by hydra** [comment]
just had a look at the code and noted the the fix for the pwm mapping is not correct since since it will break the cc3d target.

The solution currently used to decide wether or not to skip a pin by looking at the PWMx index or the TIMER (as in the case of the existing code from @Pierre-A ) should be replaced by code the looks at the GPIO port and pin since that is what matters in the case of ADC inputs.  This should be applied to all F1 targets to start with.

Perhaps the best way to proceed here is to remove the pwm mapping changes from this PR and create a new PR to fix the ADC PWM Mapping problem and we can merge that first and then merge this, what do you think?

**Comment by hydra** [comment]
Thanks also for including documentation in the PR too.

**Comment by tracernz** [comment]
Okay, I'll split the PWM mapping patch off if I get a chance tomorrow. I now see that it will break the CC3D, a quick interim fix would be to move the if(useCurrentMeterAdc... into a separate #ifdef NAZE. Would you agree?

The virtual current sensor code doesn't depend on that bug being fixed. In fact the ADC current meter is broken on NAZE with the 0.6.0 release (and probably earlier, I haven't tested).

**Comment by ledvinap** [comment]
I am not sure about quadratic term (1/50) in current computation. Is there some background behind this value? Or is it good only for one propeller/driver combo?

**Comment by hydra** [comment]
I have fixed up the ADC / PWM mapping initialsation, so no need to do that now.  See recent commits.  All target specifi `#ifdefs` have gone from related PWM mapping and ADC initialisation code.

**Comment by hydra** [comment]
I think the pwm_mappings.c change can be removed from this PR.

Then simple update main.c change change this line:
```
pwm_params.useCurrentMeterADC = feature(FEATURE_CURRENT_METER);
```
So that it does /not/ set that value to `true` if a virtual current meter is used.

**Comment by tracernz** [comment]
@ledvinap, the quadratic term is related to the propeller drag. I have taken the 0.02 (1/50) factor from the MW OSD implementation as it is said to work rather well. I can certainly do some more rigorous testing (e.g. comparing to a real ammeter in a variety of situations) but I think deriving an accurate mathematical model would be far too much work for something which is intended only to be an estimate anyway. It will never be an accurate substitute for a real ammeter. I am reluctant to add another CLI setting to tune the quadratic term unless it's proven necessary.

@hydra, your ADC mapping fix is much nicer, great work! I will modify and test the code, and then update the pull request in the next couple of days.

**Comment by hydra** [comment]
@tracernz great, looking forward to seeing it

**Comment by fiveangle** [comment]
While the code seems almost too simple to work, I can confirm the MWOSD implementation does produce surprisingly good approximations of current usage.  With Blackbox (my Openlog just arrived today: yes) we should be able to refine the algo further once it's in the main.

-=dave

**Comment by ledvinap** [comment]
I did quick test on table, slowly increasing throttle. when I approximate m=avg(motorCommand)-1000 to current, I get I = 4.9e-05 m^2  + 1.5e-03 m + 0.3 (A), the fit seems very good.

The linear term is almost  negligible(in my case it is zero if motorCommand-984 is used) , so the equation is fine. Maybe the linear term may be dropped to avoid confusion.

I'll have some flight data soon, I'll write some update ..

**Comment by Pierre-A** [comment]
Hi guys,
coming back after 2 weeks in a no-internet area.. 
bravo for this virtual current support !  not merged yet ?

**Comment by johnlenfr** [comment]
@Pierre-A : Did I understand this new feature could be implemented in the Hott Telemetry (mAh draw)?

**Comment by Pierre-A** [comment]
sure,
mAh are there , no matter how they are estimated.

**Comment by hydra** [comment]
I have just added current_meter_type into 7bd98e557a8eac7b74d55d6da31876ea83b6c059

**Comment by hydra** [comment]
Please see #459

that needs fixing.  There is a check which will disable current meter if it detects a conflict, that code needs updated.  can you add a PR to fix this?

**Comment by tracernz** [comment]
Ah, yes. My bad, I'll take a look.

**Pull request merged**
