### PR TITLE
Updated Ubuntu gcc toolchain version date

### PR DESCRIPTION
**Pull request by wfrisby**
There is a updated gcc 4.9.3 toolchain from https://launchpad.net/~terry.guo/+archive/ubuntu/gcc-arm-embedded. The previous version is no longer hosted on Terry Guo's page.

This pull request updates the doc with the correct date/version and includes the version for Ubuntu 15.04.

### CODE REVIEW

**Comment by Echelon9** [comment]
Looks good to me.

**Comment by tracernz** [comment]
I'm curious why the official builds at https://launchpad.net/gcc-arm-embedded wouldn't work?

**Comment by wfrisby** [comment]
@tracernz Good question. From what I can see, it looks like the Terry Guo's repo is the Ubuntu PPA for https://launchpad.net/gcc-arm-embedded.

> For Ubuntu 10.04/12.04/13.04 32/64-bit user, PPA is available at https://launchpad.net/~terry.guo/+archive/gcc-arm-embedded.

**Comment by Echelon9** [comment]
The ARM-recommended Terry Guo PPA now lists the latest `4.9.3.2015q3` version of gcc-arm-embedded. This PR should be reviewed to ensure the latest version works without issues, and update accordingly.

**Pull request closed without merging**
