### PR TITLE
Add explanation of yaw controllability at low throttle (tricopters)

### PR DESCRIPTION
**Pull request by thenickdude**

### CODE REVIEW

**Comment by hydra** [comment]
Hi @thenickdude thanks for the PR.  Can you adjust the table format so it follows the markdown format used for tables elsewhere and not the html table format?

See https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by thenickdude** [comment]
No, because GitHub Flavoured Markdown doesn't support col- or row-spanning of cells.

**Comment by hydra** [comment]
Hmm OK.  Can the table be re-worked so that column/row spanning is not required.  I'm loathed to have HTML in the docs.  Also I've got no idea if the PDF generation will like the HTML.

**Comment by thenickdude** [comment]
The PDF rendering pipeline first does a conversion from Markdown to HTML, then converts the resulting HTML to PDF, so inline HTML code is fully supported:

13480348c44a23f3584dae9dbc2669de

I can convert it over to a non-span format if really necessary, but I suspect the table will be much easier to read this way.

**Comment by hydra** [comment]
ok, i will merge.

**Pull request merged**
