### PR TITLE
Added doc for building on Fedora linux

### PR DESCRIPTION
**Pull request by iforce2d**
Instructions for building on Fedora linux, also works on Ubuntu.

### CODE REVIEW

**Comment by iforce2d** [comment]
This is only a documentation change - looks like travis failed on something unrelated:
"The command "sudo apt-get update" failed"
I think if you can kick-off the travis check again it will pass without any changes.

**Comment by thenickdude** [comment]
Is that the same toolchain as https://launchpad.net/gcc-arm-embedded ? gcc-arm-embedded is the toolchain we use for official builds, so we want everybody to be on the same page as much as possible.

**Comment by iforce2d** [comment]
@thenickdude I think so, at least it produces a binary that differs only by a byte or two (the build timesta mp I guess?) to the one which travis is using. If it's preferable I could change this to use the zip that travis uses:
https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q3-update/+download/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2

**Comment by thenickdude** [comment]
Ah I guess if the compiled binaries are the same then there's no need to change it (they're probably copies of the same compiler binaries anyway).

**Comment by btimby** [comment]
This documentation was useful to me since I run Fedora. :thumbsup:

**Comment by iforce2d** [comment]
Can't the build check be overridden/ignored, or just run again?

**Comment by iforce2d** [comment]
Bump.... 11 months now... can't the build check be run again?

**Comment by martinbudden** [comment]
@iforce2d , I don't know a way of "properly" forcing the build to run again, but if you make a minor change (e.g. change some whitespace) and resubmit, then the build will run again.

**Pull request merged**
