### PR TITLE
Chapters missing from Manual.pdf when there are no \n before '#SectionName'

### PR DESCRIPTION
**Pull request by aergid**
Using build_docs.sh to generate Manual.pdf I get document with 26 pages 
and a lot of dead referencess to different chapters. This holds true when I 
use either gimli from build_docs.sh or switch to pandoc. 
Turned out that sections with #-headers not separated by a new line from previous 
text got ignored in final pdf.
E.g. after 'Getting Started.md' and 'Safety.md' joint:
  ^* [Migrating from baseflight](Migrating from baseflight.md)
  ^# Safety

Just added new line concatenation between *.md files in concat-loop.
Newly generated pdf contains 64 pages and everything seems in place.

### CODE REVIEW

**Comment by tracernz** [comment]
I think you'll find this is the actual problem: http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by ledvinap** [comment]
@tracernz : Only these files do not end with newline:
```
./development/Blackbox Internals.md
./Board - Sparky.md
```

**Comment by aergid** [comment]
You both are right. The problem is in missing lineending and correct way is to fix 'broken' .md files. 
However, we all make mistakes from time to time, and one could accidentialy forget to end with linefeed after updating files. 
I believe that this 'guardian' echo won't hurt.

**Comment by ledvinap** [comment]
@aergid : Probably combination of both - some .md files end with empty line, but that should not be necessary.
`./development/Blackbox Internals.md`, `./Board - Sparky.md` (POSIX violation) should be fixed in addition to blank line insertion.

**Comment by tracernz** [comment]
Good stuff. Github gives you a nice little warning char in the diff viewer for text files when the linefeed at the end is missing. ;-)

**Pull request merged**
