### PR TITLE
Battery.md:  clarify current_meter_scale

### LINKED ISSUE #740: Virtual Current Sensor documentation unclear
I'm trying to setup the virtual current sensor, but the docs aren't quite clear on how to do it.

```
Adjust current_meter_scale until the mAh draw reported by Cleanflight matches the charging data given by your battery charger after the flight (if the mAh draw is lower than reported by your battery charger, increase current_meter_scale, and vice-versa).
```

By the time you get home to the charger, the board's been powered off so CF's mah count it lost and you can't tweak it.

I'd like to help improve the docs to make the setup more clear, but don't know what the process should be. I'm guessing it's either linear or a multiplier, ie. if CF reports 1000mah but the reality was 1500, set the offset to 500, but don't know for sure.

If anyone's done it and has a step-by-step worked out, I'd love to hear it, otherwise I'll poke around and post my finding here (and update the doc if I get somewhere conclusive)

### PR DESCRIPTION
**Pull request by payne92**
fixes #740 

@dkisselev  Per your comments on #814 about calculating `current_meter_scale`, could you eyeball and see if this addresses your comments?

### CODE REVIEW

**Comment by payne92** [comment]
@hydra This PR should now be ready to go; incorporated user feedback discussed in issue #740 (which this fixes).  Please let me know if you need anything else here.

**Comment by hydra** [comment]
This PR cannot be merged as is, please update your PR branch so that there is just a single commit that updates the documentation.

**Comment by payne92** [comment]
Ok, a single commit -- let me know if you need more.

**Comment by dkisselev** [comment]
@payne92 Could you also please change the commit message to reflect the change? Something like "Clarify virtual current sensor documentation"

**Comment by payne92** [comment]
Sorry for the noise on this (A bit of git thrashing on my end) -- it should be good now.

**Comment by hydra** [comment]
thanks for the pr/commit cleanup, merging.

**Pull request merged**
