### PR TITLE
Update LedStrip documentation from issue tracker 555

### PR DESCRIPTION
**Pull request by joefarmer**
I've added the default LED colors to the documentation for indication and orientation modes.

### CODE REVIEW

**Comment by hydra** [comment]
can you remove the 'COLOR' and all '_' characters from the LED Color column, then i will merge.

**Comment by joefarmer** [comment]
I need help with github. I didn't mean to get the Custom Mixer docs included in this pull request. How do I put them back in a separate branch after I've already committed them to my master branch?

**Comment by joefarmer** [comment]
Okay, I fixed my master history to remove the extra commits and it should be ready to merge.

**Comment by hydra** [comment]
Thanks

**Pull request merged**
