### PR TITLE
Added generic MSP commands to access development variables

### PR DESCRIPTION
**Pull request by ProDrone**
I would like to have these additional MSP commands to aid in development.
The benefit is that you don't need to bump up the API version to write and test firmware and client side modifications. It also does not interfere with existing structure and operations. What do you think?

### CODE REVIEW

**Comment by digitalentity** [comment]
This can replace CLI altogether (#922). Make `variableIndex` a uint32_t and we can have up to 4 billion parameters, accesible via MSP_GET_VAR_VALUE/ MSP_SET_VAR_VALUE. We can also add an MSP command to get a list of all supported variables, their names and indexes. This way CLI will be replaced by a simple, yet powerfull, way to access all configuration data.
Similar approach is done in APM via MAVLink parameter protocol (http://qgroundcontrol.org/mavlink/parameter_protocol)

**Comment by ProDrone** [comment]
Thank. Yes. But 4 billion variable name texts would not fit in those tiny flash devices :D Only humans need to see names for these variables, so it is logic to just use indexes and make the client know the names for them. I also would like to extend this, so that a full backup/restore can be done using the cleanflight-configurator. That is what i think we all like to have. Related to this issue are #347 and #963

**Comment by digitalentity** [comment]
I was thinking if we remove a variable or add a new one we **do not reuse** the index to avoid mis-interpretation. 4 billion IDs should be more than enough for this. I was also thinking that a client may be a very generic client, unaware of indexes and names, and providing a way this generic client can receive a complete list of parameters is probably a good idea. What do you think?

**Comment by ProDrone** [comment]
Yes that is the intention with not reusing indexes. If i get you well, you mean a generic client that can retrieve a list and knows the total number of variables, their valid range and default setting and should refer to them by (index) number. So access is anonymous?

**Comment by digitalentity** [comment]
Yes, I mean that the client should be able to figure out what parameters
are available, their type, valid range and name for showing in gui. This
way we will be able to add features to FC without modifying the client
(pretty much what we have with cli, but more generic and effective)

**Comment by ProDrone** [comment]
These variables get meaning by how and where they are used, the name ultimately communicates that for human understanding. These names represent a lot of data and can/should not be stored in FLASH. We should not need to modify the client itself, but the variable-name-link-information (database like thing). So we need a way to make the client link those names to the variables.

**Comment by hydra** [comment]
Not wanting to add anything to MSP right now.  Configuration storage needs to be reworked and then we can come back to this.

**Comment by hydra** [comment]
See stuff like this:

https://github.com/ChrisNisbet01/nizfc/blob/master/src/flightcontroller/config_structure.h

**Comment by nzmichaelh** [comment]
FYI, I'm hacking on a solution to this in #1049

**Comment by hydra** [comment]
don't think we need this right now.  #1049 is in progress.

**Pull request closed without merging**
