### PR TITLE
Added pid delta from error calculation

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by ledvinap** [comment]
This will break old config - variable was added in middle of config structure and id/version is the same.

Correct way to do this change is to add the variable last into parameter group and define it so that `0` is default value.

Also merging changes into master (and with Travis failing) without warning is bad idea ...

**Comment by martinbudden** [comment]
@ledvinap , you are correct - I should not have merged this without discussion. My apologies.

The reason the travis build failed was not because of build or test errors, but rather some internal problem. This seems to happen occasionally. Error message was:
```
The command "eval git fetch origin +refs/pull/2307/merge:" failed 3 times.
The command "git fetch origin +refs/pull/2307/merge:" failed and exited with 128 during .
```

**Comment by ledvinap** [comment]
This Travis error is caused by missing PR branch - martinbudden:pid_delta_from_error was deleted after merging.
When build fails for same temporary reason, is is possible to restart it on Travis status page ..

**Comment by ledvinap** [comment]
There is still problem with breaking old pidProfile - `deltaMethod` probably ended up in place where padding was before, someone should check that.
And even then pidProfile will silently switch to  PID_DELTA_FROM_ERROR on upgrade...

**Pull request merged**
