### PR TITLE
Consolidated separate checking of dterm_cut_hz

### PR DESCRIPTION
**Pull request by martinbudden**
Fixes issue https://github.com/cleanflight/cleanflight/issues/1862.

Also fixes double-negative anti-pattern in checking of `ANGLE_MODE`.

ie anti-pattern
```
if (!condition)
    doWhenFalse;
else
   doWhenTrue;
```
replaced by
```
if (condition)
    doWhenTrue;
else
   doWhenFalse;
```

### CODE REVIEW

**Comment by ledvinap** [comment]
Noww it would make sense to replace `deltaSum = delta1[axis] + delta2[axis] + delta;` with `deltaSum = applyAveraging3filter(delta, averagingFilterState);` (or make window length configurable)

**Comment by martinbudden** [comment]
I had a look, and there doesn't appear to be a `applyMean3filter`. There's a `quickMedianFilter3` and also a `filterApplyPt1` and a `applyBiQuadFilter`.

**Comment by ledvinap** [comment]
Yes, one will need to be created. Or implement FIR filter and use coefficients of {1/3 1/3 1/3}. I'll look into it.

The idea is to use filter code explicitly where filter is used, not hiding it.

**Comment by borisbstyle** [comment]
That part certainly requires a cleanup.

@ledvinap 
I agree about making a general averaging function with flexible configuration. I would prefer dynamic memory allocation for averaging samples for states, but CF doesn't use that coding style.

Why do you suggest 1/3 1/3 1/3 FIR?

**Comment by ledvinap** [comment]
IMO dynamic allocation will cause more problems than it will fix. RAM is not limited resource (yet),  static allocation is simple, easy to debug and robust. Even allocating buffer large enough for all filter types / using union for filter state is reasonable solution.

FIR with {1/3 1/3 1/3} is equivalent to 3point average - current code. It is a bit more expensive (3x multiplication) but also more generic.

BTW: moving average/mean is quite poor filter..

**Comment by borisbstyle** [comment]
@ledvinap 
I agree that averaging is not the best filter, but it helps getting rid of spiking. Somehow I reach the best results with averaging than with filtering. I mean the flight characteristics....even though i can get super clean traces it doesnt mean it improves the flight behaviour.
I will soon do some more flight testing with my "test" group to dig more into it.

I suspect that the phase between P and D is quite important somehow. But I also do suspect that good filtering can generate some lower frequencies out of higher frequencies what again requires higher filtering values and that again increases phase shift..

**Comment by borisbstyle** [comment]
What I meant with phase shifting mainly is cluttering of some frequencies. Near cutoff frequency there are some frequencies being cluttered together what can generate different frequencies again.
That is mostly shown in prop wash scenarios.

**Comment by ledvinap** [comment]
@borisbstyle : 3point mean filter has notch at 0.67*Fs. Maybe it helps .. 

To get 'super clean traces' you need longer filter and introduce considerable delay. D term may be sensitive to delay ...

As long as filtering is linear, no new frequencies should be created. Only attenuated or amplified. 
Frequency spectrum will wrap (and possibly overlap) when you downsample data.

**Comment by borisbstyle** [comment]
The moving average filters are definately not bad for smoothing out noise. There are not a good lowpass filters.

http://www.analog.com/media/en/technical-documentation/dsp-book/dsp_book_Ch15.pdf

**Comment by borisbstyle** [comment]
I will def also def play with double pass moving average

**Comment by hydra** [comment]
I'm going to merge these changes that remove the not operator. I mentioned this is preferred to @borisbstyle via chats before so nice to see another develeloper thinks the same as me on this.

**Comment by martinbudden** [comment]
@hydra , double negatives are not unknown to have uses in written and spoken English. But they have no place in code.

**Pull request merged**
