### PR TITLE
Update Board - Naze32.md

### PR DESCRIPTION
**Pull request by modem158**
Added Wiring diagram to show UART locations.

### CODE REVIEW

**Comment by dkisselev** [comment]
I think you may have forgotten to commit the image to the repository

**Comment by modem158** [comment]
It's in a different pull request #798

**Comment by thenickdude** [comment]
Is this PR obsolete, then? Please close it.

**Comment by modem158** [comment]
I did a pull request for the image and a pull request for the update to the document page to include the image.  I will close both of them as hydra wanted me to make a few more modifications to the pinout drawing. I'm still getting used to GIT so I thing both requests may be included in the other.....

**Comment by thenickdude** [comment]
You can just add commits to an existing PR instead of making a new one (just add commits to the branch you used for your original PR, they'll be added to the PR automatically).

**Pull request closed without merging**
