### PR TITLE
Fix CJMCU pin mapping.

### LINKED ISSUE #2796: Firmware 2.0.2 not worked on CJMCU
Hi. please fix firmware 2.0.2 on CJMCU. when uploading firmware motors run selfi

### PR DESCRIPTION
**Pull request by Smeat**
This should fix #2796.
The problem occurred because motor 3 and 4 were mapped to PB6 and PB7, which are used for I2C.

I am no expert on this and don't know if I broke anything else with this.
For now I just restored the functionality from 1.14.2 with PA8 as CH5/AUX1.

### CODE REVIEW

**Comment by mikeller** [comment]
Well spotted, @Smeat. But this will change the assignments of PWM inputs and motors to pins. I am not sure that this is what users of this board would want?

As an alternative, how about disabling I2C? (disclaimer: I don't know much about this target.)

**Comment by Smeat** [comment]
This board acts as a frame, so the motor outputs are more or less fixed.
As for inputs: Since 1.14.2 seems to be the last working release for this target, my intention was to restore the assignments used there. But I am not opposed to change this if there is any valid reason.

Disabling I2C would be rather bad because the gyro and acc use I2C.

**Comment by mikeller** [comment]
Fair enough. So you've tested your change, and all input / output mappings are correct?

**Comment by AleksandrNull** [comment]
That's correct commit. At least I've tested it from point of view of setting PB0,PB1,PB8 and PB9 s motor output but didn't touched I2C pins PB6 and PB7. I just changed their role to TIM_USE_PWM but with INPUT(0) state. So this fix looks good to me. From what I see it probably also requires reassignment of motors still.

**Comment by AleksandrNull** [comment]
Anyway, I've tested it and it at least not flying away 5 seconds after booting up and testing of motors and all i2c devs is fine.

**Comment by Smeat** [comment]
I made a little mistake with the motor assignments. But now it should map to the default "Quad X".
However I had to remove PA6 and PA7 to make motor 1 and 3 work properly. Those are used for the onboard nrf24l01-IC, so I think it shouldn't matter to remove that timer, but I am not entirely sure.

So far I was able to test it with a 5 channel "PWM RX input" and it flew just fine.

**Comment by mikeller** [comment]
Mergeing this since it makes the target work. Any testing and feedback for further improvements appreciated.

**Comment by AleksandrNull** [comment]
Last one works perfectly but I have one question to Kevin: you're talking about nrf24l01 onboard. Are you talking about CJMCU ? There is no such chip on board by default. Or you talking about soldered nrf24l01 module ?

**Comment by Smeat** [comment]
@AleksandrNull yes you are right, I worded that poorly. I meant a module connected to the exposed pins.

**Pull request merged**
