### PR TITLE
Delay no data detection for serial rx when no signal received

### PR DESCRIPTION
**Pull request by fnurgel**
detectAndApplySignalLossBehaviour() currently assumes rxData is always present when the rx is connected properly (rxDataReceived == true). This does not seem to be the case atleast when failsafe kicks in on a SBUS receiver.
rxSignalReceived is reset based on time and rxDataReceived is reset every frame, which seems to create the difference.
When the rx flags failsafe, rxDataReceived is sometimes not flagged true when entering detectAndApplySignalLossBehaviour() resulting in a 'flickering' between the rx values and PPM_RCVR_TIMEOUT (in turn resulting in invalid pulse).
On current master this is not too big of an issue, but it is there:
cf_master-150923

However, when tinkering with the loops, like in borisbstyle/betaflight, the issue is much more visible:
cf_betaflight-150923
(the actual failsafe values are abnormal for the sake of simply displaying the issue)

The failsafe and signalLoss code seems a bit complex as it is and this certainly does not help the cause.
Also this might simply be the result of some other timing problem and thus this workaround might in that case just hide the actual problem.
The attached commit is requiring 50 frames with no data before it treats it as actual no data.

### CODE REVIEW

**Comment by henn1001** [comment]
@ProDrone should have more insight into this.

**Comment by ProDrone** [comment]
Does the problem disappear when setting the looptime higher (like 2000, 3000)?

Unfortunately I do not have an SBUS receiver to reproduce this. 50 frames delay results probably in a long detection time when a _real_ rx failsafe occurs.

Can you please (using latest master code) experiment with the required amount of frames for different looptimes, to see when it disappears? And possibly what the rate of errors is.

I tried to reproduce this with SUMD serial RX, all sensors except gyro disabled and looptime = 0, but that did not fail:
screenhunter_59

**Comment by fnurgel** [comment]
I tried different looptimes and the dips showed up on all I tried from 0 up to 3500

**Comment by hydra** [comment]
The PR, as i stands, does not seem like the right solution to the problem at all.

See also #1266.

**Comment by fnurgel** [comment]
Heh, I mistakenly put the frame counter inside the channel loop, so the delay is more like 3 frames (50/16).

**Comment by fnurgel** [comment]
Checked with master as of today and two different receivers (both connected with sbus):
Futaba R2008SB
Out of 25000 frames, 50 flagged rxDataReceived = false
Only one frame at a time missed the flag, so when I set delay frames to 3 it was fine.

FrSky TFR4
Out of 25000 frames, none missed

Switched to betaflight branch to check if FrSky TFR4 was unaffected now, but it got it as well on that branch:
FrSky TFR4
27000 frames, 986 flag false

R2008SB
27000 frames, 2420 flag false

So it also looks like it's receiver dependent.

**Comment by fnurgel** [comment]
Futaba R7008SB
10000 frames, 693 flag false
with this receiver up to 5 frames had the flag false in a row, so the delay had to be increased

**Comment by ProDrone** [comment]
@fnurgel I see no debug[n] counters in your branch. Where exactly do you log these? I would like to reproduce the errors you see, using the same test method.

**Comment by fnurgel** [comment]
@ProDrone pushed enabled debugging to my branch now

**Comment by ProDrone** [comment]
@fnurgel Can you please try my branch `improved_rx_failsafe_detection` to see if that solves this issue and also #1342 ?

**Comment by borisbstyle** [comment]
Interresting

@fnurgel 
My branch uses identical rx code as the master. I do get many complaints there from SBUS users and thus might be the reason.

**Comment by borisbstyle** [comment]
I was also analysing why my SBUS failsafe didn''t work and found this part of code below. Why should we assume that there is valid RX data when my X4RSB is turned off in this scenario? It assumes my rx failsafe is active while its not.
https://github.com/cleanflight/cleanflight/blob/master/src/main/rx/sbus.c#L230-L231

**Comment by fnurgel** [comment]
@borisbstyle the Rx has to send a) a valid data frame and b) failsafe flag = 1 to get to that code. If your Rx is not powered that should not be the case?

**Comment by borisbstyle** [comment]
My rx is powered and sends a short 1 and than a 3

**Comment by fnurgel** [comment]
Sorry misunderstood your "X4RSB is turned off" then.
So is it sending a data frame with the failsafe flag = 1 but no actual channel data?

**Comment by borisbstyle** [comment]
@fnurgel 
I will have to look what my receiver is doing again to understand that part better. Kind of new in SBUS protocol.

**Comment by fnurgel** [comment]
@ProDrone 's branch has disabled the Rx data altogether during failsafe. This ofcourse gets rid of the 'flickering'.
If the failsafe feature is enabled and entering failsafe in the Rx, the throttle channel goes down to 885 for a split second then it goes up to 1000 (rxfail 3 a  I presume), red light goes on.
If I uncheck failsafe feature, throttle goes down to 885 and stays there, no beeps or lights.

It makes more sense now when the failsafe feature is active, but not when it's inactive.
If disabled, I'd expect it to use my Rx values, otherwise I see no point in being able to disable it?

**Comment by borisbstyle** [comment]
@fnurgel 
So this PR should indeed prevent those dropouts. Perhaps something for me to merge to give to some people to test who experienced these drops.

**Comment by fnurgel** [comment]
@borisbstyle 
@ProDrone 's branch improved_rx_failsafe_detection has stable failsafe behaviour on both master and combined with your branch (from sept 29) and acts like I commented above.
As far as dropouts go during normal operation that is probably a different issue.

**Comment by borisbstyle** [comment]
@fnurgel 
I think those dropouts during normal operations are hardware related probably.

But real failsafe drops are immediatelly giving these throttle glitches, which should not be the case I
guess?

**Comment by ProDrone** [comment]
@fnurgel The thought behind it is like this:

__Step 1 -  RX needs to communicate the failsafe state to the FC:__

* For PPM & PWM RX's this must be done by setting the failsafe values in the RX for at least one of the stick control channels. These must be out of normal operating range (as defined by `rx_min_usec` and `rx_max_usec`) to clearly indicate a failsafe state.
* For serial RX's that have a failsafe flag there is no need for setting specific failsafe values.

__Step 2 - On RX failure substitute out of range values with `rxfail` values:__

* AUX channels are substituted with `rxfail` value (per channel) when they are out of range.
* If one of the stick control channels is out of range, ALL channels are substituted with `rxfail` values.

__Step 3 - On persistent failure start a failsafe handling procedure:__

* persistent failure means longer then 200usec (internal delay) + `failsafe_delay` (default at 1 sec). **
* recovery takes approx. 200usec. **
* Auto-landing in current application.
* RTH is work in progress by @digitalentity.

** Detection takes time, which is painful. When flying at 20 m/s (72 km/h) only recovery means 4 meters! 

===

> If the failsafe feature is enabled and entering failsafe in the Rx, the throttle channel goes down to 885 for a split second then it goes up to 1000 (rxfail 3 a I presume), red light goes on.
If I uncheck failsafe feature, throttle goes down to 885 and stays there, no beeps or lights.

885 is caused by `rxfail a.` The automatic control sets throttle value to `rx_min_usec` (step 2 above).
1000 is default failsafe throttle setting applied by the failsafe handler procedure (step 3 above).
The red light is because level mode is activated by failsafe auto-landing.

> It makes more sense now when the failsafe feature is active, but not when it's inactive.
If disabled, I'd expect it to use my Rx values, otherwise I see no point in being able to disable it?

The intention is that in case of a failsafe event the `rxfail` values are used instead of the settings from your RX.
An airplane without a FC is directly controlled by the RX, so it makes sense to use RX failsafe values there. For multirotors the FC is in control and has taken the place of the RX.

You are right that, unless you just want to use the `rxfail` settings, there is not much use in disabling the failsafe feature.

> As far as dropouts go during normal operation that is probably a different issue.

I have not yet seen any drop outs on normal operation. Any idea of how to reproduce these to investigate?

===

@borisbstyle Would be a good thing if you merge this in betaflight. It needs field testing before making it a pull request. I hope it will solve the issue and i'm looking forward to some feedback.

If you don't like the fast reaction to glitches of `rxfail a` on throttle, you can set throttle channel to `rxfail h`, but be sure to combine that with failsafe active to prevent race-away events...

I intend to change this behaviour in the future, but first like to see it works well as it is.

**Comment by fnurgel** [comment]
> You are right that, unless you just want to use the rxfail settings, there is not much use in disabling the failsafe feature.

Thanks for the explanation @ProDrone , rxfail is actually what I want in the end.

I see where my confusion has been, the `FAILSAFE` feature toggle is (in my traditional RC-mind) in fact something more like: Simple FC Failsafe (off) vs Procedural FC Failsafe (on).

Your change makes this PR obsolete and solves #1342

**Comment by ProDrone** [comment]
@fnurgel Thanks for testing! I closed this PR and #1342. New PR is #1374 now.

**Pull request closed without merging**
