### PR TITLE
AlienFlightF3 V2 support(MPU6500/9250 via SPI)

### PR DESCRIPTION
**Pull request by MJ666**
Enable Gyro interrupt for all AlienFlight F3 board revisions 
AK8963 mag implementation (part of MPU9250)
Update LED driver for alternative LED set (AlienFlightF3 V2)
Add SPI port 3 for STM32F303 targets
reintroduce SPI driver timeout to avoid blockage
AlienFlight/AlienWii documentation update
Rename AlienWii to AlienFlight

### CODE REVIEW

**Comment by MJ666** [comment]
Rebased to latest master.

**Comment by MJ666** [comment]
Finally also renamed AlienWii to AlienFlight.

**Comment by MJ666** [comment]
@hydra what is the status for getting this PR merged? There are also improvements for the existing AlienFlight controllers like the support of the Gyro interrupt. I have continuously rebased this to the actual master. The same code is in BetaFlight already for a while and is working well.

**Comment by MJ666** [comment]
The community is building more F3 controllers. This PR also contain some improvement for the V1 controllers.

http://community.micro-motor-warehouse.com/t/open-source-alienflight-fc/178/872

The F3 V2 revision is shortly before the official launch.

http://alienflight.com/

@hydra Is there anything to work on this PR before it can be merged?

**Comment by MJ666** [comment]
Rebase code again. For me this is good to go.

**Comment by martinbudden** [comment]
@MJ666 , I hadn't seen this PR. A couple of comments:

In `config.c`, could you change
```
rxConfig()->serialrx_provider = 1;
```
to
```
rxConfig()->serialrx_provider = SERIALRX_SPEKTRUM2048;
```
and
```
pidProfile()->pidController = 2;
```
to
```
pidProfile()->pidController = PID_CONTROLLER_LUX_FLOAT;
```
Sorry to be a bit pedantic.

Also you might like to merge in my PR https://github.com/cleanflight/cleanflight/pull/2038, which changes
```
customMotorMixer(0)->throttle = 1.0f;
customMotorMixer(0)->roll = -0.414178f;
customMotorMixer(0)->pitch = 1.0f;
customMotorMixer(0)->yaw = -1.0f;
```
etc, to
```
*customMotorMixer(0) = (motorMixer_t){ 1.0f, -0.414178f,  1.0f, -1.0f };    // REAR_R
```
This saves @hyrdra having to do the PR. My PR reduces the number of lines of code under the `ALIENFLIGHT` build flag, helping keep `config.c` compact. It also saves a bit of ROM space.

**Comment by MJ666** [comment]
@martinbudden I like this updates and will incooperate this when merging. 

@hydra @blckmn Updated the AK8936 driver.

**Comment by hydra** [comment]
@MJ666 yes, please add another commit as per @martinbudden 's comments above.

**Comment by MJ666** [comment]
@hydra looks to be you already merged @martinbudden's PR with most of the recommended updates. I added the reminder and rebased to latest master.

**Comment by MJ666** [comment]
Rebased and Squashed.

**Comment by MJ666** [comment]
This should be good to go. The AK8963 driver update is working on the AlienFlight F3 prototype an my development hardware. May be an final test on the SPR 3 EVO would be good also.

**Comment by MJ666** [comment]
Rebased again.

**Comment by MJ666** [comment]
Rebased and updated for latest CF changes.

**Comment by hydra** [comment]
@MJ666 ok this looks good apart from the boolean argument to `ledInit()`.

as we do for things like sonar, etc, the preferred way is to first detect hardware revision, then select a configuration, then pass the configuration to the initialisation function.

However, I will merge this now but can you please submit a new PR to address this?  We can then merge the new PR into a later release candidate.

**Comment by hydra** [comment]
@MJ666 unit test failed, fixed here. about to commit.

**Comment by MJ666** [comment]
Thanks for finally merging this. I will take a look at the LED initialization during the next days. the update IO code cold make this change even more easy. Do we have an timeline for this? Otherwise I can make an intermediate update.

**Pull request merged**
