### PR TITLE
Battery Scaling

### PR DESCRIPTION
**Pull request by bdoiron74**
- Added a time constant filter to the vbat calculation
- Roll/Pitch/Yaw PID output gets scaled down to batteryWarningVoltage to maintain constant gain.
- Throttle gets scaled up to batteryMaxVoltage to maintain constant hover throttle stick position.

### CODE REVIEW

**Comment by bdoiron74** [comment]
This is my very fist pull request. Be gentle....

**Comment by bdoiron74** [comment]
Here's what the battery filter looked like for me. You could lengthen the filter to smooth it out more, but I kept it short enough to react to momentary dips as well, without too much delay. 

image

**Comment by bdoiron74** [comment]
Can anyone explain how my additions broke the test build? For example, my updateBatteryVoltage function calls the exact same adcGetChannel as before, but somehow it's now undefined?

    ../../obj/test/libcleanflight.a(failsafe.o): In function `failsafeIsActive':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/flight/failsafe.c:93: multiple definition of `failsafeIsActive'
    /tmp/ccFCl9d3.o:/home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/unit/flight_mixer_unittest.cc:432: first defined here
    ../../obj/test/libcleanflight.a(battery.o): In function `updateBatteryVoltage':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/sensors/battery.c:65: undefined reference to `adcGetChannel'
    ../../obj/test/libcleanflight.a(battery.o): In function `batteryInit':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/sensors/battery.c:87: undefined reference to `adcGetChannel'
    ../../obj/test/libcleanflight.a(battery.o): In function `updateCurrentMeter':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/sensors/battery.c:123: undefined reference to `adcGetChannel'
    ../../obj/test/libcleanflight.a(rc_controls.o): In function `processRcStickPositions':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:155: undefined reference to `mwArm'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:163: undefined reference to `mwDisarm'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:165: undefined reference to `mwDisarm'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:179: undefined reference to `mwDisarm'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:181: undefined reference to `beeper'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:188: undefined reference to `mwDisarm'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:190: undefined reference to `beeper'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:206: undefined reference to `gyroSetCalibrationCycles'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:210: undefined reference to `GPS_reset_home_position'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:215: undefined reference to `sensors'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:216: undefined reference to `baroSetCalibrationCycles'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:219: undefined reference to `sensors'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:220: undefined reference to `heading'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:227: undefined reference to `handleInflightCalibrationStickPosition'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:239: undefined reference to `changeProfile'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:244: undefined reference to `saveConfigAndNotify'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:251: undefined reference to `mwArm'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:257: undefined reference to `mwArm'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:264: undefined reference to `accSetCalibrationCycles'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:296: undefined reference to `applyAndSaveAccelerometerTrimsDelta'
    ../../obj/test/libcleanflight.a(rc_controls.o): In function `applyStepAdjustment':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:472: undefined reference to `beeperConfirmationBeeps'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:474: undefined reference to `beeperConfirmationBeeps'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:480: undefined reference to `generatePitchRollCurve'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:486: undefined reference to `generatePitchRollCurve'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:492: undefined reference to `generateThrottleCurve'
    ../../obj/test/libcleanflight.a(rc_controls.o): In function `applySelectAdjustment':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:638: undefined reference to `getCurrentControlRateProfile'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:639: undefined reference to `changeControlRateProfile'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:647: undefined reference to `beeperConfirmationBeeps'
    ../../obj/test/libcleanflight.a(rc_controls.o): In function `processRcAdjustments':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/io/rc_controls.c:656: undefined reference to `millis'
    ../../obj/test/libcleanflight.a(rx.o): In function `rxInit':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/rx/rx.c:133: undefined reference to `rxMspInit'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/rx/rx.c:137: undefined reference to `rxPwmInit'
    ../../obj/test/libcleanflight.a(rx.o): In function `updateRx':
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/rx/rx.c:252: undefined reference to `rxMspFrameComplete'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/rx/rx.c:267: undefined reference to `isPPMDataBeingReceived'
    /home/bob/work/CleanFlight/cleanflight-bdoiron74/src/test/../main/rx/rx.c:270: undefined reference to `resetPPMDataReceivedState'
    ../../obj/test/libcleanflight.a(failsafe.o): In function `failsafeUpdateState':
    failsafe.c:(.text+0x2dd): undefined reference to `mwDisarm'
    failsafe.c:(.text+0x2f8): undefined reference to `beeper'

**Comment by borisbstyle** [comment]
It looks like something is linked wrong.

It would be much better if you integrate this feature into cli setting where you can disable and enable it. I also think that this should not be the part of mixer code, but rather part of the pid controller.

**Comment by bdoiron74** [comment]
OK. Yeah - definitely something linked wrong just because battery.h was added. 

I see the mixer's purpose as converting throttle + PID outputs into a motor voltage, but I can just make it a function to call in between pid_controller() and mixTable() in the main mw.c loop to avoid breaking the mixer.c unit test. 

I'll make the changes when I get a chance.

**Comment by thenickdude** [comment]
Hm, if battery resistance is high then battery voltage will sag during punchouts. It seems like this would generate a feedback loop where this code will correct throttle higher, which will cause higher sag, which will correct throttle higher? Would this create a "sticky throttle" feeling?

Do some ESCs maybe do this themselves already? It seems like turning a PWM value into a constant rotor speed is the job of the ESC rather than the FC. I note that in a SimonK discussion this capability is mentioned:

http://www.multiwii.com/forum/viewtopic.php?f=7&t=3450

**Comment by borisbstyle** [comment]
@thenickdude I think this is worth testing to check the theory. I discussed this a while ago with taulabs guys as well and they had the same idea.
I have many batteries and when I would tune my older batteries to the edge I will get much higher pids than on my newer ones or the ones with higher C rating.
It think it totally makes sense to add feature which could compensate it somehow, but it may not be that straight forward.
It's worth giving a try and see if it makes any sense.

**Comment by bdoiron74** [comment]
The only place the throttle should feel sticky is at when the stick saturates. As the battery sags, 100% throttle shows up earlier on the stick. Also remember this works as the throttle is reduced too - as the battery bounces back, it will re-adjust. 

I don't think rpm control in the esc would work well. The load on the motor lessens with speed through the air, so the actual RPM you get from a certain voltage changes dynamically. 

Yes, voltage compensation per ESC would be better (since the voltage seen by each ESC may be different due to wiring/PDB loss), but if done in the ESC you can't manage saturation properly. The mixer deals with this situation by reducing the average throttle on all 4 to maintain proper gyro response.

**Comment by ledvinap** [comment]
@thenickdude : IMO the 'gain' in feedback you describe will be very low (and the decay should be exponential), so it wont be noticeable.

@bdoiron74 : Decreasing thrust with speed at constant RPM may be beneficial, making TPA unnecessary..
As for saturation ... current saturation reduction will work if mixer output range is not clipped in ESC. Easy if ESC has enough headroom, but it will cost some available power. At least it is worth testing ...

**Comment by bdoiron74** [comment]
If the ESCs are doing voltage scaling, to avoid saturation issues, as you said, you have to limit their output to the voltage of a flat battery. So you lose 20% of your fresh battery performance for racing... (up to 20% of your top speed, up to 40% of your punch power)

If the ESCs are doing constant rpm control, the you have to set the max RPM available to the max rpm the flat battery/ESC/motor/prop combo can do under maximum load (static thrust) for the same saturation reasons. Very tricky to even figure out, and you'd lose a lot of available speed of a fresh battery.

Now if we had rpm feedback into the flight controller you might be able to do fancy TPA type PID gain scaling based on requested voltage and resulting rpm (Estimating the work the motor is doing). TPA as it currently stands doesn't know if you're moving through the air, so it's probably not doing the 'right' thing in all cases. I'm thinking the difference between a 100% throttle punch from a hover, versus a high speed descent, versus high speed ascent...

**Pull request closed without merging**
