### PR TITLE
Buzzer - Change buzzer pin to RC_Output_6 on CC3D

### PR DESCRIPTION
**Pull request by digitalentity**
As per #653 this is a PR for buzzer on Out6

### CODE REVIEW

**Comment by Pierre-A** [comment]
**digitalentity**, as the buzzer is no longer connected on PA15, you should add this PR the appropriate correction in doc (last CC3D section)
https://github.com/cleanflight/cleanflight/blob/master/docs/Buzzer.md

**Comment by digitalentity** [comment]
@Pierre-A, thanks for noting this. Fixed.

**Comment by Pierre-A** [comment]
y're welcome !

**Comment by Arakon** [comment]
It would be nice if this remained configurable, for people (like me) who have the buzzer soldered to PA15 and covered the wires in epoxy.

**Comment by hydra** [comment]
@Arakon I can understand that that is not an ideal situation.  Perhaps this PR should wail until #357 and #884 are done.

**Comment by Fheilmann** [comment]
Did something essential change about this? I merged the 3 commits to my local branch and the buzzer just stays mute.
(Confirmed the buzzer is working)

**Comment by Arakon** [comment]
I merge these every time I update the version and had no issues. Make sure you actually built the buzzer circuit too.

**Comment by Fheilmann** [comment]
I thought the buzzer was unnecessary when connected to Motor_out6?

**Comment by Arakon** [comment]
Nope. The outputs on the STM are only rated for 15 or 20 mA, the buzzers pull 30+.

**Pull request closed without merging**
