### PR TITLE
serial: implement a buffered writer to batch up USB data

### PR DESCRIPTION
**Pull request by nzmichaelh**
This greatly speeds up the USB VCP communications by allowing sending one 20 byte frame instead of 20 one byte frames.  It also makes the CLI much faster.

### CODE REVIEW

**Comment by hydra** [comment]
cool, i will take a look at this - will be very handy for sparky and cc3d builds.

**Comment by hydra** [comment]
Just testing this, inital thoughts is that it seems to make a big difference to the speed.

**Comment by andymac4182** [comment]
Any update on which of the three buffered VCP PR will be merged or fixed to sort it out as there are more VCP boards being released. https://github.com/cleanflight/cleanflight/pull/1143 https://github.com/cleanflight/cleanflight/pull/886

**Comment by nzmichaelh** [comment]
Hi @andymac4182.  No news sorry.  I've been waiting on feedback.

**Comment by andymac4182** [comment]
No worries. I believe @borisbstyle has done some testing on these different PRs. Hopefully we can sort it out soon :smile:

**Pull request closed without merging**
