### PR TITLE
I2C Overclock Feature

### PR DESCRIPTION
**Pull request by borisbstyle**
This speeds up IMU speed significantly.
F1 Targets like NAZE Looptime of ~900 is possible
F3 Targets like  SPRACINGF3 looptime of 370 is possible

This has been tested on many boards with success.

### CODE REVIEW

**Comment by dkisselev** [comment]
Is there any need to have a discussion about making the setting a boolean vs an adjustable value? The other thread had a few good points about being able to customize the close speed (to be able to tune in a precise value or even underclock for new/interesting hardware configurations).

Setting it to a variable with a doc suggesting that 800mhz is a known good value would achieve a similar effect as this revision.

**Comment by borisbstyle** [comment]
@dkisselev 
We want something safe what works in 100% of cases and this is it. We dont want users to cause bad behaviour

On f3 boards 1000khz lets the looptime go from 590 down to 370 with acc enabled of course
On f1 board like naze32 looptime goes down from 1200 to ~900

**Comment by hydra** [comment]
Before this can be merged a documentation update is required:

"Using this will likely void your warranty as it pushes components past manufacturers specifications which may result in shorted lifespan of your FC or total failure and may be dangerous to you, other people and property."

Or something along those lines.

**Comment by ProDrone** [comment]
@hydra Maybe we should make some kind of mode switch that varies from safe to extreme and switches a set of settings/operation modes at once. That way cleanflight in race mode would behave completely different then cleanflight in navigation mode. This setting could be part of race mode.

In racing land it is normal practice to squeeze the most out of all components, i really think nobody cares about a long life, it is only performance that counts.

**Comment by ledvinap** [comment]
Overclocking I2C is very unlikely to cause damage/shorten component life.
I2C speed is is limited mainly by noise filters and signal rise time (pullup resistor + parasitic capacitance).
SPI is specified at 1MHz (for slow registers), I2C is probably using similar logic, so I2C may be fine up to 1MHz for 6050, if rise/fall times are short enough (SCL/SDA capacitance is low enough).

**Comment by borisbstyle** [comment]
Yeah this went through any possible stability test and the values I choose here are safe on any board till now

**Comment by ledvinap** [comment]
@borisbstyle : Users with off-board I2C connections may run into problems, but simple warning in documentation should take care of that ...

**Comment by borisbstyle** [comment]
@ledvinap 
Those users will probably notice it right away as there will no gyro/baro communiction be possible.
But yes documentation needs to warn about that.

**Pull request merged**
