### PR TITLE
Yaw Expo Feature

### PR DESCRIPTION
**Pull request by borisbstyle**
I am trying to implement yaw expo feature as rc_yaw_expo in cli.

Please comment the changes and give me some feedback about this approach. I actually just reused the code from pitch/roll expo and applied it to yaw. Still didn't do testing, but want to first know if the code I used is in the right direction.

Watch this video and you will understand why this feature could be handy. The current yaw on some multirotors can be close to the speeds of roll and pitch and those do have rc expo.
https://www.youtube.com/watch?v=zQtE0nrz2Sk

### CODE REVIEW

**Comment by borisbstyle** [comment]
Ok guys after the latest code fixes it works. I had to remove the serial_msp.c as that one was giving problems in my configurator.

**Comment by thenickdude** [comment]
This change adds linear scaling by rcRate to the yaw which wasn't present before (it's being used to scale the yaw curve). I'm not sure if that is desirable or not, any thoughts?

**Comment by borisbstyle** [comment]
Yes you are right. After I did the change I realize this is probably not something we want. RC rate should not affect yaw. I initially wanted to use yaw rate in the initial commit, bit now I realize its better to remove this scaling at all for yaw.
I will make a change and test it. Thanks for the feedback.

**Comment by hydra** [comment]
MSP needs to be updated, you were on the right track.

To keep MSP backwards compatible with older clients new data can only be added to the END of the existing data. so `currentControlRateProfile->rcYawExpo8` should appear after `currentControlRateProfile->tpa_breakpoint`.

Similarly in 'MSP_SET_RC_TUNING' you need to check the data size >= 10, then do the old stuff, then after reading the old data check data size >= the new size and then read and set rcYawExpo8.

Have a go at it and i can fix it up as required.

**Comment by borisbstyle** [comment]
Thanks hydra. I used PITCH_LOOKUP_LENGTH as it is just a number used for generating curve and I think the same value is fine for yaw as well, but will include YAW_PITCH_LENGTH to keep it more neat and fix the other stuff.
So far the fix is flight tested.....FPV tested and different EXPO values with different PID controllers and it works so damn well!
I will try to fix it today and commit it after flight tests.

**Comment by borisbstyle** [comment]
Can you clarify that part of dataSize >= 10?

I see this line in the current code?
if (currentPort->dataSize == 10) {//allow for tpa_breakpoint

I guess this should be changed to
if (currentPort->dataSize == 11) {//allow for tpa_breakpoint + yaw expo

**Comment by borisbstyle** [comment]
Does this work for 0.63.1 configurator? My configurator is still not loading the PIDs and RC tab.

Considering the yaw expo I think it's done now. I had to add the scaling of 100 what equals to RC rate of 1.00.

**Comment by thenickdude** [comment]
Boris, at the end of that expression you currently have "* 100 / 2500", you can simplify that to just "/ 25"

**Comment by borisbstyle** [comment]
Yes that sounds like an idea. Going to flight test that right now.

**Comment by borisbstyle** [comment]
Ok thanks thenickdude.....it works like expected.

**Comment by hydra** [comment]
Merged, see f5bfe1ce83f671a6d6130cf3db0b941ae2738a12

**Comment by hydra** [comment]
@borisbstyle Please now create a PR for the configurator that adds YawExpo to the Receiver tab if you can.

**Comment by borisbstyle** [comment]
Thanks man. Ok will have to look into the code of the configurator.

**Comment by hydra** [comment]
@borisbstyle See also this commit which was also needed 4a22227b609ecbfe378974656e377b595453492d

**Comment by hydra** [comment]
@borisbstyle Also, please check that the current configurator works still and that the yaw expo is never modified, it works fine here but confirmation would be good.

**Comment by borisbstyle** [comment]
@hydra Ok just tested as you said and no problems found with the old configurator.

I now see what you meant with the serial_msp.c mod. Sorry for misunderstanding you there.

**Comment by borisbstyle** [comment]
https://github.com/cleanflight/cleanflight/commit/f5bfe1ce83f671a6d6130cf3db0b941ae2738a12

**Comment by hydra** [comment]
@borisbstyle I will be working on the api 1.2 / 1.10 problem tonight.

**Comment by borisbstyle** [comment]
I was actually about to ask you that as that is a separate issue.
I will wait for that to be able to continue :)

**Comment by hydra** [comment]
Done, see 244685c9a69f5a2baa2531ccddfe4d463c64f2ab

**Pull request closed without merging**
