### PR TITLE
Added driver/adc.o to rx unit tests. Build failed.

### PR DESCRIPTION
**Pull request by AndersHoglund**
Added missing driver/adc.o to the rx unittests. Jenkins build failed, in RED. This PR fixes that.
http://andwho.sytes.net:8080/job/Hydra_CleanFlight/202/

### CODE REVIEW

**Comment by hydra** [comment]
this wasn't needed, see 84b3afddabce4e67320da88763ade0db64a8fe45

**Comment by hydra** [comment]
thanks for the timely PR though :smile:

**Comment by AndersHoglund** [comment]
OK, but rx still has this dependency to adc. Even if not used right now....

**Comment by hydra** [comment]
i think it would be better to link it only when a test is written to exercise the code.  It makes refactoring easier in the mean time.

**Pull request closed without merging**
