### PR TITLE
New target: F3FC Racing

### PR DESCRIPTION
**Pull request by lkaino**
Upcoming standalone F3 board from RCExplorer.se (not the Tricopter integrated one ).

### CODE REVIEW

**Comment by hydra** [comment]
rebase please.

**Comment by lkaino** [comment]
@hydra rebased.

**Comment by lkaino** [comment]
Rebased to get the CI jobs pass.

**Comment by martinbudden** [comment]
@lkaino , because of PR https://github.com/cleanflight/cleanflight/pull/2288 , you no longer need to include `system_stm32f30x.c` and `system_stm32f30x.h`

Note also your previous build failed because you accidentally removed `SPRACINGF3OSD` and `SPRACINGF1OSD` from the `..._TARGETS=` lines in the `makefile`.

**Comment by martinbudden** [comment]
@lkaino , you've ommitted  `SPRACINGF1OSD` from `VCP_TARGETS = ...`

Also you can get rid of  `system_stm32f30x.c` and `system_stm32f30x.h`

**Comment by lkaino** [comment]
@martinbudden Yes my bad, added it back.

Wow this thing changes fast :). Rebased again, removed the system files.

**Comment by hydra** [comment]
I'm going to rename this target to 'REF3'  i.e. 'RC Explorer F3'.

**Pull request merged**
