### PR TITLE
Added PT1 Element to PID1,2 and 3

### PR DESCRIPTION
**Pull request by borisbstyle**
PID1 on gyro_lpf = 256 without PT1 element (current logic)
pid1

PID1 on gyro_lpf = 256 with PT1 element
pid6

Flown on PID1 with this mod
https://www.youtube.com/watch?v=D41JSw75D4c

### CODE REVIEW

**Comment by MJ666** [comment]
Sounds like I should try this fro my WarpQuad and the MiniQuad 160mm. Likely the buzzing sound I can here are kind of micro oscillations and may be not only propeller noise.

**Comment by borisbstyle** [comment]
@MJ666 
Let me know how it goes! To me it made a huge difference. I always knew gyro_lpf of 256 was awesome, but so sensitive to tuning and vibrations and now it isn't.
What mode do you fly?

**Comment by MJ666** [comment]
@borisbstyle I mainly fly Acro mode. Likely not as advanced as you are. Horizon/angle only for emergency (if I'm fast enough to switch). 

May be it is also a good plan to review the Harakiri PT1 element code and align the code between PID controllers. Some of the constants are redundant now and it may also possible share the configuration variables. The G-Tune PR is containing code to make this configurable for the Harakiri PID and the plan is to have this as part the next release.

**Comment by borisbstyle** [comment]
@MJ666 That's indeed a good idea. I was thinking to share that one, but didn't want to impact that 12hz chosen there already.
We probably want to make this configurable indeed. I suggest changing it already both to 17 if you don't mind?

I will have another look to default value of level parameters for PID1, but it seemed pretty good with this mod already. In my private branch I decreased the dividing value to make default parameters work better already.

**Comment by borisbstyle** [comment]
Had to place back the moving average as I tested before as it is really needed for the best result. PT1 only isn't enough.

**Comment by MJ666** [comment]
@borisbstyle Had just flashed my two quads 30 minutes ago for testing tomorrow morning. Will update again and see how it goes.

**Comment by borisbstyle** [comment]
cool....let me know.

I have to say I am happy. Both pid1 and pid2 work really well now.
Maybe we can play with the cut frequency to see if things can get even better, although that would only be cosmetical as this already feel super locked in :)

**Comment by MJ666** [comment]
@borisbstyle here are the logs from my WarpQuad without and with PT1 element update and PID1:

blackbox_log_2015-06-11_000754 txt
blackbox_log_2015-06-11_214904 txt

more locked in in general. The Warpquad looks to be relatively well tunes. My 160mm MiiniQuad make still the buzzing sound but motors running more cool and the battery is lasting longer than before. likely I need to tune a bit more. Unfortunately I'm not able to make logs from this one.

**Comment by borisbstyle** [comment]
@MJ666 
Wow what a difference man in the logs. All that D overreacting on small ripples is gone. D tightly follows P. You get less corrections and the motors get more room for normal flying :dancer: 
Glad you see the same things as my setups.

This is the proof that filter really helps. Notice how D over reacts on small quick changing ripples, while in filtered situation only reacts where it is supposed to do.

Your log without filter
ripple_nofilter

And with filter
ripple_filter

This is a bigger zoomed out overview of entire flight. 

Normal
zoomed_normal

Zoomed with Filter. Clearly an improvement!
zoomed_pt1

**Comment by borisbstyle** [comment]
@MJ666 
By the way it has nothing to do with this PR, but your accelerometers are much more noisy than in mine graphs. Did you disable acc filtering?

**Comment by MJ666** [comment]
Here you can find my actual settings which are different from the defaults:

http://www.multiwii.com/forum/viewtopic.php?f=12&t=6456#p64083

For now using the same for the Warpquad and the 160mm MiniQuad.

**Comment by fedorcomander** [comment]
Hi Boris!

Just flashed and hovered a bit.
Here is the log file:

Index1: Before flash, 1.9 (almost release, from your branch actually). lpf 42
Index3: Same as Index1 but lpf 256
Index4: Flashed your hex, with lpf 256

Enjoy!

https://www.dropbox.com/s/7eug0cw2b9r37gx/blackbox_log_2015-06-12_133630.TXT?dl=1

**Comment by borisbstyle** [comment]
@fedorcomander 
Thanks. Wow.....yours is really smooth man! The best example so far :dancer: 
Did you try to fly with it more to see how it feels? Take it through some acro and prop wash scenarios. It should reallly make a difference.

There is no point using so much gyro lpf with this modification anymore.

**Comment by fedorcomander** [comment]
Well.. I tuned this one from 0,0,0 myself learning on the way, reading your posts and using blackbox ;)) It feels really locked in... I will take it for a short fly later on tonight if time permits.

What do you mean by: "There is no point using so much gyro lpf with this modification anymore."?

**Comment by borisbstyle** [comment]
I was just saying that in general. gyro_lpf of 42 is meant to overcome small vibrations from the frame, but it adds delay to the gyro. With this PT1 element the PID controller gets more resistant to those like you see and you can fly with the smallest gyro lag.

Your basher looks good in this data :D. Seen much worse bearings

**Comment by stronnag** [comment]
5 packs on my sub-200g  park flyer. Very smooth and responsive (pidc2, horizon with a fair bit of p/r rate for tight loops and rolls). Like this PR!

**Comment by fedorcomander** [comment]
Well... Just went to the park and burned 3 packs... I LIKE it. Had to increase D a bit (3 ticks). It works very well! Very nice and responsive... I like it. See attached log (Its from basher)...

https://www.dropbox.com/s/ar54nobogns1rrs/blackbox_log_2015-06-12_173017.TXT?dl=1

Video still has some vibrations, but hay, it was already there before ;)))

**Comment by lucafedechen** [comment]
Hi people..I need to test this enhanced..I have a flip32+ board, any link to download a compile hex??
Thanks to all
Regards

**Comment by stronnag** [comment]
@lucafedechen <http://seyrsnys.myzen.co.uk/cf-1.9_pr1007/cleanflight_NAZE.hex>. Let me know if you  another board.

**Comment by fedorcomander** [comment]
Hi kinda told you ;)

**Comment by fedorcomander** [comment]
Looking at the log, i have pitch P on the high side... I was checking roll axis, and it looks darn good!!!

**Comment by lucafedechen** [comment]
@stronnag  Thanks...I test  and report my  results..regards

**Comment by borisbstyle** [comment]
Ok guys I made it configuratble. It is disabled by default

To enable old setting:
set main_cut_hz = 17


@fedorcomander 
Will check the log tomorrow. I have some headache from my laptop :(. Time to sleep.

**Comment by stronnag** [comment]
New hex files for naze32 and cc3d with above CLI parameter <http://seyrsnys.myzen.co.uk/cf-1.9_pr1007/>

**Comment by lucafedechen** [comment]
@borisbstyle  Hi boris..now to enable pt1 element I need to set the parameters below??

set main_cut_hz = 17 and gyro_lpf = 256 

Regards

**Comment by CrazyCoder** [comment]
It's a bit inconsistent that gyro_lpf is global, but main_cut_hz is profile specific. You can't create old style profile with gyro_lpf = 42 and main_cut_hz = 0 and another new profile with gyro_lpf = 256 and main_cut_hz = 17. To change to the old style behavior you will have to access CLI and set gyro_lpf = 42.

**Comment by borisbstyle** [comment]
@lucafedechen 
You only need set main_cut_hz = 17 (tested setting), but gyro_lpf isn't really needed I think when having this filter.

@CrazyCoder 
Yes you are right. The master config is not available in pid.c so had to do it through profile. The gyro_lpf is being used on other core parts and can't just be changed to be in here. It's same thing with looptime as well. It's not in the profile settings. I guess you can't have it all in profile as it would be too much. So for testing just land....change and fly again :dancer: 

Guys I added the PT1 to PID3 as well. PID3 is a good candidate for being new default Pid controller I guess. PID0 and PID4 should be removed. Not sure if I should try to do that in this PR or separate one?

**Comment by MJ666** [comment]
I would recommend to make a seperate PR for removing the obsolete PID controllers. Personaly I tend to renumber them to make it quite clean. PID0 and PID4 will go away. PID3 gets new PID0 and PID5 will get new PID3. This change will definitely impact user configuration and we need to be careful. I was starting this discussion a while ago in RCG but the feedback was limited.

**Comment by borisbstyle** [comment]
I already did before you mentioned it :)

Good thing is that we think the same.

How is gtune doing?

**Comment by fedorcomander** [comment]
Why we don't call pid controllers by name and have internal mapping??? 

set pid_controller=luxfloat

In mean while accept names and indexes for compatibility. Loose indexes later on?

**Comment by ATA250** [comment]
Just done some testing on this PR: Extremely precise control response and a joy to fly, by far the best flight experience I've had.

This really needs to be a part of Clean Flight! Thanks Boris!

**Comment by MJ666** [comment]
@borisbstyle in my view G-Tune is ready to merge since quite some time. Its planned for the next milestone. Waiting for @hydra. Would be good if this PR get merged son since the are a few  dependencies and in general some cleanup of the PID controller part with all the nice improvements would be good.

**Comment by borisbstyle** [comment]
@fedorcomander 
That can't be done as the entire cli is integer based. This would be a fundemental change and would increase the hex size as well. There are still some boards with limited space for the code.

@ATA250 
Glad you experience the same like you :D. May I know what PID controller you were using?

@MJ666 
Ok nice. I agree about the cleaning up the pid controllers :D.
I am also thinking to look into Harakiri to see if it is possible to not use the the dynP8, but rather just P8 values like luxfloat and pidrewrite. 
It think that would totally be awesome if I could work out that. Linear rates through the tunes and always same pitch and roll behaviour. What do you think about that?

**Comment by ATA250** [comment]
@borisbstyle PC2

**Comment by Ben250** [comment]
@borisbstyle Just flown a few flights with this build (PC2). Was pretty gusty wind so it wasn't exactly a fair test but I was impressed at how well it was handing in the wind. Couple of issues with my config after reloading it on this build but I assume that has nothing to do with this code. Great work @borisbstyle !

**Comment by CrazyCoder** [comment]
It appears that my gyro on HK Naze32 is quite noisy even on the ground. With this new fw version and gyro_lpf = 256 calibration takes a lot of time with default moron_threshold. Seems better with moron_threshold = 64.

Is it still worth using gyro_lpf = 98 with main_cut_hz = 17? Will it reduce the delay comparing to the default gyro_lpf = 42 and main_cut_hz = 0?

**Comment by borisbstyle** [comment]
I never heard of that. Non moving gyro should never cause calibration issue. It really sounds faulty to me.

But anyway you can use whatever value you want. I was just suggesting the most optimal what I tested on my setups.

**Comment by CrazyCoder** [comment]
It has never caused the issue before with the default filter. Only after installing this fw and disabling gyro_lpf I found that I can't arm sometimes and LED is blinking.

Probably it's a good idea to try another naze32 and see if it works better.

**Comment by borisbstyle** [comment]
Did you recalibrate the acc?

**Comment by CrazyCoder** [comment]
Nope, didn't calibrate it after flashing. That might be the case, thanks for the tip.

**Comment by fedorcomander** [comment]
Recalibrate acc. I had the same.

**Comment by CrazyCoder** [comment]
@fedorcomander thanks, recalibrating acc has fixed the problem.

**Comment by borisbstyle** [comment]
I just fixed harakiri to use the same config parameter as the rest

**Comment by MJ666** [comment]
@borisbstyle making changes on the Harakiri PID will be fine if they make sense. I think we should wait till this PR and G-Tune are merged into the master otherwise it would get a mess to rebase and mix the code.

**Comment by borisbstyle** [comment]
@MJ666 
Do you mean the last change or the one I suggested above with removing dynP8? If it's the last I did tried removing dynP8, but it's hard to get it right as the harakiri logic is pretty complex. Do you know someone who wrote it before if they can look into it? Of course in a separate PR.
The thing I was scratching my head about for example is why the ITerm calculation uses P for calculation and some of the scaling factors were hard to understand.
The basic problem for me on harakiri controller is that especially on high power setups where you have to lower the P by much the rates get very quick and that the difference between pitch and roll rates becomes incredibly high. That's really too bad as there is so much nice floating logic in there.
I tried removing dynP8 and replacing by P8 with some added rate multiplying and had more success, but not understanding some parts made it hard to get the scaling right.

This particular PR is complete if you ask me. I don't see any reasons to improve, except some documentation what needs to be added or perhaps EEPROM version and API stuff?
Only thing being affected with this PR is the default harakiri Dterm. So when users who use harakiri upgrade they might be affected. What do you think to make disabling in harakiri impossible? So when disabled it sets it to 12hz and makes that as the lowest possible value. What do you think @MJ666?

**Comment by MJ666** [comment]
@borisbstyle the last change here is fine and can be handled easily during merge of the two PR. @Crashpilot1000 did the original implementation of the Harakiri PID in his Haraikiri fork of the Baseflight firmware. I only did the port to Cleanflight a while ago since I was very satisfied with the flight behavior of Harakiri and had a lot trouble to get our small brushed multicopters tuned with the Cleanflight PD controller at this time. This was specially the case for the original yaw behavior. the small copters are turning on yaw like a tank. Nothing you can use during speed flying.

**Comment by borisbstyle** [comment]
@MJ666 Thanks for clarification.
Yes I was also pretty happy with the handling of harakiri. Nice stable and aggressive, but the rate scaling is a nightmare and especially if P gets below 2-3 on roll and pitch axis. 
The main cause of that is the multiwii legacy where P is scaled dynamically in mw.c to dynP8. That was the multiwii super expo implementation for the rates.
@Crashpilot1000 I can open an issue for the above mentioned. Do you see an issue of replacing dynP8 to pidProfile->P8[axis]? When doing that normal TPA functionality will be removed, but you can use the new PIDweight[axis] to scale the P directly without influence of pitch/roll stick.
It has nothing to do with this PR, but might be a part of full pid controller optimalization part :dancer: 
Doing this will require re-scaling some multipliers to make a nice configurable range and adding race  multiplier to error calculations as well. See for example how this was done in PID1 and PID2.

**Comment by borisbstyle** [comment]
I am also going to try this butterwroth filter to compare it with PT1.
http://www.rcgroups.com/forums/showpost.php?p=31882733&postcount=8873

**Comment by borisbstyle** [comment]
It turns out the current code doesn't allow lpf to be set to 256 (disabled), but puts it to 188 instead.
https://github.com/cleanflight/cleanflight/issues/1014

**Comment by borisbstyle** [comment]
I made a rebase of this one
https://github.com/cleanflight/cleanflight/pull/1016

**Pull request closed without merging**
