### PR TITLE
Cleaning main.c

### PR DESCRIPTION
**Pull request by mgirlando**
This is the pull request corresponding to issue : https://github.com/cleanflight/cleanflight/issues/957

I corrected 60 header files that was missing include and now they can be added in any order.
I added also the inits that was not in the headers.
Splitted main.c that was really too big in 3 files :
- main.c to handle main()
- main_initialisation that contains init() (the code is strictly the same)
- main_faulthandler that contains HardFault_Handler()

I flew with the modifications on flip32 noticing no difference.

### CODE REVIEW

**Comment by ledvinap** [comment]
Please correct your line-endings first (And possibly tabs), this PR is unreadable this way ...

**Comment by mgirlando** [comment]
Do you know witch line endings I must use? Windows or unix ? it is not clear.
All files seems to be  ASCII text, with CRLF line terminators, and I didn't change that.
Tabs seems to be soft one (spaces)

**Comment by mgirlando** [comment]
My mistake... I left eclipse on default parameters. So now I corrected to encoding US-ASCII and line endings UNIX.

**Comment by hydra** [comment]
Hi, thanks for working on it, however I don't want include files that include other include files.

There are some instances of this in the project, in frsky.h, telemetry.h and maybe one or two more and need to be fixed.

platform.h and target.h should be the only exceptions.

In general, to allow easy refactoring, instantly see the dependencies and to improve code re-usability .h files should not include other .h files.  Only .c/.cpp files should include .h files.


It can become an unmaintainable mess unless this isn't followed.

**Comment by mgirlando** [comment]
Ok no personnal problem with that. I have a little concern about that because it is against all basic rules of C coding (I am doing aeronautical real time coding for more than 20 years now). One of the rules is that a header file MUST compile by itself. The reasons for that are :
-  a user of the module does not have to dig into the .c to find what is missing. 
- any change in the module may cause problems in others
I have seen that dependancy problems are mainly caused by incomplete header files ( there was one in the corrections I made) 
For reference you can see the rule 9 of http://www.umich.edu/~eecs381/handouts/CHeaderFileGuidelines.pdf

**Comment by mgirlando** [comment]
Ok no personal problem with that. I have a little concern about that because it is against all basic rules of C coding (I am doing aeronautical real time coding for more than 20 years now). One of the rules is that a header file MUST compile by itself. The reasons for that are :

*	a user of the module does not have to dig into the .c to find what is missing. 
*	any change in the module may cause problems in others 

I have seen that dependancy problems are mainly caused by incomplete header files ( there was one in the corrections I made) For reference you can see the rule 9 of  <http://www.umich.edu/%7Eeecs381/handouts/CHeaderFileGuidelines.pdf> http://www.umich.edu/~eecs381/handouts/CHeaderFileGuidelines.pdf 

 

 

De : Dominic Clifton [mailto:notifications@github.com] 
Envoyé : mercredi 10 juin 2015 03:42
À : cleanflight/cleanflight
Cc : mgirlando
Objet : Re: [cleanflight] Cleaning main.c (#1001)

 

Hi, thanks for working on it, however I don't want include files that include other include files.

There are some instances of this in the project, in frsky.h, telemetry.h and maybe one or two more and need to be fixed.

platform.h and target.h should be the only exceptions.

In general, to allow easy refactoring, instantly see the dependencies and to improve code re-usability .h files should not include other .h files. Only .c/.cpp files should include .h files.

It can become an unmaintainable mess unless this isn't followed.

—
Reply to this email directly or view it on GitHub <https://github.com/cleanflight/cleanflight/pull/1001#issuecomment-110554261> .  <https://github.com/notifications/beacon/AHYr3f-WvHt6lKIf8kSBMKsryKAMm5Kuks5oR41ngaJpZM4E8xIr.gif> 

 

  _____  


 <https://www.avast.com/antivirus> 

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast. 
www.avast.com <https://www.avast.com/antivirus>  

 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by ledvinap** [comment]
I fully agree with @mgirlando ...

**Comment by thenickdude** [comment]
As do I. For example, currently if you want to import the master config header then you basically have to individually list every header in the project to go along with it (by trial and error), and every time the master config header changes, so do all the places that import it. But these secondary header files must always be included in order to include the config header, so why doesn't the config header (for example) include those itself so we only have to do that once?

**Pull request closed without merging**
