### PR TITLE
Airmode Implementation / Acro optimised mixer and PID controllers

### PR DESCRIPTION
**Pull request by borisbstyle**
Airmode concept implementation. Mixer improvements to have better stability over the entire throtle range and especially low throttle. 
Additionally to that there are several other tweaks to Iterm to make acrobatic things much more natural and to prevent unnecessary Iterm windups.
This also improves 3D flight experience

Initial idea was from @bdoiron74 like 6 months ago, but I did some extensive testing with it and did some optimalisations to it.

There is some double code in the mixer code, but this is intentional to make it possible to easy remove the old mixer method as this could eventually be a full replacement for the current mixer

### CODE REVIEW

**Comment by borisbstyle** [comment]
@martinbudden 
Can you perhaps help with the unit tests in this one? Need to find out a way to test things.

**Comment by martinbudden** [comment]
@borisbstyle I've just submitted a PR that fixes the tests so they run.
Is that all you wanted, or would you like me to look into writing some test code as well?

**Comment by borisbstyle** [comment]
@martinbudden 
Which PR? I dont see anything?

Yeah I mention fixing + setting up a test :D

**Comment by martinbudden** [comment]
@borisbstyle 
Oops. I accidentally issued a PR against my own fork of betaflight, not against your code. I still haven't quite got the hang of multiple forks. Anyway fixed now. You should now be able to see my PR.

OK, I'll have a look at writing some test code for this. It may take a little while though - I need to get my head around how it works first.

**Comment by martinbudden** [comment]
@hydra , the only reason the travis build is failing now is because the CJMCU ROM size is exceeded by 1036 bytes, see: https://travis-ci.org/cleanflight/cleanflight/jobs/106676044
```
/home/travis/build/cleanflight/cleanflight/gcc-arm-none-eabi-4_9-2015q2/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld:
    obj/main/cleanflight_CJMCU.elf section `.text' will not fit in region `FLASH'
/home/travis/build/cleanflight/cleanflight/gcc-arm-none-eabi-4_9-2015q2/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld:
    region `FLASH' overflowed by 1036 bytes
collect2: error: ld returned 1 exit status
make: *** [obj/main/cleanflight_CJMCU.elf] Error 1
The command "./.travis.sh" exited with 2.
```

https://github.com/cleanflight/cleanflight/pull/1752 fixes this and so should allow this PR to be merged in.

**Comment by hydra** [comment]
@martinbudden and @borisbstyle thanks, looking now

**Comment by hydra** [comment]
closing, replaced by #1766

**Pull request closed without merging**
