### PR TITLE
Fix I2C bus error handling for F1 targets

### PR DESCRIPTION
**Pull request by digitalentity**
Fix for too aggressive error handling when a NAK (a normal bus event) was treated as a bus error and resulted in bus "unstick". Additionally, unstick was only clocking out 8 bits, while in most cases it should be 9 (8 bit data and ACK/NAK) and clock was followed by an empty trasnaction (START-STOP with no clock).

See https://github.com/iNavFlight/inav/pull/668

### CODE REVIEW

**Comment by hydra** [comment]
is this tried, tested and working for you @digitalentity ?

ready for merge?

**Comment by hydra** [comment]
p.s. thanks for the timely PR too 😄

**Comment by digitalentity** [comment]
@hydra this is bench tested, no ill effects. Should be safe to merge.

**Comment by hydra** [comment]
tested it on on a naze32 full, no issues with I2C detection here either, merged.

**Pull request merged**
