### PR TITLE
Update to Battery monitor docs

### PR DESCRIPTION
**Pull request by Q-Branch**
Added warning note to battery monitor docs to avoid Naze32 board destruction.

### CODE REVIEW

**Comment by hydra** [comment]
This is a bit confusing to me since you say before connecting the main battery you should disconnect the main battery.  Can you update and clarify what you mean?

**Comment by Q-Branch** [comment]
Yes, when wiring up battery monitoring there will come a moment where you connect the pair of wires directly from the main battery (+12v and GND) to the VBAT pins on the Naze32 board.  I (foolishly) still had the battery connected to the frame at the XT60 connector, and I had the Naze32 connected to the PC via USB.  I had already unplugged the servo connectors from the Naze32.

For no reason in particular I chose to connect the +12v wire to the pair of VBAT pins, rather than GND.  This resulted in a current flow from the main battery, through *half* of the voltage divider network, through the Naze32 board to its GND on the PCB, and then to the only GND that existed on the board, which happened to be the USB connection.  Bang!

**Comment by timkostka** [comment]
What you're describing shouldn't fry the board.  The VBAT connection goes through a 10K resistor to the STM32 chip (and a further 1K to GND).  There's no way it can draw any significant current through that circuit.  Are you sure it wasn't something else?

**Comment by tracernz** [comment]
A high impedance path from the NAZE ground to the battery ground would cause a high voltage on the ADC pin. This will result in the ESD protection diode passing whatever current it is limited to by the 10k resistor. That current is not going to blow the chip up itself but a more concerning issue is latchup inside the STM32 which could result in potentially quite a high current flowing from Vdd to ground and then possible destruction of the device. The only way to clear a latch-up condition is to remove power from the device completely.

**Comment by Q-Branch** [comment]
I agree with @timkostka that the 10K resistor would limit some of the damage, but I think that @tracernz is on the right track here with the current path through the ESD protection diode.  Without the second half of the potential divider network connected to GND, the voltage applied to the ADC pin would pretty much be the same as that of the main battery so let's assume that to be 12v.  The STM32 datasheet seems to indicate that the abs max rating on the ADC pins is 4v, and therefore it's reasonable to assume that the ESD diode would be conducting to Vdd long before we reached 12v.

I examined the board further and found that there is a neat burn hole in the top of the STM32's package lid in the upper right corner (near to pin 23).  This is consistent with the origin of the flash and the smoke that I (briefly!) saw before moving myself rapid in the direction of the power connector.  Nothing else on the board shows any physical signs of death, but it's clear that the board is functionally very dead indeed.  The CP2102 is also dead, even with the USB connected on its own, and was very hot immediately after the incident happened.  The CO2102 devices **are** known to have a latch-up problem, which might be relevant.  I don't have schematics for the Naze32 boards, but it would be interesting to learn whether the CP2102 and the STM32 share the same Vdd rail.  I suspect that they do, given that they are both 3v3 devices.

In any eventuality, I am of the opinion that we should at least do what we can to adjust the docs to help prevent future users from repeating my somewhat silly mistake.  There are a number of suggestions that we could make to avoid it, and I am happy to make the changes to the docs and submit it via a pull request if the community thinks it's worthwhile.  These include:

* Avoiding the use of single pin dupont connectors for VBAT, and recommending that at least a 2 pin chassis be used.  This would make it less likely that the VBATT +ve pin could be connected without its corresponding GND (for the potential divider network).
* Disconnecting both the USB and main battery from the craft before connecting or disconnecting the VBATT pins.

Open to ideas and suggestions, of course.

cheers,
Rich

**Comment by ledvinap** [comment]
Current through 10k resistor is well within ESD diode capability and should not cause latchup (current in 1A range for few ms is probably necessary).
Also without GND and BATT- connection no current will flow, so the 'half of divider' argument does not make much sense.

Most probable cause is direct connection of BATT+ to GND side of VBAT connector (or solder bridge with similar effect). This will result in large current flowing through PCB and ESC GND connection, probably burning PCB in some point (can you test PCB resistance between VBAT GND point and servo header GND?). If the weak point is under STM32, next weak point will be internal GND connection inside STM32, consistent with hole in package ...

**Comment by Q-Branch** [comment]
Resistance between VBAT GND and Servo GND is 38 Ohms

**Comment by ledvinap** [comment]
@Q-Branch : Part of PCB should be visibly burned ... or some via vaporized, solder mask around it should bear visible changes... Only possible source of current this large is direct short of LiPo pack through board - either there was solder bridge on VBAT+ pin to GND or you connected +12V to wrong side of VBAT.
Disconnecting battery before connecting VBAT won't help (unless you fix this problem before connecting battery again).
So the warning should be about correct VBAT connector polarity ...

**Comment by tricopterY** [comment]
How many GND refs can we have? If the Lipo was connected to the frame, GND would have been established in the whole circuit (with small impedence here and there to GND).

**Comment by ledvinap** [comment]
@tricopterY : There is only one GND on existing designs (unless using ESC with true optocoupler input and separate pack for FC power). 38 Ohm is far too large, normal impedance will be at most tens of mOhm (http://www.wolframalpha.com/input/?i=30cm+of+26awg+copper+wire+resistance)

**Comment by Q-Branch** [comment]
@tricopterY @ledvinap There was only one path to the battery GND connected at the time of the incident, and that would have been via the ESC on motor 1 through the Naze32 board to the servo connector.  I guess we could continue to debate this for some time, and I am sure that eventually we might come to a group conclusion.  The key point here is that current flowed from the main battery to / through somewhere on the Naze32 board which didn't end well, and I ended up with a very expensive but useless square section of FR4, with an STM32 with a hole in the top, and a CP2102 that was of no use to man nor beast.

This was my own mistake and, whilst I believe I connected the cable to VBAT +ve, there is always the possibility that I accidentally touched something else instead.  It would not have happened if I had disconnected the battery from the frame at the XT60 connector before I started, and again this was my own mistake and I blame nobody but myself.

However, I am keen to try to prevent others from making the same mistake and that is the point of my Pull Request; to add sufficient advice to the documentation which guides people to ensure that they have disconnected the battery from the frame / PDB before they start messing about with VBAT connections.

I am happy to re-word the modification to the docs to please everyone, but I think that's what we should now be focusing on.  @hydra, would you like me to re-word it at all, and are you happy to merge it to master?  If not then I guess we are all wasting our time and we could go and debate another PR instead.  :-)

Kind regards,
Rich

**Comment by ledvinap** [comment]
What about:

*When installing connection from main battery to the VBAT connector, disconnect the main battery first and double-check wiring before connecting battery again. Wrong connection can immediately and completely destroy flight controller and even connected peripherals (ESC, GPS, Receiver etc.)*

**Comment by Q-Branch** [comment]
Updated the docs based on suggestions.

Kind regards,
Rich

**Comment by hydra** [comment]
@ledvinap thanks for the suggestion, that makes more sense to me and should be fine for most users i think too.

@Q-Branch thanks for the PR, healthy discussion ensued; without the PR the discussion would not have taken place and the caution would be missing.

**Pull request merged**
