### PR TITLE
Board recovery documentation.

### PR DESCRIPTION
**Pull request by OpCode1300**

### CODE REVIEW

**Comment by thenickdude** [comment]
You might want to explicitly say to be careful not to use the 5V pad. Also you should mention that in the configurator you must tick the no reboot box.

**Comment by OpCode1300** [comment]
Added the warning and software setting.

**Comment by thenickdude** [comment]
Ah your ASCII art is looking like this in the web view:

https://github.com/OpCode1300/cleanflight/blob/docs/docs/Board%20-%20Naze32.md

You probably need to wrap it with "```" on a line above it and below it in order to format it as "code" (i.e. monospaced):

```
/-------------------\
|O                 O|
| []5V              |
| [][]Boot          |
|                   |
|                   |
|                   |
|                   |
|O                 O|
\-------[USB]-------/
```

**Comment by hydra** [comment]
Thanks, merging!

**Pull request merged**
