### PR TITLE
Add 5-9 MPU interrupt support and enable Colibri Race MPU sensor interrupt

### PR DESCRIPTION
**Pull request by larryho5**

### CODE REVIEW

**Comment by hydra** [comment]
The sonar code needs to be updated to use the exti callback mechanism.  the `#ifndef SONAR` is a problem here.

**Comment by larryho5** [comment]
I just try to put all the pin interrupt together, please take a look to see if this work.

**Comment by hydra** [comment]
@larryho5 Can you update this now that the MPU INT has been merged?  The sonar stuff is still needed.

**Comment by larryho5** [comment]
@hydra Sorry, i'm not sure what you want me to do.
I saw the Colibri Race MPU INT has been merged already.
you want me to fix the sonar stuff?

**Pull request closed without merging**
