### PR TITLE
Added new MSP codes to serial_msp.c

### PR DESCRIPTION
**Pull request by tricopterY**
New codes: MSP_SET_ARM_CONFIG, MSP_ARM_CONFIG, MSP_SET_LOOP_TIME, MSP_LOOP_TIME
Incremented minor version to 8.

### CODE REVIEW

**Comment by hydra** [comment]
looking good, just a quick reminder to configure your editor to use spaces not tabs though.

**Comment by tricopterY** [comment]
Ok, will do that. Thanks.

**Comment by tricopterY** [comment]
@Hydra - I just checked my editor, it's set to 4 space indent, NO hard tabs. Not sure what the end result has been on my committed files.

**Comment by hydra** [comment]
Merging but will follow up with another commit that changes the MSP codes used.

**Comment by hydra** [comment]
@tricopterY Please review 60835923c4432b47816b442bbcd0778b928ccb72.  Please update your PR for the configurator to match if you have time.

**Comment by tricopterY** [comment]
@hydra - I will make the changes thanks.

**Comment by tricopterY** [comment]
I just noticed:
```C
#define MSP_SET_LOOP_TIME               64
#define MSP_RX_MAP                              64
```

**Pull request merged**
