### PR TITLE
Test inclination angle

### PR DESCRIPTION
**Pull request by avoid3d**

### CODE REVIEW

**Comment by hydra** [comment]
@avoid3d thanks for the additional tests.  Just a quick note, I prefer there to be zero TODO's in the codebase since they just get stale and forgotten.  So instead of a TODO there are generally 2 solutions:

1. leave as-is and raise an issue outside the codebase - this generates discussion and interest - if people care it will get done.
2. fix it now.

I prefer 2, but sometimes 1 is more appropriate if it requires discussion, in this case i don't think discussion is needed - if the name can be better then make it better.

You often find that the first time you name something it's wrong or sub-optimal.  In this case the code was burried inside a larger function and it was moved outside, the name of the function came from the variable the result was assigned to.

```
tiltAngle = calculateTiltAngle(&inclination);
```

Fancy doing another commit to name it properly?

**Comment by hydra** [comment]
also, i note that you're following the expectation pattern now, great!

Perhaps it's worth looking into the googletest api reference a bit more to see if there's other tricks we can use to avoid the repeated code (the loop in the test)

**Comment by avoid3d** [comment]
Yeah agreed on both counts :)

On Sun, Jan 25, 2015 at 2:52 PM, Dominic Clifton <notifications@github.com>
wrote:

> also, i note that you're following the expectation pattern now, great!
>
> Perhaps it's worth looking into the googletest api reference a bit more to
> see if there's other tricks we can use to avoid the repeated code (the loop
> in the test)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cleanflight/cleanflight/pull/424#issuecomment-71398180>
> .
>



-- 
Pierre Hugo
Founder, MyNames <http://mynames.co.za/#/?ref=email>: Painless Domain
Management
Check if your brand is still available? <http://mynames.co.za/#/?ref=email>

**Comment by hydra** [comment]
@avoid3d are you going to do another commit?  would like to merge this today.

**Comment by avoid3d** [comment]
I will commit in 6 hrs.

**Pull request merged**
