### PR TITLE
Updated Eclipse Build Instructions

### PR DESCRIPTION
**Pull request by CraigJPerry**
Hello,

Both #1537 and #1298 complain that the current build in eclipse docs don't work, at least on Windows.

Having just gone through this myself, the project docs are incomplete. I've re-done the doc making sure all appropriate version numbers are recorded and have added some screenshots and links for each step too.

I've taken the format of a quick checklist for people who know what they're doing but just want to make sure they didn't miss a step, perhaps when setting up a new machine. I've also linked to more in-depth detail further down.

Tested on Windows 10.

@Bengt-M can you please test this on your platform. Please start afresh from the beginning of my checklist so that we can prove it will work for others.

@Boomer91 can you please test on your platform also.

Cheers,

Craig

### CODE REVIEW

**Comment by Bengt-M** [comment]
Even more complicated than before but still cant find anything about make clean and make test. So I see no point in trying. Sorry.
And why should I install JDK? Eclipse is usually fine with a JRE.

**Comment by CraigJPerry** [comment]
I can't see anything that can be skipped for a working full env, except the parts marked optional (openocd etc).

The read more link next to jdk has a link to the gnu arm eclipse page saying they suggest jdk over jre.

To test, just run "make test”. There's nothing else to it. Step 10 creates a shortcut in the ide for convenience: 'Run the tests by creating and running a make target named "test"'

Similarly for make clean although eclipse provides this target out of the box so no config step, just click clean project.

**Comment by Bengt-M** [comment]
I followed "Building in Windows.md" to install cygwin, but skipped VIM and added g++ (so I can build the tests). I installed GNU Tools ARM Embedded 4.9 2015q3

I don't use GNU ARM Eclipse\Build Tools; no need with cygwin installed. No need for JDK either, Eclipse is fine with latest JRE (usually even for Java). 

I use eclipse-cpp-mars-2-win32-x86_64 (which was the latest CDT when I installed it) and keep it updated. Added http://gnuarmeclipse.sourceforge.net/updates as an update site (inside Eclipse) and installed.

I have removed the tools in the system path (because someone said it's unsafe to have a compiler available so easy).
Inside Eclipse setting for build environment: ```PATH = C:\cygwin64\bin;C:\Program Files (x86)\GNU Tools ARM Embedded\4.9 2015q3\bin```

I don't use the "Build xxx" commands. I build with "make target", which has a dedicated view.

That's it!

For me it was a very long and painful detour via configuration of the build tools to finally arrive at something easy.

The builds ```make, make -k test, make clean``` are all working fine and default make produces a hex file that flies as expected in the copter.

The only issue now is that Eclipse is indicating many code problems caused by wrong includes, i.e. Eclipse gets it wrong but the makefile is right. With so many different targets that is no surprise anyway.

**Comment by gaelj** [comment]
I followed your very good document and finally got it working. I just had trouble compiling for a NAZE target with debug gdb - it could be good to mention this.

**Comment by hydra** [comment]
merging, the old doc was very out of date.  this is better, even it if might be a little out of date now.

**Pull request merged**
