### PR TITLE
smartport: added MSP/SPORT bridge

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This new feature allows for using the MSP interface over smart port, for example from a LUA script.
Please note that it has not been tested with cleanflight, only with betaflight. I need to shrink the naze target first, so that I can test it on my devel board.

This PR is related to issue #2474.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Another thing: the build fails with NAZE only, because of that:
```
region `FLASH' overflowed by 584 bytes
```

Any suggestion how to solve it? Should it be made optional? I have no idea what should be done here.

**Comment by hydra** [comment]
yes, make it optional.  Current there are SKIP_* and USE_* defines.  We prefer USE_*.  So please add USE_SMARTPORT_MSP_BRIDGE. Then edit the makefile and add a section to add USE_SMARTPORT_BRIDGE for all F3 targets.  There's an example of this at around 224-234.

All the F1 targets are space limited.

Unless you prefer adding 'USE_SMARTPORT_MSP_BRIDGE' to each F3 target.h file?

Other suggestions welcomed.  Pick one at your discretion, we can always change that bit later anyway, not critical.  

Please perform some testing too.

**Comment by raphaelcoeffic** [comment]
@hydra the current head of master does not fit either into NAZE target:
```
ld: region `FLASH' overflowed by 194 bytes`).
```

However, with the current modifications to smartport (MSP bridge OFF), I get 20 bytes back.

**Comment by raphaelcoeffic** [comment]
I've tested it on SPRACINGF3EVO + opentx 2.2 + LUA script, and it works just fine. Some modifications might still be needed to better adapt the LUA script to cleanflight's rate settings (had some troubles first understanding how they work).

**Comment by TobysF** [comment]
https://github.com/cleanflight/cleanflight/pull/2504/commits/661eb506c71d30c0d686f2e7f147f46cf1032ea4
https://github.com/cleanflight/cleanflight/pull/2504/commits/108551f39783aa695523512c192e4c62dc8e30d
https://github.com/cleanflight/cleanflight/pull/2504/commits/bb363aefd8dbc84a6c36a800f4d148311502ab1fa

**Comment by hydra** [comment]
Hi @raphaelcoeffic 

Is this code up to date?  have there been any more changes in BF that need merging in with this PR?

**Comment by raphaelcoeffic** [comment]
Hi @hydra!

Nope, the code in smartport.c has been pretty stable and working steadily. Did you try it out? I'm not 100% sure I've understood the configuration in cleanflight correctly. If you get the chance, it would be good if you could have a try at the LUA script and see if the values are used/interpreted correctly.

**Comment by hydra** [comment]
@raphaelcoeffic which part of the configuration are you struggling with?

**Comment by raphaelcoeffic** [comment]
The rates, I think it's different from BF.

**Pull request closed without merging**
