### PR TITLE
Cli command which displays sonar altitude.

### PR DESCRIPTION
**Pull request by rosek86**
It'd be useful to have command which tests sonar on a test bench.

### CODE REVIEW

**Comment by enly1** [comment]
rosek86 - Very handy for me - was playing with a sonar unit the other day and the only way I could tell if it was working on the bench was with a scope - so just pulled your sonar repo and threw it onto a naze32 - tested it out very quickly and I like it :-)

**Comment by hydra** [comment]
@enly1 You could tell if sonar is working by looking at the 'barometer' graph in the configurator's sensors tab, that's how i verify settings and connections.

But yes, the cli command might be useful, and the scope of change is small here.

**Comment by hydra** [comment]
i should note that i have my reservations with this, i am wary of adding non-configuration related commands to the cli.

Perhaps, instead a new MSP command should be added so that the confgurator can display the altitude, barometer and sonar values?  I think that long-term that would be more useful.   @rosek86 @enly1  What do you guys think?

**Comment by enly1** [comment]
From a purely end user perspective, If I had the option i would prefer something in the configurator if i'm honest.

Thinking is that more people would find it (although I missed the barometer graph (don't have one, so didn't think of checking it for sonar)) and seeing a dynamic updating value would have suited my testing needs better.

But - given this is coded, simple and there ...

**Comment by hydra** [comment]
@enly1 yes, it's simple and there - if we merge it users will expect it, and then if we replace it users may complain and need educating - all of which takes time.  I'd like to get a few more thoughts on this before deciding whether to merge it.

**Comment by vadav** [comment]
I would agree with enly1 that from a end user view, it would be best to have a checkbox/graph in the Sensors tab. 

It is the most logical place to look for it..

**Comment by MJ666** [comment]
Have this shown in the GUI is more natural than in the CLI. 

BTW: with the sonar sensors I have used you even can hear if the are functioning. You can hear some rhythmic cirping sound at the sensor. Not sure if everybody is able to hear this.

**Comment by rosek86** [comment]
Hi, I agree that it'd be much better to have this in GUI, I couldn't see any other option to test sonar right now so that why I've proposed this modification.

btw, I can't hear this sonar :)

**Comment by enly1** [comment]
Hydra - just an FYI - you can't check the sonar on the baro graph as its not selectable if you only have a sonar device ( i.e. no Baro ) as the graph checkbox is disabled.

**Pull request closed without merging**
