### PR TITLE
Free up USART2 while using PPM on Sparky

### PR DESCRIPTION
**Pull request by DaTwo**
This moves the PPM pin off UART2 so UART2 can be used for other things while using PPM on the Sparky board. Remap is to PWM10.  Docs are also updated to show the change for PPM.

### CODE REVIEW

**Comment by modem158** [comment]
After discussion today DaOne and I thought that this change should be pushed into the master branch as the default for the sparky.  Currently PWM10 isn't being used (unless you have a lot of motors/servos) for anything and it seems that freeing up UART2 is a high priority.

**Comment by JohnieBraaf** [comment]
This is great, I was also missing an additional serial port.

**Comment by DaTwo** [comment]
Right now its RX only but still better than nothing. The TX pin is unfortunately mapped to PWM6 so I feel there is way too many things tied to it to free it up. Maybe someone can implement a CLI option?

**Comment by hydra** [comment]
I'm not so sure about this PR.  Yes, i agree that freeing up a serial port while using PPM is nice, but the PCB layout of the sparky is designed so that people use the RX header for the RX and not some other random pin.

Comments?

**Comment by DaTwo** [comment]
Hydra, any way to make this a CLI option? unfortunately I am not skilled enough to feel comfortable making that change. I do know there are many that would love an extra serial port while using PPM. Since there isn't soft serial on Sparky yet this is about the only way.

**Comment by digitalentity** [comment]
Don't have a Sparky to use, but I would definitely love a possibility to have an extra serial port - you always need more than you have.

**Comment by DaTwo** [comment]
Gonna close this pull request and reopen it. I needed to fix a few things on my github setup.

**Pull request closed without merging**
