### PR TITLE
rename logfile suffix

### PR DESCRIPTION
**Pull request by TheAngularity**

### CODE REVIEW

**Comment by McGiverGim** [comment]
There's one PR to change the extension in configurator and blackbox viewer to `.BBL`, adding a prefix to differentiate the FC firmware. For example:

https://github.com/cleanflight/cleanflight-configurator/pull/456

**Comment by TheAngularity** [comment]
evertheless with onboard-sd logfiles will stored with the suffix .BFL ... which irritates ?-(
to keep the logfiles apart i prefer .BFL and .CFL as suffix

**Comment by hydra** [comment]
I have merged the configurator change, can you update this so the extension is BBL please.

**Comment by TheAngularity** [comment]
@hydra 
the extension is now .BBL

**Comment by hydra** [comment]
great, thanks for helping out, all these little fixes and tweaks really do help.

**Pull request merged**
