### PR TITLE
 Free up USART2 while using PPM on Sparky

### PR DESCRIPTION
**Pull request by DaTwo**
This moves the PPM pin off UART2 so UART2 can be used for other things while using PPM on the Sparky board. Remap is to PWM10. Docs are also updated to show the change for PPM. UART2 can be used for RX only.

This is a resubmit of PR #  808. (Had to do do cleanup on my repo)

Original closed PR can be found here...
https://github.com/cleanflight/cleanflight/pull/808

### CODE REVIEW

**Comment by JohnieBraaf** [comment]
I like it, but would there be any way to preserve backward compatibility? This might break someones current setup. It would be great if this was configurable for any given PWM pin, maybe defaulting to UART ports.

**Comment by DaTwo** [comment]
I might try to do a CLI option but I am not sure if I can.

**Comment by hydra** [comment]
Commit from #808 - "I'm not so sure about this PR. Yes, i agree that freeing up a serial port while using PPM is nice, but the PCB layout of the sparky is designed so that people use the RX header for the RX and not some other random pin.

Comments?"

**Comment by hydra** [comment]
I will close this, when we have #357 done we can look at this again.

**Pull request closed without merging**
