### PR TITLE
Port of refactored beeper code

### PR DESCRIPTION
**Pull request by ethomas997**
Ported beeper code from upstream and made some improvements (issue #648).  See
"beeper.h" for list of beeper tones.  The 'queueConfirmationBeep()'
function can be called to beep out the specified number of short tones.
There are still instances of 'blinkLedAndSoundBeeper()' in the code --
these are tricky to replace because they synchronize LED blinks with
beeps.  There are also still instances of BEEP_ON and BEEP_OFF -- might
be better to have a new function like 'beeperOnOffState()' in
"beeper.c".

There are now arm and disarm tones.  While the copter is armed and not
flying, the beeper chirps to warn the operator.  If the arm/disarm is
via the control stick, holding the stick in the disarm position will
make the disarm tone repeat.  This can be used as a lost-model locator.
These changes should address issue #317 ("Beep to sound on arm/disarm").

There is now a special arming tone used if a GPS fix has been attained,
and there's a "ready" tone sounded after a GPS fix has been attained
(only happens once).  The tone sounded via the TX-AUX-switch will count
out the number of satellites (if GPS fix).  I did some "bench" testing
of these tones, but I don't have a GPS on my copter.

I don't have a blackbox logger setup, so I can't test how the
blackbox-arm beep works with the new beeper code.  Seems like it should
be OK, but someone should test it.

Other indicator beeps (like up/down adjustments and rate profile changes
via transmitter switch) should operate same as before.    The critical-battery tone is now more of a longer beep, which I'd say is an improvement.

--ET

### CODE REVIEW

**Comment by thenickdude** [comment]
Startup beeps seem unchanged from the previous behaviour, which is good. When I tried to arm before calibration had completed, it also behaved the same as previously.

I don't really enjoy the "holding disarm causes a repeating beep" feature, since I normally end up walking to my model with my left hand holding the stick in the disarm position, which is now really noisy (and hearing a beep when moving the stick to the disarmed position while already disarmed makes me unsure if it was disarmed or not to start with, which makes me paranoid that I'm not disarming when I should). However, others may like the feature and it's certainly nice if you haven't already set up a beeper switch.

The arm / disarm beeps seem good to me. I also tested both VBAT warning beeps and I liked the patterns better than the original ones.

The beep to remind you that throttle is zero while you're still armed (with MOTOR_STOP) seems to start way too quickly for me, causing an immediate beep every time my throttle dips a little bit too low in flight. If you just do some revving up on the ground, the props never have time to brake to a stop, but you still end up hearing a warning beep. It seems like this should only beep after a second or two of sustained zero throttle.

Blackbox beep doesn't work any more, because it is attempted to be played halfway through the arming beep. Probably what should happen is something like this to record the time of the start of the arming beep in beeperUpdate():

```c
if (beeperPtr[beeperPos] != 0) {
    BEEP_ON;
    if (beeperPos == 0 && (beeperMode == BEEPER_ARMING || beeperMode == BEEPER_ARMING_GPS_FIX)) {
        armBeepTime = mills();
}
```

Then blackbox.c's `blackboxPlaySyncBeep()` doesn't need to play a beep any more, and the time that it records in its event for the start of the sync beep will be `armBeepTime` instead of `millis()`.

**Comment by ethomas997** [comment]
I'll change it so the first 'armed' beep is delayed, and I'll do those changes for blackbox.  For the extra disarm beeps, is it worth adding a new CLI flag to enable/disable it?  (The functionality mimics what the KK2 does.  I used it a while back to find my little copter in the snow. :)

--ET

**Comment by ledvinap** [comment]
@thenickdude : What about using different sequence when holding disarm after CF is already disarmed?

**Comment by ethomas997** [comment]
Yeah -- I'm thinking:  If copter is armed then disarm tone is different and is not followed by repeated tones while the stick is held.  If copter is not armed then, after a bit of a delay, the generic beeping is sounded while the stick is held.

--ET

**Comment by ethomas997** [comment]
I've done some updates and merged with the current master branch.

Added delay to initial armed warning tone.  Made disarm tone different if copter was armed (two beeps) vs. holding disarm stick when copter not armed (periodic tones, only if copter wasn't armed).  Made it compatible with blackbox.
Additional tweaks to improve battery-low tones and make TX_SET not delayed when ARMED tone in progress.

--ET

**Comment by ethomas997** [comment]
Added beeps when changing flight modes (issue #647).  Added stubs in unit tests to resolve references to new functions.  Revised buzzer documentation.

--ET

**Comment by ethomas997** [comment]
Looks like the Travis build failed because of problems with the remote build system (not code errors).  Please test and let me know if anything should be changed.

--ET

**Comment by hydra** [comment]
Thanks for all your work on this.  I think we'll include this in 1.9.x.  I will merge after 1.8.x stable is done.

**Comment by dkisselev** [comment]
Just to tie the related issues into this, #366 can now be easily solved with the refactored code.

**Comment by ethomas997** [comment]
@hydra:  Sounds good.  If you'd like me to redo the PR against the current code later on let me know.

(Code and hex test file are also here:  http://www.etheli.com/CF/refactoredBeeperCode)

--ET

**Comment by ethomas997** [comment]
I've posted an updated PR applied to version 1.8.1 (4/4/2015) of the code:  https://github.com/cleanflight/cleanflight/pull/730

--ET

**Comment by hydra** [comment]
@ethomas997 merged #730

**Pull request closed without merging**
