### PR TITLE
Add support for 64Mbit (8MB) SPI flash chip Macronix MX25L64.

### PR DESCRIPTION
**Pull request by edusteinhorst**
This is to add support for another 8MB SPI flash chip, Macronix MX25L64. It's another option for people who want to mod and expand their CF onboard memory for use with Blackbox. Tested on a CC3D. Attached is a picture of the mod and a sample log file recorded with the chip and patch. The log has only some stick movement, no flying.

img_20160130_244940108 2

[blackbox_log_2016-01-29_232216_8MB.TXT](https://github.com/cleanflight/cleanflight/files/110644/blackbox_log_2016-01-29_232216_8MB.TXT)

### CODE REVIEW

**Comment by hydra** [comment]
Thanks for the code.  Do you have a link to the datasheet for the docs?  We should probably add datasheet urls in to the docs for these chips.

**Comment by edusteinhorst** [comment]
There you go, I added datasheet links to the other chips as well. Cheers

**Comment by hydra** [comment]
nice one.  we'll look at merging this once some other things are done.

**Comment by edusteinhorst** [comment]
Great, thanks.

**Pull request merged**
