### PR TITLE
Quaternion Controller

### PR DESCRIPTION
**Pull request by bdoiron74**
This is phase 1 of an attempt to switch over to a Quaternion IMU. Credit should go to Philip Schmidt since it is pretty much a direct port of his work from here: http://philstech.blogspot.ca/2015/06/complimentary-filter-example-quaternion.html.

I only made minor changes to the algorithm - some filtering and the attitude correction also zeros out yaw drift when it can.

Running on a CC3D, the sensor read + imu calculation takes about 400us, compared to the stock 650us. It doesn't currently do any MAG correction, so I expect that would got up a bit... (edit: I just noticed that my time measurment of the original -doesn't- in include the i2c read!)

With logging enabled 1/1:
    Looptime           1001 avg            7.8 std dev (0.8%)

Phase two will be to add an outer position controller using quaternions that will track the pilots inputs and keep the rate controllers honest. ...and also allow angle mode with inversion possibilities. No gimbal lock! Here's the simulation: https://youtu.be/3tcacDUp7qo

(this wouldn't be the final pull request... the relevant bits are in "Quaternion IMU" and "added acc_lpf"

### CODE REVIEW

**Comment by borisbstyle** [comment]
Interresting. Do you have some videos of the test?

If this all works and safe we can put it in my betaflight project for testers. It always helps to get more feedback from users.

**Comment by bdoiron74** [comment]
Not yet - I only flew 1/2 a battery in my back yard, which doesn't have a lot of room. I'd like to get the position controller outer loop in place before I do the serious testing (i.e. +/- 180 degree pitch/roll angle mode) to prove gimbal lock is gone. The current PIDs will still show gimbal lock because I convert back to RPY at this stage.

Eventually I'm hoping I can call the actual c-code in my python simulation since that is a lot safer environment to find coding bugs! 

Note the edit in the top post - I only measured the imuCalculateEstimatedAttitude() function of the original, whereas the measurement of this code included gyroUpdate() and updateAccelerationReadings().

**Comment by henn1001** [comment]
This would be an awesome addition indeed. I always prefered the quaternions approach :)
Should give us a nice speedboost together with the fast-trig-improvements. And no gimbal lock indeed :)

**Comment by digitalentity** [comment]
I like this PR. But Why defining a new type for a vector? We already have
one. Also naming convention is not what other of CF uses.

**Comment by bdoiron74** [comment]
I just hacked this in for experimentation - once it does everything I want, the style can be cleaned up. I put it up early so others can see what I'm up to and run with it themselves if they like.

**Comment by bdoiron74** [comment]
@borisbstyle - I just gave it a good kick around the yard and I'm really happy with the way it's performing. I never noticed any gravity creep that I used to experience after doing lots of consecutive flips and thrashing around with the original kalman filter (is that why people turn acc off?). I think you should give it a shot and see what you think. Watch the target.h files - I disable everything I don't want so I don't have to worry about code space during development. This change pulls in 4K of code, which I think is related to not having atan2/acos approximations at the moment. 

Phase two is a big lift, so I better get to work.

**Comment by henn1001** [comment]
check out  ctzsnooze long post here regarding the usage of the accel in level/horizon mode  https://github.com/cleanflight/cleanflight/issues/1105

I think gimbal lock was never that big of an issue although i only sometimes use horizon mode and i´m certainly not the one who can judge that. The biggest advantage here i think is that the amount of computation needed for the state estimation will be lowered. This is also the reason why people turned off the ACC. The state estimation was still computed even when we´re only in rate mode. By disabling the acc you can shave of a good 1000us from the looptime on a f1 processor.

**Comment by borisbstyle** [comment]
@bdoiron74 
This is an interresting concept to let some people try it out once you are happy with the results. 

@henn1001 Yes this is definately a task for F3 boards :D

**Comment by bdoiron74** [comment]
@henn1001 - You're right, the current IMU doesn't suffer from gimbal lock, it's the PIDs usage of Roll/Pitch/Heading that do. That's why an outer position controller is needed to do the leveling, and the inner rate controllers shouldn't.

So with the fast atan2 / acos in I'm seeing 280us for the IMU calculation (with acc, but without MAG defined). Nice. I forgot the CC3D used SPI for the MPU.. that's an additional 30us. 

Code-wise, this is using 2.4KB more than the original, which some may frown on. 

    Quaternion with fast atan2/acos patch:
    arm-none-eabi-size ./obj/main/cleanflight_CC3D.elf
       text    data     bss     dec     hex filename
      83260     336    9712   93308   16c7c ./obj/main/cleanflight_CC3D.elf
  
    Original with fast atan2/acos patch
    arm-none-eabi-size ./obj/main/cleanflight_CC3D.elf
       text    data     bss     dec     hex filename
      80796     348    9712   90856   162e8 ./obj/main/cleanflight_CC3D.elf

**Comment by henn1001** [comment]
The f3 does a much better job at calculating and transforming those state estimation frames because of the hardware FPU capability. Hence those f3 boards run much faster even though they run at the same speed as the f1 boards.

**Comment by bdoiron74** [comment]
Oh, yes I know that - my point was that this runs damn quick on an F1 - 280us. The F1 does the original with ACC in 650us. The real performance killer is the I2C I imagine.

**Comment by bdoiron74** [comment]
Have you seen this? http://flysherlockair.com/2015/07/how-does-cleanflight-spend-its-time-lets-profile/

He got a stable 325us looptime out of a naze - and implies that it takes 234us just to read the gyro data - so probably 468us to read the acc=gyro.

**Comment by cfischer9009** [comment]
This is great news bdoiron74!
I have been trying to familiarize myself with this problem ever since posting this issue here.
https://github.com/cleanflight/cleanflight/issues/1105
So happy to hear you are working directly on the problem. I will be trying this out asap and trying to help out since I believe this is a big deal. 
Horay for quaternions!

**Comment by MauroMombelli** [comment]
yes, a lot of time is taken by i2c communication because is slow and we wait for roundtrip (request+response), THAT should be broken into 3 state:
Waiting interrupt data ready (if available),  making request, and waiting answer.

This also show how bad it the IMU code, where imu logic is mixed with sensor reading, making this switch a bit(?) more problematic; the trick could be to use a struct to keep the sensor reading, and move the reading request in a specific part of the code that does only that.

Also please note that MahonyDCM without fastmath WITH magnetometer take 147us, WITHOUT magnetometer is take 85us(!), this is without sensor reading (see#1253 to get more information and data, please take attention that timing are for 5000 loop to get a better averange)

**Comment by ProDrone** [comment]
@bdoiron74 I am playing with this and noticed that the yaw is moving in the opposite direction compared to the standard imu (a shown in the configurator setup tab)? Where can that direction be changed (in the code)?

**Comment by bdoiron74** [comment]
@ProDrone Hmm - It seemed to be going in the right direction and flew well for me (CC3D build, harakiri PID). I do fly reversed yaw stick, but the graphic moved correctly. 

At the end of qimuUpdate I convert to the normal cleanflight inclination / heading values. You might be able to get away with mirroring the heading there. I'd check the sensor orientation though. Does it move as expected if you build this branch with USE_QUATERNION undefined and use the same config?

I ran out of free time and haven't been in to this in a while. I've also been kind of waiting for the next release of cleanflight to settle out.

**Comment by ProDrone** [comment]
@bdoiron74 I'm using NAZE32, just a bare board connected to the configurator. When build with USE_QUATERNION undefined (using same config) the graphic moves in the correct direction. So it really does change yaw direction.

Defines in target.h were already restored during my tests.

**Comment by bdoiron74** [comment]
So the Naze CW270 vs the CC3D CW0 alignment must be doing it somehow. As a hack you can try adding o->y = -o->y to the very end of the quaternion_to_rpy() function. 

I'll see if I can replicate your issue over the weekend and find a proper solution. Strange though... yaw should only be affected by 'XXX_FLIP'

**Comment by MauroMombelli** [comment]
*aehm* clockwise 270 degree?

**Comment by bdoiron74** [comment]
Sorry I guess it's the CC3D at 270 and NAZE at 0. But again, that should only affect the Roll/Pitch not the Yaw. 

https://github.com/cleanflight/cleanflight/blob/master/src/main/target/CC3D/target.h#L50
https://github.com/cleanflight/cleanflight/blob/master/src/main/target/NAZE/target.h#L91

**Comment by MauroMombelli** [comment]
depends witch axis in witch direction :)

**Comment by ProDrone** [comment]
@bdoiron74 Just tested this: the SPARKY has the exact same behavior as the NAZE.

**Comment by hydra** [comment]
hi guys, there's some great info on this PR, but there seems to be some extra commits that have crept into it.  Please can you ensure the PR branch with the code only has the appropriate new code?

Can you also rebase the PR of current master?

**Comment by bdoiron74** [comment]
I still need to get back to this. Yes - it's currently more of a working
directory snapshot that has unrelated edits in it.

**Comment by digitalentity** [comment]
@bdoiron74 hi!
Any news on this one? I'm very interested in getting a better (more precise, faster) attitude estimator for inertial navigation. I'm experimenting with DCM filter in quaternion form but without much success :(

**Comment by henn1001** [comment]
We´re using this already in betaflight :) seems to work fine.

**Comment by digitalentity** [comment]
@henn1001 does it support compass heading?

**Comment by henn1001** [comment]
I doubt it.. not even sure how much of this pr was merged into betaflight.

**Comment by bdoiron74** [comment]
Closing - looks like @borisbstyle included the IMU here: https://github.com/cleanflight/cleanflight/pull/1404

**Pull request closed without merging**
