### PR TITLE
Add failsafe-test TX-AUX-switch mode

### PR DESCRIPTION
**Pull request by ethomas997**
Adds a new TX-AUX-switch mode named FAILSAFE for testing of failsafe functionality.  This allows the operator to simulate a failsafe without turning off the transmitter, and regain control instantly by resetting the TX switch.

This PR also has the "failsafe disarm motors armed throttle low" (#717) changes.

--ET

### CODE REVIEW

**Comment by digitalentity** [comment]
Probably we should split failsafe into two parts:
1) FAILSAFE mode - actually setting throttle and performing other failsafe-related tasks
2) Failsafe detector - detect loss of signal and actually enabling FAILSAFE mode (or other mode of user choice)
This will now only allow to trigger FAILSAFE more by AUX switch, but also activate i.e. GPS RTH on failsafe condition.

**Comment by ethomas997** [comment]
digitalentity:  You should create a new issue for that functionality request.

--ET

**Comment by ProDrone** [comment]
@Hydra  Modified failsafe (issue #112) #185 has this already implemented. A failsafe mode that is triggered by a failsafe condition and/or a configurable TX failsafe switch.

**Comment by ethomas997** [comment]
If #185 is what's going to be merged in, I'm alright with redoing my #717 ("Make failsafe disarm if motors armed and throttle low") to go in after that (assuming that #717 is wanted).

--ET

**Comment by ProDrone** [comment]
@digitalentity It is split in #185 with a more complicated fail safe procedure in mind. For now it is just landing, but could be expanded when we have achieved a good working PH and RTH system. @ethomas997 Ehm, yes, separate issue for this request required.

**Comment by ProDrone** [comment]
@ethomas997 Maybe you should close this pull request since it is included in #185.

**Comment by ethomas997** [comment]
Functionality implemented in PR #185

--ET

**Pull request closed without merging**
