### PR TITLE
Added an enable switch to stick arming/disarming for safety

### PR DESCRIPTION
**Pull request by ProDrone**
Added CLI variable `stick_arm_enable_switch`
Intended to partially cover the concerns as discussed in issue
https://github.com/cleanflight/cleanflight/issues/498

With this modification it is possible to prevent accidental arming and allow instant disarming.
This does not to change behavior of feature `MOTOR_STOP`.

| `Variable`                      | Description/Units                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Min    | Max    | Default       |
|---------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|--------|---------------|
| `stick_arm_enable_switch`       | Enabled by default. Allow stick arming when AUX switch for ARM mode is ON. Disarms instantly and independently of throttle value when AUX switch for ARM mode is OFF (kill switch function). Only applies when arming and disarming with an AUX channel is configured.                                                                                                                                                                                                                                                                                                                                                                                 | 0      | 1      | 1             |

### CODE REVIEW

**Comment by ProDrone** [comment]
@ethomas997 I took the idea you coined some time ago in https://github.com/cleanflight/cleanflight/pull/852 and intend to remove the `failsafe_kill_switch` function from the failsafe features.

**Comment by ProDrone** [comment]
__BUMMER__ :hand: `TARGET=CC3D OPBL=yes`

`/home/travis/build/cleanflight/cleanflight/gcc-arm-none-eabi-4_9-2015q2/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: region 'FLASH' overflowed by 52 bytes`

When building this target locally using `gcc-arm-none-eabi-4_8-2014q3` everything is fine.
The newer compiler seems to create bigger images...

**Comment by ethomas997** [comment]
@ProDrone I like the proposed functionality -- being able to have an enable/disarm switch while still having stick arm/disarm would be good.  However, it would really need to be disabled by default, otherwise guys with ARM switches setup would find, after doing a Cleanflight upgrade, that stick arming is suddenly needed (any they'd be quite unhappy with having to figure out why and change the setting).

If you don't mind some recommendations, I'd suggest naming and describing this in terms of changing the functionality of the ARM aux-mode switch:

stick_switch_arming:  When enabled and an ARM aux-mode switch is configured, the motors are not armed until the switch is on and stick-arming is performed (usually holding rudder stick to the right).  Turning off the ARM-mode switch will still disarm the motors immediately, but stick disarming may also be used (usually holding rudder stick left).

Other potential names could be "stick_and_switch_arming" or "require_stick_arming".  But I find the first one kind of long, and the second one could be confusing when an ARM aux-mode switch is not enabled and this function has no effect.

--ET

**Comment by ProDrone** [comment]
@ethomas997 It is default enabled because the main issue is making the defaults safer for (inexperienced) users. It is important that a note goes into the release notes about the changed functionality.

Choosing a good name for these settings is always hard. I admit the name is quite long and i like short names too (as long as it is not something like `moron_threshold` or `retarded_arm`).

Thanks for your input, i will change the description If and when this pull-request is accepted. I hope it will be reviewed by many...

**Comment by ethomas997** [comment]
@ProDrone The default config of the board has no AUX-Mode switches enabled, so in the default config this parameter has no effect.  It doesn't help the newbies who just run the defaults.  I can see where having it in place could make it harder to have a "surprising arm" event after an ARM aux-mode switch is configured, but if a Cleanflight upgrade changes the arming requirements like I described above, there will be a lot of angry blowback.

---ET

**Comment by ProDrone** [comment]
The more i look at the different arguments in #498 and think about this, the more i got he idea that nothing can be changed to make it safer and at the same time keep everyone happy.

I think it will end with either a tough decision or no change at all. Suggestions are welcome...

**Comment by Redshifft** [comment]
Your Kill switch is perfect and I have been using it for a few weeks :)
I stick arm because all my quads have always been that way. I also run motor Idle because it's safer and the motors respond faster. especially being that the current failsafe does not work properly you must push to make sure it's in future CF releases on the grounds it's a safety feature for the "stick armers"

**Comment by ethomas997** [comment]
Don't get me wrong -- I think this is a very good feature and should go in.  I just don't think it should be enabled by default.

--ET

**Comment by mosh1** [comment]
This is a good idea in theory, however seems redundant to a Throttle Hold switch that you set on the transmitter. This has been standard by RCers to set this switch in radio (usually bottom right switch so it's a flick up of right index finger to Throttle Hold). I can't see a radio have an AUX switch but not have settings to enable Throttle Hold.

**Comment by joshuabardwell** [comment]
Throttle hold is moot if you're not using motor_stop. The props will spin whenever you arm. In fact, throttle hold would lock the throttle in the zero position, allowing arming via yaw even when the throttle was not zeroed.

**Comment by mosh1** [comment]
That's true. For that case I'd argue to have the motors always stop when throttle is below a certain value under 0% (usually throttle hold is set to -5% for example) no matter if MOTOR_STOP is enabled or disabled. This wouldn't have any effect other than when Throttle Hold switch is enabled and still let you configure with MOTOR_STOP or not.

**Comment by joshuabardwell** [comment]
>If it's under 0% then we assume a throttle hold switch is set, and even if the motors dont' spin on arm it's not a safety issue since throttle stick wouldn't do anything anyway.

Setting throttle to -5% gets into interactions with rx_min_usec and failsafe. Remember that some people are used to setting their throttle to negative values in order to trigger failsafe, except that made big problems when the rx_min_usec and failsafe behavior changed. So this idea of overloading the throttle channel to have multiple meanings is problematic. If you want a switch to trigger a throttle hold mode, the right way to handle it is to assign it to a Mode using an Aux channel, not to overload an existing input channel in a potentially confusing way.

**Comment by ProDrone** [comment]
@hydra Do you like this feature or should we drop it?

**Comment by ProDrone** [comment]
This behavior is an implicit part of PR #852 

When an AUX switch is assigned to the new FAILSAFE mode it will act as follows:
* in the OFF position arming via a switch or the sticks is allowed.

* In the ON position arming is blocked and (by default) the failsafe auto landing is started. Intended for testing this function and/or to trigger it on a real failsafe event (by setting the ON position in your RX as the failsafe position). When `failsafe_kill_switch` is set to `1` (default is 0), the ON position instantly disarms.

**Pull request closed without merging**
