### PR TITLE
Naze gyro fix for 1.14

### PR DESCRIPTION
**Pull request by dhoulton**
My NAZE32 rev 6 does not see gyro data since 1.14.0.  Described in issue #2587.  Resolved with one define in NAZE target.h.

### CODE REVIEW

**Comment by martinbudden** [comment]
@dhoulton , although this fixes the symptoms, it doesn't fix the underlying problem. Namely `MPU_INT_EXTI` is not defined in the NAZE `target.h` file.

Instead the following lines should be added to the `target.h` file (after the line`#define USE_EXTI`):
```
#define MAG_INT_EXTI            PC14
#define MPU_INT_EXTI            PC13
```

The difference between NAZE and CJMCU is that the CJMCU does not have the interrupt pin connected, whereas the NAZE does, so the fix is different.

Can you test, and if all works update the PR accordingly?

**Comment by daveh-lunarg** [comment]
Yes, I will try that tonight and will update the PR if it works.  Thanks!

**Comment by dhoulton** [comment]
Yes, I will try that tonight and will update the PR if successful.  Thanks!

**Comment by dhoulton** [comment]
Added the EXTI definitions suggested by martin, and verified that this does indeed fix the gyro problem on my NAZE32 rev6.

**Pull request merged**
