### PR TITLE
adding support for Multiplex SRXL V2

### PR DESCRIPTION
**Pull request by saperlot**
Multiplex introduced a new protocol with identifier "A2" as an indicator for Version 2 protocol of the SRXL. it can now contain 16 Channels instead of 12.
Previous working recievers with identifier "A1" are not affected on this change.
Tested with Mutliplex RX-4/9 FLEXX receiver.
Thanks to Steffen Graap for the code.

Maybe a short comment helps to understand what SRXL is. In fact JR's XBus mode B is SRXL which is used by a couple of manufacurers. It makes more sense to use the name SRXL because thats the standard defined by srxl.org. But a rename is a lot of work and confuses users but definately make sense in along term period.

### CODE REVIEW

**Comment by ledvinap** [comment]
@hydra : X-bus driver is getting a bit too complicated and ugly, it should be cleaned up ...

**Comment by saperlot** [comment]
@hydra @ledvinap Very good idea, maybe a good approach would be leave the code in there for the RJ01 (because it is anyway different). And move the SRXL (Xbus-modeB) to a new sourcefile? With this step i also suggest to take the SRXL name and not xbus modeB. See: http://wiki.beastx.com/index.php/SRXL_-_Serial_Receiver_Link_protocol/en

**Comment by hydra** [comment]
This PR is missing documentation.  The docs need to be updated.  

@saperlot can you do as you suggest and move the SRXL code to a new file?  @ledvinap do you think it's best to keep them seperate too?

**Comment by ledvinap** [comment]
Splitting will only increase code size and result in code duplication.

The code needs some rewrite ... 

Main problem is parsing packets in IRS handler. It is increasing interrupt latency, increasing max stack usage and bas practice in general.

I would redesign receiver routine to just store packets, possibly decoding it's length (it is not strictly necessary - just use interbyte interval to terminate packet). Also waiting for header byte is problematic - receiver may sync into packet. Interbyte timing handles this easily.

Packet processing may be called from main loop (quite easy with task scheduling) and decode what is received.

Also crc calculation should be moved to separate file (reuse is possible) and implemented efficiently.

**Pull request closed without merging**
