### PR TITLE
Low-pass filtering for servos

### PR DESCRIPTION
**Pull request by fusterjj**
Hi,

My Tricopter needed some filtering on the servo to dampen some resonance in the tail.  It seems like it is a common feature that is present in other flight software, e.g. KK2.

I'll be creating a separate pull request which includes a documentation update for this and some other items.

### CODE REVIEW

**Comment by ledvinap** [comment]
Some thoughts:

- there is CMSIS library with filtering functions. It has fixed point implementation of filters that would be considerably faster on cortex M3 processors.

- maybe the problem with servos is that loop time is much shorter that servo update period (~400Hz loop / 50Hz servo signal). Did you try to use simple averaging filter to downsample servo control signal? Or simple exponential decay IIR? Using fifth-order IIR seems like overkill to me (at least considering filters in other parts of code)..

- using linear cutoff frequency is probably unnecessary - exponential frequency steps may provide comparable results with only few values per decade.

**Comment by fusterjj** [comment]
Thanks for the feedback!

* CPU utilization - CMSIS looks interesting.  I was hoping of course to avoid the extra design issues with fixed-point implementations.  Is the performance gain really that significant for ~8*11 multiply adds? However 5th order is almost certainly overkill, yes :)  I haven't tried backing it off yet, but I could certainly do that and it might just make it not worth dealing with fixed point.

* Flash resource use - once again I will claim laziness in generating a table, and linear at that.  I can just generate the coefficients when the frequency is changed which would solve the issue outright. I should have guessed that some targets would be more limited.  Again I'd be more comfortable doing that in floating-point though.

* Supposedly my servo handles 400Hz; false advertising is possible of course. And I do have `servo_pwm_rate` set to 400.  I haven't tried exponential decay or averaging.  Based on my searches this seems like it is/was a common issue with tricopters, but I will admit that this is my first multirotor...

I propose that I just try perhaps a 2nd order butterworth and see if that takes care of it.  I'll generate the coefficients to resolve the flash resource use issue, and I would think 2nd order is low enough to not care about using fixed-point (~8*5 multiply adds per cycle).

Thoughts?

**Comment by fusterjj** [comment]
FYI I did some benchmarking.  218us for the 5th order filter in this branch.  So ~100us for the 2nd order I would guess.

**Comment by ledvinap** [comment]
200us at 500Hz loop is 10% CPU time ...

**Comment by fusterjj** [comment]
OK, I made the following changes:
* Filter is now second-order
* Coefficients are generated at runtime when frequency changes
* Filter is now fixed-point
* Added unit tests

Execution time is now 26us to filter all 8 servo channels.

**Comment by hydra** [comment]
26us seems much better.
Is documentation included in the PR?

**Comment by fusterjj** [comment]
It's currently in the other PR from me together with some other documentation updates. If my other documentation changes are controversial I can back them out to make sure these go in.

**Comment by fusterjj** [comment]
To make things simpler I pulled in the Mixer.md file that I made into this branch.  It includes documentation for the filtering.

**Comment by hydra** [comment]
excellent, thanks @fusterjj.  I have quite a few PR's to review and merge at the moment, hopefully I'll get some time soon.

**Comment by hydra** [comment]
@ledvinap forgot to mention: thanks for all your input on this an other PR's, much appreciated!

**Comment by fusterjj** [comment]
Merged with upstream

**Comment by hydra** [comment]
@fusterjj Still not had time to review and test.  I'm off on holiday for a couple of weeks too, I should be able to look at this on my return.

**Comment by fusterjj** [comment]
I split the filtering into separate files to hopefully make review easier.

**Comment by fusterjj** [comment]
@hydra Looks like CJMCU is running out of flash (this PR doesn't grow it that much...).  Should I move this to HIGHEND_SRC and per-target defines?

**Comment by fusterjj** [comment]
@hydra Have you had a chance to look at this yet?  Thanks

**Comment by hydra** [comment]
Been busy with other PR's recently.  Gonna look at it now.

**Comment by hydra** [comment]
Merged.

I also did a bit of cleanup around the servo code.  One of the goals for 1.8.0 is to allow backbox on the CJMCU target and this new code along with other code is now only enabled with `#ifdef USE_SERVOS`.

**Comment by stronnag** [comment]
I'm looking forward (weather permitting) to trying this on mini (300m2m) and maxi (600m2m) tricopters. Hopefully mitigating the current solution for yaw servo oscillation of dramatically culling yaw 'P'. 

@fusterjj, it would be really helpful to have some user documentation on tuning the frequency parameter beyond the current engineering / factual description in Mixer.md.

**Comment by fusterjj** [comment]
@hydra  Ahh okay, that makes sense.  Thanks.

@stronnag Hmm, sure that might be a good idea.  Mine was excited pretty easily by a "ping" test.  With the copter on the ground if you tapped the side of the tail boom it would start oscillating, sometimes rather dramatically.  I had the configurator GUI connected and just kept reducing the frequency cutoff until tapping it produced little-to-no oscillations.  If you subsequently increase the yaw gain you should repeat this test to see if you need to reduce the cutoff further.

**Comment by hydra** [comment]
@fusterjj you you create a new PR with some tuning documentation for this?  A link to a video on youtube from the docs might also help.

**Comment by fusterjj** [comment]
Sure I'll add some tuning info to the docs.  I'll look into doing a video too, though that might come later.

**Comment by stronnag** [comment]
I flew this at default setting on a mini (300mm m2m) tri this evening. Nice, removed the tail servo oscillation previously occasionally observed levelling out of violent manoeuvres.

**Comment by fusterjj** [comment]
@stronnag Awesome, glad to hear it.  FYI, I submitted PR #571 with some tuning suggestions.

**Pull request merged**
