### PR TITLE
Update Blackbox.md

### PR DESCRIPTION
**Pull request by 2dogrc**
Added more info about setting up SD card.

### CODE REVIEW

**Comment by thenickdude** [comment]
Not needed IMO, neither of these things will do any harm if you're using SD card logging.

**Comment by 2dogrc** [comment]
You are correct they won't do any harm, its just the information is wrong.

Mark Grohe
support@2dogrc.com
www.2dogrc.com
800-517-3810 ext 1
Twitter: http://www.twitter.com/2dogrc
Facebook: 2dogrc
<https://www.facebook.com/pages/2dogrcs-RC-Warehouse/155034941272913>
YouTube:2dogrc <http://www.youtube.com/2dogrc>


On Sat, Feb 20, 2016 at 5:45 AM, Nicholas Sherlock <notifications@github.com

**Comment by thenickdude** [comment]
No it isn't? The instructions you're talking about are in the sections about using a serial OpenLog logging device.

**Comment by hydra** [comment]
@2dogrc thanks for the PR.  I'm in agreement with nick here, think you were just reading the wrong section of the documentation when you set things up.

I would prefer LESS documentation and only what is necessary, otherwise it's maintenance overhead.

**Pull request closed without merging**
