### PR TITLE
if target defined VCP, it will always selected as MSP port.

### PR DESCRIPTION
**Pull request by larryho5**

### CODE REVIEW

**Comment by readerror67** [comment]
Unsure why a FC would require default PIDs different from the software's default PIDs, something like Vortex maybe...

**Comment by larryho5** [comment]
This number is from our flight tester, this can help a beginner easier to start.

**Comment by JohnOCFII** [comment]
These two commits seem unrelated to each other. Should they be in separate PRs?

**Comment by ledvinap** [comment]
IMO forcing VCP as MSP_PORT is bad idea, user should be able to configure this. But mapping VCP to MSP_PORT when resetting defaults is OK.

Port indexes in this PR do not make much sense - disabling USE_x in target.h will break code in config.c
It you need enabled port index, you can use some preprocessor code:
```
// normalise USE_x, define port indexes
#ifdef USE_VCP
# define SERIAL_VCP_USED 1
# define SERIAL_VCP_INDEX (0)
#else
# define SERIAL_VCP_USED 0
#endif
#ifdef USE_USART1
# define SERIAL_USART1_USED 1
# define SERIAL_USART1_INDEX (SERIAL_VCP_USED)
#else
# define SERIAL_USART1_USED 0
#endif
#ifdef USE_USART2
# define SERIAL_USART2_USED 1
# define SERIAL_USART2_INDEX (SERIAL_VCP_USED + SERIAL_USART1_USED)
#else
# define SERIAL_USART2_USED 0
#endif
...

```

Or you can define bit for each known serial port and define used ports as bitmask. Then it is possible to use `BITCOUNT` to get index of port:
```
#define SERIAL_VCP_ID (1 << 0)
#define SERIAL_USART1_ID (1 << 1)
...

#ifdef USE_VCP
# define SERIAL_VCP_ID_MASK SERIAL_VCP_ID 
#else
# define SERIAL_VCP_IS_MASK 0
#endif
...

#define SERIAL_PORT_USED (SERIAL_VCP_ID_MASK | SERIAL_USART1_ID_MASK | ...)

#define SERIAL_PORT_INDEX(port_id) BITCOUNT((SERIAL_PORTS_USED) & ((port_id) - 1))

index = SERIAL_PORT_INDEX(SERIAL_USART1_ID);
```
This is quite useful when building conditions - just define mask for all interesting port groups:
```
#define SERIAL_USARTX_MASK (SERIAL_USART1_ID | SERIAL_USART2_ID  | SERIAL_USART3_ID)

#if SERIAL_PORT_USED & SERIAL_USARTX_MASK
// some usart port is enabled for target
#endif
```

**Comment by readerror67** [comment]
Are the indexes even necessary? If VCP is defined it will always be 0 anyways..
https://github.com/cleanflight/cleanflight/blob/master/src/main/io/serial.c#L56-L59

**Comment by larryho5** [comment]
Ok, then i commit the "mapping VCP to MSP_PORT when resetting defaults" first.

**Comment by larryho5** [comment]
I think this

**Comment by larryho5** [comment]
#define SERIAL_VCP_ID (1 << 0)
#define SERIAL_USART1_ID (1 << 1)
I think this will not work, since the number is already mapped to MSP, changing this number will cause the current version of configurator not working.

**Comment by ledvinap** [comment]
@larryho5 : It may be possible to generate mask from SERIAL_PORT_* constants, if they are '#define' instead of 'enum'. Preprocessor is required to do arithmetic in longest width supported on target, so 64 bits are available.
It is questionable if it is worth the effort ...

**Pull request closed without merging**
