### PR TITLE
Gyro Soft LPF Rework // Filter rework

### PR DESCRIPTION
**Pull request by borisbstyle**
New way of gyro soft filtering. Dynamic FIR filter thanks to @digitalentity 

Removed pterm_cut_hz
Added yaw_pterm_cut_hz
Removed 3 point moving average when soft filtering enabled

@hydra 
This is for review, best to merge after gyro sync stuff is merged

At the moment all disabled by default, but we can change defaults for the users to have simillar performance to "betaflight"

### CODE REVIEW

**Comment by digitalentity** [comment]
@borisbstyle this FIR can also be applied to accelerometer and eliminate the need for acc_lpf in IMU.

**Comment by borisbstyle** [comment]
@digitalentity 
Once it's merged its in the planning to add another PR for that or you can add it

**Comment by digitalentity** [comment]
Good, good!

**Comment by hydra** [comment]
@digitalentity ready for the next filter PR when you have it ready.  Keep us posted.

**Comment by digitalentity** [comment]
Thanks.

That scheduler is not going to be fast. It's too much of a change and it
does not work well with looptime=0. It starts to slow down other tasks,
like receiver processing.

Stay tuned :)

**Pull request merged**
