### PR TITLE
For discussion - split serial_msp.c into serial part and protocol part

### PR DESCRIPTION
**Pull request by martinbudden**
This PR splits `serial_msp.c` into a much smaller `serial_msp.c` which only includes the serial specific items and `msp_protocol.c` which contains all the actual MSP protocol, with its dependencies on serial removed.

The primary motivation for this is to make it much easier to write tests for the MSP protocol, but a secondary motivation is to allow MSP to be implemented over another carrier, in particular I2C. This would allow future OSD other devices to connect via I2C and help solve the lack of serial ports problem.

[Note this PR is for discussion only, not yet ready to be merged.]

### CODE REVIEW

**Comment by jflyper** [comment]
+1
Oh, this was going to be my next project:)
I actually have started to quickly hack an i2c capable osd by combining uminimosd and SC16IS740 I2C/SPI to UART bridge. All I need now is then mspI2cProcess(), and may be an interrupt line?

**Comment by martinbudden** [comment]
I've now virtualised the callbacks from `map_protocol.c` into `serial_msp.c`. This means that it should be straightforward implement MSP over I2C. All that is required is to create a `mspI2CProcess` (which can be loosely based on `mspSerialProcess` in `serial_msp.c` and create a new `taskHandleI2C` and hook it into the scheduler.

**Comment by ledvinap** [comment]
@martinbudden : 
Still working on my version

My idea is to completely separate command handling from command transfer.
From point of MSP handling, command may be abstracted to:
- `int cmd` - use larger command, let driver handle wire encoding (reserved codes for 2 byte command may be transparent from handling)
- (direction, but it is mostly implicit)
- error status / error code. Current implementation uses only 1 bit and no data on error, by we may use error codes easily (mapping nonzero error code to '!' in serial msp
- message data + length

It new protocols, it may be useful to add:
- message ID - reply is easily matched to command
- message sequence number - refuse out-of-sequence important commands / avoid executing command twice when reply is lost.

Checksum calculation, serial headers, `cmd` and `lenght` encoding framing etc can be handled in serial driver, command processing can be totally independent ..

**Comment by martinbudden** [comment]
@ledvinap , I look forward to having a look at it.

One comment - I think the checksum, framing etc are part of the MSP protocol and so shouldn't really be done in the serial driver. Or are you talking about the ability to add a new protocol using the existing `serialize/read` code?

**Comment by ledvinap** [comment]
I want to separate MSP protocol (frame format, synchronization, ...) from MSP command handling command IDs and strucutre of data messages).
Adding new transport protocol will be easy (I am planning extensible multiplexed protocol with blackbox, msp, possibly CLI)

**Comment by ledvinap** [comment]
It will take some time .. 
basic idea is :
```
typedef struct sbuf_s {
    uint8_t *ptr;          // data pointer must be first (sbuff_t* is equivalent to uint8_t **)
    uint8_t *end;
} sbuf_t;

void sbufPutU32(sbuf_t *dst, uint32_t val);
void sbufPutData(sbuf_t *dst, const uint8_t *data, int len);

uint8_t sbufGetU8(sbuf_t *src);
uint16_t sbufGetU16(sbuf_t *src);
uint32_t sbufGetU32(sbuf_t *src);

int sbufBytesRemaining(sbuf_t *buf);
uint8_t* sbufPtr(sbuf_t *buf);
void sbufAdvance(int size);

typedef struct {
  sbuf_t buf;
  int command;
  ...
} mspPacket_t;
static void serializeSDCardSummaryReply(mspPacket_t *dst)

static bool processOutCommand(mspPacket *cmd, mspPacket_t *reply)
static bool processInCommand(mspPacket_t *cmd)
```


```

**Comment by jflyper** [comment]
@ledvinap 
So it would not be 'Serial' protocol any more; MMP (Multiwii Messaging Protocol) or CFMP ?:)

`
typedef struct sbuf_s {
    uint8_t *ptr;          // data pointer must be first (sbuff_t* is equivalent to uint8_t **)
    uint8_t *end;
} sbuf_t;

typedef struct {
  sbuf_t buf;
  int command;
  ...
} mspPacket_t;
'
Ah, just like any other networking code.

**Comment by hydra** [comment]
full agree with splitting command handling out and making the msp core re-usable.  ideally there should be an implmentation of the MSP core that doesn't know how or were it's being used so it can be reused.

**Comment by ledvinap** [comment]
@2062

**Comment by ledvinap** [comment]
My take on this is in #2062

**Comment by martinbudden** [comment]
Closing, superseded by https://github.com/cleanflight/cleanflight/pull/2062.

**Pull request closed without merging**
