### PR TITLE
add Larson Scanner (Cylon effect) to possible led configurations

### PR DESCRIPTION
**Pull request by ddb**
This set of changes adds the ability to display a "Larson Scanner" on the LED Strip.

The Larson Scanner is named after Glen A. Larson who was a television producer and writer. Most notably he produced the original Battlestar Galactica and Knight Rider, both shows featuring machines with a red "eye" that would scan back and forth.

The set of LEDs that are tagged as being part of the Larson Scanner will have the brightness of the LEDs modified in sequence, producing the effect of a scanning "eye."  The color is specified by the color specifier (or by any other function that produces a color). It is possible to have a larson scanner that changes color with the ARM state, by combining the ARM function with the Larson Scanner function. It is possible to create any number of effects.

### CODE REVIEW

**Comment by ddb** [comment]
I have submitted a cleanflight-configurator pull request to handle the configuration side of this new feature.

**Comment by hydra** [comment]
Cool, I will merge some other LED related PR's at the same time as I test this.

**Comment by ddb** [comment]
I am looking into making the scanning speed configurable, but it looks like to do that properly I have to modify MSP and break configuration compatibility, and I'm not sure I want to do that with my current level of comfort with the codebase.

**Comment by skaman82** [comment]
@hydra this is so cool! sadly it got swept under the rug...

**Pull request closed without merging**
