### PR TITLE
Building Cleanflight to run on PC with X-Plane simulator

### PR DESCRIPTION
**Pull request by DreamNik**
I'm writing support for running Cleanflight on PC with X-Plane simulator.

This would allow verify new code behavior on PC, like new PID controllers, waypoints and other stuff which requires in-flight testing.

Currently i was able to compile base Cleanflight sources for PC with minimal modifications.
I've created simple GUI with LED and Display emulation.

I've implemented simple bidirectional interface with X-Plane.

Currently supported (simulated):
-ACC sensor
-GYR sensor
-GPS
-motors
-EEPROM
-Serial ports (redirect to real/virtual)
-PPM input (from WINAPI joystick)
-ADC

Requirements for building:
- Windows OS (joystick support currently via WINAPI)
- Qt Creator + Qt Framework (MinGW)

To build, just open "x_plane/x_plane.pro" file with Qt Creator and run it.

I'll upload detailed instructions later, if there any interest in this.

### CODE REVIEW

**Comment by digitalentity** [comment]
Cool! Exactly what I need to test and debug navigation for airplanes.

**Comment by marksev1** [comment]
Great stuff. I have X-plane 10.36 installed on my PC. Is this like "hardware in the loop" testing?

**Comment by digitalentity** [comment]
It's more like software in the loop. No actual hardware is being connected, cleanflight controller is emulated for x-plane.

**Comment by marksev1** [comment]
Digitalentity will you pull this to a "debug-oriented" branch of your nav-rewrite fw?

**Comment by DreamNik** [comment]
I've created somewhat detailed instructions for building, running and configuring.

**Comment by DreamNik** [comment]
Ok, the bare-minimal bundle is finished.
The quadrocopter model behavior is not "natural", but it works.

**Comment by DreamNik** [comment]
Does anyone have suggestions or feedback on this?

**Comment by sytelus** [comment]
Just wondering what is the status of this... Is this usable? Can this be merged to master? This looks very cool and would be great to see this addition in cleanflight.

**Comment by sytelus** [comment]
Hi @DreamNik, I'm really interested in running CleanFlight in SITL mode. Have your changes merged? Is it working now? I would appreciate any pointer docs.

**Pull request closed without merging**
