### PR TITLE
Fix Blackbox header truncation by using new serial Tx buffer freespace API

### PR DESCRIPTION
**Pull request by thenickdude**
Uses the API that will be introduced in #1108 to make Blackbox aware of Tx buffer free space during Blackbox header writing. This allows Blackbox to avoid overrunning the serial Tx buffer space, which now allows logging at very slow baud rates such as 19200 over softserial.

In general this should fix reported problems with Blackbox headers becoming truncated while the rest of the log is fine.

### CODE REVIEW

**Comment by ledvinap** [comment]
After removing blackboxWriteChunkSize, what prevents too fast header output? openlog can't always keep up even on 115200 ...

**Comment by thenickdude** [comment]
Really, which MicroSD card are you using? This code tests fine here with 19,200 baud or 250,000 baud at looptime ~325. Sandisk Extreme 16GB

**Comment by ledvinap** [comment]
I use 8GB Sandisk ultra and there is occasional broken frame.
Old code was limiting header speed to make sure headers are intact.
Headers are about 1400 bytes now, that is larger than openlog buffer. What happens when long erase occurs after first header block at 256k?
Testing won't help here unless you accept some (low) percentage of errors as 'by design' state ...

**Comment by thenickdude** [comment]
Okay, after reviewing the maximum write latency of some of these cards, I agree, this needs reworked to include a maximum speed limit.

**Pull request closed without merging**
