### PR TITLE
Docs: Added detailed steps for flashing

### PR DESCRIPTION
**Pull request by cmavr8**

### CODE REVIEW

**Comment by hydra** [comment]
this isn't quite right.  it doesn't (yet) apply to all boards. there's no need to start with it disconnected and no need for full chip erase since that will erase settings when upgrading.

**Comment by hydra** [comment]
there should also be a note to see the board specific flashing instructions too probably.

**Comment by cmavr8** [comment]
Ok, sorry. Got ahead of myself. I'll correct and re-request merge. Please deny this :)

**Comment by hydra** [comment]
just add new commits to this PR and squash all the commits into one using git rebase and then force push the new commit to the PR branch.  if you can't squash then i can do it but please try.  no need for new PR.

**Comment by cmavr8** [comment]
Done! Please take another look and let me know if another round of corrections is needed.
Thanks of the feedback and instructions!

**Comment by hydra** [comment]
Merged, please review ab30a208e19c36531ef0445ad5c8f3cfe311acfd

**Comment by hydra** [comment]
and 02d8313437576b1283ad0339359497925aa2f36 - oops!

**Pull request merged**
