### PR TITLE
Update serial_msp.c

### PR DESCRIPTION
**Pull request by tricopterY**
Enhanced MSP_RC_TUNING and MSP_SET_RC_TUNING. 
Configurator's PID Tuning tab must be enhanced to use this update.
Agnostic if older versions of Configurator are used.
Addresses cleanflight/cleanflight-configurator#59.

### CODE REVIEW

**Comment by hydra** [comment]
yeah, this is much requested and since we're changing this msp command for this api version it makes sense to do this now.

**Comment by hydra** [comment]
For future commits please say what the commit is doing in the commit message rather than just `Update <filename>`

**Comment by hydra** [comment]
Same goes for the pull request title too :smile:

**Comment by tricopterY** [comment]
Great - Noted. Sadly, I have a bunch of PRs with the same oversight - bear with me, I will get there. Thanks.

**Pull request merged**
