### PR TITLE
Implement ALIENWIIF3 target and documentation updates

### PR DESCRIPTION
**Pull request by MJ666**
Adding board ID's for ALIENWIIF1 and ALIENWIIF3
Update documentation

We actually testing both variants of the AlienWii32. More details can be found in the "Board - AlienWii32.md" file.

### CODE REVIEW

**Comment by hydra** [comment]
Hi MJ666.  If you don't mind i'd prefer to hold off merging this until the boards are out there.

I have been having similar thoughts with regards to the Naze32Pro and MassiveF3 targets, and some of the other targets like the Olimexino and Chebuzz F3.  At the moment supporting boards and sheilds that are not a) popular, or b) commercially available is just code that gets in the way.

I'm undecided as yet, but I'm guessing there is no hurry to merge this until your boards are ready to ship.

**Comment by MJ666** [comment]
The support of the two AlienWii targets don't create much code overhead since they mostly share the code with the NAZE or the SPARKY targets. It also will not affect the binaries for other targets. For now it would be fine to wait for a while with the merging. Our goal would be to have this integrated in Cleanflight when the boards are getting more widely avialable.

**Comment by hydra** [comment]
Agreed.

**Comment by hydra** [comment]
Hi @MJ666 

So, tonight I am also working on a new F3 based target and will merge in the code even though it's not commercially available.  I note that I am back-tracking on my previous comment above here so I just wanted to give you the reasons why it's now appropriate:

1. makefile cleanup
2. conditional usb vcp support
3. replaces legacy MASSIVEF3 target
4. various target.h cleanups
5. other cleanups found along the way.

Once my changes are in I'll be happy to merge in your change, however I would prefer it in the AlienWiiF3 was not based on a variant of the sparky and that it is a target in it's own right.

During the implementation of the SPARKY support I have tried to keep all target-aware code (e.g. `#ifdef SPARKY`) out of the codebase.  There are a couple of, currently, unavoidable places but they will be cleaned up eventually.

Can you make some additional commits to this PR once i've pushed my changes?

**Comment by MJ666** [comment]
Hello @hydra 
nut sure what you mean with additional commits? I can rebase again. My approach to reuse most of the NAZE and Sparky target was to avoid lots of duplication. since both AlienWii controller using very much the same hardware layout. The impact of the changes is very minimal. likely future sparky updates of the code will affect the AlienWii F3 in the same way and will not hurt

**Comment by MJ666** [comment]
Rebased.

**Comment by MJ666** [comment]
Rebased again. Any new feedback here?

**Comment by hydra** [comment]
Hi MJ666. I would prefer a new non-variant target since I don't have your new hardware to test and that restricts me from making changes since I will never know if a commit breaks the build for your board.

  I don't mind a target.h and duplication there since that is the right place to configure the hardware layout.

Your thoughts?

**Comment by MJ666** [comment]
I see relative low risk to break something on our targets since you already removed almost all of the sparky dependencies from other code. If you prefer this way I can go ahead to make ALIENWIIF1 and ALIENWIF3  an individual target.

**Comment by hydra** [comment]
I think this is only needed for the F3 target, the F1 target can stay as-is.

**Comment by MJ666** [comment]
Make ALIENWIIF3 an independent target and rebased.

**Comment by hydra** [comment]
I squashed all the commits and merged the code.  Please can you build the code from development branch and make sure you're happy with it.  If there's any issues please re-open this.

**Comment by MJ666** [comment]
All is fine thanks.

**Comment by MJ666** [comment]
Please can we also release the related Hex for the F3 with future releases. Thanks.

**Pull request closed without merging**
