### PR TITLE
ibusFramePosition update

### PR DESCRIPTION
**Pull request by andrew-milovidov**
ibusFramePosition was not set to zero after finishing frame

### CODE REVIEW

**Comment by ledvinap** [comment]
What's wrong with current version? 
It waits for interframe pause to sync to next frame.

**Comment by andrew-milovidov** [comment]
I found that in some reasons frames could be lost. Besides it, it's more safe.

**Comment by ledvinap** [comment]
As for safety - the problem with current code is that byte received after frame without enough delay will set ibusFrameDone flag again, processing the frame multiple times. 
You fix may increase potential for race conditions (there is delay between clearing done and resetting position). Also more state than necessary is shared.

Waiting for delay+sync char as frame sync is probably good idea, but it should be implemented correctly.
Setting ibusFramePosition to 'wait-for-sync' value when packet is received and ignoring all chars till interframe gap may handle most cases.

**Comment by andrew-milovidov** [comment]
There is no race condition. Technically ibusFramePosition was also static variable. You must clear the array index var after the job is done. If flysky will decrease sync pause (they can and we will know it a post factum), this index var will be out of range. In case of setting zero to ibusFramePosition  ibusFrameDone will not be setting many times during sync pause.

**Comment by hydra** [comment]
@ledvinap @andrew-milovidov can we come to some agreement here please so we can get this completed.  Since I don't have test equipment here I can't verify the fix.

Perhaps write a unit test that simulates the conditions you are experiencing and what the expected behavior should be when it occurs?

**Comment by andrew-milovidov** [comment]
I found this potential trouble while making ibus-to-pwm converter based on this code. And I found hard faults because of out of range pointer.
I can test these changes on sp f3 and fs-ia6b/ia10.

**Comment by hydra** [comment]
@andrew-milovidov please can you test this on your equipment and report back?

**Comment by hydra** [comment]
I'm going to merge this. I don't like this situation but some other guys have also added iBus telemetry so between this PR and the iBus telemetry we should get some good reports as to whether it works OK or not.  If there's issues they can be raised as new bugs.

**Pull request merged**
