### PR TITLE
Luxfloat more precision on Tuning

### PR DESCRIPTION
**Pull request by borisbstyle**
Change needed to get real PID's in configurator for luxfloat. No need to restrict us to 8bit integer.

image

### CODE REVIEW

**Comment by hydra** [comment]
Boris, what do you think about removing the old INT based PID storage and using floats everywhere in the MSP for ALL pid controllers?

For a long while now the int vs float pid value storage has been a pain, i think while it may add a bit of conversion code it would remove a lot of conditional code thoughout the project?

See all usages of `IS_PID_CONTROLLER_FP_BASED`

This PR seems like a good place to start tackling the problem.

**Comment by borisbstyle** [comment]
@hydra I will have a look. It sounds like a good idea to me. I also think only one PID bank should be enough for them all. No need to separate them.
The floats can be converted to int anyway in the integer based pid controllers.

**Comment by borisbstyle** [comment]
@hydra 
Going to check this. But there is one thing. Different PID controllers have different "default" values. If we would move them all to same pid bank people will get very dangerous defaults if the same defaults are used on luxfloat like PID0 for example. That's my only concern with this to not do it.

**Comment by leothehuman** [comment]
Can we use scaling factors to default values from, let say, 1 in every controller? Like, put defaults into the controllers and tune adjustments?

**Comment by borisbstyle** [comment]
@leothehuman What exacty do you mean? To scale default values for each pid controller?

**Comment by leothehuman** [comment]
I mean, let's use 1.0 as a default value for everything in the UI. Each pid controller will then scale that 1.0 to its own current default. For example, let's say, default roll P is currently 4.5 for pid 0. Let's define roll_P_scale in pid 0, which is equal to 4.5 and set default roll_P to 1.0 for each pid controller in UI. When we actually start flying on the pid 0, it will take our 1.0, multiply it by 4.5 and will get its default value. Let say I want to tune it and bring it down to 0.8. pid 0 then takes my value, multiplies it by 4.5 and gets 3.6.

**Comment by joshuabardwell** [comment]
What's the benefit of that approach?

**Comment by leothehuman** [comment]
All the magic numbers will be held with the pid controllers and will have nothing to do with config code. It will be easier to reset to defaults, even manually.

**Comment by bdoiron74** [comment]
Agreed.

**Comment by jaapp** [comment]
@leothehuman If I understand you correctly you are suggesting to index the PID-gains. So (for example) a D-gain of 1.5 in PID0 would correspond with a D-gain of 1.5 in PID1.

The only benefit I see is that you know that the default is 1. For the rest I only see disadvantages. It breaks backwards compatibility. Everybody will have to retune. Every documented PID-gain on the internet will become unusable. Indexing the PID-gains still won't make it possible to switch PID-controller without retuning. You can get rid of the different default values in the code, but now you'd still have to store a index value somewhere.

**Comment by borisbstyle** [comment]
I will close this one as I will work on another PR in the near future to save all pids in the same PID bank.

**Comment by thenickdude** [comment]
Note that storing PIDs as floating point values for all PID controllers will require that they be converted from floats back into integers on every PID evaluation for the non-FP controllers. This isn't a free operation.

**Comment by borisbstyle** [comment]
Yeah I am still thinking if there is a way to do it. My current conclusion is that it's better to scale luxfloat to integers.

**Comment by leothehuman** [comment]
There's no need to convert every time, it can be done on arm and after in-flight adjustments.

**Comment by thenickdude** [comment]
You can also change PIDs while armed using MSP.

**Pull request closed without merging**
