### PR TITLE
Fix Hott telemetry timing issue

### PR DESCRIPTION
**Pull request by Pierre-A**
This is a proposal to solve issue #1413.

### CODE REVIEW

**Comment by ledvinap** [comment]
The test logic is a bit wrong - the workaround is necessary on UART, so it would be better to check for UART ports (but that means more values to check)

**Comment by Pierre-A** [comment]
Not sure this would make a difference as there are only UART's and Softserial ports (and VCP but this port is not concerned here).

**Comment by ledvinap** [comment]
Yes, the result will be identical.

**Comment by ReganGTX** [comment]
Please take me off the Mailer

**Comment by andymac4182** [comment]
@ReganGTX then unsubscribe from notifications. It is on the right of the pull request.

**Comment by Pierre-A** [comment]
**@ledvinap**, this one is for you :wink:  ,  you're right, it's "Clean"er

**Pull request merged**
