### PR TITLE
Enable battery monitoring for Sparky and ALIENWII F3

### PR DESCRIPTION
**Pull request by MJ666**
Voltage monitoring is tested for an AlienWii32 F3 prototype. For Sparky it should also work. Documentation is updated accordingly.

This is related to issue #523

### CODE REVIEW

**Comment by JohnieBraaf** [comment]
Looks good. I will see if I can get it working on the Sparky.

Assuming you use an attopilot sensor, isn't it better to use PWM9 and PWM10 on the Sparky. As they both seem to have a 10K resistor on the board diagram (PA1, PA4)? 

From the attopilot datasheet:  
"You may use this sensor directly with a 5V ADC, however some resolution will be lost relative to a 3.3V 12 bit ADC unless a higher bit ADC is used."

http://dlnmh9ip6v2uc.cloudfront.net/datasheets/Sensors/Current/DC%20Voltage%20and%20Current%20Sense%20PCB%20with%20Analog%20Output.pdf

**Comment by MJ666** [comment]
The AlienWii F3 has only the voltage monitoring. The required voltage divider is alredy build in to the board. The reason why PWM8 and PWM9 are used is explained in #523.

**Comment by hydra** [comment]
I had the chance to test the Sparky code on a new V-Tail build tonight, works great.  Making the voltage divider using my usual resistor combinations didn't work due to the inline resistor on the VBat pin so I documented what worked for me in this commit: 54419ef97c722c900b199e77fb221d0ff8db6053

**Comment by JohnieBraaf** [comment]
Yes, also works fine out of the box with the attopilot sensors. Great work!

**Pull request merged**
