### PR TITLE
tests: fix the tests when building with GCC

### PR DESCRIPTION
**Pull request by nzmichaelh**
Note that travis-ci builds with clang, as Precise comes with GCC 4.6 and GCC 4.6 doesn't support designated initialisers.

### CODE REVIEW

**Comment by MauroMombelli** [comment]
gcc (GCC) 5.1.0 and previous version work fine building test even without this commit.

What version and what error you get?

**Comment by nzmichaelh** [comment]
4.9 which is the default with Ubuntu 15.04. Note that designated
initialisers were introduced in G++ 4.7 but were limited (eg by not
allowing holes, which this patch fixes) through at least 4.9.

**Comment by MauroMombelli** [comment]
oh, sorry, deleted my message meanwhile as found this out, thanks anyway!

**Comment by hydra** [comment]
Thanks for the pointers, i cleaned up the issues in 0df22f80496038a48a22edc7ce820e5d1e0121d3 and 704dcf46bae4495e9a60ff864acdef3a2f64bf36

**Comment by hydra** [comment]
And also in dcc54a9aec03c41eee1bbb8d158ab3b8a7dc72f4

**Comment by DarkVegetableMatter** [comment]
Please put pthread back in at line 30 of the makefile 

I am still have problems building

unit/rc_controls_unittest.cc:248:5: sorry, unimplemented: non-trivial designated initializers not supported

**Comment by ledvinap** [comment]
maybe extern "C" { }; will help with this? designated initializers are fully supported in C ..

**Comment by DarkVegetableMatter** [comment]
nope

**Pull request closed without merging**
