### PR TITLE
Improve BOX serialization

### PR DESCRIPTION
**Pull request by ledvinap**
Use loops to move bits instead of crazy expression. Future extension shall be easier. Saves about 240b of flash

```
  text	   data	    bss	    dec	    hex	filename
 121740	    272	  14544	 136556	  2156c	./obj/main/cleanflight_NAZE.elf
 121412	    272	  14536	 136220	  2141c	./obj/main/cleanflight_NAZE.elf
                           -336

 122356	    440	  13444	 136240	  21430	./obj/main/cleanflight_CC3D.elf
 122124	    440	  13444	 136008	  21348	./obj/main/cleanflight_CC3D.elf
                           -232

 114696	    448	  13332	 128476	  1f5dc	./obj/main/cleanflight_SPARKY.elf
 114464	    448	  13324	 128236	  1f4ec	./obj/main/cleanflight_SPARKY.elf
                           -240
```

### CODE REVIEW

**Comment by ledvinap** [comment]
Rebased ... this code did not change for months ;-)

**Comment by hydra** [comment]
Seems to be some unit tests failures. Can you take a look?

**Comment by hydra** [comment]
Will merge once the unit tests are passing.  Good to be getting rid of that express, I'd noticed that was getting larger when I did some other changes a while ago. The solution is nice.

**Comment by ledvinap** [comment]
OK, ready now ...

**Comment by ledvinap** [comment]
But ... some testing will be nice ..

**Comment by ledvinap** [comment]
BOXGTUNE is copied both from FLIGHT_MODE and rcMode. The operation is logical OR, so the result is correct .. but it may be fixed with mask of FLIGHT_MODEs to copy ...

Is it worth the trouble? Or just comment it?

**Comment by hydra** [comment]
Will target this for 1.13.0

**Comment by ledvinap** [comment]
@hydra: Can you look at this? It would be nice to merge this before MSP changes ...

**Comment by ledvinap** [comment]
BTW: is `activeBoxIds` order important? Or is it enough to match `MSP_BOXNAMES`, 'MSP_BOXIDS' and MSP_STATUS_EX ?

**Comment by martinbudden** [comment]
@hydra, I second this - it would be good to get it in sooner rather than later.

**Comment by hydra** [comment]
superceded by #2075.

**Pull request closed without merging**
