### PR TITLE
New config fields and bugfixes for LED config restore

### PR DESCRIPTION
**Pull request by NightHawk32**
This corresponds to configurator PR no 294: https://github.com/cleanflight/cleanflight-configurator/pull/296

### CODE REVIEW

**Comment by hydra** [comment]
Not keen on `MSP_RC_CONTROLS` - it's a bit generic.  When things are generic they often change frequently over time.  See `MSP_MISC` for an example of this nastyness.  Compare it to 

I think in this case MSP_RC_DEADBAND might make sense, and then remove `alt_hold_fast_change` - that way nothing will ever go in there other than deadband configuration and it will be less likely to change.

Changing API's = developer pain.

**Comment by hydra** [comment]
The changes also break the CJMCU target.  It doesn't fit in the flash anymore.  Can't merge until this is resolved.

**Comment by hydra** [comment]
I have cherry-picked the new MSP commands and replaced MSP_RC_CONTROLS with MSP_RC_READBAND.

**Comment by hydra** [comment]
closing, see #1584 instead.

**Comment by NightHawk32** [comment]
@hydra you are right MSP_RC_DEADBAND make much more sense.
You can clearly see the pain of changing APIs in the configurator, the migration of old backups got pretty complicated, so we should avoid that.

**Pull request closed without merging**
