### PR TITLE
split PID inflight adjustments for pitch and roll

### PR DESCRIPTION
**Pull request by jdn-za**

### CODE REVIEW

**Comment by thenickdude** [comment]
I think Pitch & Roll could probably share the same code in `applyStepAdjustment` by using an "axis" variable to switch between the two target values.

**Comment by nekwebdev** [comment]
This is a much needed change, thanks for the commit!

I really hope this makes it into the next release :+1:

**Comment by dkisselev** [comment]
@jdn-za have you made the appropriate changes in the Configurator too? https://github.com/cleanflight/cleanflight-configurator

**Comment by hydra** [comment]
I did this in a recent commit to 1.9.0RC.  I had missed this PR.  My implementation cuts down on the duplication found in this by following though in the switch statements.  Please see c174a52ebeaa7f5edbf5e3186db0b2ef02d24cea

The development configurator branch has also been updated and so have the corresponding docs.

**Pull request closed without merging**
