### PR TITLE
Add "servo" CLI command to get/set servo conf, and include in dump

### LINKED ISSUE #468: CLI Dump does not save servo information
I believe the CLI Dump does not save the servo channel and rate % information of set as part of the servo_tilt functionality. I had the issue going to 1.7 both on a naze32 and a sparky. Can someone verify?

### PR DESCRIPTION
**Pull request by thenickdude**
Sample dump output:

```
# servo
servo 0 1020 2000 1500 30 -1
servo 1 1020 2000 1500 30 -1
servo 2 1020 2000 1500 100 -1
servo 3 1020 2000 1500 100 -1
servo 4 1020 2000 1500 100 -1
servo 5 1020 2000 1500 100 -1
servo 6 1020 2000 1500 100 -1
servo 7 1020 2000 1500 100 -1
```

Fixes #468

### CODE REVIEW

**Comment by thenickdude** [comment]
Looks like CJMCU doesn't quite fit into flash, I'll see if there's anything that can be trimmed down.

**Comment by MJ666** [comment]
All CJMCU ' s i have seen have also 128 flash memory. You only need to swith to 128 manualy during initial flashing with STM demo loader. Later the GUI will not care at all.

**Comment by thenickdude** [comment]
Really? Maybe in that case we can switch to the 128kB linker script so we can take advantage of it. @hydra can you confirm with your CJCMU?

**Comment by MJ666** [comment]
I was involved in the CJMCU development for BF and after reducing the code initially we added more features back again later.

**Comment by hydra** [comment]
We can disable this on the CJMCU target if needed in the future since the CJMCU target only supports quad mixer anyway.

**Pull request merged**
