### PR TITLE
Fix wrong declaration for baro parameters in CLI

### PR DESCRIPTION
**Pull request by Pierre-A**
MODE_LOOKUP was affected to baro parameters (*baro_noise_lpf* , *baro_cf_vel* , *baro_cf_alt*) while they are float and so **should stay** in DIRECT mode with minmax (0 , 1).

### CODE REVIEW

**Comment by Pierre-A** [comment]
**/@hydra**, this fixes wrong declaration (in PR #1488) commit 238b3c3   (lines 585-586-587 in serial_cli.c).
I was on the wa

**Comment by hydra** [comment]
doh!  Good spot!  thanks @Pierre-A 

Your PR contails some other unrelated commits. I will cherry-pick the fix now.

**Comment by Pierre-A** [comment]
yes I know these unrelated should not be there.. I did some wrong github command somewhere...

**Comment by hydra** [comment]
merged the single commit 26b1d8f631eb0eb483235770bae5f63ec9a25349

**Comment by Pierre-A** [comment]
OK, thanks

**Pull request closed without merging**
