### PR TITLE
Improved tricopter yaw for PID controller 0 (MultiWii)

### PR DESCRIPTION
**Pull request by SteveAmor**
I have been working with David Windestål to improve the yaw error control for tricopters and this is the result. Enabling the feature NEW_TRICOPTER_YAW, via the CLI, it will remove the yaw gyro smoothing in imu.c and, when using PID controller 0 (MultiWii), it will not reset the yaw I term if you are commanding the tricopter to yaw.  This is close to the way the KK control loop works and now provides a much better, "locked in" feel.  David has extensively test flown this modification and is extremely happy with it.

### CODE REVIEW

**Comment by SteveAmor** [comment]
I've now got unit tests working on my dev machine :-)

**Comment by SteveAmor** [comment]
I've realised this isn't a "feature". I will split this into two pull requests using " set ". One to enable/disable tricopter yaw gyro smoothing in imu.c and one always calculate the I term.

**Comment by thenickdude** [comment]
It's unlikely that we want this to be configurable because it'd split an already small category of pilots up (tricopters) into yet smaller categories and make testing and maintenance harder. If it's definitely a win for tricopters then it should probably just always be enabled. 

All just IMHO.

**Comment by SteveAmor** [comment]
Shall I reopen this PR with the modification that would make this permanent rather than configurable?

**Comment by RCExplorer** [comment]
Steve has done fantastic work helping me getting the yaw on tricopters working better. The changes he's made really made a huge difference. Especially on mini tricopters. I'm now running the fixed code on 3 machines and have a friend trying out as well. Code seems stable and the copter flies great throughout the whole flight.
Time in the air with the new code is close to 2 hours or so.
I vote to have it implemented into the code :D

**Comment by RCExplorer** [comment]
I thought I would share a little bit more how the code improved the flight characteristics on the tricopters. I've tried all 5 PID controllers and none of them really worked well with the yaw. It felt like there was a wet eel controlling the tail. Especially while flying FPV. You had to be on your toes all the time and the tail would drift, feel mushy or waggle, depending on the PID values. It was impossible to find a sweetspot.
The best way to describe it probably is that it felt like you had to fight the tail all the time. Like you were beating it into submission, but the wet eel would never give up.
The new code made it possible to stop concentrating on the tail while flying. It hold much much better. It's much easier to find the sweatspot on the PIDs, It doesn't overshoot of feel mushy. It also made the tail feel more responsive. It kind of felt like there was a slight delay before or something. The new code makes the tail feel more like it did on the KK2 board. Pretty much locked in :)

**Comment by thenickdude** [comment]
Is there a rationale for retaining the I term under high speed yaw? It seems like all this accomplishes is provides a large accumulated error which will take longer to bring to zero when you want to stop or move in the other direction. 

Have you tried #741 out? It's a series of changes intended to allow a stronger yaw response by removing or relaxing limiters that were in place. It should bring dramatic improvements in reaction time for yaw stopping and direction changing.

**Comment by RCExplorer** [comment]
No idea, but it seem to work well on the tricoter. Have not tried #741, but I wouldn't mind trying it just to compare and get a broader experience :)

**Comment by thenickdude** [comment]
If you could get a blackbox set up, it makes a huge difference on examining
and tuning the PID controllers.

**Comment by SteveAmor** [comment]
RCExplorer, I'll send you the #741 code later.

**Comment by RCExplorer** [comment]
Thank you Steve :)

**Comment by thenickdude** [comment]
So just to summarise, there are currently these changes:

- Removed yaw gyro smoothing. This was probably in there as a substitute for yaw servo output smoothing, because smoothing the input will also smooth the yaw PID output to eliminate high frequency shakes. Cleanflight actually has servo output low-pass filtering available as a feature now, so removing the input side is a good idea. But we may want people who had issues with their servo jittering to test this version. If many people find this causes a jittery servo, we may want to consider enabling output smoothing by default instead.

- Yaw "I" error term is reset when on the ground (throttle is low). This will be helpful because it will allow fairly linear control of the servo when on the ground, which is useful for testing the servo with the RC sticks. People complain about the current odd-looking "I" behaviour that causes very nonlinear control on the ground.

- Yaw "I" error term is no longer reset under high speed yaw, or under heavy yaw RC input commands. On the plus side this removes a discontinuity where the servo would suddenly snap toward the origin when the error was reset. But on the negative side, the "I" error is unhelpful during high speed yaw because it will increase the time taken to brake to a stop at the end (since that error accumulated during the yaw must be slowly brought back to zero). I wouldn't suggest merging this without blackbox evidence.

**Comment by SteveAmor** [comment]
@thenickdude: many thanks for your summary.

I've been waiting for RCExplorer to check the #741 code but he's not had a chance yet.

Removing the yaw gyro smoothing: this made minimal change to the handling but it did make a small improvement.

Yaw term "I" error term is reset when on the ground (throttle is low): I think this is actually done in mw.c on line 541 https://github.com/cleanflight/cleanflight/blob/master/src/main/mw.c#L541 but not sure it gets done every loop cycle due to it being in processRx.  So I may not need to do it.  I put it in just to make sure as I was coding this on the road.

Yaw "I" error term is no longer reset under high speed yaw, or under heavy yaw RC input commands: I removed this as it isn't in the KK2 code.  It's based on the assumption that error = angle - rccommand.

I would like to implement two

**Comment by SteveAmor** [comment]
I built an Openlog blackbox and recorded some flight data that is available here:

http://www.rcgroups.com/forums/showthread.php?t=2410014#post31575570

There are recordings for:

1.8.1 with no changes
1.8.1 with no yaw gyro smoothing
1.8.1 with no yaw gyro smoothing and always calculate I term
1.8.1 always calculate I term

**Comment by thenickdude** [comment]
Hi @SteveAmor thanks for the logs, that is some fantastic experimental data! 

From the first log it makes it look like when you release your yaw stick, there is a large oscillation on the yaw axis before it finally brakes to a stop, seeming like the tail must wag backwards and forwards like a dog, is that what you actually observe? It looks crazy.

It looks like when your craft is in an idle hover, the yaw "I" term has to max itself out (to 90) in order to maintain a solid heading. This will create an asymmetry to your yaw response, because you can't increase "I" any further in the direction that your yaw servo is currently leaning during hover, but you are able to get almost double the throw from "I" in the other direction (compared to idle).

You're currently hovering with the yaw servo getting a command around 1650 (30% deflection). If it is physically feasible, you should see an improvement in flight if you realign your servo so that the tail rotor is tilted to that direction when it is getting a *neutral* 1500 command, because you'll no longer require the yaw "I" term to provide that offset to maintain a stable hover. This should improve yaw symmetry considerably. Do all of your props spin the same way? If so, you might get the same improvement by switching one of the front ones to the opposite direction.

Here's the "stock", followed by the "always calc I" response, aligned to the point where your yaw stick returns to the origin from a full-right yaw:

stock
always-calc-i

The behaviour (for stopping) between those two looks very similar. Here's the "stock" one compared to the "no smoothing, always calc I" one:

stock
no-smoothing-always-calc-i

The oscillation looks like it converges to zero much much faster in this version with no yaw smoothing. I can't work out a cause for that though? I notice that the yaw "I" term is on the correct side of the axis to provide dampening for the first yaw overshoot.

It looks like most of the oscillation is due to the servo's response time, which appears to be about 100ms. CF notices that the yaw gyro has braked to a stop, and the tail servo is commanded to return to the neutral position, but that tail servo command doesn't take full effect till 100ms later, so there is always overshoot. It really looks like the sort of problem that a "D" term in the PID controller is designed to solve (damp the strength of the command much earlier if it looks like the error is approaching zero). Which PID controller are you using at the moment? You should see less oscillation (and so faster braking to a stop) if you reduce yaw "P" as well.

**Comment by SteveAmor** [comment]
@thenickdude I have tuned my tricopter, increased the tail servo frequency to 330Hz and reduced the looptime to 2500.  I have updated my blog http://www.rcgroups.com/forums/showthread.php?t=2410014#post31575570 and added new log files plus a config dump (openlog2.zip).

**Pull request closed without merging**
