### PR TITLE
HoTT check serial data improvement

### PR DESCRIPTION
**Pull request by Pierre-A**
The first two bytes after initial Hott request are either 0x8080 (request for binary mode) or 0x7F0F (request for text mode).
The *useSoftserialRxFailureWorkaround* bool was introduced as the first byte 0x80 is read as 0x00 (softserail timing issue somewhere ?) and so to skip this first byte. The second byte (also 0x80) is correctly read.
In order to account for other Hott receivers and allow text_mode (in preparation), this PR enlarges the test on the requestID so the workaround process is no longer needed.
(but the timing issue observed with the highest bit ot the first byte after initial hott request is not solved)

### CODE REVIEW

**Comment by johnlenfr** [comment]
Tested it works nicely like this way with GR12 - GR16 - GR24 - GR12L all in PPM or SUMD with Naze32 on fw 1.6.0 of CF.

Nice work @Pierre-A

**Comment by Pierre-A** [comment]
**hydra**,
I am ready for opening a new PR with Graupner Hott_Text_Mode.
However, the code uses this present PR≠428 for accessing text mode, so what do you think 
       shall I wait for you merging the ≠428
or 
       open a new PR including this mod ?
thanks

**Comment by hydra** [comment]
@Pierre-A the workaround will be removed when softserial is fixed.

Does the new code for the HoTT text mode code with the exiting workaround?  If so I'd rather leave the existing workaround in place for now.

If not then please update the code to say why the `requestId == 0` is needed via a `// FIXME` comment and I will merge it.

**Comment by Pierre-A** [comment]
**@hydra***, the Hott request frame sent by the Graupner TX is only two bytes.
The first of which is for differentiating between binary (0x80) and text (0x7F) modes and takes no other value.
The existing workaround ignores this byte (as 0x80 was read as 0x00) which makes the text mode detection impossible.
So the  `requestId == 0` replaces (but is equivalent to) this workaround for detecting the binary mode request BUT this allows detecting the text mode.
Since I introduced that, for coding the text mode, I had no issue with the detection between text and binary. 
Up to now, (and unless Graupner introducing new codes..) I think there is no risk with this last workaround and I don't see any other way to access the text mode.

**Comment by Pierre-A** [comment]
**@hydra**
can't add a FIXME in the code as I have no more access to the branch I deleted (too soon) a few days ago. 
So I put a note where it should be but maybe it's insufficient for you.
If so, and if there is no other way, I can open a new PR for that.
What do you think ?

**Comment by johnlenfr** [comment]
Can't wait the PR merged to tests all og this nice stuff :)

**Comment by hydra** [comment]
ok, will merge this now @Pierre-A

**Pull request merged**
