### PR TITLE
Added information about TPA rate.

### PR DESCRIPTION
**Pull request by azaitsev**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
So, for every 1% throttle after the TPA breakpoint, P is reduced by the TPA rate.

I think it could be a little more clear.

**Comment by hydra** [comment]
Merged, will add another commit to clarify.

**Comment by NullVoxPopuli** [comment]
Thanks. :-)

**Comment by hydra** [comment]
Done, see 07ff844725ea7aae3e2a92e3f78ec2745d6b7cf1

**Comment by NullVoxPopuli** [comment]
Sounds good!

**Pull request merged**
