### PR TITLE
Fixes #316: better arithmetics for FrSky CELL voltages, VFAS battery vol...

### LINKED ISSUE #316: Increased Vbat resolution and calibration accuracy
Vbat resolution is current 0.1V and the accuracy of the reading gets worse when sent via FrSky telemetry.  I am seeing 0.2V resolution jumps in the Vbat value in OpenTX. The accuracy of the Cell value sent is even worse as it doesn't seem to be rounded properly,  so 11.0v sends a cell value of 3.6v instead of 3.7v.

Would there be any issues working in millivolt steps for Vbat? 

Also an increase in the 110 Vbat scale factor would enable finer voltage calibration if increased to 1100. Frsky voltage values could be properly rounded and sent at max precision for that particular field.

### PR DESCRIPTION
**Pull request by projectkk2glider**
...tage send with other ID that allows 0.1V resolution

Compiled and tested on my Flip32+ board with 2S battery.

Closes #316

### CODE REVIEW

**Comment by dave-pitman** [comment]
Thank You!

**Comment by hydra** [comment]
Is this specifically for OpenTX or does this also apply to the displays that FrSky sell too?

**Comment by projectkk2glider** [comment]
@hydra You are right, I forgot about the older systems (like FrSky display), they won't work with the new ID. There are two options here:
* Add a new configuration option to Cleanflight and use its value to choose what to send for VFAS (the old way or the new way). This is my preferred solution.
* Or send first the VFAS value the old way and then immediately with the new ID. This way the OpenTX will (mostly) use the more precise VFAS value with the new ID. There could be minor side effects (in OpenTX) if other parts of the code trigger between parsing of the old and the new VFAS values and older value with poorer resolution could be used for some data points of telemetry log.

**Comment by projectkk2glider** [comment]
The last two commits were not tested on actual hardware. Since I am new to the project, I might forgotten something, please check carefully.

**Comment by projectkk2glider** [comment]
@ledvinap how about now?

**Comment by ledvinap** [comment]
Looks very good. 

just minor notes:
- Did you check ID_VOLTAGE_AMP units?
- eeprom version needs bump

**Comment by projectkk2glider** [comment]
>Did you check ID_VOLTAGE_AMP units?

If you mean on OpenTX, then yes, I've also tested that change on my hardware.

**Comment by dave-pitman** [comment]
I would be happy to try the firmware if you provide a .hex.   I'm sorry if it is possible to compile it myself from your repo.  I don't know the steps to do that.

**Comment by maca55** [comment]
@projectkk2glider Awesome work! Thanks very much. This commit is very welcome and much appreciated. I'll try to test it tonight if it doesn't get automatically merged.

As requested in #316, I believe we should be using 0.01V (or even 0.001V) steps for VBAT internally in Cleanflight so that when the individual cell voltage is calculated we get a 0.003V (for a 3 cell) resolution which matches closer to what FrSky Telemetry and openTX could be displaying for cells. Currently VBAT is rounded to 0.1V  and this value is divided by cell count giving 0.03V steps. 

eg) Battery voltage of 10.749V (3.583V per cell) will now give a VBAT of 10.7V and display as 3.56V per cell (or 3.57 if rounding was used) on openTX - a **0.023V error**.

However if 0.01V was used for VBAT then 10.749V (3.583V per cell) would give a VBAT of 10.74V (rounds down by 0.01V when the ADC average value is truncated rather than rounded). This will be displayed as 3.58V per cell in openTX - a **0.003V** error.

The Cleanflight SPORT telemetry code also make good use of the 0.01V VBAT resolution. Instead of doing this:

            case FSSP_DATAID_VFAS       :
                smartPortSendPackage(id, vbat * 83); // supposedly given in 0.1V, unknown requested unit
                // multiplying by 83 seems to make Taranis read correctly
                smartPortHasRequest = 0;
                break;

**Comment by tracernz** [comment]
@maca55 There is little point in having more significance than the ADC is capable of measuring. The errors you mention are similar or smaller than the accuracy of the ADC + tolerance of the divider resistors. If you're really that concerned about battery usage a current meter is a much more accurate way to measure it.

**Comment by maca55** [comment]
@tracernz Agree, but the ADC **is** capable of measuring 0.01V steps (.009V actually). And for a per cell voltage that equates to 0.003V steps for a 3 Cell, and close to 0.002V steps for a 4 Cell!

Tolerance of the resistors is adjusted by the VBAT_SCALE parameter. If this is increased to 1100, instead of 110, you can calibrate out any errors in the resistor values and the 3.3V Vref. Yes there is noise, but that is what the averaging of the ADC is for. 

I am already using 0.01V with rounding fixes and can now get the same VBAT value shown in openTX as I get on a Multimeter (would be even better if openTX sorted there truncation issue and displayed the extra available digits).  If it helps I can take a screen shot of a Telemetry log for a flight where I used 0.01V precision for VBAT (scaling it up by 10 before sending). You can clearly see the difference compared to a 0.1V log. It's like going from CGA resolution graphics to XGA!

Doesn't everyone want the Telemetry shown on Taranis to be precise and accurate? For the sake of a few lines of code, I really don't understand why anyone would not want to do this? Is there no spare memory available or something?

**Comment by projectkk2glider** [comment]
>I would be happy to try the firmware if you provide a .hex.

@dave-pitman for which board?

@maca55 I agree with upping vbat resolution to 0.01V, but I will let others decide if it should be implemented or not.

I still have to test the old VFAS code to see if it can be improved, since everybody reported that it was always 0.2V smaller than real value.

**Comment by projectkk2glider** [comment]
@dave-pitman hex for naze is here https://github.com/projectkk2glider/cleanflight/releases/tag/issue_316_test_1

Don't forget to `set frsky_hiprec_vfas = 1`

**Comment by projectkk2glider** [comment]
The conversion to 0.01V vbat resolution is on branch https://github.com/projectkk2glider/cleanflight/compare/projectkk2glider/issue_316_vbat_10mv

**Comment by hydra** [comment]
Does this change the values that the users are using for the warning voltages?  E.g. If I had a config dump would the number need to be multiplex by 10 now?

**Comment by hydra** [comment]
I agree with @ledvinap the magic numbers 10 / 100 / etc need to be constants.

The comment regarding fuel and mahDrawn should be removed and a new issue raised to fix it.

**Comment by projectkk2glider** [comment]
>Does this change the values that the users are using for the warning voltages?

No they retained their resolution. IF there is a need to change their resolution, just say so, but the eeprom structure must be changed then.

>The comment regarding fuel and mahDrawn should be removed and a new issue raised to fix it.

OK.

**Comment by ledvinap** [comment]
@hydra: My suggestion was to use (x*33)/(0xfff*10) instead of (x*3.3)/0xfff.

It may be improved by specifying ADC reference in mV and sharing it with other ADC code

But overusing constants doesn't help that much.

**Comment by dave-pitman** [comment]
@projectkk2glider Thanks for the hex. Will report back later.

**Comment by projectkk2glider** [comment]
I've just tested 0.01V vbat resolution on my hardware. The 8 bit `vbat_scale` is not accurate enough to get a good calibration. When I upped it to 16 bit (multiplied by 10) it was satisfactory. For example my board uses `set vbat_scale = 1112`

Now the question on how to implement `vbat_scale` resolution increase:
* change from uint8_t to uint16_t. Requires eeprom change and MSP protocol
* or change to int8_t and use it as a adjuster - ie `actual_vbat_scale = 1100 + vbat_scale`. This will only work is the vbat divisor is fixed for particular board. This change will still require changes to eeprom and MSP (but less impact).

What do you think?

**Comment by dave-pitman** [comment]
Looks much better to me.  I will test some more, but I am pretty happy so far.
Nice, thanks!

Naze32 clone
fw. 1.7.1 with #316 patch
Taranis Plus
3s lipo

**Comment by dave-pitman** [comment]
I was able to get another user to try the test firmware.  He reported that they lost VFAS completely, at which point the switched back to 1.7.1.  He said that is did set 'frsky_hiprec_vfas = 1' after flashing.  I asked him if he received any telem at all with 'set frsky_hiprec_vfas = 0' and he said that he did not try it.

He reported using
Naze32 Full
D4R-II

I have been using the test firmware for a few days now, and the VFAS is spot on within the resolution we have.

**Comment by dave-pitman** [comment]
Another user that I shared the firmware with has reported it has improved voltage telemetry for them.

**Comment by pinkywafer** [comment]
Just to report that ny Naze had been reporting VFAS pretty well (better than most from what I can tell), but I've been running the 1.7.1_naze_w-vfas firmware (sent by dave-pitman) recently, and I have also noticed improved reading with set frsky_hiprec_vfas = 1

Naze32 Acro
Taranis B - Open-TX 2.0.15
D4R-II
3s

**Comment by dave-pitman** [comment]
Thanks for your report, Jenny.  I hope this gets rolled into v.1.8  ( Please Dom!  )

**Comment by projectkk2glider** [comment]
@hydra Pull request rebased and squashed into one commit.

**Comment by hydra** [comment]
Ok, will merge this but will rename 'hiprec' to 'high_precision' since 'hiprec' is meaningless.

See https://cleancoders.com/episode/clean-code-episode-2/show

**Comment by hydra** [comment]
See https://github.com/cleanflight/cleanflight/commit/4cf6fe6571daf3147819ca01f3cd547fd7f88762 for the rename.

**Pull request merged**
