### PR TITLE
Fix broken airplane servo mixer on CC3D/NAZE

### PR DESCRIPTION
**Pull request by digitalentity**
…n servo mixer on CC3D/NAZE (#1323).

Flaps support was actually removed by 783a4c4bfa095e41ba234c5a74ad56739fbb17bd (#1066), but SERVO_FLAPS was kept in the code and occupied the servo slot. This actually moved elevator to output 7 (unavailable on CC3D/NAZE). This PR removes the now deprecated SERVO_FLAPS and moves elevator back to Pin6.

### CODE REVIEW

**Comment by digitalentity** [comment]
A side effect of this is that on MIXER_TRI tail servo output will be moved 1 pin to the beginning.

**Comment by sppnk** [comment]
Thx @digitalentity.

**Comment by hydra** [comment]
how about we keep the tricopter servo output for tri where it is, and switch flaps / elevator?

**Comment by digitalentity** [comment]
Good idea. Will keep things as it is for tri flyers and make airplane mixer
usable on cc3d. Not the way it was on 1.8 release, but usable. Will update
the PR asap.

On Friday, October 30, 2015, Dominic Clifton <notifications@github.com>
wrote:

> how about we keep the tricopter servo output for tri where it is, and
> switch flaps / elevator?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cleanflight/cleanflight/pull/1425#issuecomment-152345933>
> .
>


-- 
Sent from Gmail Mobile

**Comment by hydra** [comment]
merged the previous commit and another one to fix it.  Additional cleanup work was needed. See df5d8058594569cb707530548d4e2629d5c2fb3e

**Comment by digitalentity** [comment]
Thanks!

**Pull request closed without merging**
