### PR TITLE
feat:add average cell voltage in CRSF telemetry

### PR DESCRIPTION
**Pull request by thomasbridi**
add the possibility to switch between main battery voltage to average cell voltage in CRSF telemetry just setting in the CLI `report_cell_voltage = OFF, ON`

### CODE REVIEW

**Comment by thomasbridi** [comment]
ok I checked out the last commit on master (I removed my changes) and found out that it was not my code to create the problem on the IMPULSERCF3. Is it possible that the problem was there before?

**Comment by hydra** [comment]
@mikeller has this been added to BF yet?

**Comment by mikeller** [comment]
@hydra: Yes: betaflight/betaflight#6624.

**Comment by hydra** [comment]
@mikeller thanks for confirmation.
@thomasbridi this will bf in CF when the corresponding BF commit has been merged.  No need for this PR.  Thanks for your contribution!

**Pull request closed without merging**
