### PR TITLE
Use constant initializers in config reset

### PR DESCRIPTION
**Pull request by ledvinap**
Not that bad, 248bytes saved:
```
 129160	   1236	  19176	 149572	  24844	./obj/main/cleanflight_SPRACINGF3MINI.elf
 128912	   1236	  19176	 149324	  2474c	./obj/main/cleanflight_SPRACINGF3MINI.elf
```

### CODE REVIEW

**Comment by martinbudden** [comment]
@ledvinap , the numbers are believable to me. Unfortunately it looks like the travis checks have failed.

When you fix it, can you also change
```
    .pidController = 1,
```
to
```
    .pidController = PID_CONTROLLER_MWREWRITE,
```
for clarity.

**Comment by ledvinap** [comment]
Hmm ... seems that resetPidConfig gets inlined twice (it is used in cli)
memory saving for other structures is not that dramatic, sometimes it's worse ...

**Comment by ledvinap** [comment]
Converted other initializers. Macro is used, to its easy to switch to old code (gcc generates per-member write code when direct assignment is used).
Only change is that unspecified fields are zeroed (which is desirable)

**Comment by hydra** [comment]
nice, can you rebase this once the build passes and I'll merge.

**Comment by hydra** [comment]
i'll merge this now.

**Pull request merged**
