### PR TITLE
Modified VBatt functionality to enable better precision.

### PR DESCRIPTION
**Pull request by EvilBadger**
Ability to change the resistor divider ratio, as well as ability to multiply scale for small voltages.

Broken out of original pull request [2/3]

### CODE REVIEW

**Comment by leothehuman** [comment]
If either of 2 values is 0, you'll get division by zero, which is quite bad. Is there any piece of code preventing that from happening?

**Comment by geebles** [comment]
Does it need a div0 check? They are defines so not going to be changed or set any other way (as they will be specific to a board type that may have a different resistor divider, should not be in CLI). The specific use case for this code is to accurately measure a single cell battery, with the specific target changing the vbat resistor divider to 15.

**Comment by leothehuman** [comment]
Sorry, I thought these are config values. There's a test failing with floating point exception, so I guessed it might be the problem.
[ RUN      ] BatteryTest.BatteryState
make: *** [test-battery_unittest] Floating point exception (core dumped)
You might want to take a look at it just in case.

**Comment by EvilBadger** [comment]
I will have a look at the UT's later today.

**Pull request merged**
