### PR TITLE
Reinit vbatt

### PR DESCRIPTION
**Pull request by DarkVegetableMatter**
Assuming my other pull request was accepted then you might like to pull this too.

### CODE REVIEW

**Comment by DarkVegetableMatter** [comment]
Sorry, I just noticed some cruft I added and needed to remove

**Comment by DarkVegetableMatter** [comment]
Bugfix, there was a chance that as VBatt falls to VBAT_DETECTthe batteryState would be BATTERY_NOTPRESENT without the 'battery unplug event' firing

**Comment by hydra** [comment]
@DarkVegetableMatter thanks for the PRs

**Comment by hydra** [comment]
Merged

**Pull request closed without merging**
