### PR TITLE
Fix submakefile inheriting CC etc

### PR DESCRIPTION
**Pull request by ledvinap**
This should help with make test failing. But something more elegant will be nice ...

### CODE REVIEW

**Comment by ledvinap** [comment]
`-Werror` is disabled for unittest now, build succeeds ...

**Comment by ledvinap** [comment]
The `CC`  inheritance in Makefile .. I can't find any elegant fix. It is sometimes useful to override compiler (and other tools), both for native and cross-compiler

**Comment by ledvinap** [comment]
also there is warning when compiling unittest - `-lgcov` should not be in `CFLAGS` (it belongs to LDLIBS https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html)

**Comment by ledvinap** [comment]
Seems to be working ...

**Comment by hydra** [comment]
great, will merge the fix.

**Pull request merged**
