### PR TITLE
RX - Hold last stick/switch position on RC link lost.

### PR DESCRIPTION
**Pull request by ProDrone**
This is to prevent throttle to jump to midrc value on rc link failure or glitches. midrc is __seriously dangerous__ when applied to throttle. It made it also impossible to test my rebased mods to failsafe from PR #852  It works for me and solves issues mentioned in #919 and #939. Today this issue was also mentioned on IRC chat and in the forums. Please check this, because i only own a Graupner mx-20 and used a GR-12 receiver to test things. When added to master i will rebase and continue checking...

### CODE REVIEW

**Comment by hydra** [comment]
We really need to work out what should happen when RX is lost.  The old behavior was to do what this PR suggests but users complained and said they wanted the configured RX failsafe output channels.

i.e.  some RX units set a failsafe flag but still also transmit channel data, the channel data can be configured per-channel on some RX units.

I don't think that using the old behavior of holding last position is right, the current situation is that some users are happy and other users are not depending on their equipment and how they have configured it.  By using the old behavior we would just make a different set of users unhappy...

The GR12 for instance, can be configured to output whatever you like in a failsafe condition (i.e. no pulse or a set pulse for each channel), but other RX's are not so configurable.

What I'm thinking is that the user should be able to set, in the FC, what each channel value should be in a failsafe condition and that we should have sensible defaults.

We should not forget about 3D fliers either.  They have different requirements for failsafe throttle.

**Comment by ProDrone** [comment]
I would say safety first, even if that makes one of the user sets unhappy. Is it a wrong assumption to say, throttle to minimum and for 3D mode to mid stick for safety reasons? As a temporary safety measure i mean. Setting an individual fail-safe value for more channels is a good solution, the question is for how many channels should that be done..., all of them?

**Comment by TighMacFanatic** [comment]
I agree completely with hydra that each user should be able to set which channels are what values when in a failsafe condition.  For example, my RX sets my AUX channels to mid point (they are two way switches, there is no mid point when toggling them).  I was going to write a change that uses the CLI to let you set the channel mask and the range of values that are failsafe (as opposed to valid).

**Comment by hydra** [comment]
@ProDrone let's close this as you suggest.

Let's cleanup and merge #995 instead.

**Pull request closed without merging**
